###
### DDR4 Channel 1
###

## 250 MHZ clk
set_property PACKAGE_PIN AW26 [get_ports c1_sys_clk_p]
set_property PACKAGE_PIN AW27 [get_ports c1_sys_clk_n]

# ACT
set_property PACKAGE_PIN AN25 [get_ports c1_ddr4_act_n]
#set_property IOSTANDARD SSTL12_DCI [get_ports c1_ddr4_act_n]

# ADDR c1_ddr4_adr
set_property PACKAGE_PIN AM27 [get_ports {c1_ddr4_adr[0]}]
set_property PACKAGE_PIN AL27 [get_ports {c1_ddr4_adr[1]}]
set_property PACKAGE_PIN AP26 [get_ports {c1_ddr4_adr[2]}]
set_property PACKAGE_PIN AP25 [get_ports {c1_ddr4_adr[3]}]
set_property PACKAGE_PIN AN28 [get_ports {c1_ddr4_adr[4]}]
set_property PACKAGE_PIN AM28 [get_ports {c1_ddr4_adr[5]}]
set_property PACKAGE_PIN AP28 [get_ports {c1_ddr4_adr[6]}]
set_property PACKAGE_PIN AP27 [get_ports {c1_ddr4_adr[7]}]
set_property PACKAGE_PIN AN26 [get_ports {c1_ddr4_adr[8]}]
set_property PACKAGE_PIN AM26 [get_ports {c1_ddr4_adr[9]}]
set_property PACKAGE_PIN AR28 [get_ports {c1_ddr4_adr[10]}]
set_property PACKAGE_PIN AR27 [get_ports {c1_ddr4_adr[11]}]
set_property PACKAGE_PIN AV25 [get_ports {c1_ddr4_adr[12]}]
set_property PACKAGE_PIN AT25 [get_ports {c1_ddr4_adr[13]}]
set_property PACKAGE_PIN AV28 [get_ports {c1_ddr4_adr[14]}]
set_property PACKAGE_PIN AU26 [get_ports {c1_ddr4_adr[15]}]
set_property PACKAGE_PIN AV26 [get_ports {c1_ddr4_adr[16]}]

#set_property IOSTANDARD SSTL12_DCI [get_ports {c1_ddr4_adr[0]}]
#set_property IOSTANDARD SSTL12_DCI [get_ports {c1_ddr4_adr[1]}]
#set_property IOSTANDARD SSTL12_DCI [get_ports {c1_ddr4_adr[2]}]
#set_property IOSTANDARD SSTL12_DCI [get_ports {c1_ddr4_adr[3]}]
#set_property IOSTANDARD SSTL12_DCI [get_ports {c1_ddr4_adr[4]}]
#set_property IOSTANDARD SSTL12_DCI [get_ports {c1_ddr4_adr[5]}]
#set_property IOSTANDARD SSTL12_DCI [get_ports {c1_ddr4_adr[6]}]
#set_property IOSTANDARD SSTL12_DCI [get_ports {c1_ddr4_adr[7]}]
#set_property IOSTANDARD SSTL12_DCI [get_ports {c1_ddr4_adr[8]}]
#set_property IOSTANDARD SSTL12_DCI [get_ports {c1_ddr4_adr[9]}]
#set_property IOSTANDARD SSTL12_DCI [get_ports {c1_ddr4_adr[10]}]
#set_property IOSTANDARD SSTL12_DCI [get_ports {c1_ddr4_adr[11]}]
#set_property IOSTANDARD SSTL12_DCI [get_ports {c1_ddr4_adr[12]}]
#set_property IOSTANDARD SSTL12_DCI [get_ports {c1_ddr4_adr[13]}]
#set_property IOSTANDARD SSTL12_DCI [get_ports {c1_ddr4_adr[14]}]
#set_property IOSTANDARD SSTL12_DCI [get_ports {c1_ddr4_adr[15]}]
#set_property IOSTANDARD SSTL12_DCI [get_ports {c1_ddr4_adr[16]}]

# BA
set_property PACKAGE_PIN AR25 [get_ports {c1_ddr4_ba[0]}]
set_property PACKAGE_PIN AU28 [get_ports {c1_ddr4_ba[1]}]

#set_property IOSTANDARD SSTL12_DCI [get_ports {c1_ddr4_ba[0]}]
#set_property IOSTANDARD SSTL12_DCI [get_ports {c1_ddr4_ba[1]}]

# BG
set_property PACKAGE_PIN AU27 [get_ports {c1_ddr4_bg[0]}]
#set_property IOSTANDARD SSTL12_DCI [get_ports {c1_ddr4_bg[0]}]

# CKE
set_property PACKAGE_PIN AW28 [get_ports {c1_ddr4_cke[0]}]
#set_property IOSTANDARD SSTL12_DCI [get_ports {c1_ddr4_cke[0]}]

# ODT
set_property PACKAGE_PIN BB29 [get_ports {c1_ddr4_odt[0]}]
#set_property IOSTANDARD SSTL12_DCI [get_ports {c1_ddr4_odt[0]}]

# CS_n
set_property PACKAGE_PIN AY29 [get_ports {c1_ddr4_cs_n[0]}]
#set_property IOSTANDARD SSTL12_DCI [get_ports {c1_ddr4_cs_n[0]}]

# CKC

#set_property IOSTANDARD DIFF_SSTL12_DCI [get_ports {c1_ddr4_ck_t[0]}]
#set_property IOSTANDARD DIFF_SSTL12_DCI [get_ports {c1_ddr4_ck_c[0]}]

# RESET
set_property PACKAGE_PIN BD35 [get_ports c1_ddr4_reset_n]
#set_property IOSTANDARD LVCMOS12 [get_ports c1_ddr4_reset_n]
#set_property DRIVE 8 [get_ports c1_ddr4_reset_n]

# DM
set_property PACKAGE_PIN BE32 [get_ports {c1_ddr4_dm_dbi_n[0]}]
set_property PACKAGE_PIN BB31 [get_ports {c1_ddr4_dm_dbi_n[1]}]
set_property PACKAGE_PIN AV33 [get_ports {c1_ddr4_dm_dbi_n[2]}]
set_property PACKAGE_PIN AR32 [get_ports {c1_ddr4_dm_dbi_n[3]}]
set_property PACKAGE_PIN BC34 [get_ports {c1_ddr4_dm_dbi_n[4]}]
set_property PACKAGE_PIN BE40 [get_ports {c1_ddr4_dm_dbi_n[5]}]
set_property PACKAGE_PIN AY37 [get_ports {c1_ddr4_dm_dbi_n[6]}]
set_property PACKAGE_PIN AV35 [get_ports {c1_ddr4_dm_dbi_n[7]}]
#set_property PACKAGE_PIN BA29 [get_ports {c1_ddr4_dm_dbi__n[9]}]

#set_property IOSTANDARD POD12_DCI [get_ports {c1_ddr4_dm_dbi_n[0]}]
#set_property IOSTANDARD POD12_DCI [get_ports {c1_ddr4_dm_dbi_n[1]}]
#set_property IOSTANDARD POD12_DCI [get_ports {c1_ddr4_dm_dbi_n[2]}]
#set_property IOSTANDARD POD12_DCI [get_ports {c1_ddr4_dm_dbi_n[3]}]
#set_property IOSTANDARD POD12_DCI [get_ports {c1_ddr4_dm_dbi_n[4]}]
#set_property IOSTANDARD POD12_DCI [get_ports {c1_ddr4_dm_dbi_n[5]}]
#set_property IOSTANDARD POD12_DCI [get_ports {c1_ddr4_dm_dbi_n[6]}]
#set_property IOSTANDARD POD12_DCI [get_ports {c1_ddr4_dm_dbi_n[7]}]
#set_property IOSTANDARD POD12_DCI [get_ports {c1_ddr4_dm_dbi_n[8]}]
##set_property IOSTANDARD  POD12_DCI [get_ports {c1_ddr4_dm_dbi_n[9]}]


# DQ
set_property PACKAGE_PIN BD30 [get_ports {c1_ddr4_dq[0]}]
set_property PACKAGE_PIN BE30 [get_ports {c1_ddr4_dq[1]}]
set_property PACKAGE_PIN BD32 [get_ports {c1_ddr4_dq[2]}]
set_property PACKAGE_PIN BE33 [get_ports {c1_ddr4_dq[3]}]
set_property PACKAGE_PIN BC33 [get_ports {c1_ddr4_dq[4]}]
set_property PACKAGE_PIN BD33 [get_ports {c1_ddr4_dq[5]}]
set_property PACKAGE_PIN BC31 [get_ports {c1_ddr4_dq[6]}]
set_property PACKAGE_PIN BD31 [get_ports {c1_ddr4_dq[7]}]
set_property PACKAGE_PIN BA32 [get_ports {c1_ddr4_dq[8]}]
set_property PACKAGE_PIN BB33 [get_ports {c1_ddr4_dq[9]}]
set_property PACKAGE_PIN BA30 [get_ports {c1_ddr4_dq[10]}]
set_property PACKAGE_PIN BA31 [get_ports {c1_ddr4_dq[11]}]
set_property PACKAGE_PIN AW31 [get_ports {c1_ddr4_dq[12]}]
set_property PACKAGE_PIN AW32 [get_ports {c1_ddr4_dq[13]}]
set_property PACKAGE_PIN AY32 [get_ports {c1_ddr4_dq[14]}]
set_property PACKAGE_PIN AY33 [get_ports {c1_ddr4_dq[15]}]
set_property PACKAGE_PIN AV30 [get_ports {c1_ddr4_dq[16]}]
set_property PACKAGE_PIN AW30 [get_ports {c1_ddr4_dq[17]}]
set_property PACKAGE_PIN AU33 [get_ports {c1_ddr4_dq[18]}]
set_property PACKAGE_PIN AU34 [get_ports {c1_ddr4_dq[19]}]
set_property PACKAGE_PIN AT31 [get_ports {c1_ddr4_dq[20]}]
set_property PACKAGE_PIN AU32 [get_ports {c1_ddr4_dq[21]}]
set_property PACKAGE_PIN AU31 [get_ports {c1_ddr4_dq[22]}]
set_property PACKAGE_PIN AV31 [get_ports {c1_ddr4_dq[23]}]
set_property PACKAGE_PIN AR33 [get_ports {c1_ddr4_dq[24]}]
set_property PACKAGE_PIN AT34 [get_ports {c1_ddr4_dq[25]}]
set_property PACKAGE_PIN AT29 [get_ports {c1_ddr4_dq[26]}]
set_property PACKAGE_PIN AT30 [get_ports {c1_ddr4_dq[27]}]
set_property PACKAGE_PIN AP30 [get_ports {c1_ddr4_dq[28]}]
set_property PACKAGE_PIN AR30 [get_ports {c1_ddr4_dq[29]}]
set_property PACKAGE_PIN AN30 [get_ports {c1_ddr4_dq[30]}]
set_property PACKAGE_PIN AN31 [get_ports {c1_ddr4_dq[31]}]
set_property PACKAGE_PIN BE34 [get_ports {c1_ddr4_dq[32]}]
set_property PACKAGE_PIN BF34 [get_ports {c1_ddr4_dq[33]}]
set_property PACKAGE_PIN BC35 [get_ports {c1_ddr4_dq[34]}]
set_property PACKAGE_PIN BC36 [get_ports {c1_ddr4_dq[35]}]
set_property PACKAGE_PIN BD36 [get_ports {c1_ddr4_dq[36]}]
set_property PACKAGE_PIN BE37 [get_ports {c1_ddr4_dq[37]}]
set_property PACKAGE_PIN BF36 [get_ports {c1_ddr4_dq[38]}]
set_property PACKAGE_PIN BF37 [get_ports {c1_ddr4_dq[39]}]
set_property PACKAGE_PIN BD37 [get_ports {c1_ddr4_dq[40]}]
set_property PACKAGE_PIN BE38 [get_ports {c1_ddr4_dq[41]}]
set_property PACKAGE_PIN BC39 [get_ports {c1_ddr4_dq[42]}]
set_property PACKAGE_PIN BD40 [get_ports {c1_ddr4_dq[43]}]
set_property PACKAGE_PIN BB38 [get_ports {c1_ddr4_dq[44]}]
set_property PACKAGE_PIN BB39 [get_ports {c1_ddr4_dq[45]}]
set_property PACKAGE_PIN BC38 [get_ports {c1_ddr4_dq[46]}]
set_property PACKAGE_PIN BD38 [get_ports {c1_ddr4_dq[47]}]
set_property PACKAGE_PIN BB36 [get_ports {c1_ddr4_dq[48]}]
set_property PACKAGE_PIN BB37 [get_ports {c1_ddr4_dq[49]}]
set_property PACKAGE_PIN BA39 [get_ports {c1_ddr4_dq[50]}]
set_property PACKAGE_PIN BA40 [get_ports {c1_ddr4_dq[51]}]
set_property PACKAGE_PIN AW40 [get_ports {c1_ddr4_dq[52]}]
set_property PACKAGE_PIN AY40 [get_ports {c1_ddr4_dq[53]}]
set_property PACKAGE_PIN AY38 [get_ports {c1_ddr4_dq[54]}]
set_property PACKAGE_PIN AY39 [get_ports {c1_ddr4_dq[55]}]
set_property PACKAGE_PIN AW35 [get_ports {c1_ddr4_dq[56]}]
set_property PACKAGE_PIN AW36 [get_ports {c1_ddr4_dq[57]}]
set_property PACKAGE_PIN AU40 [get_ports {c1_ddr4_dq[58]}]
set_property PACKAGE_PIN AV40 [get_ports {c1_ddr4_dq[59]}]
set_property PACKAGE_PIN AU38 [get_ports {c1_ddr4_dq[60]}]
set_property PACKAGE_PIN AU39 [get_ports {c1_ddr4_dq[61]}]
set_property PACKAGE_PIN AV38 [get_ports {c1_ddr4_dq[62]}]
set_property PACKAGE_PIN AV39 [get_ports {c1_ddr4_dq[63]}]
#set_property PACKAGE_PIN BC25 [get_ports {c1_ddr4_dq[72]}]
#set_property PACKAGE_PIN BC26 [get_ports {c1_ddr4_dq[73]}]
#set_property PACKAGE_PIN BB28 [get_ports {c1_ddr4_dq[74]}]
#set_property PACKAGE_PIN BC28 [get_ports {c1_ddr4_dq[75]}]
#set_property PACKAGE_PIN AY27 [get_ports {c1_ddr4_dq[76]}]
#set_property PACKAGE_PIN AY28 [get_ports {c1_ddr4_dq[77]}]
#set_property PACKAGE_PIN BA27 [get_ports {c1_ddr4_dq[78]}]
#set_property PACKAGE_PIN BB27 [get_ports {c1_ddr4_dq[79]}]

#set_property IOSTANDARD POD12_DCI [get_ports {c1_ddr4_dq[0]}]
#set_property IOSTANDARD POD12_DCI [get_ports {c1_ddr4_dq[1]}]
#set_property IOSTANDARD POD12_DCI [get_ports {c1_ddr4_dq[2]}]
#set_property IOSTANDARD POD12_DCI [get_ports {c1_ddr4_dq[3]}]
#set_property IOSTANDARD POD12_DCI [get_ports {c1_ddr4_dq[4]}]
#set_property IOSTANDARD POD12_DCI [get_ports {c1_ddr4_dq[5]}]
#set_property IOSTANDARD POD12_DCI [get_ports {c1_ddr4_dq[6]}]
#set_property IOSTANDARD POD12_DCI [get_ports {c1_ddr4_dq[7]}]
#set_property IOSTANDARD POD12_DCI [get_ports {c1_ddr4_dq[8]}]
#set_property IOSTANDARD POD12_DCI [get_ports {c1_ddr4_dq[9]}]
#set_property IOSTANDARD POD12_DCI [get_ports {c1_ddr4_dq[10]}]
#set_property IOSTANDARD POD12_DCI [get_ports {c1_ddr4_dq[11]}]
#set_property IOSTANDARD POD12_DCI [get_ports {c1_ddr4_dq[12]}]
#set_property IOSTANDARD POD12_DCI [get_ports {c1_ddr4_dq[13]}]
#set_property IOSTANDARD POD12_DCI [get_ports {c1_ddr4_dq[14]}]
#set_property IOSTANDARD POD12_DCI [get_ports {c1_ddr4_dq[15]}]
#set_property IOSTANDARD POD12_DCI [get_ports {c1_ddr4_dq[16]}]
#set_property IOSTANDARD POD12_DCI [get_ports {c1_ddr4_dq[17]}]
#set_property IOSTANDARD POD12_DCI [get_ports {c1_ddr4_dq[18]}]
#set_property IOSTANDARD POD12_DCI [get_ports {c1_ddr4_dq[19]}]
#set_property IOSTANDARD POD12_DCI [get_ports {c1_ddr4_dq[20]}]
#set_property IOSTANDARD POD12_DCI [get_ports {c1_ddr4_dq[21]}]
#set_property IOSTANDARD POD12_DCI [get_ports {c1_ddr4_dq[22]}]
#set_property IOSTANDARD POD12_DCI [get_ports {c1_ddr4_dq[23]}]
#set_property IOSTANDARD POD12_DCI [get_ports {c1_ddr4_dq[24]}]
#set_property IOSTANDARD POD12_DCI [get_ports {c1_ddr4_dq[25]}]
#set_property IOSTANDARD POD12_DCI [get_ports {c1_ddr4_dq[26]}]
#set_property IOSTANDARD POD12_DCI [get_ports {c1_ddr4_dq[27]}]
#set_property IOSTANDARD POD12_DCI [get_ports {c1_ddr4_dq[28]}]
#set_property IOSTANDARD POD12_DCI [get_ports {c1_ddr4_dq[29]}]
#set_property IOSTANDARD POD12_DCI [get_ports {c1_ddr4_dq[30]}]
#set_property IOSTANDARD POD12_DCI [get_ports {c1_ddr4_dq[31]}]
#set_property IOSTANDARD POD12_DCI [get_ports {c1_ddr4_dq[32]}]
#set_property IOSTANDARD POD12_DCI [get_ports {c1_ddr4_dq[33]}]
#set_property IOSTANDARD POD12_DCI [get_ports {c1_ddr4_dq[34]}]
#set_property IOSTANDARD POD12_DCI [get_ports {c1_ddr4_dq[35]}]
#set_property IOSTANDARD POD12_DCI [get_ports {c1_ddr4_dq[36]}]
#set_property IOSTANDARD POD12_DCI [get_ports {c1_ddr4_dq[37]}]
#set_property IOSTANDARD POD12_DCI [get_ports {c1_ddr4_dq[38]}]
#set_property IOSTANDARD POD12_DCI [get_ports {c1_ddr4_dq[39]}]
#set_property IOSTANDARD POD12_DCI [get_ports {c1_ddr4_dq[40]}]
#set_property IOSTANDARD POD12_DCI [get_ports {c1_ddr4_dq[41]}]
#set_property IOSTANDARD POD12_DCI [get_ports {c1_ddr4_dq[42]}]
#set_property IOSTANDARD POD12_DCI [get_ports {c1_ddr4_dq[43]}]
#set_property IOSTANDARD POD12_DCI [get_ports {c1_ddr4_dq[44]}]
#set_property IOSTANDARD POD12_DCI [get_ports {c1_ddr4_dq[45]}]
#set_property IOSTANDARD POD12_DCI [get_ports {c1_ddr4_dq[46]}]
#set_property IOSTANDARD POD12_DCI [get_ports {c1_ddr4_dq[47]}]
#set_property IOSTANDARD POD12_DCI [get_ports {c1_ddr4_dq[48]}]
#set_property IOSTANDARD POD12_DCI [get_ports {c1_ddr4_dq[49]}]
#set_property IOSTANDARD POD12_DCI [get_ports {c1_ddr4_dq[50]}]
#set_property IOSTANDARD POD12_DCI [get_ports {c1_ddr4_dq[51]}]
#set_property IOSTANDARD POD12_DCI [get_ports {c1_ddr4_dq[52]}]
#set_property IOSTANDARD POD12_DCI [get_ports {c1_ddr4_dq[53]}]
#set_property IOSTANDARD POD12_DCI [get_ports {c1_ddr4_dq[54]}]
#set_property IOSTANDARD POD12_DCI [get_ports {c1_ddr4_dq[55]}]
#set_property IOSTANDARD POD12_DCI [get_ports {c1_ddr4_dq[56]}]
#set_property IOSTANDARD POD12_DCI [get_ports {c1_ddr4_dq[57]}]
#set_property IOSTANDARD POD12_DCI [get_ports {c1_ddr4_dq[58]}]
#set_property IOSTANDARD POD12_DCI [get_ports {c1_ddr4_dq[59]}]
#set_property IOSTANDARD POD12_DCI [get_ports {c1_ddr4_dq[60]}]
#set_property IOSTANDARD POD12_DCI [get_ports {c1_ddr4_dq[61]}]
#set_property IOSTANDARD POD12_DCI [get_ports {c1_ddr4_dq[62]}]
#set_property IOSTANDARD POD12_DCI [get_ports {c1_ddr4_dq[63]}]
#set_property IOSTANDARD POD12_DCI [get_ports {c1_ddr4_dq[64]}]
#set_property IOSTANDARD POD12_DCI [get_ports {c1_ddr4_dq[65]}]
#set_property IOSTANDARD POD12_DCI [get_ports {c1_ddr4_dq[66]}]
#set_property IOSTANDARD POD12_DCI [get_ports {c1_ddr4_dq[67]}]
#set_property IOSTANDARD POD12_DCI [get_ports {c1_ddr4_dq[68]}]
#set_property IOSTANDARD POD12_DCI [get_ports {c1_ddr4_dq[69]}]
#set_property IOSTANDARD POD12_DCI [get_ports {c1_ddr4_dq[70]}]
#set_property IOSTANDARD POD12_DCI [get_ports {c1_ddr4_dq[71]}]
##set_property IOSTANDARD  POD12_DCI [get_ports {c1_ddr4_dq[72]}]
##set_property IOSTANDARD  POD12_DCI [get_ports {c1_ddr4_dq[73]}]
##set_property IOSTANDARD  POD12_DCI [get_ports {c1_ddr4_dq[74]}]
##set_property IOSTANDARD  POD12_DCI [get_ports {c1_ddr4_dq[75]}]
##set_property IOSTANDARD  POD12_DCI [get_ports {c1_ddr4_dq[76]}]
##set_property IOSTANDARD  POD12_DCI [get_ports {c1_ddr4_dq[77]}]
##set_property IOSTANDARD  POD12_DCI [get_ports {c1_ddr4_dq[78]}]
##set_property IOSTANDARD  POD12_DCI [get_ports {c1_ddr4_dq[79]}]

# DQS_C
#set_property PACKAGE_PIN BA26 [get_ports {c1_ddr4_dqs_t[9]}]
#set_property PACKAGE_PIN BB26 [get_ports {c1_ddr4_dqs_c[9]}]

#set_property IOSTANDARD DIFF_POD12_DCI [get_ports {c1_ddr4_dqs_c[0]}]
#set_property IOSTANDARD DIFF_POD12_DCI [get_ports {c1_ddr4_dqs_t[0]}]
#set_property IOSTANDARD DIFF_POD12_DCI [get_ports {c1_ddr4_dqs_c[1]}]
#set_property IOSTANDARD DIFF_POD12_DCI [get_ports {c1_ddr4_dqs_t[1]}]
#set_property IOSTANDARD DIFF_POD12_DCI [get_ports {c1_ddr4_dqs_c[2]}]
#set_property IOSTANDARD DIFF_POD12_DCI [get_ports {c1_ddr4_dqs_t[2]}]
#set_property IOSTANDARD DIFF_POD12_DCI [get_ports {c1_ddr4_dqs_c[3]}]
#set_property IOSTANDARD DIFF_POD12_DCI [get_ports {c1_ddr4_dqs_t[3]}]
#set_property IOSTANDARD DIFF_POD12_DCI [get_ports {c1_ddr4_dqs_c[4]}]
#set_property IOSTANDARD DIFF_POD12_DCI [get_ports {c1_ddr4_dqs_t[4]}]
#set_property IOSTANDARD DIFF_POD12_DCI [get_ports {c1_ddr4_dqs_c[5]}]
#set_property IOSTANDARD DIFF_POD12_DCI [get_ports {c1_ddr4_dqs_t[5]}]
#set_property IOSTANDARD DIFF_POD12_DCI [get_ports {c1_ddr4_dqs_c[6]}]
#set_property IOSTANDARD DIFF_POD12_DCI [get_ports {c1_ddr4_dqs_t[6]}]
#set_property IOSTANDARD DIFF_POD12_DCI [get_ports {c1_ddr4_dqs_c[7]}]
#set_property IOSTANDARD DIFF_POD12_DCI [get_ports {c1_ddr4_dqs_t[7]}]
#set_property IOSTANDARD DIFF_POD12_DCI [get_ports {c1_ddr4_dqs_c[8]}]
#set_property IOSTANDARD DIFF_POD12_DCI [get_ports {c1_ddr4_dqs_t[8]}]
##set_property IOSTANDARD  DIFF_POD12_DCI [get_ports {c1_ddr4_dqs_c[9]}]
##set_property IOSTANDARD  DIFF_POD12_DCI [get_ports {c1_ddr4_dqs_t[9]}]

### End of DDR4 channel 1

set_property PACKAGE_PIN BE39 [get_ports {c1_ddr4_dqs_t[5]}]
set_property PACKAGE_PIN BF39 [get_ports {c1_ddr4_dqs_c[5]}]
set_property PACKAGE_PIN BE35 [get_ports {c1_ddr4_dqs_t[4]}]
set_property PACKAGE_PIN BF35 [get_ports {c1_ddr4_dqs_c[4]}]
set_property PACKAGE_PIN AT26 [get_ports {c1_ddr4_ck_t[0]}]
set_property PACKAGE_PIN AT27 [get_ports {c1_ddr4_ck_c[0]}]
set_property PACKAGE_PIN AY34 [get_ports {c1_ddr4_dqs_t[1]}]
set_property PACKAGE_PIN BA34 [get_ports {c1_ddr4_dqs_c[1]}]
set_property PACKAGE_PIN AP31 [get_ports {c1_ddr4_dqs_t[3]}]
set_property PACKAGE_PIN AP32 [get_ports {c1_ddr4_dqs_c[3]}]
set_property PACKAGE_PIN AU29 [get_ports {c1_ddr4_dqs_t[2]}]
set_property PACKAGE_PIN AV29 [get_ports {c1_ddr4_dqs_c[2]}]
set_property PACKAGE_PIN BF30 [get_ports {c1_ddr4_dqs_t[0]}]
set_property PACKAGE_PIN BF31 [get_ports {c1_ddr4_dqs_c[0]}]
set_property PACKAGE_PIN BA35 [get_ports {c1_ddr4_dqs_t[6]}]
set_property PACKAGE_PIN BA36 [get_ports {c1_ddr4_dqs_c[6]}]
set_property PACKAGE_PIN AW37 [get_ports {c1_ddr4_dqs_t[7]}]
set_property PACKAGE_PIN AW38 [get_ports {c1_ddr4_dqs_c[7]}]
set_property IOSTANDARD DIFF_SSTL12 [get_ports c1_sys_clk_p]
set_property IOSTANDARD DIFF_SSTL12 [get_ports c1_sys_clk_n]

set_property PACKAGE_PIN N22 [get_ports {c0_ddr4_dqs_t[5]}]
set_property PACKAGE_PIN M22 [get_ports {c0_ddr4_dqs_c[5]}]
set_property PACKAGE_PIN A19 [get_ports {c0_ddr4_dqs_t[4]}]
set_property PACKAGE_PIN A18 [get_ports {c0_ddr4_dqs_c[4]}]
set_property PACKAGE_PIN F14 [get_ports {c0_ddr4_ck_t[0]}]
set_property PACKAGE_PIN E14 [get_ports {c0_ddr4_ck_c[0]}]
set_property PACKAGE_PIN P17 [get_ports {c0_ddr4_dqs_t[1]}]
set_property PACKAGE_PIN P16 [get_ports {c0_ddr4_dqs_c[1]}]
set_property PACKAGE_PIN F16 [get_ports {c0_ddr4_dqs_t[3]}]
set_property PACKAGE_PIN E16 [get_ports {c0_ddr4_dqs_c[3]}]
set_property PACKAGE_PIN K19 [get_ports {c0_ddr4_dqs_t[2]}]
set_property PACKAGE_PIN J19 [get_ports {c0_ddr4_dqs_c[2]}]
set_property PACKAGE_PIN D11 [get_ports {c0_ddr4_dqs_t[0]}]
set_property PACKAGE_PIN D10 [get_ports {c0_ddr4_dqs_c[0]}]
set_property PACKAGE_PIN M20 [get_ports {c0_ddr4_dqs_t[6]}]
set_property PACKAGE_PIN L20 [get_ports {c0_ddr4_dqs_c[6]}]
set_property PACKAGE_PIN H24 [get_ports {c0_ddr4_dqs_t[7]}]
set_property PACKAGE_PIN G23 [get_ports {c0_ddr4_dqs_c[7]}]
set_property IOSTANDARD DIFF_SSTL12 [get_ports c0_sys_clk_p]
set_property IOSTANDARD DIFF_SSTL12 [get_ports c0_sys_clk_n]