#### PCIe

# Clock
set_property PACKAGE_PIN AL8 [get_ports {pcie_clk_clk_n[0]}]
set_property PACKAGE_PIN AL9 [get_ports {pcie_clk_clk_p[0]}]

# Reset
set_property PACKAGE_PIN AM17 [get_ports perst_n_nb]
set_property IOSTANDARD LVCMOS18 [get_ports perst_n_nb]
set_property PULLUP true [get_ports perst_n_nb]

# PCIe ext.
set_property PACKAGE_PIN AA4 [get_ports {pcie_x16_rxp[0]}]
set_property PACKAGE_PIN AA3 [get_ports {pcie_x16_rxn[0]}]
set_property PACKAGE_PIN Y7 [get_ports {pcie_x16_txp[0]}]
set_property PACKAGE_PIN Y6 [get_ports {pcie_x16_txn[0]}]
set_property PACKAGE_PIN AB2 [get_ports {pcie_x16_rxp[1]}]
set_property PACKAGE_PIN AB1 [get_ports {pcie_x16_rxn[1]}]
set_property PACKAGE_PIN AB7 [get_ports {pcie_x16_txp[1]}]
set_property PACKAGE_PIN AB6 [get_ports {pcie_x16_txn[1]}]
set_property PACKAGE_PIN AC4 [get_ports {pcie_x16_rxp[2]}]
set_property PACKAGE_PIN AC3 [get_ports {pcie_x16_rxn[2]}]
set_property PACKAGE_PIN AD7 [get_ports {pcie_x16_txp[2]}]
set_property PACKAGE_PIN AD6 [get_ports {pcie_x16_txn[2]}]
set_property PACKAGE_PIN AD2 [get_ports {pcie_x16_rxp[3]}]
set_property PACKAGE_PIN AD1 [get_ports {pcie_x16_rxn[3]}]
set_property PACKAGE_PIN AF7 [get_ports {pcie_x16_txp[3]}]
set_property PACKAGE_PIN AF6 [get_ports {pcie_x16_txn[3]}]
set_property PACKAGE_PIN AE4 [get_ports {pcie_x16_rxp[4]}]
set_property PACKAGE_PIN AE3 [get_ports {pcie_x16_rxn[4]}]
set_property PACKAGE_PIN AH7 [get_ports {pcie_x16_txp[4]}]
set_property PACKAGE_PIN AH6 [get_ports {pcie_x16_txn[4]}]
set_property PACKAGE_PIN AF2 [get_ports {pcie_x16_rxp[5]}]
set_property PACKAGE_PIN AF1 [get_ports {pcie_x16_rxn[5]}]
set_property PACKAGE_PIN AK7 [get_ports {pcie_x16_txp[5]}]
set_property PACKAGE_PIN AK6 [get_ports {pcie_x16_txn[5]}]
set_property PACKAGE_PIN AG4 [get_ports {pcie_x16_rxp[6]}]
set_property PACKAGE_PIN AG3 [get_ports {pcie_x16_rxn[6]}]
set_property PACKAGE_PIN AM7 [get_ports {pcie_x16_txp[6]}]
set_property PACKAGE_PIN AM6 [get_ports {pcie_x16_txn[6]}]
set_property PACKAGE_PIN AH2 [get_ports {pcie_x16_rxp[7]}]
set_property PACKAGE_PIN AH1 [get_ports {pcie_x16_rxn[7]}]
set_property PACKAGE_PIN AN5 [get_ports {pcie_x16_txp[7]}]
set_property PACKAGE_PIN AN4 [get_ports {pcie_x16_txn[7]}]

#x16
set_property PACKAGE_PIN AJ4 [get_ports {pcie_x16_rxp[8]}]
set_property PACKAGE_PIN AJ3 [get_ports {pcie_x16_rxn[8]}]
set_property PACKAGE_PIN AP7 [get_ports {pcie_x16_txp[8]}]
set_property PACKAGE_PIN AP6 [get_ports {pcie_x16_txn[8]}]
set_property PACKAGE_PIN AK2 [get_ports {pcie_x16_rxp[9]}]
set_property PACKAGE_PIN AK1 [get_ports {pcie_x16_rxn[9]}]
set_property PACKAGE_PIN AR5 [get_ports {pcie_x16_txp[9]}]
set_property PACKAGE_PIN AR4 [get_ports {pcie_x16_txn[9]}]
set_property PACKAGE_PIN AM2 [get_ports {pcie_x16_rxp[10]}]
set_property PACKAGE_PIN AM1 [get_ports {pcie_x16_rxn[10]}]
set_property PACKAGE_PIN AT7 [get_ports {pcie_x16_txp[10]}]
set_property PACKAGE_PIN AT6 [get_ports {pcie_x16_txn[10]}]
set_property PACKAGE_PIN AP2 [get_ports {pcie_x16_rxp[11]}]
set_property PACKAGE_PIN AP1 [get_ports {pcie_x16_rxn[11]}]
set_property PACKAGE_PIN AU5 [get_ports {pcie_x16_txp[11]}]
set_property PACKAGE_PIN AU4 [get_ports {pcie_x16_txn[11]}]
set_property PACKAGE_PIN AT2 [get_ports {pcie_x16_rxp[12]}]
set_property PACKAGE_PIN AT1 [get_ports {pcie_x16_rxn[12]}]
set_property PACKAGE_PIN AW5 [get_ports {pcie_x16_txp[12]}]
set_property PACKAGE_PIN AW4 [get_ports {pcie_x16_txn[12]}]
set_property PACKAGE_PIN AV2 [get_ports {pcie_x16_rxp[13]}]
set_property PACKAGE_PIN AV1 [get_ports {pcie_x16_rxn[13]}]
set_property PACKAGE_PIN BA5 [get_ports {pcie_x16_txp[13]}]
set_property PACKAGE_PIN BA4 [get_ports {pcie_x16_txn[13]}]
set_property PACKAGE_PIN AY2 [get_ports {pcie_x16_rxp[14]}]
set_property PACKAGE_PIN AY1 [get_ports {pcie_x16_rxn[14]}]
set_property PACKAGE_PIN BC5 [get_ports {pcie_x16_txp[14]}]
set_property PACKAGE_PIN BC4 [get_ports {pcie_x16_txn[14]}]
set_property PACKAGE_PIN BB2 [get_ports {pcie_x16_rxp[15]}]
set_property PACKAGE_PIN BB1 [get_ports {pcie_x16_rxn[15]}]
set_property PACKAGE_PIN BE5 [get_ports {pcie_x16_txp[15]}]
set_property PACKAGE_PIN BE4 [get_ports {pcie_x16_txn[15]}]

# Set false path
set_false_path -from [get_ports perst_n_nb]

