#QSPF28 Connector1
set_property PACKAGE_PIN W8 [get_ports gt0_refclk_n]
set_property PACKAGE_PIN W9 [get_ports gt0_refclk_p]

set_property PACKAGE_PIN V7 [get_ports {gt0_txp_out[0]}]
set_property PACKAGE_PIN V6 [get_ports {gt0_txn_out[0]}]
set_property PACKAGE_PIN Y2 [get_ports {gt0_rxp_in[0]}]
set_property PACKAGE_PIN Y1 [get_ports {gt0_rxn_in[0]}]
set_property PACKAGE_PIN T7 [get_ports {gt0_txp_out[1]}]
set_property PACKAGE_PIN T6 [get_ports {gt0_txn_out[1]}]
set_property PACKAGE_PIN W4 [get_ports {gt0_rxp_in[1]}]
set_property PACKAGE_PIN W3 [get_ports {gt0_rxn_in[1]}]
set_property PACKAGE_PIN P7 [get_ports {gt0_txp_out[2]}]
set_property PACKAGE_PIN P6 [get_ports {gt0_txn_out[2]}]
set_property PACKAGE_PIN V2 [get_ports {gt0_rxp_in[2]}]
set_property PACKAGE_PIN V1 [get_ports {gt0_rxn_in[2]}]
set_property PACKAGE_PIN M7 [get_ports {gt0_txp_out[3]}]
set_property PACKAGE_PIN M6 [get_ports {gt0_txn_out[3]}]
set_property PACKAGE_PIN U4 [get_ports {gt0_rxp_in[3]}]
set_property PACKAGE_PIN U3 [get_ports {gt0_rxn_in[3]}]