#QSPF28 Connector2
set_property PACKAGE_PIN R8 [get_ports gt1_refclk_n]
set_property PACKAGE_PIN R9 [get_ports gt1_refclk_p]

set_property PACKAGE_PIN L5 [get_ports {gt1_txp_out[0]}]
set_property PACKAGE_PIN L4 [get_ports {gt1_txn_out[0]}]
set_property PACKAGE_PIN T2 [get_ports {gt1_rxp_in[0]}]
set_property PACKAGE_PIN T1 [get_ports {gt1_rxn_in[0]}]
set_property PACKAGE_PIN K7 [get_ports {gt1_txp_out[1]}]
set_property PACKAGE_PIN K6 [get_ports {gt1_txn_out[1]}]
set_property PACKAGE_PIN R4 [get_ports {gt1_rxp_in[1]}]
set_property PACKAGE_PIN R3 [get_ports {gt1_rxn_in[1]}]
set_property PACKAGE_PIN J5 [get_ports {gt1_txp_out[2]}]
set_property PACKAGE_PIN J4 [get_ports {gt1_txn_out[2]}]
set_property PACKAGE_PIN P2 [get_ports {gt1_rxp_in[2]}]
set_property PACKAGE_PIN P1 [get_ports {gt1_rxn_in[2]}]
set_property PACKAGE_PIN H7 [get_ports {gt1_txp_out[3]}]
set_property PACKAGE_PIN H6 [get_ports {gt1_txn_out[3]}]
set_property PACKAGE_PIN M2 [get_ports {gt1_rxp_in[3]}]
set_property PACKAGE_PIN M1 [get_ports {gt1_rxn_in[3]}]