{
  "default_candidate": "cnn_medium_img512",
  "candidates": {
    "cnn_medium_img512": {
      "model": "cnn_medium_hls_img512",
      "representation": "2d",
      "img_size": 512,
      "sequence_length": 262144,
      "min_ro": 8000,
      "run_dir": "/mnt/scratch/sdeheredia/Coyote/examples/ml_baseline/runs/20260419_191657_cnn_medium_ro8000_ep300_fliponly_img512_lr3e4_img512_kfold5",
      "saved_run_dir": "/mnt/scratch/sdeheredia/Coyote/examples/ml_baseline/saved_runs/20260419_191657_cnn_medium_ro8000_ep300_fliponly_img512_lr3e4_img512_kfold5",
      "folds": [0, 1, 2, 3, 4],
      "default_stage": "pytorch_float",
      "target_part": "xcu55c-fsvh2892-2L-e",
      "fallback_part": "xcu250-figd2104-2L-e",
      "io_type": "io_stream",
      "strategy": "Resource",
      "reuse_factors": [4, 8, 16]
    },
    "cnn_medium": {
      "model": "cnn_medium_hls",
      "representation": "2d",
      "img_size": 1024,
      "sequence_length": 1048576,
      "min_ro": 8000,
      "run_dir": "../runs/20260419_042908_cnn_medium_hls_ro8000_ep500_kfold5_fliponly_kfold5",
      "saved_run_dir": "../saved_runs/20260419_042908_cnn_medium_hls_ro8000_ep500_kfold5_fliponly_kfold5",
      "folds": [0, 1, 2, 3, 4],
      "default_stage": "pytorch_float",
      "target_part": "xcu55c-fsvh2892-2L-e",
      "fallback_part": "xcu250-figd2104-2L-e",
      "io_type": "io_stream",
      "strategy": "Resource",
      "reuse_factors": [4, 8, 16]
    },
  "cnn_b_img256": {
      "model": "cnn_b_hls_img256",
      "representation": "2d",
      "img_size": 256,
      "sequence_length": 65536,
      "min_ro": 8000,
      "run_dir": "/mnt/scratch/sdeheredia/Coyote/examples/ml_baseline/runs/20260419_191701_cnn_b_ro8000_ep300_fliponly_img256_img256_kfold5",
      "saved_run_dir": "/mnt/scratch/sdeheredia/Coyote/examples/ml_baseline/saved_runs/20260419_191701_cnn_b_ro8000_ep300_fliponly_img256_img256_kfold5",
      "folds": [0, 1, 2, 3, 4],
      "default_stage": "pytorch_float",
      "target_part": "xcu55c-fsvh2892-2L-e",
      "fallback_part": "xcu250-figd2104-2L-e",
      "io_type": "io_stream",
      "strategy": "Resource",
      "reuse_factors": [4, 8, 16]
    },
    "cnn_small_hls_opt_img256": {
      "model": "cnn_small_hls_opt_img256",
      "representation": "2d",
      "img_size": 256,
      "sequence_length": 65536,
      "min_ro": 8000,
      "run_dir": "/mnt/scratch/sdeheredia/Coyote/examples/ml_baseline/runs/20260420_012941_cnn_small_hls_opt_ro8000_ep300_fliponly_img256_lr3e4_img256_kfold5",
      "saved_run_dir": "/mnt/scratch/sdeheredia/Coyote/examples/ml_baseline/saved_runs/20260420_012941_cnn_small_hls_opt_ro8000_ep300_fliponly_img256_lr3e4_img256_kfold5",
      "folds": [0, 1, 2, 3, 4],
      "default_stage": "pytorch_float",
      "target_part": "xcu55c-fsvh2892-2L-e",
      "fallback_part": "xcu250-figd2104-2L-e",
      "io_type": "io_stream",
      "strategy": "Resource",
      "reuse_factors": [4, 8, 16]
    },
    "cnn_small_hls_opt_img512": {
      "model": "cnn_small_hls_opt_img512",
      "representation": "2d",
      "img_size": 512,
      "sequence_length": 262144,
      "min_ro": 8000,
      "run_dir": "/mnt/scratch/sdeheredia/Coyote/examples/ml_baseline/runs/20260420_001453_cnn_small_hls_opt_ro8000_ep300_fliponly_img512_img512_kfold5",
      "saved_run_dir": "/mnt/scratch/sdeheredia/Coyote/examples/ml_baseline/saved_runs/20260420_001453_cnn_small_hls_opt_ro8000_ep300_fliponly_img512_img512_kfold5",
      "folds": [0, 1, 2, 3, 4],
      "default_stage": "pytorch_float",
      "target_part": "xcu55c-fsvh2892-2L-e",
      "fallback_part": "xcu250-figd2104-2L-e",
      "io_type": "io_stream",
      "strategy": "Resource",
      "reuse_factors": [4, 8, 16]
    }
  }
}
