// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module arp_server_subnet_top_generate_arp_pkg_512_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        myIpAddress_dout,
        myIpAddress_num_data_valid,
        myIpAddress_fifo_cap,
        myIpAddress_empty_n,
        myIpAddress_read,
        myMacAddress_dout,
        myMacAddress_num_data_valid,
        myMacAddress_fifo_cap,
        myMacAddress_empty_n,
        myMacAddress_read,
        arpRequestMetaFifo_dout,
        arpRequestMetaFifo_num_data_valid,
        arpRequestMetaFifo_fifo_cap,
        arpRequestMetaFifo_empty_n,
        arpRequestMetaFifo_read,
        arpReplyMetaFifo_dout,
        arpReplyMetaFifo_num_data_valid,
        arpReplyMetaFifo_fifo_cap,
        arpReplyMetaFifo_empty_n,
        arpReplyMetaFifo_read,
        arpDataOut_internal_din,
        arpDataOut_internal_num_data_valid,
        arpDataOut_internal_fifo_cap,
        arpDataOut_internal_full_n,
        arpDataOut_internal_write
);

parameter    ap_ST_iter0_fsm_state1 = 1'd1;
parameter    ap_ST_iter1_fsm_state2 = 2'd2;
parameter    ap_ST_iter1_fsm_state0 = 2'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [31:0] myIpAddress_dout;
input  [2:0] myIpAddress_num_data_valid;
input  [2:0] myIpAddress_fifo_cap;
input   myIpAddress_empty_n;
output   myIpAddress_read;
input  [47:0] myMacAddress_dout;
input  [2:0] myMacAddress_num_data_valid;
input  [2:0] myMacAddress_fifo_cap;
input   myMacAddress_empty_n;
output   myMacAddress_read;
input  [31:0] arpRequestMetaFifo_dout;
input  [2:0] arpRequestMetaFifo_num_data_valid;
input  [2:0] arpRequestMetaFifo_fifo_cap;
input   arpRequestMetaFifo_empty_n;
output   arpRequestMetaFifo_read;
input  [127:0] arpReplyMetaFifo_dout;
input  [2:0] arpReplyMetaFifo_num_data_valid;
input  [2:0] arpReplyMetaFifo_fifo_cap;
input   arpReplyMetaFifo_empty_n;
output   arpReplyMetaFifo_read;
output  [1023:0] arpDataOut_internal_din;
input  [2:0] arpDataOut_internal_num_data_valid;
input  [2:0] arpDataOut_internal_fifo_cap;
input   arpDataOut_internal_full_n;
output   arpDataOut_internal_write;

reg ap_done;
reg ap_idle;
reg ap_ready;

reg   [0:0] ap_CS_iter0_fsm;
wire    ap_CS_iter0_fsm_state1;
reg   [1:0] ap_CS_iter1_fsm;
wire    ap_CS_iter1_fsm_state0;
wire   [0:0] gap_state_load_load_fu_288_p1;
wire   [0:0] tmp_2_i_nbreadreq_fu_126_p3;
wire   [0:0] tmp_7_i_nbreadreq_fu_134_p3;
reg    ap_predicate_op36_read_state1;
reg    ap_predicate_op43_read_state1;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
reg   [0:0] gap_state_load_reg_499;
reg    ap_block_state2_pp0_stage0_iter1;
wire    ap_CS_iter1_fsm_state2;
reg   [0:0] guard_variable_for_void_generate_arp_pkg_stream_stream_stream_ap_uint_ap_uint;
reg   [15:0] header_idx_1;
reg   [335:0] header_header_1;
reg   [0:0] gap_state;
reg    myMacAddress_blk_n;
reg    myIpAddress_blk_n;
reg    arpReplyMetaFifo_blk_n;
reg    arpRequestMetaFifo_blk_n;
reg    arpDataOut_internal_blk_n;
wire   [335:0] empty_fu_460_p3;
reg   [335:0] empty_reg_509;
reg   [0:0] ap_phi_mux_header_idx_1_flag_0_i_phi_fu_164_p4;
wire   [0:0] ap_phi_reg_pp0_iter0_header_idx_1_flag_0_i_reg_161;
wire   [0:0] guard_variable_for_void_generate_arp_pkg_stream_stream_stream_ap_uint_ap_uint_1_load_fu_255_p1;
reg   [15:0] ap_phi_mux_header_idx_1_loc_0_i_phi_fu_175_p4;
wire   [15:0] ap_phi_reg_pp0_iter0_header_idx_1_loc_0_i_reg_172;
reg   [335:0] ap_phi_mux_sendWord_data_phi_fu_185_p4;
wire   [335:0] tmp_i_fu_269_p5;
wire   [335:0] ap_phi_reg_pp0_iter0_sendWord_data_reg_182;
reg   [0:0] ap_phi_mux_header_idx_1_flag_2_i_phi_fu_194_p8;
wire   [0:0] header_idx_1_flag_1_i_fu_438_p2;
wire   [0:0] ap_phi_reg_pp0_iter0_header_idx_1_flag_2_i_reg_191;
reg   [15:0] ap_phi_mux_header_idx_1_new_2_i_phi_fu_210_p8;
wire   [15:0] header_idx_1_new_1_i_fu_445_p3;
wire   [15:0] ap_phi_reg_pp0_iter0_header_idx_1_new_2_i_reg_207;
reg   [0:0] ap_phi_mux_header_header_1_flag_3_i_phi_fu_226_p8;
wire   [0:0] ap_phi_reg_pp0_iter0_header_header_1_flag_3_i_reg_223;
reg   [335:0] ap_phi_mux_header_header_1_new_3_i_phi_fu_243_p8;
wire   [335:0] ap_phi_reg_pp0_iter0_header_header_1_new_3_i_reg_240;
wire   [335:0] tmp_10_i_fu_330_p5;
wire   [335:0] tmp_6_i_fu_399_p5;
reg    myIpAddress_read_local;
reg    myMacAddress_read_local;
reg    arpRequestMetaFifo_read_local;
reg    arpReplyMetaFifo_read_local;
wire   [1023:0] zext_ln147_1_fu_491_p1;
reg    arpDataOut_internal_write_local;
wire   [335:0] tmp_8_i3_fu_292_p5;
wire   [335:0] tmp_9_i4_fu_304_p5;
wire   [175:0] tmp_11_i_fu_316_p6;
wire   [47:0] trunc_ln98_fu_349_p1;
wire   [335:0] tmp_4_i1_fu_353_p5;
wire   [79:0] tmp_fu_377_p4;
wire   [335:0] tmp_5_i2_fu_365_p5;
wire   [175:0] tmp_i_35_fu_387_p5;
wire   [24:0] shl_ln_fu_418_p3;
wire   [0:0] icmp_ln82_fu_426_p2;
wire   [15:0] add_ln85_fu_432_p2;
wire   [511:0] zext_ln147_fu_480_p1;
wire   [576:0] zext_ln147_1_cast_fu_483_p3;
reg   [0:0] ap_NS_iter0_fsm;
reg   [1:0] ap_NS_iter1_fsm;
reg    ap_ST_iter0_fsm_state1_blk;
reg    ap_ST_iter1_fsm_state2_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_iter0_fsm = 1'd1;
#0 ap_CS_iter1_fsm = 2'd1;
#0 ap_done_reg = 1'b0;
#0 guard_variable_for_void_generate_arp_pkg_stream_stream_stream_ap_uint_ap_uint = 1'd0;
#0 header_idx_1 = 16'd0;
#0 header_header_1 = 336'd0;
#0 gap_state = 1'd0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter0_fsm <= ap_ST_iter0_fsm_state1;
    end else begin
        ap_CS_iter0_fsm <= ap_NS_iter0_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter1_fsm <= ap_ST_iter1_fsm_state0;
    end else begin
        ap_CS_iter1_fsm <= ap_NS_iter1_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state2_pp0_stage0_iter1)) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter1_fsm_state2) & (1'b1 == ap_block_state2_pp0_stage0_iter1))) & (gap_state_load_load_fu_288_p1 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        gap_state <= 1'd0;
    end else if (((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter1_fsm_state2) & (1'b1 == ap_block_state2_pp0_stage0_iter1))) & (tmp_2_i_nbreadreq_fu_126_p3 == 1'd1) & (gap_state == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1)) | (~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter1_fsm_state2) & (1'b1 == ap_block_state2_pp0_stage0_iter1))) & (tmp_7_i_nbreadreq_fu_134_p3 == 1'd1) & (tmp_2_i_nbreadreq_fu_126_p3 == 1'd0) & (gap_state == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1)))) begin
        gap_state <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter1_fsm_state2) & (1'b1 == ap_block_state2_pp0_stage0_iter1))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        empty_reg_509 <= empty_fu_460_p3;
        gap_state_load_reg_499 <= gap_state;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter1_fsm_state2) & (1'b1 == ap_block_state2_pp0_stage0_iter1))) & (1'b1 == ap_CS_iter0_fsm_state1) & (guard_variable_for_void_generate_arp_pkg_stream_stream_stream_ap_uint_ap_uint_1_load_fu_255_p1 == 1'd0))) begin
        guard_variable_for_void_generate_arp_pkg_stream_stream_stream_ap_uint_ap_uint <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter1_fsm_state2) & (1'b1 == ap_block_state2_pp0_stage0_iter1))) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_phi_mux_header_header_1_flag_3_i_phi_fu_226_p8 == 1'd1))) begin
        header_header_1 <= ap_phi_mux_header_header_1_new_3_i_phi_fu_243_p8;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter1_fsm_state2) & (1'b1 == ap_block_state2_pp0_stage0_iter1))) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_phi_mux_header_idx_1_flag_2_i_phi_fu_194_p8 == 1'd1))) begin
        header_idx_1 <= ap_phi_mux_header_idx_1_new_2_i_phi_fu_210_p8;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_iter0_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_iter0_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state2_pp0_stage0_iter1)) begin
        ap_ST_iter1_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_iter1_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state2_pp0_stage0_iter1)) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_iter1_fsm_state0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_2_i_nbreadreq_fu_126_p3 == 1'd1) & (gap_state == 1'd0)) | ((tmp_7_i_nbreadreq_fu_134_p3 == 1'd1) & (tmp_2_i_nbreadreq_fu_126_p3 == 1'd0) & (gap_state == 1'd0)))) begin
        ap_phi_mux_header_header_1_flag_3_i_phi_fu_226_p8 = 1'd1;
    end else if (((gap_state_load_load_fu_288_p1 == 1'd1) | ((tmp_7_i_nbreadreq_fu_134_p3 == 1'd0) & (tmp_2_i_nbreadreq_fu_126_p3 == 1'd0) & (gap_state == 1'd0)))) begin
        ap_phi_mux_header_header_1_flag_3_i_phi_fu_226_p8 = ap_phi_mux_header_idx_1_flag_0_i_phi_fu_164_p4;
    end else begin
        ap_phi_mux_header_header_1_flag_3_i_phi_fu_226_p8 = ap_phi_reg_pp0_iter0_header_header_1_flag_3_i_reg_223;
    end
end

always @ (*) begin
    if (((tmp_2_i_nbreadreq_fu_126_p3 == 1'd1) & (gap_state == 1'd0))) begin
        ap_phi_mux_header_header_1_new_3_i_phi_fu_243_p8 = tmp_6_i_fu_399_p5;
    end else if (((tmp_7_i_nbreadreq_fu_134_p3 == 1'd1) & (tmp_2_i_nbreadreq_fu_126_p3 == 1'd0) & (gap_state == 1'd0))) begin
        ap_phi_mux_header_header_1_new_3_i_phi_fu_243_p8 = tmp_10_i_fu_330_p5;
    end else if (((gap_state_load_load_fu_288_p1 == 1'd1) | ((tmp_7_i_nbreadreq_fu_134_p3 == 1'd0) & (tmp_2_i_nbreadreq_fu_126_p3 == 1'd0) & (gap_state == 1'd0)))) begin
        ap_phi_mux_header_header_1_new_3_i_phi_fu_243_p8 = ap_phi_mux_sendWord_data_phi_fu_185_p4;
    end else begin
        ap_phi_mux_header_header_1_new_3_i_phi_fu_243_p8 = ap_phi_reg_pp0_iter0_header_header_1_new_3_i_reg_240;
    end
end

always @ (*) begin
    if ((guard_variable_for_void_generate_arp_pkg_stream_stream_stream_ap_uint_ap_uint_1_load_fu_255_p1 == 1'd1)) begin
        ap_phi_mux_header_idx_1_flag_0_i_phi_fu_164_p4 = 1'd0;
    end else if ((guard_variable_for_void_generate_arp_pkg_stream_stream_stream_ap_uint_ap_uint_1_load_fu_255_p1 == 1'd0)) begin
        ap_phi_mux_header_idx_1_flag_0_i_phi_fu_164_p4 = 1'd1;
    end else begin
        ap_phi_mux_header_idx_1_flag_0_i_phi_fu_164_p4 = ap_phi_reg_pp0_iter0_header_idx_1_flag_0_i_reg_161;
    end
end

always @ (*) begin
    if ((((tmp_2_i_nbreadreq_fu_126_p3 == 1'd1) & (gap_state == 1'd0)) | ((tmp_7_i_nbreadreq_fu_134_p3 == 1'd1) & (tmp_2_i_nbreadreq_fu_126_p3 == 1'd0) & (gap_state == 1'd0)) | ((tmp_7_i_nbreadreq_fu_134_p3 == 1'd0) & (tmp_2_i_nbreadreq_fu_126_p3 == 1'd0) & (gap_state == 1'd0)))) begin
        ap_phi_mux_header_idx_1_flag_2_i_phi_fu_194_p8 = 1'd1;
    end else if ((gap_state_load_load_fu_288_p1 == 1'd1)) begin
        ap_phi_mux_header_idx_1_flag_2_i_phi_fu_194_p8 = header_idx_1_flag_1_i_fu_438_p2;
    end else begin
        ap_phi_mux_header_idx_1_flag_2_i_phi_fu_194_p8 = ap_phi_reg_pp0_iter0_header_idx_1_flag_2_i_reg_191;
    end
end

always @ (*) begin
    if ((guard_variable_for_void_generate_arp_pkg_stream_stream_stream_ap_uint_ap_uint_1_load_fu_255_p1 == 1'd1)) begin
        ap_phi_mux_header_idx_1_loc_0_i_phi_fu_175_p4 = header_idx_1;
    end else if ((guard_variable_for_void_generate_arp_pkg_stream_stream_stream_ap_uint_ap_uint_1_load_fu_255_p1 == 1'd0)) begin
        ap_phi_mux_header_idx_1_loc_0_i_phi_fu_175_p4 = 16'd0;
    end else begin
        ap_phi_mux_header_idx_1_loc_0_i_phi_fu_175_p4 = ap_phi_reg_pp0_iter0_header_idx_1_loc_0_i_reg_172;
    end
end

always @ (*) begin
    if ((((tmp_2_i_nbreadreq_fu_126_p3 == 1'd1) & (gap_state == 1'd0)) | ((tmp_7_i_nbreadreq_fu_134_p3 == 1'd1) & (tmp_2_i_nbreadreq_fu_126_p3 == 1'd0) & (gap_state == 1'd0)) | ((tmp_7_i_nbreadreq_fu_134_p3 == 1'd0) & (tmp_2_i_nbreadreq_fu_126_p3 == 1'd0) & (gap_state == 1'd0)))) begin
        ap_phi_mux_header_idx_1_new_2_i_phi_fu_210_p8 = 16'd0;
    end else if ((gap_state_load_load_fu_288_p1 == 1'd1)) begin
        ap_phi_mux_header_idx_1_new_2_i_phi_fu_210_p8 = header_idx_1_new_1_i_fu_445_p3;
    end else begin
        ap_phi_mux_header_idx_1_new_2_i_phi_fu_210_p8 = ap_phi_reg_pp0_iter0_header_idx_1_new_2_i_reg_207;
    end
end

always @ (*) begin
    if ((guard_variable_for_void_generate_arp_pkg_stream_stream_stream_ap_uint_ap_uint_1_load_fu_255_p1 == 1'd1)) begin
        ap_phi_mux_sendWord_data_phi_fu_185_p4 = header_header_1;
    end else if ((guard_variable_for_void_generate_arp_pkg_stream_stream_stream_ap_uint_ap_uint_1_load_fu_255_p1 == 1'd0)) begin
        ap_phi_mux_sendWord_data_phi_fu_185_p4 = tmp_i_fu_269_p5;
    end else begin
        ap_phi_mux_sendWord_data_phi_fu_185_p4 = ap_phi_reg_pp0_iter0_sendWord_data_reg_182;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter1_fsm_state2) & (1'b1 == ap_block_state2_pp0_stage0_iter1))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((gap_state_load_reg_499 == 1'd1) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        arpDataOut_internal_blk_n = arpDataOut_internal_full_n;
    end else begin
        arpDataOut_internal_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state2_pp0_stage0_iter1)) & (gap_state_load_reg_499 == 1'd1) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        arpDataOut_internal_write_local = 1'b1;
    end else begin
        arpDataOut_internal_write_local = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (ap_start == 1'b1) & (ap_predicate_op43_read_state1 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        arpReplyMetaFifo_blk_n = arpReplyMetaFifo_empty_n;
    end else begin
        arpReplyMetaFifo_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter1_fsm_state2) & (1'b1 == ap_block_state2_pp0_stage0_iter1))) & (ap_predicate_op43_read_state1 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        arpReplyMetaFifo_read_local = 1'b1;
    end else begin
        arpReplyMetaFifo_read_local = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (ap_start == 1'b1) & (ap_predicate_op36_read_state1 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        arpRequestMetaFifo_blk_n = arpRequestMetaFifo_empty_n;
    end else begin
        arpRequestMetaFifo_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter1_fsm_state2) & (1'b1 == ap_block_state2_pp0_stage0_iter1))) & (ap_predicate_op36_read_state1 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        arpRequestMetaFifo_read_local = 1'b1;
    end else begin
        arpRequestMetaFifo_read_local = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (ap_start == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        myIpAddress_blk_n = myIpAddress_empty_n;
    end else begin
        myIpAddress_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter1_fsm_state2) & (1'b1 == ap_block_state2_pp0_stage0_iter1))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        myIpAddress_read_local = 1'b1;
    end else begin
        myIpAddress_read_local = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (ap_start == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        myMacAddress_blk_n = myMacAddress_empty_n;
    end else begin
        myMacAddress_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter1_fsm_state2) & (1'b1 == ap_block_state2_pp0_stage0_iter1))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        myMacAddress_read_local = 1'b1;
    end else begin
        myMacAddress_read_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_iter0_fsm)
        ap_ST_iter0_fsm_state1 : begin
            ap_NS_iter0_fsm = ap_ST_iter0_fsm_state1;
        end
        default : begin
            ap_NS_iter0_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter1_fsm)
        ap_ST_iter1_fsm_state2 : begin
            if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state2_pp0_stage0_iter1)) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state2_pp0_stage0_iter1)) & ((1'b0 == ap_CS_iter0_fsm_state1) | ((1'b1 == ap_CS_iter0_fsm_state1) & (1'b1 == ap_block_state1_pp0_stage0_iter0))))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end
        end
        ap_ST_iter1_fsm_state0 : begin
            if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter1_fsm_state2) & (1'b1 == ap_block_state2_pp0_stage0_iter1))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter1_fsm = 'bx;
        end
    endcase
end

assign add_ln85_fu_432_p2 = (ap_phi_mux_header_idx_1_loc_0_i_phi_fu_175_p4 + 16'd1);

assign ap_CS_iter0_fsm_state1 = ap_CS_iter0_fsm[32'd0];

assign ap_CS_iter1_fsm_state0 = ap_CS_iter1_fsm[32'd0];

assign ap_CS_iter1_fsm_state2 = ap_CS_iter1_fsm[32'd1];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1) | (myMacAddress_empty_n == 1'b0) | (myIpAddress_empty_n == 1'b0) | ((ap_predicate_op43_read_state1 == 1'b1) & (arpReplyMetaFifo_empty_n == 1'b0)) | ((ap_predicate_op36_read_state1 == 1'b1) & (arpRequestMetaFifo_empty_n == 1'b0)));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = ((gap_state_load_reg_499 == 1'd1) & (arpDataOut_internal_full_n == 1'b0));
end

assign ap_phi_reg_pp0_iter0_header_header_1_flag_3_i_reg_223 = 'bx;

assign ap_phi_reg_pp0_iter0_header_header_1_new_3_i_reg_240 = 'bx;

assign ap_phi_reg_pp0_iter0_header_idx_1_flag_0_i_reg_161 = 'bx;

assign ap_phi_reg_pp0_iter0_header_idx_1_flag_2_i_reg_191 = 'bx;

assign ap_phi_reg_pp0_iter0_header_idx_1_loc_0_i_reg_172 = 'bx;

assign ap_phi_reg_pp0_iter0_header_idx_1_new_2_i_reg_207 = 'bx;

assign ap_phi_reg_pp0_iter0_sendWord_data_reg_182 = 'bx;

always @ (*) begin
    ap_predicate_op36_read_state1 = ((tmp_7_i_nbreadreq_fu_134_p3 == 1'd1) & (tmp_2_i_nbreadreq_fu_126_p3 == 1'd0) & (gap_state == 1'd0));
end

always @ (*) begin
    ap_predicate_op43_read_state1 = ((tmp_2_i_nbreadreq_fu_126_p3 == 1'd1) & (gap_state == 1'd0));
end

assign arpDataOut_internal_din = zext_ln147_1_fu_491_p1;

assign arpDataOut_internal_write = arpDataOut_internal_write_local;

assign arpReplyMetaFifo_read = arpReplyMetaFifo_read_local;

assign arpRequestMetaFifo_read = arpRequestMetaFifo_read_local;

assign empty_fu_460_p3 = ((icmp_ln82_fu_426_p2[0:0] == 1'b1) ? ap_phi_mux_sendWord_data_phi_fu_185_p4 : 336'd0);

assign gap_state_load_load_fu_288_p1 = gap_state;

assign guard_variable_for_void_generate_arp_pkg_stream_stream_stream_ap_uint_ap_uint_1_load_fu_255_p1 = guard_variable_for_void_generate_arp_pkg_stream_stream_stream_ap_uint_ap_uint;

assign header_idx_1_flag_1_i_fu_438_p2 = (icmp_ln82_fu_426_p2 | ap_phi_mux_header_idx_1_flag_0_i_phi_fu_164_p4);

assign header_idx_1_new_1_i_fu_445_p3 = ((icmp_ln82_fu_426_p2[0:0] == 1'b1) ? add_ln85_fu_432_p2 : 16'd0);

assign icmp_ln82_fu_426_p2 = ((shl_ln_fu_418_p3 < 25'd336) ? 1'b1 : 1'b0);

assign myIpAddress_read = myIpAddress_read_local;

assign myMacAddress_read = myMacAddress_read_local;

assign shl_ln_fu_418_p3 = {{ap_phi_mux_header_idx_1_loc_0_i_phi_fu_175_p4}, {9'd0}};

assign tmp_10_i_fu_330_p5 = {{tmp_11_i_fu_316_p6}, {tmp_9_i4_fu_304_p5[159:0]}};

assign tmp_11_i_fu_316_p6 = {{{{{arpRequestMetaFifo_dout}, {48'd0}}, {myIpAddress_dout}}, {myMacAddress_dout}}, {16'd256}};

assign tmp_2_i_nbreadreq_fu_126_p3 = arpReplyMetaFifo_empty_n;

assign tmp_4_i1_fu_353_p5 = {{ap_phi_mux_sendWord_data_phi_fu_185_p4[335:48]}, {trunc_ln98_fu_349_p1}};

assign tmp_5_i2_fu_365_p5 = {{tmp_4_i1_fu_353_p5[335:96]}, {myMacAddress_dout}, {tmp_4_i1_fu_353_p5[47:0]}};

assign tmp_6_i_fu_399_p5 = {{tmp_i_35_fu_387_p5}, {tmp_5_i2_fu_365_p5[159:0]}};

assign tmp_7_i_nbreadreq_fu_134_p3 = arpRequestMetaFifo_empty_n;

assign tmp_8_i3_fu_292_p5 = {{ap_phi_mux_sendWord_data_phi_fu_185_p4[335:48]}, {48'd281474976710655}};

assign tmp_9_i4_fu_304_p5 = {{tmp_8_i3_fu_292_p5[335:96]}, {myMacAddress_dout}, {tmp_8_i3_fu_292_p5[47:0]}};

assign tmp_fu_377_p4 = {{arpReplyMetaFifo_dout[127:48]}};

assign tmp_i_35_fu_387_p5 = {{{{tmp_fu_377_p4}, {myIpAddress_dout}}, {myMacAddress_dout}}, {16'd512}};

assign tmp_i_fu_269_p5 = {{header_header_1[335:159]}, {63'd289919260388492808}, {header_header_1[95:0]}};

assign trunc_ln98_fu_349_p1 = arpReplyMetaFifo_dout[47:0];

assign zext_ln147_1_cast_fu_483_p3 = {{65'd18446748471756062719}, {zext_ln147_fu_480_p1}};

assign zext_ln147_1_fu_491_p1 = zext_ln147_1_cast_fu_483_p3;

assign zext_ln147_fu_480_p1 = empty_reg_509;

endmodule //arp_server_subnet_top_generate_arp_pkg_512_s
