# DDR clocks

####
### DDR4 c0
####

set_property -dict {PACKAGE_PIN AR36 IOSTANDARD SSTL12_DCI} [get_ports {c0_ddr4_adr[16]}]
set_property -dict {PACKAGE_PIN AP36 IOSTANDARD SSTL12_DCI} [get_ports {c0_ddr4_adr[15]}]
#set_property -dict {PACKAGE_PIN AN34 IOSTANDARD SSTL12_DCI     } [get_ports c0_ddr4_odt[1]   ]; # Bank 42 VCCO - VCC1V2 Net "DDR4_C0_ODT1"    - IO_L22N_T3U_N7_DBC_AD0N_42
#set_property -dict {PACKAGE_PIN AM34 IOSTANDARD SSTL12_DCI     } [get_ports c0_ddr4_cs_n[3]  ]; # Bank 42 VCCO - VCC1V2 Net "DDR4_C0_CS_B3"   - IO_L22P_T3U_N6_DBC_AD0P_42
set_property -dict {PACKAGE_PIN AR33 IOSTANDARD SSTL12_DCI} [get_ports {c0_ddr4_cs_n[0]}]
set_property -dict {PACKAGE_PIN AN36 IOSTANDARD SSTL12_DCI} [get_ports {c0_ddr4_adr[13]}]
#set_property -dict {PACKAGE_PIN AN35 IOSTANDARD SSTL12_DCI     } [get_ports c0_ddr4_adr[17]  ]; # Bank 42 VCCO - VCC1V2 Net "DDR4_C0_ADR17"   - IO_L24P_T3U_N10_42
set_property -dict {PACKAGE_PIN AP35 IOSTANDARD SSTL12_DCI} [get_ports {c0_ddr4_adr[14]}]
set_property -dict {PACKAGE_PIN AP34 IOSTANDARD SSTL12_DCI} [get_ports {c0_ddr4_odt[0]}]
#set_property -dict {PACKAGE_PIN AP33 IOSTANDARD SSTL12_DCI     } [get_ports c0_ddr4_cs_n[1]  ]; # Bank 42 VCCO - VCC1V2 Net "DDR4_C0_CS_B1"   - IO_L20N_T3L_N3_AD1N_42
#set_property -dict {PACKAGE_PIN AN33 IOSTANDARD SSTL12_DCI     } [get_ports c0_ddr4_cs_n[2]  ]; # Bank 42 VCCO - VCC1V2 Net "DDR4_C0_CS_B2"   - IO_L20P_T3L_N2_AD1P_42
set_property -dict {PACKAGE_PIN AT35 IOSTANDARD SSTL12_DCI} [get_ports {c0_ddr4_ba[0]}]
set_property -dict {PACKAGE_PIN AR35 IOSTANDARD SSTL12_DCI} [get_ports {c0_ddr4_adr[10]}]
set_property -dict {PACKAGE_PIN AW38 IOSTANDARD DIFF_SSTL12_DCI} [get_ports {c0_ddr4_ck_c[0]}]
set_property -dict {PACKAGE_PIN AV38 IOSTANDARD DIFF_SSTL12_DCI} [get_ports {c0_ddr4_ck_t[0]}]
#set_property -dict {PACKAGE_PIN AU35 IOSTANDARD DIFF_SSTL12_DCI} [get_ports c0_ddr4_ck_c[1]  ]; # Bank 42 VCCO - VCC1V2 Net "DDR4_C0_CK_C1"   - IO_L16N_T2U_N7_QBC_AD3N_42
#set_property -dict {PACKAGE_PIN AU34 IOSTANDARD DIFF_SSTL12_DCI} [get_ports c0_ddr4_ck_t[1]  ]; # Bank 42 VCCO - VCC1V2 Net "DDR4_C0_CK_T1"   - IO_L16P_T2U_N6_QBC_AD3P_42
set_property -dict {PACKAGE_PIN AT34 IOSTANDARD SSTL12_DCI} [get_ports {c0_ddr4_ba[1]}]
set_property -dict {PACKAGE_PIN AU36 IOSTANDARD SSTL12_DCI} [get_ports c0_ddr4_par]
set_property -dict {PACKAGE_PIN AT36 IOSTANDARD SSTL12_DCI} [get_ports {c0_ddr4_adr[0]}]
set_property -dict {PACKAGE_PIN AV37 IOSTANDARD SSTL12_DCI} [get_ports {c0_ddr4_adr[2]}]
set_property -dict {PACKAGE_PIN AV36 IOSTANDARD SSTL12_DCI} [get_ports {c0_ddr4_adr[1]}]
set_property -dict {PACKAGE_PIN AW36 IOSTANDARD SSTL12_DCI} [get_ports {c0_ddr4_adr[4]}]
set_property -dict {PACKAGE_PIN AW35 IOSTANDARD SSTL12_DCI} [get_ports {c0_ddr4_adr[3]}]
set_property -dict {PACKAGE_PIN BA37 IOSTANDARD SSTL12_DCI} [get_ports {c0_ddr4_adr[8]}]
set_property -dict {PACKAGE_PIN BA40 IOSTANDARD SSTL12_DCI} [get_ports {c0_ddr4_adr[7]}]
set_property -dict {PACKAGE_PIN BA39 IOSTANDARD SSTL12_DCI} [get_ports {c0_ddr4_adr[11]}]
set_property -dict {PACKAGE_PIN BB37 IOSTANDARD SSTL12_DCI} [get_ports {c0_ddr4_adr[9]}]
set_property -dict {PACKAGE_PIN AY36 IOSTANDARD SSTL12_DCI} [get_ports {c0_ddr4_adr[5]}]
set_property -dict {PACKAGE_PIN AY35 IOSTANDARD SSTL12_DCI} [get_ports {c0_ddr4_adr[6]}]
#set_property -dict {PACKAGE_PIN BC40 IOSTANDARD SSTL12_DCI     } [get_ports c0_ddr4_cke[1]   ]; # Bank 42 VCCO - VCC1V2 Net "DDR4_C0_CKE1"    - IO_L9N_T1L_N5_AD12N_42
set_property -dict {PACKAGE_PIN BC39 IOSTANDARD SSTL12_DCI} [get_ports {c0_ddr4_bg[1]}]
set_property -dict {PACKAGE_PIN BB40 IOSTANDARD SSTL12_DCI} [get_ports {c0_ddr4_adr[12]}]
set_property -dict {PACKAGE_PIN BB39 IOSTANDARD SSTL12_DCI} [get_ports c0_ddr4_act_n]
set_property -dict {PACKAGE_PIN BC38 IOSTANDARD SSTL12_DCI} [get_ports {c0_ddr4_cke[0]}]
set_property -dict {PACKAGE_PIN BC37 IOSTANDARD SSTL12_DCI} [get_ports {c0_ddr4_bg[0]}]
set_property -dict {PACKAGE_PIN BF43 IOSTANDARD POD12_DCI} [get_ports {c0_ddr4_dq[66]}]
set_property -dict {PACKAGE_PIN BF42 IOSTANDARD POD12_DCI} [get_ports {c0_ddr4_dq[67]}]
set_property -dict {PACKAGE_PIN BF38 IOSTANDARD DIFF_POD12_DCI} [get_ports {c0_ddr4_dqs_c[16]}]
set_property -dict {PACKAGE_PIN BE38 IOSTANDARD DIFF_POD12_DCI} [get_ports {c0_ddr4_dqs_t[16]}]
set_property -dict {PACKAGE_PIN BD40 IOSTANDARD POD12_DCI} [get_ports {c0_ddr4_dq[64]}]
set_property -dict {PACKAGE_PIN BD39 IOSTANDARD POD12_DCI} [get_ports {c0_ddr4_dq[65]}]
set_property -dict {PACKAGE_PIN BF41 IOSTANDARD POD12_DCI} [get_ports {c0_ddr4_dq[71]}]
set_property -dict {PACKAGE_PIN BE40 IOSTANDARD POD12_DCI} [get_ports {c0_ddr4_dq[70]}]
set_property -dict {PACKAGE_PIN BF37 IOSTANDARD POD12_DCI} [get_ports {c0_ddr4_dq[68]}]
set_property -dict {PACKAGE_PIN BE37 IOSTANDARD POD12_DCI} [get_ports {c0_ddr4_dq[69]}]
set_property -dict {PACKAGE_PIN BF40 IOSTANDARD DIFF_POD12_DCI} [get_ports {c0_ddr4_dqs_c[17]}]
set_property -dict {PACKAGE_PIN BF39 IOSTANDARD DIFF_POD12_DCI} [get_ports {c0_ddr4_dqs_t[17]}]
set_property -dict {PACKAGE_PIN AU32 IOSTANDARD POD12_DCI} [get_ports {c0_ddr4_dq[34]}]
set_property -dict {PACKAGE_PIN AT32 IOSTANDARD POD12_DCI} [get_ports {c0_ddr4_dq[35]}]
set_property -dict {PACKAGE_PIN AM32 IOSTANDARD DIFF_POD12_DCI} [get_ports {c0_ddr4_dqs_c[8]}]
set_property -dict {PACKAGE_PIN AM31 IOSTANDARD DIFF_POD12_DCI} [get_ports {c0_ddr4_dqs_t[8]}]
#set_property -dict {PACKAGE_PIN AT33 IOSTANDARD LVCMOS12       } [get_ports c0_ddr4_event_n  ]; # Bank 41 VCCO - VCC1V2 Net "DDR4_C0_EVENT_B" - IO_T3U_N12_41
set_property -dict {PACKAGE_PIN AM30 IOSTANDARD POD12_DCI} [get_ports {c0_ddr4_dq[33]}]
set_property -dict {PACKAGE_PIN AL30 IOSTANDARD POD12_DCI} [get_ports {c0_ddr4_dq[32]}]
set_property -dict {PACKAGE_PIN AR32 IOSTANDARD POD12_DCI} [get_ports {c0_ddr4_dq[38]}]
set_property -dict {PACKAGE_PIN AR31 IOSTANDARD POD12_DCI} [get_ports {c0_ddr4_dq[39]}]
set_property -dict {PACKAGE_PIN AN32 IOSTANDARD POD12_DCI} [get_ports {c0_ddr4_dq[37]}]
set_property -dict {PACKAGE_PIN AN31 IOSTANDARD POD12_DCI} [get_ports {c0_ddr4_dq[36]}]
set_property -dict {PACKAGE_PIN AP31 IOSTANDARD DIFF_POD12_DCI} [get_ports {c0_ddr4_dqs_c[9]}]
set_property -dict {PACKAGE_PIN AP30 IOSTANDARD DIFF_POD12_DCI} [get_ports {c0_ddr4_dqs_t[9]}]
set_property -dict {PACKAGE_PIN AV32 IOSTANDARD POD12_DCI} [get_ports {c0_ddr4_dq[25]}]
set_property -dict {PACKAGE_PIN AV31 IOSTANDARD POD12_DCI} [get_ports {c0_ddr4_dq[24]}]
set_property -dict {PACKAGE_PIN AW33 IOSTANDARD DIFF_POD12_DCI} [get_ports {c0_ddr4_dqs_c[6]}]
set_property -dict {PACKAGE_PIN AV33 IOSTANDARD DIFF_POD12_DCI} [get_ports {c0_ddr4_dqs_t[6]}]
set_property -dict {PACKAGE_PIN AU31 IOSTANDARD LVCMOS12} [get_ports c0_ddr4_reset_n]
set_property -dict {PACKAGE_PIN AW34 IOSTANDARD POD12_DCI} [get_ports {c0_ddr4_dq[27]}]
set_property -dict {PACKAGE_PIN AV34 IOSTANDARD POD12_DCI} [get_ports {c0_ddr4_dq[26]}]
set_property -dict {PACKAGE_PIN AY31 IOSTANDARD POD12_DCI} [get_ports {c0_ddr4_dq[29]}]
set_property -dict {PACKAGE_PIN AW31 IOSTANDARD POD12_DCI} [get_ports {c0_ddr4_dq[28]}]
set_property -dict {PACKAGE_PIN BA35 IOSTANDARD POD12_DCI} [get_ports {c0_ddr4_dq[30]}]
set_property -dict {PACKAGE_PIN BA34 IOSTANDARD POD12_DCI} [get_ports {c0_ddr4_dq[31]}]
set_property -dict {PACKAGE_PIN BA33 IOSTANDARD DIFF_POD12_DCI} [get_ports {c0_ddr4_dqs_c[7]}]
set_property -dict {PACKAGE_PIN BA32 IOSTANDARD DIFF_POD12_DCI} [get_ports {c0_ddr4_dqs_t[7]}]
set_property -dict {PACKAGE_PIN BB32 IOSTANDARD POD12_DCI} [get_ports {c0_ddr4_dq[17]}]
set_property -dict {PACKAGE_PIN BB31 IOSTANDARD POD12_DCI} [get_ports {c0_ddr4_dq[16]}]
set_property -dict {PACKAGE_PIN BB36 IOSTANDARD DIFF_POD12_DCI} [get_ports {c0_ddr4_dqs_c[4]}]
set_property -dict {PACKAGE_PIN BB35 IOSTANDARD DIFF_POD12_DCI} [get_ports {c0_ddr4_dqs_t[4]}]
set_property -dict {PACKAGE_PIN AY33 IOSTANDARD POD12_DCI} [get_ports {c0_ddr4_dq[19]}]
set_property -dict {PACKAGE_PIN AY32 IOSTANDARD POD12_DCI} [get_ports {c0_ddr4_dq[18]}]
set_property -dict {PACKAGE_PIN BC33 IOSTANDARD POD12_DCI} [get_ports {c0_ddr4_dq[21]}]
set_property -dict {PACKAGE_PIN BC32 IOSTANDARD POD12_DCI} [get_ports {c0_ddr4_dq[20]}]
set_property -dict {PACKAGE_PIN BC34 IOSTANDARD POD12_DCI} [get_ports {c0_ddr4_dq[23]}]
set_property -dict {PACKAGE_PIN BB34 IOSTANDARD POD12_DCI} [get_ports {c0_ddr4_dq[22]}]
set_property -dict {PACKAGE_PIN BD31 IOSTANDARD DIFF_POD12_DCI} [get_ports {c0_ddr4_dqs_c[5]}]
set_property -dict {PACKAGE_PIN BC31 IOSTANDARD DIFF_POD12_DCI} [get_ports {c0_ddr4_dqs_t[5]}]
set_property -dict {PACKAGE_PIN BE33 IOSTANDARD POD12_DCI} [get_ports {c0_ddr4_dq[58]}]
set_property -dict {PACKAGE_PIN BD33 IOSTANDARD POD12_DCI} [get_ports {c0_ddr4_dq[57]}]
set_property -dict {PACKAGE_PIN BE36 IOSTANDARD DIFF_POD12_DCI} [get_ports {c0_ddr4_dqs_c[14]}]
set_property -dict {PACKAGE_PIN BE35 IOSTANDARD DIFF_POD12_DCI} [get_ports {c0_ddr4_dqs_t[14]}]
set_property -dict {PACKAGE_PIN BD35 IOSTANDARD POD12_DCI} [get_ports {c0_ddr4_dq[59]}]
set_property -dict {PACKAGE_PIN BD34 IOSTANDARD POD12_DCI} [get_ports {c0_ddr4_dq[56]}]
set_property -dict {PACKAGE_PIN BF33 IOSTANDARD POD12_DCI} [get_ports {c0_ddr4_dq[61]}]
set_property -dict {PACKAGE_PIN BF32 IOSTANDARD POD12_DCI} [get_ports {c0_ddr4_dq[60]}]
set_property -dict {PACKAGE_PIN BF35 IOSTANDARD POD12_DCI} [get_ports {c0_ddr4_dq[63]}]
set_property -dict {PACKAGE_PIN BF34 IOSTANDARD POD12_DCI} [get_ports {c0_ddr4_dq[62]}]
set_property -dict {PACKAGE_PIN BE32 IOSTANDARD DIFF_POD12_DCI} [get_ports {c0_ddr4_dqs_c[15]}]
set_property -dict {PACKAGE_PIN BE31 IOSTANDARD DIFF_POD12_DCI} [get_ports {c0_ddr4_dqs_t[15]}]
set_property -dict {PACKAGE_PIN AP29 IOSTANDARD POD12_DCI} [get_ports {c0_ddr4_dq[40]}]
set_property -dict {PACKAGE_PIN AP28 IOSTANDARD POD12_DCI} [get_ports {c0_ddr4_dq[41]}]
set_property -dict {PACKAGE_PIN AL29 IOSTANDARD DIFF_POD12_DCI} [get_ports {c0_ddr4_dqs_c[10]}]
set_property -dict {PACKAGE_PIN AL28 IOSTANDARD DIFF_POD12_DCI} [get_ports {c0_ddr4_dqs_t[10]}]
set_property -dict {PACKAGE_PIN AN27 IOSTANDARD POD12_DCI} [get_ports {c0_ddr4_dq[42]}]
set_property -dict {PACKAGE_PIN AM27 IOSTANDARD POD12_DCI} [get_ports {c0_ddr4_dq[43]}]
set_property -dict {PACKAGE_PIN AR28 IOSTANDARD POD12_DCI} [get_ports {c0_ddr4_dq[47]}]
set_property -dict {PACKAGE_PIN AR27 IOSTANDARD POD12_DCI} [get_ports {c0_ddr4_dq[46]}]
set_property -dict {PACKAGE_PIN AN29 IOSTANDARD POD12_DCI} [get_ports {c0_ddr4_dq[44]}]
set_property -dict {PACKAGE_PIN AM29 IOSTANDARD POD12_DCI} [get_ports {c0_ddr4_dq[45]}]
set_property -dict {PACKAGE_PIN AT30 IOSTANDARD DIFF_POD12_DCI} [get_ports {c0_ddr4_dqs_c[11]}]
set_property -dict {PACKAGE_PIN AR30 IOSTANDARD DIFF_POD12_DCI} [get_ports {c0_ddr4_dqs_t[11]}]
set_property -dict {PACKAGE_PIN AV27 IOSTANDARD POD12_DCI} [get_ports {c0_ddr4_dq[49]}]
set_property -dict {PACKAGE_PIN AU27 IOSTANDARD POD12_DCI} [get_ports {c0_ddr4_dq[50]}]
set_property -dict {PACKAGE_PIN AU30 IOSTANDARD DIFF_POD12_DCI} [get_ports {c0_ddr4_dqs_c[12]}]
set_property -dict {PACKAGE_PIN AU29 IOSTANDARD DIFF_POD12_DCI} [get_ports {c0_ddr4_dqs_t[12]}]
set_property -dict {PACKAGE_PIN AT28 IOSTANDARD POD12_DCI} [get_ports {c0_ddr4_dq[48]}]
set_property -dict {PACKAGE_PIN AT27 IOSTANDARD POD12_DCI} [get_ports {c0_ddr4_dq[51]}]
set_property -dict {PACKAGE_PIN AV29 IOSTANDARD POD12_DCI} [get_ports {c0_ddr4_dq[52]}]
set_property -dict {PACKAGE_PIN AV28 IOSTANDARD POD12_DCI} [get_ports {c0_ddr4_dq[55]}]
set_property -dict {PACKAGE_PIN AY30 IOSTANDARD POD12_DCI} [get_ports {c0_ddr4_dq[53]}]
set_property -dict {PACKAGE_PIN AW30 IOSTANDARD POD12_DCI} [get_ports {c0_ddr4_dq[54]}]
set_property -dict {PACKAGE_PIN AY28 IOSTANDARD DIFF_POD12_DCI} [get_ports {c0_ddr4_dqs_c[13]}]
set_property -dict {PACKAGE_PIN AY27 IOSTANDARD DIFF_POD12_DCI} [get_ports {c0_ddr4_dqs_t[13]}]
set_property -dict {PACKAGE_PIN BA28 IOSTANDARD POD12_DCI} [get_ports {c0_ddr4_dq[2]}]
set_property -dict {PACKAGE_PIN BA27 IOSTANDARD POD12_DCI} [get_ports {c0_ddr4_dq[3]}]
set_property -dict {PACKAGE_PIN BB30 IOSTANDARD DIFF_POD12_DCI} [get_ports {c0_ddr4_dqs_c[0]}]
set_property -dict {PACKAGE_PIN BA30 IOSTANDARD DIFF_POD12_DCI} [get_ports {c0_ddr4_dqs_t[0]}]
set_property -dict {PACKAGE_PIN AW29 IOSTANDARD POD12_DCI} [get_ports {c0_ddr4_dq[1]}]
set_property -dict {PACKAGE_PIN AW28 IOSTANDARD POD12_DCI} [get_ports {c0_ddr4_dq[0]}]
set_property -dict {PACKAGE_PIN BC27 IOSTANDARD POD12_DCI} [get_ports {c0_ddr4_dq[6]}]
set_property -dict {PACKAGE_PIN BB27 IOSTANDARD POD12_DCI} [get_ports {c0_ddr4_dq[7]}]
set_property -dict {PACKAGE_PIN BB29 IOSTANDARD POD12_DCI} [get_ports {c0_ddr4_dq[4]}]
set_property -dict {PACKAGE_PIN BA29 IOSTANDARD POD12_DCI} [get_ports {c0_ddr4_dq[5]}]
set_property -dict {PACKAGE_PIN BC26 IOSTANDARD DIFF_POD12_DCI} [get_ports {c0_ddr4_dqs_c[1]}]
set_property -dict {PACKAGE_PIN BB26 IOSTANDARD DIFF_POD12_DCI} [get_ports {c0_ddr4_dqs_t[1]}]
set_property -dict {PACKAGE_PIN BF28 IOSTANDARD POD12_DCI} [get_ports {c0_ddr4_dq[9]}]
set_property -dict {PACKAGE_PIN BE28 IOSTANDARD POD12_DCI} [get_ports {c0_ddr4_dq[8]}]
set_property -dict {PACKAGE_PIN BD29 IOSTANDARD DIFF_POD12_DCI} [get_ports {c0_ddr4_dqs_c[2]}]
set_property -dict {PACKAGE_PIN BD28 IOSTANDARD DIFF_POD12_DCI} [get_ports {c0_ddr4_dqs_t[2]}]
set_property -dict {PACKAGE_PIN BE30 IOSTANDARD POD12_DCI} [get_ports {c0_ddr4_dq[10]}]
set_property -dict {PACKAGE_PIN BD30 IOSTANDARD POD12_DCI} [get_ports {c0_ddr4_dq[11]}]
set_property -dict {PACKAGE_PIN BF27 IOSTANDARD POD12_DCI} [get_ports {c0_ddr4_dq[12]}]
set_property -dict {PACKAGE_PIN BE27 IOSTANDARD POD12_DCI} [get_ports {c0_ddr4_dq[13]}]
set_property -dict {PACKAGE_PIN BF30 IOSTANDARD POD12_DCI} [get_ports {c0_ddr4_dq[14]}]
set_property -dict {PACKAGE_PIN BF29 IOSTANDARD POD12_DCI} [get_ports {c0_ddr4_dq[15]}]
set_property -dict {PACKAGE_PIN BE26 IOSTANDARD DIFF_POD12_DCI} [get_ports {c0_ddr4_dqs_c[3]}]
set_property -dict {PACKAGE_PIN BD26 IOSTANDARD DIFF_POD12_DCI} [get_ports {c0_ddr4_dqs_t[3]}]

set_property PACKAGE_PIN AY37 [get_ports c0_sys_clk_p]
set_property PACKAGE_PIN AY38 [get_ports c0_sys_clk_n]

set_property IOSTANDARD DIFF_POD12_DCI [get_ports c0_sys_clk_n]
set_property IOSTANDARD DIFF_POD12_DCI [get_ports c0_sys_clk_p]

####################################################################################
# Constraints from file : 'u250_ddr_1.xdc'
####################################################################################

