create_ip -name ila -vendor xilinx.com -library ip -version 6.2 -module_name ila_perf
set_property -dict [list CONFIG.C_PROBE42_WIDTH {32} CONFIG.C_PROBE41_WIDTH {32} CONFIG.C_PROBE40_WIDTH {32} CONFIG.C_PROBE39_WIDTH {32} CONFIG.C_PROBE30_WIDTH {32} CONFIG.C_PROBE29_WIDTH {16} CONFIG.C_PROBE28_WIDTH {32} CONFIG.C_PROBE27_WIDTH {16} CONFIG.C_PROBE26_WIDTH {64} CONFIG.C_PROBE25_WIDTH {30} CONFIG.C_PROBE21_WIDTH {16} CONFIG.C_PROBE20_WIDTH {32} CONFIG.C_PROBE19_WIDTH {16} CONFIG.C_PROBE18_WIDTH {64} CONFIG.C_PROBE17_WIDTH {64} CONFIG.C_PROBE16_WIDTH {32} CONFIG.C_PROBE15_WIDTH {2} CONFIG.C_NUM_OF_PROBES {43} CONFIG.Component_Name {ila_perf} CONFIG.C_INPUT_PIPE_STAGES {1} CONFIG.ALL_PROBE_SAME_MU_CNT {5}] [get_ips ila_perf]

create_ip -name ila -vendor xilinx.com -library ip -version 6.2 -module_name ila_mem_inf
set_property -dict [list CONFIG.C_PROBE13_WIDTH {32} CONFIG.C_PROBE10_WIDTH {32} CONFIG.C_PROBE7_WIDTH {23} CONFIG.C_PROBE6_WIDTH {64} CONFIG.C_PROBE3_WIDTH {23} CONFIG.C_PROBE2_WIDTH {64} CONFIG.C_NUM_OF_PROBES {31} CONFIG.Component_Name {ila_mem_inf} CONFIG.C_INPUT_PIPE_STAGES {1}] [get_ips ila_mem_inf]

create_ip -name ila -vendor xilinx.com -library ip -version 6.2 -module_name ila_network_statistic
set_property -dict [list CONFIG.C_PROBE10_WIDTH {8} CONFIG.C_PROBE9_WIDTH {16} CONFIG.C_PROBE8_WIDTH {16} CONFIG.C_PROBE7_WIDTH {16} CONFIG.C_PROBE6_WIDTH {16} CONFIG.C_PROBE5_WIDTH {16} CONFIG.C_PROBE4_WIDTH {16} CONFIG.C_PROBE3_WIDTH {16} CONFIG.C_PROBE2_WIDTH {16} CONFIG.C_PROBE1_WIDTH {16} CONFIG.C_PROBE0_WIDTH {16} CONFIG.C_NUM_OF_PROBES {11} CONFIG.Component_Name {ila_network_statistic} CONFIG.C_INPUT_PIPE_STAGES {1}] [get_ips ila_network_statistic]

create_ip -name ila -vendor xilinx.com -library ip -version 6.2 -module_name ila_controller
set_property -dict [list CONFIG.C_PROBE8_WIDTH {16} CONFIG.C_PROBE7_WIDTH {16} CONFIG.C_PROBE6_WIDTH {64} CONFIG.C_PROBE5_WIDTH {32} CONFIG.C_PROBE4_WIDTH {32} CONFIG.C_PROBE3_WIDTH {16} CONFIG.C_PROBE2_WIDTH {16} CONFIG.C_NUM_OF_PROBES {11} CONFIG.Component_Name {ila_controller} CONFIG.C_INPUT_PIPE_STAGES {1}] [get_ips ila_controller]


set_property TRIGGER_COMPARE_VALUE eq1'b1 [get_hw_probes inst_dynamic/inst_user_wrapper_0/inst_user_c0_0/user_role/s_axis_tcp_port_status_tvalid -of_objects [get_hw_ilas -of_objects [get_hw_devices xcvu9p_0] -filter {CELL_NAME=~"inst_dynamic/inst_user_wrapper_0/inst_user_c0_0/user_role/benchmark_debug"}]]
set_property TRIGGER_COMPARE_VALUE eq1'b1 [get_hw_probes inst_dynamic/inst_user_wrapper_0/inst_user_c0_0/user_role/m_axis_tcp_listen_port_tvalid -of_objects [get_hw_ilas -of_objects [get_hw_devices xcvu9p_0] -filter {CELL_NAME=~"inst_dynamic/inst_user_wrapper_0/inst_user_c0_0/user_role/benchmark_debug"}]]
set_property TRIGGER_COMPARE_VALUE eq1'b1 [get_hw_probes inst_dynamic/inst_user_wrapper_0/inst_user_c0_0/user_role/m_axis_tcp_open_connection_tvalid -of_objects [get_hw_ilas -of_objects [get_hw_devices xcvu9p_0] -filter {CELL_NAME=~"inst_dynamic/inst_user_wrapper_0/inst_user_c0_0/user_role/benchmark_debug"}]]
set_property TRIGGER_COMPARE_VALUE eq1'b1 [get_hw_probes inst_dynamic/inst_user_wrapper_0/inst_user_c0_0/user_role/m_axis_tcp_read_pkg_tvalid -of_objects [get_hw_ilas -of_objects [get_hw_devices xcvu9p_0] -filter {CELL_NAME=~"inst_dynamic/inst_user_wrapper_0/inst_user_c0_0/user_role/benchmark_debug"}]]
set_property TRIGGER_COMPARE_VALUE eq1'b1 [get_hw_probes inst_dynamic/inst_user_wrapper_0/inst_user_c0_0/user_role/m_axis_tcp_tx_meta_tvalid -of_objects [get_hw_ilas -of_objects [get_hw_devices xcvu9p_0] -filter {CELL_NAME=~"inst_dynamic/inst_user_wrapper_0/inst_user_c0_0/user_role/benchmark_debug"}]]
set_property TRIGGER_COMPARE_VALUE eq1'bB [get_hw_probes inst_dynamic/inst_user_wrapper_0/inst_user_c0_0/user_role/running -of_objects [get_hw_ilas -of_objects [get_hw_devices xcvu9p_0] -filter {CELL_NAME=~"inst_dynamic/inst_user_wrapper_0/inst_user_c0_0/user_role/benchmark_debug"}]]
set_property TRIGGER_COMPARE_VALUE eq1'b1 [get_hw_probes inst_dynamic/inst_user_wrapper_0/inst_user_c0_0/user_role/s_axis_tcp_notification_tvalid -of_objects [get_hw_ilas -of_objects [get_hw_devices xcvu9p_0] -filter {CELL_NAME=~"inst_dynamic/inst_user_wrapper_0/inst_user_c0_0/user_role/benchmark_debug"}]]
set_property TRIGGER_COMPARE_VALUE eq1'b1 [get_hw_probes inst_dynamic/inst_user_wrapper_0/inst_user_c0_0/user_role/s_axis_tcp_open_status_tvalid -of_objects [get_hw_ilas -of_objects [get_hw_devices xcvu9p_0] -filter {CELL_NAME=~"inst_dynamic/inst_user_wrapper_0/inst_user_c0_0/user_role/benchmark_debug"}]]
set_property TRIGGER_COMPARE_VALUE {eq1'b1 eq1'b1} [get_hw_probes inst_dynamic/inst_user_wrapper_0/inst_user_c0_0/user_role/s_axis_tcp_port_status_tvalid -of_objects [get_hw_ilas -of_objects [get_hw_devices xcvu9p_0] -filter {CELL_NAME=~"inst_dynamic/inst_user_wrapper_0/inst_user_c0_0/user_role/benchmark_debug"}]]
set_property TRIGGER_COMPARE_VALUE {eq1'b1 eq1'b1} [get_hw_probes inst_dynamic/inst_user_wrapper_0/inst_user_c0_0/user_role/s_axis_tcp_port_status_tvalid -of_objects [get_hw_ilas -of_objects [get_hw_devices xcvu9p_0] -filter {CELL_NAME=~"inst_dynamic/inst_user_wrapper_0/inst_user_c0_0/user_role/benchmark_debug"}]]
set_property TRIGGER_COMPARE_VALUE eq1'b1 [get_hw_probes inst_dynamic/inst_user_wrapper_0/inst_user_c0_0/user_role/s_axis_tcp_port_status_tvalid -of_objects [get_hw_ilas -of_objects [get_hw_devices xcvu9p_0] -filter {CELL_NAME=~"inst_dynamic/inst_user_wrapper_0/inst_user_c0_0/user_role/benchmark_debug"}]]
set_property TRIGGER_COMPARE_VALUE eq1'b1 [get_hw_probes inst_dynamic/inst_user_wrapper_0/inst_user_c0_0/user_role/s_axis_tcp_rx_meta_tvalid -of_objects [get_hw_ilas -of_objects [get_hw_devices xcvu9p_0] -filter {CELL_NAME=~"inst_dynamic/inst_user_wrapper_0/inst_user_c0_0/user_role/benchmark_debug"}]]
set_property TRIGGER_COMPARE_VALUE eq1'b1 [get_hw_probes inst_dynamic/inst_user_wrapper_0/inst_user_c0_0/user_role/s_axis_tcp_tx_status_tvalid -of_objects [get_hw_ilas -of_objects [get_hw_devices xcvu9p_0] -filter {CELL_NAME=~"inst_dynamic/inst_user_wrapper_0/inst_user_c0_0/user_role/benchmark_debug"}]]
set_property CONTROL.TRIGGER_CONDITION OR [get_hw_ilas -of_objects [get_hw_devices xcvu9p_0] -filter {CELL_NAME=~"inst_dynamic/inst_user_wrapper_0/inst_user_c0_0/user_role/benchmark_debug"}]
startgroup 
set_property CONTROL.DATA_DEPTH 16 [get_hw_ilas -of_objects [get_hw_devices xcvu9p_0] -filter {CELL_NAME=~"inst_dynamic/inst_user_wrapper_0/inst_user_c0_0/user_role/benchmark_debug"}]
set_property CONTROL.TRIGGER_POSITION 15 [get_hw_ilas -of_objects [get_hw_devices xcvu9p_0] -filter {CELL_NAME=~"inst_dynamic/inst_user_wrapper_0/inst_user_c0_0/user_role/benchmark_debug"}]
set_property CONTROL.WINDOW_COUNT 64 [get_hw_ilas -of_objects [get_hw_devices xcvu9p_0] -filter {CELL_NAME=~"inst_dynamic/inst_user_wrapper_0/inst_user_c0_0/user_role/benchmark_debug"}]
endgroup
set_property CONTROL.TRIGGER_POSITION 1 [get_hw_ilas -of_objects [get_hw_devices xcvu9p_0] -filter {CELL_NAME=~"inst_dynamic/inst_user_wrapper_0/inst_user_c0_0/user_role/benchmark_debug"}]
