extends: ../hls4ml_selected_feasible_candidates/res512_layers7_W8A8_P50_RFbase.yaml

experiment:
  name: res512_layers7_W8A8_P50_manual_v1_global
  phase: hand_tuning
  suite: hls4ml_hand_tuning
  tier: green
  source_experiment: res512_layers7_W8A8_P50_RFbase
  hand_optimized: true
  hand_tuning_label: Manual v1 global
  selected_run_root: /pub/scratch/sdeheredia/Coyote/examples/ml_baseline/hls4ml/artifacts_selected_feasible_candidates/cnn_small_hls_opt_img512/notebook_pruned_qat/res512_layers7_W8A8_P50_RFbase_b3a09a3d898b
  selected_hls_sweep_root: /pub/scratch/sdeheredia/Coyote/examples/ml_baseline/hls4ml/artifacts_selected_feasible_candidates/cnn_small_hls_opt_img512/notebook_pruned_qat/res512_layers7_W8A8_P50_manual_v1_global_a3b46c23cc50/hls_sweeps/manual_v1_global_hls_e8b0dc08647f

run:
  iteration_name: res512_layers7_W8A8_P50_manual_v1_global

training:
  allow_stale_fold_cache: true

hls:
  sweep_name: manual_v1_global
  layer_tuning:
    mode: manual_layers
    layers:
      conv0: {Strategy: Latency, ReuseFactor: 1}
      conv1: {Strategy: Latency, ReuseFactor: 1}
      conv2: {Strategy: Resource, ReuseFactor: 32}
      conv3: {Strategy: Resource, ReuseFactor: 32}
      conv4: {Strategy: Resource, ReuseFactor: 32}
      conv5: {Strategy: Resource, ReuseFactor: 32}
      conv6: {Strategy: Resource, ReuseFactor: 32}

      act0: {Strategy: Latency, ReuseFactor: 1}
      act1: {Strategy: Latency, ReuseFactor: 1}
      act2: {Strategy: Resource, ReuseFactor: 32}
      act3: {Strategy: Resource, ReuseFactor: 32}
      act4: {Strategy: Resource, ReuseFactor: 32}
      act5: {Strategy: Resource, ReuseFactor: 32}
      act6: {Strategy: Resource, ReuseFactor: 32}

      pool0: {Strategy: Latency, ReuseFactor: 1}
      pool1: {Strategy: Latency, ReuseFactor: 1}
      pool2: {Strategy: Resource, ReuseFactor: 32}
      pool3: {Strategy: Resource, ReuseFactor: 32}
      pool4: {Strategy: Resource, ReuseFactor: 32}
      pool5: {Strategy: Resource, ReuseFactor: 32}
      pool6: {Strategy: Resource, ReuseFactor: 32}

      pad_conv0: {Strategy: Latency, ReuseFactor: 1}
      pad_conv1: {Strategy: Latency, ReuseFactor: 1}
      pad_conv2: {Strategy: Resource, ReuseFactor: 32}
      pad_conv3: {Strategy: Resource, ReuseFactor: 32}
      pad_conv4: {Strategy: Resource, ReuseFactor: 32}
      pad_conv5: {Strategy: Resource, ReuseFactor: 32}
      pad_conv6: {Strategy: Resource, ReuseFactor: 32}

      gap: {Strategy: Resource, ReuseFactor: 32}
