##
## Default examples
##

if(NOT EXAMPLE EQUAL 0) 
    if(EXAMPLE STREQUAL "bmark_host") #
        message("** Link benchmarks, host. Force config.")
        set(EN_HLS 0)
        set(EN_MEM 0)
        set(EN_STRM 1) # Should work with MEM as well
        set(EN_MEM 0)  
        set(N_REGIONS 3)
    elseif(EXAMPLE STREQUAL "bmark_fpga")
        message("** Link benchmarks, fpga. Force config.")
        set(EN_HLS 0)
        set(EN_BPSS 1) 
        set(EN_STRM 1) # Should work with MEM as well
        set(EN_MEM 0) 
        set(EN_WB 1)
    elseif(EXAMPLE STREQUAL "gbm_dtrees")
        message("** Gradient boosting decision tree benchmarks. Force config.")
        set(EN_HLS 0)
        set(EN_STRM 1)
        set(EN_MEM 0)
    elseif(EXAMPLE STREQUAL "hyper_log_log")
        message("** HyperLogLog cardinality estimation. Force config.")
        set(EN_HLS 1)
        set(EN_STRM 1)
        set(EN_MEM 0)
    elseif(EXAMPLE STREQUAL "service_aes")
        message("** Coyote as a service (AES). Force config.")
        set(EN_HLS 0)
        set(EN_STRM 1)
        set(EN_MEM 0)
        set(N_REGIONS 1)
    elseif(EXAMPLE STREQUAL "dram") 
        message("** Striping DRAM example. Force config.")
        set(N_REGIONS 4)
        set(EN_HLS 0)
        set(EN_STRM 0)
        set(EN_MEM 1)
        set(N_DDR_CHAN 2) # This depends on how many channels you actually have, u250 for instance can go up to 4
    elseif(EXAMPLE STREQUAL "hbm") 
        message("** Striping HBM example. Force config.")
        set(N_REGIONS 4)
        set(EN_HLS 0)
        set(EN_STRM 0)
        set(EN_MEM 1)
    elseif(EXAMPLE STREQUAL "rdma_host")
        message("** RDMA host HOST benchmarks. Force config.")
        set(EN_HLS 0)
        set(EN_BPSS 1)
        set(EN_STRM 1)
        set(EN_MEM 0)
        set(EN_RDMA_1 1)
    elseif(EXAMPLE STREQUAL "rdma_card")
        message("** RDMA card CARD benchmarks. Force config.")
        set(EN_HLS 0)
        set(EN_BPSS 1)
        set(EN_STRM 0)
        set(EN_MEM 1)
        set(N_DDR_CHAN 1) # 
        set(EN_RDMA_1 1)
    elseif(EXAMPLE STREQUAL "rdma_regex")
        message("** RDMA regex. Force config.")
        set(EN_HLS 0)
        set(EN_BPSS 1)
        set(EN_STRM 0)
        set(EN_MEM 0)
        set(EN_RDMA_1 1)
    elseif(EXAMPLE STREQUAL "tcp")
        message("** TCP/IP benchmarks. Force config.")
        set(EN_HLS 0)
        set(EN_STRM 1)
        set(EN_TCP_0 1)
        add_subdirectory(hdl/operators/examples/tcp_bench/hls)
    elseif(EXAMPLE STREQUAL "pr_scheduling")
        message("** PR scheduling. Force config.")
        set(EN_HLS 0)
        set(EN_STRM 1)
        set(EN_MEM 0)
        set(EN_PR 1)
        set(N_CONFIG 4)
        set(N_REGIONS 2)
    endif()
endif()