if(NOT EXAMPLE EQUAL 0) 
    if(EXAMPLE STREQUAL "bmark_host") #
        message("** Link benchmarks, host. Force config.")
        set(EN_HLS 0)
        set(EN_HBM 0)
        set(EN_STRM 1) # Should work with DDR and HBM as well
        set(EN_DDR 0)  
        set(EN_HBM 0) 
        set(N_REGIONS 3)
    elseif(EXAMPLE STREQUAL "bmark_fpga")
        message("** Link benchmarks, fpga. Force config.")
        set(EN_HLS 0)
        set(EN_BPSS 1) 
        set(EN_STRM 1) # Should work with DDR and HBM as well
        set(EN_DDR 0)  
        set(EN_HBM 0) 
    elseif(EXAMPLE STREQUAL "gbm_dtrees")
        message("** Gradient boosting decision tree benchmarks. Force config.")
        set(EN_HLS 0)
        set(EN_STRM 1)
        set(EN_DDR 0)
        set(EN_HBM 0)
    elseif(EXAMPLE STREQUAL "hyper_log_log")
        message("** HyperLogLog cardinality estimation. Force config.")
        set(EN_HLS 1)
        set(EN_STRM 1)
        set(EN_DDR 0)
        set(EN_HBM 0)
    elseif(EXAMPLE STREQUAL "service_aes")
        message("** Coyote as a service (AES). Force config.")
        set(EN_HLS 0)
        set(EN_STRM 1)
        set(EN_DDR 0)
        set(EN_HBM 0)
        set(N_REGIONS 1)
    elseif(EXAMPLE STREQUAL "striping") 
        message("** Striping memory example. Force config.")
        set(N_REGIONS 4)
        set(EN_HLS 0)
        set(EN_STRM 0)
        set(EN_DDR 1)
        set(N_DDR_CHAN 2)
    elseif(EXAMPLE STREQUAL "hbm") 
        message("** HBM memory example. Force config.")
        set(N_REGIONS 4)
        set(EN_HLS 0)
        set(EN_STRM 0)
        set(EN_HBM 1)
    elseif(EXAMPLE STREQUAL "rdma_host")
        message("** RDMA host DRAM benchmarks. Force config.")
        set(EN_HLS 0)
        set(EN_BPSS 1)
        set(EN_STRM 1)
        set(EN_DDR 0)
        set(EN_HBM 0)
        set(EN_RDMA_1 1)
    elseif(EXAMPLE STREQUAL "rdma_card")
        message("** RDMA card DRAM benchmarks. Force config.")
        set(EN_HLS 0)
        set(EN_BPSS 1)
        set(EN_STRM 0)
        set(EN_DDR 1)
        set(N_DDR_CHAN 1)
        set(EN_HBM 0)
        set(EN_RDMA_1 1)
    elseif(EXAMPLE STREQUAL "tcp")
        message("** TCP/IP benchmarks. Force config.")
        set(EN_HLS 0)
        set(EN_STRM 1)
        # set(EN_DDR 0)
        # set(EN_HBM 0)
        set(EN_TCP_0 1)
        add_subdirectory(hdl/operators/examples/tcp_bench/hls)
    elseif(EXAMPLE STREQUAL "pr_scheduling")
        message("** PR scheduling. Force config.")
        set(EN_HLS 0)
        set(EN_STRM 1)
        set(EN_DDR 0)
        set(EN_HBM 0)
        set(EN_PR 1)
        set(N_CONFIG 4)
        set(N_REGIONS 2)
    endif()
endif()