// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module arp_server_subnet_top_generate_arp_pkg_512_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        myIpAddress_dout,
        myIpAddress_empty_n,
        myIpAddress_read,
        myIpAddress_num_data_valid,
        myIpAddress_fifo_cap,
        myMacAddress_dout,
        myMacAddress_empty_n,
        myMacAddress_read,
        myMacAddress_num_data_valid,
        myMacAddress_fifo_cap,
        arpRequestMetaFifo_dout,
        arpRequestMetaFifo_empty_n,
        arpRequestMetaFifo_read,
        arpRequestMetaFifo_num_data_valid,
        arpRequestMetaFifo_fifo_cap,
        arpReplyMetaFifo_dout,
        arpReplyMetaFifo_empty_n,
        arpReplyMetaFifo_read,
        arpReplyMetaFifo_num_data_valid,
        arpReplyMetaFifo_fifo_cap,
        arpDataOut_internal_din,
        arpDataOut_internal_full_n,
        arpDataOut_internal_write,
        arpDataOut_internal_num_data_valid,
        arpDataOut_internal_fifo_cap
);

parameter    ap_ST_iter0_fsm_state1 = 1'd1;
parameter    ap_ST_iter1_fsm_state2 = 2'd2;
parameter    ap_ST_iter1_fsm_state0 = 2'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [31:0] myIpAddress_dout;
input   myIpAddress_empty_n;
output   myIpAddress_read;
input  [2:0] myIpAddress_num_data_valid;
input  [2:0] myIpAddress_fifo_cap;
input  [47:0] myMacAddress_dout;
input   myMacAddress_empty_n;
output   myMacAddress_read;
input  [2:0] myMacAddress_num_data_valid;
input  [2:0] myMacAddress_fifo_cap;
input  [31:0] arpRequestMetaFifo_dout;
input   arpRequestMetaFifo_empty_n;
output   arpRequestMetaFifo_read;
input  [2:0] arpRequestMetaFifo_num_data_valid;
input  [2:0] arpRequestMetaFifo_fifo_cap;
input  [127:0] arpReplyMetaFifo_dout;
input   arpReplyMetaFifo_empty_n;
output   arpReplyMetaFifo_read;
input  [2:0] arpReplyMetaFifo_num_data_valid;
input  [2:0] arpReplyMetaFifo_fifo_cap;
output  [1023:0] arpDataOut_internal_din;
input   arpDataOut_internal_full_n;
output   arpDataOut_internal_write;
input  [2:0] arpDataOut_internal_num_data_valid;
input  [2:0] arpDataOut_internal_fifo_cap;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg myIpAddress_read;
reg myMacAddress_read;
reg arpRequestMetaFifo_read;
reg arpReplyMetaFifo_read;
reg arpDataOut_internal_write;

reg   [0:0] ap_CS_iter0_fsm;
wire    ap_CS_iter0_fsm_state1;
reg   [1:0] ap_CS_iter1_fsm;
wire    ap_CS_iter1_fsm_state0;
wire   [0:0] gap_state_load_load_fu_267_p1;
wire   [0:0] tmp_2_i_nbreadreq_fu_122_p3;
wire   [0:0] tmp_7_i_nbreadreq_fu_130_p3;
reg    ap_predicate_op15_read_state1;
reg    ap_predicate_op18_read_state1;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
reg   [0:0] gap_state_load_reg_500;
wire   [0:0] gap_state_load_reg_500_pp0_iter0_reg;
reg    ap_block_state2_pp0_stage0_iter1;
wire    ap_CS_iter1_fsm_state2;
reg   [0:0] guard_variable_for_void_generate_arp_pkg_stream_stream_stream_ap_uint_ap_uint;
reg   [15:0] header_idx_1;
reg   [335:0] header_header_1;
reg   [0:0] gap_state;
reg    myMacAddress_blk_n;
reg    myIpAddress_blk_n;
reg    arpReplyMetaFifo_blk_n;
reg    arpRequestMetaFifo_blk_n;
reg    arpDataOut_internal_blk_n;
reg   [31:0] myIpAddress_2_reg_482;
reg   [47:0] myMacAddress_1_reg_488;
wire   [0:0] guard_variable_for_void_generate_arp_pkg_stream_stream_stream_ap_uint_ap_uint_1_load_fu_257_p1;
reg   [0:0] guard_variable_for_void_generate_arp_pkg_stream_stream_stream_ap_uint_ap_uint_1_reg_496;
wire   [0:0] guard_variable_for_void_generate_arp_pkg_stream_stream_stream_ap_uint_ap_uint_1_reg_496_pp0_iter0_reg;
reg   [0:0] tmp_2_i_reg_504;
wire   [0:0] tmp_2_i_reg_504_pp0_iter0_reg;
reg   [0:0] tmp_7_i_reg_508;
wire   [0:0] tmp_7_i_reg_508_pp0_iter0_reg;
reg   [31:0] arpRequestMetaFifo_read_reg_512;
wire   [47:0] trunc_ln98_fu_277_p1;
reg   [47:0] trunc_ln98_reg_517;
reg   [79:0] tmp_reg_522;
wire   [0:0] ap_phi_reg_pp0_iter0_header_idx_1_flag_0_i_reg_157;
reg   [0:0] ap_phi_reg_pp0_iter1_header_idx_1_flag_0_i_reg_157;
reg   [15:0] ap_phi_mux_header_idx_1_loc_0_i_phi_fu_174_p4;
wire   [15:0] ap_phi_reg_pp0_iter0_header_idx_1_loc_0_i_reg_170;
reg   [15:0] ap_phi_reg_pp0_iter1_header_idx_1_loc_0_i_reg_170;
reg   [335:0] ap_phi_mux_sendWord_data_phi_fu_184_p4;
wire   [335:0] tmp_i_fu_313_p5;
wire   [335:0] ap_phi_reg_pp0_iter1_sendWord_data_reg_181;
reg   [0:0] ap_phi_mux_header_idx_1_flag_2_i_phi_fu_194_p8;
wire   [0:0] header_idx_1_flag_1_i_fu_429_p2;
reg   [0:0] ap_phi_reg_pp0_iter1_header_idx_1_flag_2_i_reg_190;
wire   [0:0] ap_phi_reg_pp0_iter0_header_idx_1_flag_2_i_reg_190;
reg   [15:0] ap_phi_mux_header_idx_1_new_2_i_phi_fu_211_p8;
wire   [15:0] header_idx_1_new_1_i_fu_436_p3;
reg   [15:0] ap_phi_reg_pp0_iter1_header_idx_1_new_2_i_reg_207;
wire   [15:0] ap_phi_reg_pp0_iter0_header_idx_1_new_2_i_reg_207;
reg   [0:0] ap_phi_mux_header_header_1_flag_3_i_phi_fu_228_p8;
reg   [0:0] ap_phi_reg_pp0_iter1_header_header_1_flag_3_i_reg_224;
wire   [0:0] ap_phi_reg_pp0_iter0_header_header_1_flag_3_i_reg_224;
reg   [335:0] ap_phi_mux_header_header_1_new_3_i_phi_fu_245_p8;
wire   [335:0] ap_phi_reg_pp0_iter1_header_header_1_new_3_i_reg_242;
wire   [335:0] tmp_10_i_fu_356_p5;
wire   [335:0] tmp_6_i_fu_396_p5;
wire   [335:0] tmp_8_i_fu_326_p4;
wire   [335:0] tmp_9_i_fu_336_p4;
wire   [175:0] tmp_11_i_fu_345_p6;
wire   [335:0] tmp_4_i_fu_369_p4;
wire   [335:0] tmp_5_i_fu_378_p4;
wire   [175:0] tmp_i_36_fu_387_p5;
wire   [24:0] shl_ln_fu_409_p3;
wire   [0:0] icmp_ln82_fu_417_p2;
wire   [15:0] add_ln85_fu_423_p2;
wire   [335:0] empty_fu_445_p3;
wire   [511:0] zext_ln147_fu_453_p1;
wire   [576:0] zext_ln147_1_cast_fu_457_p3;
reg   [0:0] ap_NS_iter0_fsm;
reg   [1:0] ap_NS_iter1_fsm;
reg    ap_ST_iter0_fsm_state1_blk;
reg    ap_ST_iter1_fsm_state2_blk;
reg    ap_condition_110;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_iter0_fsm = 1'd1;
#0 ap_CS_iter1_fsm = 2'd1;
#0 ap_done_reg = 1'b0;
#0 guard_variable_for_void_generate_arp_pkg_stream_stream_stream_ap_uint_ap_uint = 1'd0;
#0 header_idx_1 = 16'd0;
#0 header_header_1 = 336'd0;
#0 gap_state = 1'd0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter0_fsm <= ap_ST_iter0_fsm_state1;
    end else begin
        ap_CS_iter0_fsm <= ap_NS_iter0_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter1_fsm <= ap_ST_iter1_fsm_state0;
    end else begin
        ap_CS_iter1_fsm <= ap_NS_iter1_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state2_pp0_stage0_iter1)) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter1_fsm_state2) & (1'b1 == ap_block_state2_pp0_stage0_iter1))) & (tmp_2_i_nbreadreq_fu_122_p3 == 1'd1) & (gap_state == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1)) | (~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter1_fsm_state2) & (1'b1 == ap_block_state2_pp0_stage0_iter1))) & (tmp_7_i_nbreadreq_fu_130_p3 == 1'd1) & (tmp_2_i_nbreadreq_fu_122_p3 == 1'd0) & (gap_state == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1)))) begin
        ap_phi_reg_pp0_iter1_header_header_1_flag_3_i_reg_224 <= 1'd1;
    end else if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter1_fsm_state2) & (1'b1 == ap_block_state2_pp0_stage0_iter1))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_phi_reg_pp0_iter1_header_header_1_flag_3_i_reg_224 <= ap_phi_reg_pp0_iter0_header_header_1_flag_3_i_reg_224;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_110)) begin
        if ((guard_variable_for_void_generate_arp_pkg_stream_stream_stream_ap_uint_ap_uint_1_load_fu_257_p1 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_header_idx_1_flag_0_i_reg_157 <= 1'd0;
        end else if ((guard_variable_for_void_generate_arp_pkg_stream_stream_stream_ap_uint_ap_uint_1_load_fu_257_p1 == 1'd0)) begin
            ap_phi_reg_pp0_iter1_header_idx_1_flag_0_i_reg_157 <= 1'd1;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_header_idx_1_flag_0_i_reg_157 <= ap_phi_reg_pp0_iter0_header_idx_1_flag_0_i_reg_157;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter1_fsm_state2) & (1'b1 == ap_block_state2_pp0_stage0_iter1))) & (tmp_2_i_nbreadreq_fu_122_p3 == 1'd1) & (gap_state == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1)) | (~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter1_fsm_state2) & (1'b1 == ap_block_state2_pp0_stage0_iter1))) & (tmp_7_i_nbreadreq_fu_130_p3 == 1'd1) & (tmp_2_i_nbreadreq_fu_122_p3 == 1'd0) & (gap_state == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1)) | (~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter1_fsm_state2) & (1'b1 == ap_block_state2_pp0_stage0_iter1))) & (tmp_7_i_nbreadreq_fu_130_p3 == 1'd0) & (tmp_2_i_nbreadreq_fu_122_p3 == 1'd0) & (gap_state == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1)))) begin
        ap_phi_reg_pp0_iter1_header_idx_1_flag_2_i_reg_190 <= 1'd1;
    end else if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter1_fsm_state2) & (1'b1 == ap_block_state2_pp0_stage0_iter1))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_phi_reg_pp0_iter1_header_idx_1_flag_2_i_reg_190 <= ap_phi_reg_pp0_iter0_header_idx_1_flag_2_i_reg_190;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_110)) begin
        if ((guard_variable_for_void_generate_arp_pkg_stream_stream_stream_ap_uint_ap_uint_1_load_fu_257_p1 == 1'd0)) begin
            ap_phi_reg_pp0_iter1_header_idx_1_loc_0_i_reg_170 <= 16'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_header_idx_1_loc_0_i_reg_170 <= ap_phi_reg_pp0_iter0_header_idx_1_loc_0_i_reg_170;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter1_fsm_state2) & (1'b1 == ap_block_state2_pp0_stage0_iter1))) & (tmp_2_i_nbreadreq_fu_122_p3 == 1'd1) & (gap_state == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1)) | (~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter1_fsm_state2) & (1'b1 == ap_block_state2_pp0_stage0_iter1))) & (tmp_7_i_nbreadreq_fu_130_p3 == 1'd1) & (tmp_2_i_nbreadreq_fu_122_p3 == 1'd0) & (gap_state == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1)) | (~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter1_fsm_state2) & (1'b1 == ap_block_state2_pp0_stage0_iter1))) & (tmp_7_i_nbreadreq_fu_130_p3 == 1'd0) & (tmp_2_i_nbreadreq_fu_122_p3 == 1'd0) & (gap_state == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1)))) begin
        ap_phi_reg_pp0_iter1_header_idx_1_new_2_i_reg_207 <= 16'd0;
    end else if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter1_fsm_state2) & (1'b1 == ap_block_state2_pp0_stage0_iter1))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_phi_reg_pp0_iter1_header_idx_1_new_2_i_reg_207 <= ap_phi_reg_pp0_iter0_header_idx_1_new_2_i_reg_207;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter1_fsm_state2) & (1'b1 == ap_block_state2_pp0_stage0_iter1))) & (gap_state_load_load_fu_267_p1 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        gap_state <= 1'd0;
    end else if (((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter1_fsm_state2) & (1'b1 == ap_block_state2_pp0_stage0_iter1))) & (tmp_2_i_nbreadreq_fu_122_p3 == 1'd1) & (gap_state == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1)) | (~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter1_fsm_state2) & (1'b1 == ap_block_state2_pp0_stage0_iter1))) & (tmp_7_i_nbreadreq_fu_130_p3 == 1'd1) & (tmp_2_i_nbreadreq_fu_122_p3 == 1'd0) & (gap_state == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1)))) begin
        gap_state <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter1_fsm_state2) & (1'b1 == ap_block_state2_pp0_stage0_iter1))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        arpRequestMetaFifo_read_reg_512 <= arpRequestMetaFifo_dout;
        gap_state_load_reg_500 <= gap_state;
        guard_variable_for_void_generate_arp_pkg_stream_stream_stream_ap_uint_ap_uint_1_reg_496 <= guard_variable_for_void_generate_arp_pkg_stream_stream_stream_ap_uint_ap_uint;
        myIpAddress_2_reg_482 <= myIpAddress_dout;
        myMacAddress_1_reg_488 <= myMacAddress_dout;
        tmp_2_i_reg_504 <= tmp_2_i_nbreadreq_fu_122_p3;
        tmp_7_i_reg_508 <= tmp_7_i_nbreadreq_fu_130_p3;
        tmp_reg_522 <= {{arpReplyMetaFifo_dout[127:48]}};
        trunc_ln98_reg_517 <= trunc_ln98_fu_277_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter1_fsm_state2) & (1'b1 == ap_block_state2_pp0_stage0_iter1))) & (1'b1 == ap_CS_iter0_fsm_state1) & (guard_variable_for_void_generate_arp_pkg_stream_stream_stream_ap_uint_ap_uint_1_load_fu_257_p1 == 1'd0))) begin
        guard_variable_for_void_generate_arp_pkg_stream_stream_stream_ap_uint_ap_uint <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state2_pp0_stage0_iter1)) & (1'b1 == ap_CS_iter1_fsm_state2) & (ap_phi_mux_header_header_1_flag_3_i_phi_fu_228_p8 == 1'd1))) begin
        header_header_1 <= ap_phi_mux_header_header_1_new_3_i_phi_fu_245_p8;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state2_pp0_stage0_iter1)) & (1'b1 == ap_CS_iter1_fsm_state2) & (ap_phi_mux_header_idx_1_flag_2_i_phi_fu_194_p8 == 1'd1))) begin
        header_idx_1 <= ap_phi_mux_header_idx_1_new_2_i_phi_fu_211_p8;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_iter0_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_iter0_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state2_pp0_stage0_iter1)) begin
        ap_ST_iter1_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_iter1_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state2_pp0_stage0_iter1)) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_iter1_fsm_state0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((gap_state_load_reg_500 == 1'd1) | ((gap_state_load_reg_500_pp0_iter0_reg == 1'd0) & (tmp_7_i_reg_508_pp0_iter0_reg == 1'd0) & (tmp_2_i_reg_504_pp0_iter0_reg == 1'd0)))) begin
        ap_phi_mux_header_header_1_flag_3_i_phi_fu_228_p8 = ap_phi_reg_pp0_iter1_header_idx_1_flag_0_i_reg_157;
    end else begin
        ap_phi_mux_header_header_1_flag_3_i_phi_fu_228_p8 = ap_phi_reg_pp0_iter1_header_header_1_flag_3_i_reg_224;
    end
end

always @ (*) begin
    if (((gap_state_load_reg_500_pp0_iter0_reg == 1'd0) & (tmp_2_i_reg_504_pp0_iter0_reg == 1'd1))) begin
        ap_phi_mux_header_header_1_new_3_i_phi_fu_245_p8 = tmp_6_i_fu_396_p5;
    end else if (((gap_state_load_reg_500_pp0_iter0_reg == 1'd0) & (tmp_7_i_reg_508_pp0_iter0_reg == 1'd1) & (tmp_2_i_reg_504_pp0_iter0_reg == 1'd0))) begin
        ap_phi_mux_header_header_1_new_3_i_phi_fu_245_p8 = tmp_10_i_fu_356_p5;
    end else if (((gap_state_load_reg_500 == 1'd1) | ((gap_state_load_reg_500_pp0_iter0_reg == 1'd0) & (tmp_7_i_reg_508_pp0_iter0_reg == 1'd0) & (tmp_2_i_reg_504_pp0_iter0_reg == 1'd0)))) begin
        ap_phi_mux_header_header_1_new_3_i_phi_fu_245_p8 = ap_phi_mux_sendWord_data_phi_fu_184_p4;
    end else begin
        ap_phi_mux_header_header_1_new_3_i_phi_fu_245_p8 = ap_phi_reg_pp0_iter1_header_header_1_new_3_i_reg_242;
    end
end

always @ (*) begin
    if ((gap_state_load_reg_500 == 1'd1)) begin
        ap_phi_mux_header_idx_1_flag_2_i_phi_fu_194_p8 = header_idx_1_flag_1_i_fu_429_p2;
    end else begin
        ap_phi_mux_header_idx_1_flag_2_i_phi_fu_194_p8 = ap_phi_reg_pp0_iter1_header_idx_1_flag_2_i_reg_190;
    end
end

always @ (*) begin
    if ((guard_variable_for_void_generate_arp_pkg_stream_stream_stream_ap_uint_ap_uint_1_reg_496_pp0_iter0_reg == 1'd1)) begin
        ap_phi_mux_header_idx_1_loc_0_i_phi_fu_174_p4 = header_idx_1;
    end else begin
        ap_phi_mux_header_idx_1_loc_0_i_phi_fu_174_p4 = ap_phi_reg_pp0_iter1_header_idx_1_loc_0_i_reg_170;
    end
end

always @ (*) begin
    if ((gap_state_load_reg_500 == 1'd1)) begin
        ap_phi_mux_header_idx_1_new_2_i_phi_fu_211_p8 = header_idx_1_new_1_i_fu_436_p3;
    end else begin
        ap_phi_mux_header_idx_1_new_2_i_phi_fu_211_p8 = ap_phi_reg_pp0_iter1_header_idx_1_new_2_i_reg_207;
    end
end

always @ (*) begin
    if ((guard_variable_for_void_generate_arp_pkg_stream_stream_stream_ap_uint_ap_uint_1_reg_496_pp0_iter0_reg == 1'd1)) begin
        ap_phi_mux_sendWord_data_phi_fu_184_p4 = header_header_1;
    end else if ((guard_variable_for_void_generate_arp_pkg_stream_stream_stream_ap_uint_ap_uint_1_reg_496_pp0_iter0_reg == 1'd0)) begin
        ap_phi_mux_sendWord_data_phi_fu_184_p4 = tmp_i_fu_313_p5;
    end else begin
        ap_phi_mux_sendWord_data_phi_fu_184_p4 = ap_phi_reg_pp0_iter1_sendWord_data_reg_181;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter1_fsm_state2) & (1'b1 == ap_block_state2_pp0_stage0_iter1))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((gap_state_load_reg_500 == 1'd1) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        arpDataOut_internal_blk_n = arpDataOut_internal_full_n;
    end else begin
        arpDataOut_internal_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state2_pp0_stage0_iter1)) & (gap_state_load_reg_500 == 1'd1) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        arpDataOut_internal_write = 1'b1;
    end else begin
        arpDataOut_internal_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (ap_start == 1'b1) & (ap_predicate_op18_read_state1 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        arpReplyMetaFifo_blk_n = arpReplyMetaFifo_empty_n;
    end else begin
        arpReplyMetaFifo_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter1_fsm_state2) & (1'b1 == ap_block_state2_pp0_stage0_iter1))) & (ap_predicate_op18_read_state1 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        arpReplyMetaFifo_read = 1'b1;
    end else begin
        arpReplyMetaFifo_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (ap_start == 1'b1) & (ap_predicate_op15_read_state1 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        arpRequestMetaFifo_blk_n = arpRequestMetaFifo_empty_n;
    end else begin
        arpRequestMetaFifo_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter1_fsm_state2) & (1'b1 == ap_block_state2_pp0_stage0_iter1))) & (ap_predicate_op15_read_state1 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        arpRequestMetaFifo_read = 1'b1;
    end else begin
        arpRequestMetaFifo_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (ap_start == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        myIpAddress_blk_n = myIpAddress_empty_n;
    end else begin
        myIpAddress_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter1_fsm_state2) & (1'b1 == ap_block_state2_pp0_stage0_iter1))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        myIpAddress_read = 1'b1;
    end else begin
        myIpAddress_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (ap_start == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        myMacAddress_blk_n = myMacAddress_empty_n;
    end else begin
        myMacAddress_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter1_fsm_state2) & (1'b1 == ap_block_state2_pp0_stage0_iter1))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        myMacAddress_read = 1'b1;
    end else begin
        myMacAddress_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_iter0_fsm)
        ap_ST_iter0_fsm_state1 : begin
            ap_NS_iter0_fsm = ap_ST_iter0_fsm_state1;
        end
        default : begin
            ap_NS_iter0_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter1_fsm)
        ap_ST_iter1_fsm_state2 : begin
            if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state2_pp0_stage0_iter1)) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state2_pp0_stage0_iter1)) & ((1'b0 == ap_CS_iter0_fsm_state1) | ((1'b1 == ap_CS_iter0_fsm_state1) & (1'b1 == ap_block_state1_pp0_stage0_iter0))))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end
        end
        ap_ST_iter1_fsm_state0 : begin
            if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter1_fsm_state2) & (1'b1 == ap_block_state2_pp0_stage0_iter1))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter1_fsm = 'bx;
        end
    endcase
end

assign add_ln85_fu_423_p2 = (ap_phi_mux_header_idx_1_loc_0_i_phi_fu_174_p4 + 16'd1);

assign ap_CS_iter0_fsm_state1 = ap_CS_iter0_fsm[32'd0];

assign ap_CS_iter1_fsm_state0 = ap_CS_iter1_fsm[32'd0];

assign ap_CS_iter1_fsm_state2 = ap_CS_iter1_fsm[32'd1];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1) | (myMacAddress_empty_n == 1'b0) | (myIpAddress_empty_n == 1'b0) | ((ap_predicate_op18_read_state1 == 1'b1) & (arpReplyMetaFifo_empty_n == 1'b0)) | ((ap_predicate_op15_read_state1 == 1'b1) & (arpRequestMetaFifo_empty_n == 1'b0)));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = ((gap_state_load_reg_500 == 1'd1) & (arpDataOut_internal_full_n == 1'b0));
end

always @ (*) begin
    ap_condition_110 = (~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter1_fsm_state2) & (1'b1 == ap_block_state2_pp0_stage0_iter1))) & (1'b1 == ap_CS_iter0_fsm_state1));
end

assign ap_phi_reg_pp0_iter0_header_header_1_flag_3_i_reg_224 = 'bx;

assign ap_phi_reg_pp0_iter0_header_idx_1_flag_0_i_reg_157 = 'bx;

assign ap_phi_reg_pp0_iter0_header_idx_1_flag_2_i_reg_190 = 'bx;

assign ap_phi_reg_pp0_iter0_header_idx_1_loc_0_i_reg_170 = 'bx;

assign ap_phi_reg_pp0_iter0_header_idx_1_new_2_i_reg_207 = 'bx;

assign ap_phi_reg_pp0_iter1_header_header_1_new_3_i_reg_242 = 'bx;

assign ap_phi_reg_pp0_iter1_sendWord_data_reg_181 = 'bx;

always @ (*) begin
    ap_predicate_op15_read_state1 = ((tmp_7_i_nbreadreq_fu_130_p3 == 1'd1) & (tmp_2_i_nbreadreq_fu_122_p3 == 1'd0) & (gap_state == 1'd0));
end

always @ (*) begin
    ap_predicate_op18_read_state1 = ((tmp_2_i_nbreadreq_fu_122_p3 == 1'd1) & (gap_state == 1'd0));
end

assign arpDataOut_internal_din = zext_ln147_1_cast_fu_457_p3;

assign empty_fu_445_p3 = ((icmp_ln82_fu_417_p2[0:0] == 1'b1) ? ap_phi_mux_sendWord_data_phi_fu_184_p4 : 336'd0);

assign gap_state_load_load_fu_267_p1 = gap_state;

assign gap_state_load_reg_500_pp0_iter0_reg = gap_state_load_reg_500;

assign guard_variable_for_void_generate_arp_pkg_stream_stream_stream_ap_uint_ap_uint_1_load_fu_257_p1 = guard_variable_for_void_generate_arp_pkg_stream_stream_stream_ap_uint_ap_uint;

assign guard_variable_for_void_generate_arp_pkg_stream_stream_stream_ap_uint_ap_uint_1_reg_496_pp0_iter0_reg = guard_variable_for_void_generate_arp_pkg_stream_stream_stream_ap_uint_ap_uint_1_reg_496;

assign header_idx_1_flag_1_i_fu_429_p2 = (icmp_ln82_fu_417_p2 | ap_phi_reg_pp0_iter1_header_idx_1_flag_0_i_reg_157);

assign header_idx_1_new_1_i_fu_436_p3 = ((icmp_ln82_fu_417_p2[0:0] == 1'b1) ? add_ln85_fu_423_p2 : 16'd0);

assign icmp_ln82_fu_417_p2 = ((shl_ln_fu_409_p3 < 25'd336) ? 1'b1 : 1'b0);

assign shl_ln_fu_409_p3 = {{ap_phi_mux_header_idx_1_loc_0_i_phi_fu_174_p4}, {9'd0}};

assign tmp_10_i_fu_356_p5 = {{tmp_11_i_fu_345_p6}, {tmp_9_i_fu_336_p4[159:0]}};

assign tmp_11_i_fu_345_p6 = {{{{{arpRequestMetaFifo_read_reg_512}, {48'd0}}, {myIpAddress_2_reg_482}}, {myMacAddress_1_reg_488}}, {16'd256}};

assign tmp_2_i_nbreadreq_fu_122_p3 = arpReplyMetaFifo_empty_n;

assign tmp_2_i_reg_504_pp0_iter0_reg = tmp_2_i_reg_504;

assign tmp_4_i_fu_369_p4 = {{ap_phi_mux_sendWord_data_phi_fu_184_p4[335:48]}, {trunc_ln98_reg_517}};

assign tmp_5_i_fu_378_p4 = {{tmp_4_i_fu_369_p4[335:96]}, {myMacAddress_1_reg_488}, {tmp_4_i_fu_369_p4[47:0]}};

assign tmp_6_i_fu_396_p5 = {{tmp_i_36_fu_387_p5}, {tmp_5_i_fu_378_p4[159:0]}};

assign tmp_7_i_nbreadreq_fu_130_p3 = arpRequestMetaFifo_empty_n;

assign tmp_7_i_reg_508_pp0_iter0_reg = tmp_7_i_reg_508;

assign tmp_8_i_fu_326_p4 = {{ap_phi_mux_sendWord_data_phi_fu_184_p4[335:48]}, {48'd281474976710655}};

assign tmp_9_i_fu_336_p4 = {{tmp_8_i_fu_326_p4[335:96]}, {myMacAddress_1_reg_488}, {tmp_8_i_fu_326_p4[47:0]}};

assign tmp_i_36_fu_387_p5 = {{{{tmp_reg_522}, {myIpAddress_2_reg_482}}, {myMacAddress_1_reg_488}}, {16'd512}};

assign tmp_i_fu_313_p5 = {{header_header_1[335:159]}, {63'd289919260388492808}, {header_header_1[95:0]}};

assign trunc_ln98_fu_277_p1 = arpReplyMetaFifo_dout[47:0];

assign zext_ln147_1_cast_fu_457_p3 = {{65'd18446748471756062719}, {zext_ln147_fu_453_p1}};

assign zext_ln147_fu_453_p1 = empty_fu_445_p3;

endmodule //arp_server_subnet_top_generate_arp_pkg_512_s
