extends: res256_layers7_W8A8_P50_manualA.yaml

run:
  iteration_name: res256_layers7_W8A8_P50_manualA_v2_fifo_opt_10k

hls:
  sweep_name: manualA_v2_fifo_opt_10k
  fifo_depth_optimization: true
  fifo_profiling_depth: 10000
