run:
  iteration_name: BASELINE_pruned_qat_w6_a6_s50_pruneend200_kfold5
  timestamped_root: false

pruning:
  end_epoch: 200

training:
  epochs: 300
  allow_stale_fold_cache: true

hls:
  sweep_name: timing_rf4_clk5p0_aclk200_opt
  reuse_factor: 4
  clock_period: 5.0
  run_cosim: false

u55c:
  coyote_root: /pub/scratch/sdeheredia/Coyote
  build_jobs: 8
  diagnostic:
    mode: full_streaming
  cmake_defines:
    ACLK_F: 200
    BUILD_OPT: 1
    COMP_CORES: 8
    HLS_CLOCK_UNCERTAINTY: 35
