// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_normalize_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_config15_s (
        ap_ready,
        data_0_val,
        data_1_val,
        data_2_val,
        data_3_val,
        data_4_val,
        data_5_val,
        data_6_val,
        data_7_val,
        data_8_val,
        data_9_val,
        data_10_val,
        data_11_val,
        data_12_val,
        data_13_val,
        data_14_val,
        data_15_val,
        data_16_val,
        data_17_val,
        data_18_val,
        data_19_val,
        data_20_val,
        data_21_val,
        data_22_val,
        data_23_val,
        data_24_val,
        data_25_val,
        data_26_val,
        data_27_val,
        data_28_val,
        data_29_val,
        data_30_val,
        data_31_val,
        data_32_val,
        data_34_val,
        data_35_val,
        data_36_val,
        data_37_val,
        data_38_val,
        data_40_val,
        data_41_val,
        data_42_val,
        data_43_val,
        data_44_val,
        data_45_val,
        data_46_val,
        data_47_val,
        data_48_val,
        data_49_val,
        data_50_val,
        data_51_val,
        data_52_val,
        data_53_val,
        data_54_val,
        data_55_val,
        data_56_val,
        data_57_val,
        data_58_val,
        data_59_val,
        data_60_val,
        data_61_val,
        data_62_val,
        data_63_val,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9,
        ap_return_10,
        ap_return_11,
        ap_return_12,
        ap_return_13,
        ap_return_14,
        ap_return_15,
        ap_return_16,
        ap_return_17,
        ap_return_18,
        ap_return_19,
        ap_return_20,
        ap_return_21,
        ap_return_22,
        ap_return_23,
        ap_return_24,
        ap_return_25,
        ap_return_26,
        ap_return_27,
        ap_return_28,
        ap_return_29,
        ap_return_30,
        ap_return_31,
        ap_return_32,
        ap_return_33,
        ap_return_34,
        ap_return_35,
        ap_return_36,
        ap_return_37,
        ap_return_38,
        ap_return_39,
        ap_return_40,
        ap_return_41,
        ap_return_42,
        ap_return_43,
        ap_return_44,
        ap_return_45,
        ap_return_46,
        ap_return_47,
        ap_return_48,
        ap_return_49,
        ap_return_50,
        ap_return_51,
        ap_return_52,
        ap_return_53,
        ap_return_54,
        ap_return_55,
        ap_return_56,
        ap_return_57,
        ap_return_58,
        ap_return_59,
        ap_return_60,
        ap_return_61
);


output   ap_ready;
input  [15:0] data_0_val;
input  [15:0] data_1_val;
input  [15:0] data_2_val;
input  [15:0] data_3_val;
input  [15:0] data_4_val;
input  [15:0] data_5_val;
input  [15:0] data_6_val;
input  [15:0] data_7_val;
input  [15:0] data_8_val;
input  [15:0] data_9_val;
input  [15:0] data_10_val;
input  [15:0] data_11_val;
input  [15:0] data_12_val;
input  [15:0] data_13_val;
input  [15:0] data_14_val;
input  [15:0] data_15_val;
input  [15:0] data_16_val;
input  [15:0] data_17_val;
input  [15:0] data_18_val;
input  [15:0] data_19_val;
input  [15:0] data_20_val;
input  [15:0] data_21_val;
input  [15:0] data_22_val;
input  [15:0] data_23_val;
input  [15:0] data_24_val;
input  [15:0] data_25_val;
input  [15:0] data_26_val;
input  [15:0] data_27_val;
input  [15:0] data_28_val;
input  [15:0] data_29_val;
input  [15:0] data_30_val;
input  [15:0] data_31_val;
input  [15:0] data_32_val;
input  [15:0] data_34_val;
input  [15:0] data_35_val;
input  [15:0] data_36_val;
input  [15:0] data_37_val;
input  [15:0] data_38_val;
input  [15:0] data_40_val;
input  [15:0] data_41_val;
input  [15:0] data_42_val;
input  [15:0] data_43_val;
input  [15:0] data_44_val;
input  [15:0] data_45_val;
input  [15:0] data_46_val;
input  [15:0] data_47_val;
input  [15:0] data_48_val;
input  [15:0] data_49_val;
input  [15:0] data_50_val;
input  [15:0] data_51_val;
input  [15:0] data_52_val;
input  [15:0] data_53_val;
input  [15:0] data_54_val;
input  [15:0] data_55_val;
input  [15:0] data_56_val;
input  [15:0] data_57_val;
input  [15:0] data_58_val;
input  [15:0] data_59_val;
input  [15:0] data_60_val;
input  [15:0] data_61_val;
input  [15:0] data_62_val;
input  [15:0] data_63_val;
output  [15:0] ap_return_0;
output  [15:0] ap_return_1;
output  [15:0] ap_return_2;
output  [15:0] ap_return_3;
output  [15:0] ap_return_4;
output  [15:0] ap_return_5;
output  [15:0] ap_return_6;
output  [15:0] ap_return_7;
output  [15:0] ap_return_8;
output  [15:0] ap_return_9;
output  [15:0] ap_return_10;
output  [15:0] ap_return_11;
output  [15:0] ap_return_12;
output  [15:0] ap_return_13;
output  [15:0] ap_return_14;
output  [15:0] ap_return_15;
output  [15:0] ap_return_16;
output  [15:0] ap_return_17;
output  [15:0] ap_return_18;
output  [15:0] ap_return_19;
output  [15:0] ap_return_20;
output  [15:0] ap_return_21;
output  [15:0] ap_return_22;
output  [15:0] ap_return_23;
output  [15:0] ap_return_24;
output  [15:0] ap_return_25;
output  [15:0] ap_return_26;
output  [15:0] ap_return_27;
output  [15:0] ap_return_28;
output  [15:0] ap_return_29;
output  [15:0] ap_return_30;
output  [15:0] ap_return_31;
output  [15:0] ap_return_32;
output  [15:0] ap_return_33;
output  [15:0] ap_return_34;
output  [15:0] ap_return_35;
output  [15:0] ap_return_36;
output  [15:0] ap_return_37;
output  [15:0] ap_return_38;
output  [15:0] ap_return_39;
output  [15:0] ap_return_40;
output  [15:0] ap_return_41;
output  [15:0] ap_return_42;
output  [15:0] ap_return_43;
output  [15:0] ap_return_44;
output  [15:0] ap_return_45;
output  [15:0] ap_return_46;
output  [15:0] ap_return_47;
output  [15:0] ap_return_48;
output  [15:0] ap_return_49;
output  [15:0] ap_return_50;
output  [15:0] ap_return_51;
output  [15:0] ap_return_52;
output  [15:0] ap_return_53;
output  [15:0] ap_return_54;
output  [15:0] ap_return_55;
output  [15:0] ap_return_56;
output  [15:0] ap_return_57;
output  [15:0] ap_return_58;
output  [15:0] ap_return_59;
output  [15:0] ap_return_60;
output  [15:0] ap_return_61;

wire   [14:0] trunc_ln_fu_518_p4;
wire   [14:0] trunc_ln54_1_fu_532_p4;
wire   [14:0] trunc_ln54_2_fu_546_p4;
wire   [14:0] trunc_ln54_3_fu_560_p4;
wire   [14:0] trunc_ln54_4_fu_574_p4;
wire   [14:0] trunc_ln54_5_fu_588_p4;
wire   [14:0] trunc_ln54_6_fu_602_p4;
wire   [14:0] trunc_ln54_7_fu_616_p4;
wire   [14:0] trunc_ln54_8_fu_630_p4;
wire   [14:0] trunc_ln54_9_fu_644_p4;
wire   [14:0] trunc_ln54_s_fu_658_p4;
wire   [14:0] trunc_ln54_10_fu_672_p4;
wire   [14:0] trunc_ln54_11_fu_686_p4;
wire   [14:0] trunc_ln54_12_fu_700_p4;
wire   [14:0] trunc_ln54_13_fu_714_p4;
wire   [14:0] trunc_ln54_14_fu_728_p4;
wire   [14:0] trunc_ln54_15_fu_742_p4;
wire   [14:0] trunc_ln54_16_fu_756_p4;
wire   [14:0] trunc_ln54_17_fu_770_p4;
wire   [14:0] trunc_ln54_18_fu_784_p4;
wire   [14:0] trunc_ln54_19_fu_798_p4;
wire   [14:0] trunc_ln54_20_fu_812_p4;
wire   [14:0] trunc_ln54_21_fu_826_p4;
wire   [14:0] trunc_ln54_22_fu_840_p4;
wire   [14:0] trunc_ln54_23_fu_854_p4;
wire   [14:0] trunc_ln54_24_fu_868_p4;
wire   [14:0] trunc_ln54_25_fu_882_p4;
wire   [14:0] trunc_ln54_26_fu_896_p4;
wire   [14:0] trunc_ln54_27_fu_910_p4;
wire   [14:0] trunc_ln54_28_fu_924_p4;
wire   [14:0] trunc_ln54_29_fu_938_p4;
wire   [14:0] trunc_ln54_30_fu_952_p4;
wire   [14:0] trunc_ln54_31_fu_966_p4;
wire   [14:0] trunc_ln54_32_fu_980_p4;
wire   [14:0] trunc_ln54_33_fu_994_p4;
wire   [14:0] trunc_ln54_34_fu_1008_p4;
wire   [14:0] trunc_ln54_35_fu_1022_p4;
wire   [14:0] trunc_ln54_36_fu_1036_p4;
wire   [14:0] trunc_ln54_37_fu_1050_p4;
wire   [14:0] trunc_ln54_38_fu_1064_p4;
wire   [14:0] trunc_ln54_39_fu_1078_p4;
wire   [14:0] trunc_ln54_40_fu_1092_p4;
wire   [14:0] trunc_ln54_41_fu_1106_p4;
wire   [14:0] trunc_ln54_42_fu_1120_p4;
wire   [14:0] trunc_ln54_43_fu_1134_p4;
wire   [14:0] trunc_ln54_44_fu_1148_p4;
wire   [14:0] trunc_ln54_45_fu_1162_p4;
wire   [14:0] trunc_ln54_46_fu_1176_p4;
wire   [14:0] trunc_ln54_47_fu_1190_p4;
wire   [14:0] trunc_ln54_48_fu_1204_p4;
wire   [14:0] trunc_ln54_49_fu_1218_p4;
wire   [14:0] trunc_ln54_50_fu_1232_p4;
wire   [14:0] trunc_ln54_51_fu_1246_p4;
wire   [14:0] trunc_ln54_52_fu_1260_p4;
wire   [14:0] trunc_ln54_53_fu_1274_p4;
wire   [14:0] trunc_ln54_54_fu_1288_p4;
wire   [14:0] trunc_ln54_55_fu_1302_p4;
wire   [14:0] trunc_ln54_56_fu_1316_p4;
wire   [14:0] trunc_ln54_57_fu_1330_p4;
wire   [14:0] trunc_ln54_58_fu_1344_p4;
wire   [14:0] trunc_ln54_59_fu_1358_p4;
wire   [14:0] trunc_ln54_60_fu_1372_p4;
wire  signed [15:0] sext_ln54_fu_528_p1;
wire  signed [15:0] sext_ln54_1_fu_542_p1;
wire  signed [15:0] sext_ln54_2_fu_556_p1;
wire  signed [15:0] sext_ln54_3_fu_570_p1;
wire  signed [15:0] sext_ln54_4_fu_584_p1;
wire  signed [15:0] sext_ln54_5_fu_598_p1;
wire  signed [15:0] sext_ln54_6_fu_612_p1;
wire  signed [15:0] sext_ln54_7_fu_626_p1;
wire  signed [15:0] sext_ln54_8_fu_640_p1;
wire  signed [15:0] sext_ln54_9_fu_654_p1;
wire  signed [15:0] sext_ln54_10_fu_668_p1;
wire  signed [15:0] sext_ln54_11_fu_682_p1;
wire  signed [15:0] sext_ln54_12_fu_696_p1;
wire  signed [15:0] sext_ln54_13_fu_710_p1;
wire  signed [15:0] sext_ln54_14_fu_724_p1;
wire  signed [15:0] sext_ln54_15_fu_738_p1;
wire  signed [15:0] sext_ln54_16_fu_752_p1;
wire  signed [15:0] sext_ln54_17_fu_766_p1;
wire  signed [15:0] sext_ln54_18_fu_780_p1;
wire  signed [15:0] sext_ln54_19_fu_794_p1;
wire  signed [15:0] sext_ln54_20_fu_808_p1;
wire  signed [15:0] sext_ln54_21_fu_822_p1;
wire  signed [15:0] sext_ln54_22_fu_836_p1;
wire  signed [15:0] sext_ln54_23_fu_850_p1;
wire  signed [15:0] sext_ln54_24_fu_864_p1;
wire  signed [15:0] sext_ln54_25_fu_878_p1;
wire  signed [15:0] sext_ln54_26_fu_892_p1;
wire  signed [15:0] sext_ln54_27_fu_906_p1;
wire  signed [15:0] sext_ln54_28_fu_920_p1;
wire  signed [15:0] sext_ln54_29_fu_934_p1;
wire  signed [15:0] sext_ln54_30_fu_948_p1;
wire  signed [15:0] sext_ln54_31_fu_962_p1;
wire  signed [15:0] sext_ln54_32_fu_976_p1;
wire  signed [15:0] sext_ln54_33_fu_990_p1;
wire  signed [15:0] sext_ln54_34_fu_1004_p1;
wire  signed [15:0] sext_ln54_35_fu_1018_p1;
wire  signed [15:0] sext_ln54_36_fu_1032_p1;
wire  signed [15:0] sext_ln54_37_fu_1046_p1;
wire  signed [15:0] sext_ln54_38_fu_1060_p1;
wire  signed [15:0] sext_ln54_39_fu_1074_p1;
wire  signed [15:0] sext_ln54_40_fu_1088_p1;
wire  signed [15:0] sext_ln54_41_fu_1102_p1;
wire  signed [15:0] sext_ln54_42_fu_1116_p1;
wire  signed [15:0] sext_ln54_43_fu_1130_p1;
wire  signed [15:0] sext_ln54_44_fu_1144_p1;
wire  signed [15:0] sext_ln54_45_fu_1158_p1;
wire  signed [15:0] sext_ln54_46_fu_1172_p1;
wire  signed [15:0] sext_ln54_47_fu_1186_p1;
wire  signed [15:0] sext_ln54_48_fu_1200_p1;
wire  signed [15:0] sext_ln54_49_fu_1214_p1;
wire  signed [15:0] sext_ln54_50_fu_1228_p1;
wire  signed [15:0] sext_ln54_51_fu_1242_p1;
wire  signed [15:0] sext_ln54_52_fu_1256_p1;
wire  signed [15:0] sext_ln54_53_fu_1270_p1;
wire  signed [15:0] sext_ln54_54_fu_1284_p1;
wire  signed [15:0] sext_ln54_55_fu_1298_p1;
wire  signed [15:0] sext_ln54_56_fu_1312_p1;
wire  signed [15:0] sext_ln54_57_fu_1326_p1;
wire  signed [15:0] sext_ln54_58_fu_1340_p1;
wire  signed [15:0] sext_ln54_59_fu_1354_p1;
wire  signed [15:0] sext_ln54_60_fu_1368_p1;
wire  signed [15:0] sext_ln54_61_fu_1382_p1;

assign ap_ready = 1'b1;

assign sext_ln54_10_fu_668_p1 = $signed(trunc_ln54_s_fu_658_p4);

assign sext_ln54_11_fu_682_p1 = $signed(trunc_ln54_10_fu_672_p4);

assign sext_ln54_12_fu_696_p1 = $signed(trunc_ln54_11_fu_686_p4);

assign sext_ln54_13_fu_710_p1 = $signed(trunc_ln54_12_fu_700_p4);

assign sext_ln54_14_fu_724_p1 = $signed(trunc_ln54_13_fu_714_p4);

assign sext_ln54_15_fu_738_p1 = $signed(trunc_ln54_14_fu_728_p4);

assign sext_ln54_16_fu_752_p1 = $signed(trunc_ln54_15_fu_742_p4);

assign sext_ln54_17_fu_766_p1 = $signed(trunc_ln54_16_fu_756_p4);

assign sext_ln54_18_fu_780_p1 = $signed(trunc_ln54_17_fu_770_p4);

assign sext_ln54_19_fu_794_p1 = $signed(trunc_ln54_18_fu_784_p4);

assign sext_ln54_1_fu_542_p1 = $signed(trunc_ln54_1_fu_532_p4);

assign sext_ln54_20_fu_808_p1 = $signed(trunc_ln54_19_fu_798_p4);

assign sext_ln54_21_fu_822_p1 = $signed(trunc_ln54_20_fu_812_p4);

assign sext_ln54_22_fu_836_p1 = $signed(trunc_ln54_21_fu_826_p4);

assign sext_ln54_23_fu_850_p1 = $signed(trunc_ln54_22_fu_840_p4);

assign sext_ln54_24_fu_864_p1 = $signed(trunc_ln54_23_fu_854_p4);

assign sext_ln54_25_fu_878_p1 = $signed(trunc_ln54_24_fu_868_p4);

assign sext_ln54_26_fu_892_p1 = $signed(trunc_ln54_25_fu_882_p4);

assign sext_ln54_27_fu_906_p1 = $signed(trunc_ln54_26_fu_896_p4);

assign sext_ln54_28_fu_920_p1 = $signed(trunc_ln54_27_fu_910_p4);

assign sext_ln54_29_fu_934_p1 = $signed(trunc_ln54_28_fu_924_p4);

assign sext_ln54_2_fu_556_p1 = $signed(trunc_ln54_2_fu_546_p4);

assign sext_ln54_30_fu_948_p1 = $signed(trunc_ln54_29_fu_938_p4);

assign sext_ln54_31_fu_962_p1 = $signed(trunc_ln54_30_fu_952_p4);

assign sext_ln54_32_fu_976_p1 = $signed(trunc_ln54_31_fu_966_p4);

assign sext_ln54_33_fu_990_p1 = $signed(trunc_ln54_32_fu_980_p4);

assign sext_ln54_34_fu_1004_p1 = $signed(trunc_ln54_33_fu_994_p4);

assign sext_ln54_35_fu_1018_p1 = $signed(trunc_ln54_34_fu_1008_p4);

assign sext_ln54_36_fu_1032_p1 = $signed(trunc_ln54_35_fu_1022_p4);

assign sext_ln54_37_fu_1046_p1 = $signed(trunc_ln54_36_fu_1036_p4);

assign sext_ln54_38_fu_1060_p1 = $signed(trunc_ln54_37_fu_1050_p4);

assign sext_ln54_39_fu_1074_p1 = $signed(trunc_ln54_38_fu_1064_p4);

assign sext_ln54_3_fu_570_p1 = $signed(trunc_ln54_3_fu_560_p4);

assign sext_ln54_40_fu_1088_p1 = $signed(trunc_ln54_39_fu_1078_p4);

assign sext_ln54_41_fu_1102_p1 = $signed(trunc_ln54_40_fu_1092_p4);

assign sext_ln54_42_fu_1116_p1 = $signed(trunc_ln54_41_fu_1106_p4);

assign sext_ln54_43_fu_1130_p1 = $signed(trunc_ln54_42_fu_1120_p4);

assign sext_ln54_44_fu_1144_p1 = $signed(trunc_ln54_43_fu_1134_p4);

assign sext_ln54_45_fu_1158_p1 = $signed(trunc_ln54_44_fu_1148_p4);

assign sext_ln54_46_fu_1172_p1 = $signed(trunc_ln54_45_fu_1162_p4);

assign sext_ln54_47_fu_1186_p1 = $signed(trunc_ln54_46_fu_1176_p4);

assign sext_ln54_48_fu_1200_p1 = $signed(trunc_ln54_47_fu_1190_p4);

assign sext_ln54_49_fu_1214_p1 = $signed(trunc_ln54_48_fu_1204_p4);

assign sext_ln54_4_fu_584_p1 = $signed(trunc_ln54_4_fu_574_p4);

assign sext_ln54_50_fu_1228_p1 = $signed(trunc_ln54_49_fu_1218_p4);

assign sext_ln54_51_fu_1242_p1 = $signed(trunc_ln54_50_fu_1232_p4);

assign sext_ln54_52_fu_1256_p1 = $signed(trunc_ln54_51_fu_1246_p4);

assign sext_ln54_53_fu_1270_p1 = $signed(trunc_ln54_52_fu_1260_p4);

assign sext_ln54_54_fu_1284_p1 = $signed(trunc_ln54_53_fu_1274_p4);

assign sext_ln54_55_fu_1298_p1 = $signed(trunc_ln54_54_fu_1288_p4);

assign sext_ln54_56_fu_1312_p1 = $signed(trunc_ln54_55_fu_1302_p4);

assign sext_ln54_57_fu_1326_p1 = $signed(trunc_ln54_56_fu_1316_p4);

assign sext_ln54_58_fu_1340_p1 = $signed(trunc_ln54_57_fu_1330_p4);

assign sext_ln54_59_fu_1354_p1 = $signed(trunc_ln54_58_fu_1344_p4);

assign sext_ln54_5_fu_598_p1 = $signed(trunc_ln54_5_fu_588_p4);

assign sext_ln54_60_fu_1368_p1 = $signed(trunc_ln54_59_fu_1358_p4);

assign sext_ln54_61_fu_1382_p1 = $signed(trunc_ln54_60_fu_1372_p4);

assign sext_ln54_6_fu_612_p1 = $signed(trunc_ln54_6_fu_602_p4);

assign sext_ln54_7_fu_626_p1 = $signed(trunc_ln54_7_fu_616_p4);

assign sext_ln54_8_fu_640_p1 = $signed(trunc_ln54_8_fu_630_p4);

assign sext_ln54_9_fu_654_p1 = $signed(trunc_ln54_9_fu_644_p4);

assign sext_ln54_fu_528_p1 = $signed(trunc_ln_fu_518_p4);

assign trunc_ln54_10_fu_672_p4 = {{data_11_val[15:1]}};

assign trunc_ln54_11_fu_686_p4 = {{data_12_val[15:1]}};

assign trunc_ln54_12_fu_700_p4 = {{data_13_val[15:1]}};

assign trunc_ln54_13_fu_714_p4 = {{data_14_val[15:1]}};

assign trunc_ln54_14_fu_728_p4 = {{data_15_val[15:1]}};

assign trunc_ln54_15_fu_742_p4 = {{data_16_val[15:1]}};

assign trunc_ln54_16_fu_756_p4 = {{data_17_val[15:1]}};

assign trunc_ln54_17_fu_770_p4 = {{data_18_val[15:1]}};

assign trunc_ln54_18_fu_784_p4 = {{data_19_val[15:1]}};

assign trunc_ln54_19_fu_798_p4 = {{data_20_val[15:1]}};

assign trunc_ln54_1_fu_532_p4 = {{data_1_val[15:1]}};

assign trunc_ln54_20_fu_812_p4 = {{data_21_val[15:1]}};

assign trunc_ln54_21_fu_826_p4 = {{data_22_val[15:1]}};

assign trunc_ln54_22_fu_840_p4 = {{data_23_val[15:1]}};

assign trunc_ln54_23_fu_854_p4 = {{data_24_val[15:1]}};

assign trunc_ln54_24_fu_868_p4 = {{data_25_val[15:1]}};

assign trunc_ln54_25_fu_882_p4 = {{data_26_val[15:1]}};

assign trunc_ln54_26_fu_896_p4 = {{data_27_val[15:1]}};

assign trunc_ln54_27_fu_910_p4 = {{data_28_val[15:1]}};

assign trunc_ln54_28_fu_924_p4 = {{data_29_val[15:1]}};

assign trunc_ln54_29_fu_938_p4 = {{data_30_val[15:1]}};

assign trunc_ln54_2_fu_546_p4 = {{data_2_val[15:1]}};

assign trunc_ln54_30_fu_952_p4 = {{data_31_val[15:1]}};

assign trunc_ln54_31_fu_966_p4 = {{data_32_val[15:1]}};

assign trunc_ln54_32_fu_980_p4 = {{data_34_val[15:1]}};

assign trunc_ln54_33_fu_994_p4 = {{data_35_val[15:1]}};

assign trunc_ln54_34_fu_1008_p4 = {{data_36_val[15:1]}};

assign trunc_ln54_35_fu_1022_p4 = {{data_37_val[15:1]}};

assign trunc_ln54_36_fu_1036_p4 = {{data_38_val[15:1]}};

assign trunc_ln54_37_fu_1050_p4 = {{data_40_val[15:1]}};

assign trunc_ln54_38_fu_1064_p4 = {{data_41_val[15:1]}};

assign trunc_ln54_39_fu_1078_p4 = {{data_42_val[15:1]}};

assign trunc_ln54_3_fu_560_p4 = {{data_3_val[15:1]}};

assign trunc_ln54_40_fu_1092_p4 = {{data_43_val[15:1]}};

assign trunc_ln54_41_fu_1106_p4 = {{data_44_val[15:1]}};

assign trunc_ln54_42_fu_1120_p4 = {{data_45_val[15:1]}};

assign trunc_ln54_43_fu_1134_p4 = {{data_46_val[15:1]}};

assign trunc_ln54_44_fu_1148_p4 = {{data_47_val[15:1]}};

assign trunc_ln54_45_fu_1162_p4 = {{data_48_val[15:1]}};

assign trunc_ln54_46_fu_1176_p4 = {{data_49_val[15:1]}};

assign trunc_ln54_47_fu_1190_p4 = {{data_50_val[15:1]}};

assign trunc_ln54_48_fu_1204_p4 = {{data_51_val[15:1]}};

assign trunc_ln54_49_fu_1218_p4 = {{data_52_val[15:1]}};

assign trunc_ln54_4_fu_574_p4 = {{data_4_val[15:1]}};

assign trunc_ln54_50_fu_1232_p4 = {{data_53_val[15:1]}};

assign trunc_ln54_51_fu_1246_p4 = {{data_54_val[15:1]}};

assign trunc_ln54_52_fu_1260_p4 = {{data_55_val[15:1]}};

assign trunc_ln54_53_fu_1274_p4 = {{data_56_val[15:1]}};

assign trunc_ln54_54_fu_1288_p4 = {{data_57_val[15:1]}};

assign trunc_ln54_55_fu_1302_p4 = {{data_58_val[15:1]}};

assign trunc_ln54_56_fu_1316_p4 = {{data_59_val[15:1]}};

assign trunc_ln54_57_fu_1330_p4 = {{data_60_val[15:1]}};

assign trunc_ln54_58_fu_1344_p4 = {{data_61_val[15:1]}};

assign trunc_ln54_59_fu_1358_p4 = {{data_62_val[15:1]}};

assign trunc_ln54_5_fu_588_p4 = {{data_5_val[15:1]}};

assign trunc_ln54_60_fu_1372_p4 = {{data_63_val[15:1]}};

assign trunc_ln54_6_fu_602_p4 = {{data_6_val[15:1]}};

assign trunc_ln54_7_fu_616_p4 = {{data_7_val[15:1]}};

assign trunc_ln54_8_fu_630_p4 = {{data_8_val[15:1]}};

assign trunc_ln54_9_fu_644_p4 = {{data_9_val[15:1]}};

assign trunc_ln54_s_fu_658_p4 = {{data_10_val[15:1]}};

assign trunc_ln_fu_518_p4 = {{data_0_val[15:1]}};

assign ap_return_0 = sext_ln54_fu_528_p1;

assign ap_return_1 = sext_ln54_1_fu_542_p1;

assign ap_return_10 = sext_ln54_10_fu_668_p1;

assign ap_return_11 = sext_ln54_11_fu_682_p1;

assign ap_return_12 = sext_ln54_12_fu_696_p1;

assign ap_return_13 = sext_ln54_13_fu_710_p1;

assign ap_return_14 = sext_ln54_14_fu_724_p1;

assign ap_return_15 = sext_ln54_15_fu_738_p1;

assign ap_return_16 = sext_ln54_16_fu_752_p1;

assign ap_return_17 = sext_ln54_17_fu_766_p1;

assign ap_return_18 = sext_ln54_18_fu_780_p1;

assign ap_return_19 = sext_ln54_19_fu_794_p1;

assign ap_return_2 = sext_ln54_2_fu_556_p1;

assign ap_return_20 = sext_ln54_20_fu_808_p1;

assign ap_return_21 = sext_ln54_21_fu_822_p1;

assign ap_return_22 = sext_ln54_22_fu_836_p1;

assign ap_return_23 = sext_ln54_23_fu_850_p1;

assign ap_return_24 = sext_ln54_24_fu_864_p1;

assign ap_return_25 = sext_ln54_25_fu_878_p1;

assign ap_return_26 = sext_ln54_26_fu_892_p1;

assign ap_return_27 = sext_ln54_27_fu_906_p1;

assign ap_return_28 = sext_ln54_28_fu_920_p1;

assign ap_return_29 = sext_ln54_29_fu_934_p1;

assign ap_return_3 = sext_ln54_3_fu_570_p1;

assign ap_return_30 = sext_ln54_30_fu_948_p1;

assign ap_return_31 = sext_ln54_31_fu_962_p1;

assign ap_return_32 = sext_ln54_32_fu_976_p1;

assign ap_return_33 = sext_ln54_33_fu_990_p1;

assign ap_return_34 = sext_ln54_34_fu_1004_p1;

assign ap_return_35 = sext_ln54_35_fu_1018_p1;

assign ap_return_36 = sext_ln54_36_fu_1032_p1;

assign ap_return_37 = sext_ln54_37_fu_1046_p1;

assign ap_return_38 = sext_ln54_38_fu_1060_p1;

assign ap_return_39 = sext_ln54_39_fu_1074_p1;

assign ap_return_4 = sext_ln54_4_fu_584_p1;

assign ap_return_40 = sext_ln54_40_fu_1088_p1;

assign ap_return_41 = sext_ln54_41_fu_1102_p1;

assign ap_return_42 = sext_ln54_42_fu_1116_p1;

assign ap_return_43 = sext_ln54_43_fu_1130_p1;

assign ap_return_44 = sext_ln54_44_fu_1144_p1;

assign ap_return_45 = sext_ln54_45_fu_1158_p1;

assign ap_return_46 = sext_ln54_46_fu_1172_p1;

assign ap_return_47 = sext_ln54_47_fu_1186_p1;

assign ap_return_48 = sext_ln54_48_fu_1200_p1;

assign ap_return_49 = sext_ln54_49_fu_1214_p1;

assign ap_return_5 = sext_ln54_5_fu_598_p1;

assign ap_return_50 = sext_ln54_50_fu_1228_p1;

assign ap_return_51 = sext_ln54_51_fu_1242_p1;

assign ap_return_52 = sext_ln54_52_fu_1256_p1;

assign ap_return_53 = sext_ln54_53_fu_1270_p1;

assign ap_return_54 = sext_ln54_54_fu_1284_p1;

assign ap_return_55 = sext_ln54_55_fu_1298_p1;

assign ap_return_56 = sext_ln54_56_fu_1312_p1;

assign ap_return_57 = sext_ln54_57_fu_1326_p1;

assign ap_return_58 = sext_ln54_58_fu_1340_p1;

assign ap_return_59 = sext_ln54_59_fu_1354_p1;

assign ap_return_6 = sext_ln54_6_fu_612_p1;

assign ap_return_60 = sext_ln54_60_fu_1368_p1;

assign ap_return_61 = sext_ln54_61_fu_1382_p1;

assign ap_return_7 = sext_ln54_7_fu_626_p1;

assign ap_return_8 = sext_ln54_8_fu_640_p1;

assign ap_return_9 = sext_ln54_9_fu_654_p1;

endmodule //myproject_normalize_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_config15_s
