// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_relu_ap_fixed_16_8_5_3_0_ap_ufixed_3_0_4_0_0_relu_config4_s (
        ap_ready,
        data_0_val,
        data_1_val,
        data_2_val,
        data_3_val,
        data_4_val,
        data_5_val,
        data_6_val,
        data_7_val,
        data_8_val,
        data_9_val,
        data_10_val,
        data_11_val,
        data_12_val,
        data_13_val,
        data_14_val,
        data_15_val,
        data_16_val,
        data_17_val,
        data_18_val,
        data_19_val,
        data_20_val,
        data_21_val,
        data_22_val,
        data_23_val,
        data_24_val,
        data_25_val,
        data_26_val,
        data_27_val,
        data_28_val,
        data_29_val,
        data_30_val,
        data_31_val,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9,
        ap_return_10,
        ap_return_11,
        ap_return_12,
        ap_return_13,
        ap_return_14,
        ap_return_15,
        ap_return_16,
        ap_return_17,
        ap_return_18,
        ap_return_19,
        ap_return_20,
        ap_return_21,
        ap_return_22,
        ap_return_23,
        ap_return_24,
        ap_return_25,
        ap_return_26,
        ap_return_27,
        ap_return_28,
        ap_return_29,
        ap_return_30,
        ap_return_31
);


output   ap_ready;
input  [15:0] data_0_val;
input  [15:0] data_1_val;
input  [15:0] data_2_val;
input  [15:0] data_3_val;
input  [15:0] data_4_val;
input  [15:0] data_5_val;
input  [15:0] data_6_val;
input  [15:0] data_7_val;
input  [15:0] data_8_val;
input  [15:0] data_9_val;
input  [15:0] data_10_val;
input  [15:0] data_11_val;
input  [15:0] data_12_val;
input  [15:0] data_13_val;
input  [15:0] data_14_val;
input  [15:0] data_15_val;
input  [15:0] data_16_val;
input  [15:0] data_17_val;
input  [15:0] data_18_val;
input  [15:0] data_19_val;
input  [15:0] data_20_val;
input  [15:0] data_21_val;
input  [15:0] data_22_val;
input  [15:0] data_23_val;
input  [15:0] data_24_val;
input  [15:0] data_25_val;
input  [15:0] data_26_val;
input  [15:0] data_27_val;
input  [15:0] data_28_val;
input  [15:0] data_29_val;
input  [15:0] data_30_val;
input  [15:0] data_31_val;
output  [2:0] ap_return_0;
output  [2:0] ap_return_1;
output  [2:0] ap_return_2;
output  [2:0] ap_return_3;
output  [2:0] ap_return_4;
output  [2:0] ap_return_5;
output  [2:0] ap_return_6;
output  [2:0] ap_return_7;
output  [2:0] ap_return_8;
output  [2:0] ap_return_9;
output  [2:0] ap_return_10;
output  [2:0] ap_return_11;
output  [2:0] ap_return_12;
output  [2:0] ap_return_13;
output  [2:0] ap_return_14;
output  [2:0] ap_return_15;
output  [2:0] ap_return_16;
output  [2:0] ap_return_17;
output  [2:0] ap_return_18;
output  [2:0] ap_return_19;
output  [2:0] ap_return_20;
output  [2:0] ap_return_21;
output  [2:0] ap_return_22;
output  [2:0] ap_return_23;
output  [2:0] ap_return_24;
output  [2:0] ap_return_25;
output  [2:0] ap_return_26;
output  [2:0] ap_return_27;
output  [2:0] ap_return_28;
output  [2:0] ap_return_29;
output  [2:0] ap_return_30;
output  [2:0] ap_return_31;

wire   [3:0] trunc_ln46_fu_332_p1;
wire   [0:0] tmp_fu_316_p3;
wire   [0:0] icmp_ln46_fu_336_p2;
wire   [0:0] or_ln46_fu_342_p2;
wire   [0:0] tmp_319_fu_324_p3;
wire   [0:0] and_ln46_fu_348_p2;
wire   [2:0] trunc_ln2_fu_306_p4;
wire   [2:0] zext_ln46_fu_354_p1;
wire   [7:0] tmp_34_fu_364_p4;
wire   [2:0] add_ln46_fu_358_p2;
wire   [0:0] tmp_321_fu_388_p3;
wire   [0:0] tmp_320_fu_380_p3;
wire   [0:0] xor_ln46_fu_396_p2;
wire   [0:0] icmp_ln46_128_fu_374_p2;
wire   [0:0] or_ln46_128_fu_402_p2;
wire   [0:0] and_ln46_128_fu_408_p2;
wire   [0:0] icmp_ln45_fu_300_p2;
wire   [2:0] select_ln46_fu_414_p3;
wire   [3:0] trunc_ln46_127_fu_462_p1;
wire   [0:0] tmp_322_fu_446_p3;
wire   [0:0] icmp_ln46_129_fu_466_p2;
wire   [0:0] or_ln46_64_fu_472_p2;
wire   [0:0] tmp_323_fu_454_p3;
wire   [0:0] and_ln46_129_fu_478_p2;
wire   [2:0] trunc_ln46_s_fu_436_p4;
wire   [2:0] zext_ln46_64_fu_484_p1;
wire   [7:0] tmp_s_fu_494_p4;
wire   [2:0] add_ln46_64_fu_488_p2;
wire   [0:0] tmp_325_fu_518_p3;
wire   [0:0] tmp_324_fu_510_p3;
wire   [0:0] xor_ln46_64_fu_526_p2;
wire   [0:0] icmp_ln46_130_fu_504_p2;
wire   [0:0] or_ln46_129_fu_532_p2;
wire   [0:0] and_ln46_130_fu_538_p2;
wire   [0:0] icmp_ln45_64_fu_430_p2;
wire   [2:0] select_ln46_64_fu_544_p3;
wire   [3:0] trunc_ln46_128_fu_592_p1;
wire   [0:0] tmp_326_fu_576_p3;
wire   [0:0] icmp_ln46_131_fu_596_p2;
wire   [0:0] or_ln46_65_fu_602_p2;
wire   [0:0] tmp_327_fu_584_p3;
wire   [0:0] and_ln46_131_fu_608_p2;
wire   [2:0] trunc_ln46_63_fu_566_p4;
wire   [2:0] zext_ln46_65_fu_614_p1;
wire   [7:0] tmp_317_fu_624_p4;
wire   [2:0] add_ln46_65_fu_618_p2;
wire   [0:0] tmp_329_fu_648_p3;
wire   [0:0] tmp_328_fu_640_p3;
wire   [0:0] xor_ln46_65_fu_656_p2;
wire   [0:0] icmp_ln46_132_fu_634_p2;
wire   [0:0] or_ln46_130_fu_662_p2;
wire   [0:0] and_ln46_132_fu_668_p2;
wire   [0:0] icmp_ln45_65_fu_560_p2;
wire   [2:0] select_ln46_65_fu_674_p3;
wire   [3:0] trunc_ln46_129_fu_722_p1;
wire   [0:0] tmp_330_fu_706_p3;
wire   [0:0] icmp_ln46_133_fu_726_p2;
wire   [0:0] or_ln46_66_fu_732_p2;
wire   [0:0] tmp_331_fu_714_p3;
wire   [0:0] and_ln46_133_fu_738_p2;
wire   [2:0] trunc_ln46_64_fu_696_p4;
wire   [2:0] zext_ln46_66_fu_744_p1;
wire   [7:0] tmp_318_fu_754_p4;
wire   [2:0] add_ln46_66_fu_748_p2;
wire   [0:0] tmp_333_fu_778_p3;
wire   [0:0] tmp_332_fu_770_p3;
wire   [0:0] xor_ln46_66_fu_786_p2;
wire   [0:0] icmp_ln46_134_fu_764_p2;
wire   [0:0] or_ln46_131_fu_792_p2;
wire   [0:0] and_ln46_134_fu_798_p2;
wire   [0:0] icmp_ln45_66_fu_690_p2;
wire   [2:0] select_ln46_66_fu_804_p3;
wire   [3:0] trunc_ln46_130_fu_852_p1;
wire   [0:0] tmp_334_fu_836_p3;
wire   [0:0] icmp_ln46_135_fu_856_p2;
wire   [0:0] or_ln46_67_fu_862_p2;
wire   [0:0] tmp_335_fu_844_p3;
wire   [0:0] and_ln46_135_fu_868_p2;
wire   [2:0] trunc_ln46_65_fu_826_p4;
wire   [2:0] zext_ln46_67_fu_874_p1;
wire   [7:0] tmp_336_fu_884_p4;
wire   [2:0] add_ln46_67_fu_878_p2;
wire   [0:0] tmp_338_fu_908_p3;
wire   [0:0] tmp_337_fu_900_p3;
wire   [0:0] xor_ln46_67_fu_916_p2;
wire   [0:0] icmp_ln46_136_fu_894_p2;
wire   [0:0] or_ln46_132_fu_922_p2;
wire   [0:0] and_ln46_136_fu_928_p2;
wire   [0:0] icmp_ln45_67_fu_820_p2;
wire   [2:0] select_ln46_67_fu_934_p3;
wire   [3:0] trunc_ln46_131_fu_982_p1;
wire   [0:0] tmp_339_fu_966_p3;
wire   [0:0] icmp_ln46_137_fu_986_p2;
wire   [0:0] or_ln46_68_fu_992_p2;
wire   [0:0] tmp_340_fu_974_p3;
wire   [0:0] and_ln46_137_fu_998_p2;
wire   [2:0] trunc_ln46_66_fu_956_p4;
wire   [2:0] zext_ln46_68_fu_1004_p1;
wire   [7:0] tmp_341_fu_1014_p4;
wire   [2:0] add_ln46_68_fu_1008_p2;
wire   [0:0] tmp_343_fu_1038_p3;
wire   [0:0] tmp_342_fu_1030_p3;
wire   [0:0] xor_ln46_68_fu_1046_p2;
wire   [0:0] icmp_ln46_138_fu_1024_p2;
wire   [0:0] or_ln46_133_fu_1052_p2;
wire   [0:0] and_ln46_138_fu_1058_p2;
wire   [0:0] icmp_ln45_68_fu_950_p2;
wire   [2:0] select_ln46_68_fu_1064_p3;
wire   [3:0] trunc_ln46_132_fu_1112_p1;
wire   [0:0] tmp_344_fu_1096_p3;
wire   [0:0] icmp_ln46_139_fu_1116_p2;
wire   [0:0] or_ln46_69_fu_1122_p2;
wire   [0:0] tmp_345_fu_1104_p3;
wire   [0:0] and_ln46_139_fu_1128_p2;
wire   [2:0] trunc_ln46_67_fu_1086_p4;
wire   [2:0] zext_ln46_69_fu_1134_p1;
wire   [7:0] tmp_346_fu_1144_p4;
wire   [2:0] add_ln46_69_fu_1138_p2;
wire   [0:0] tmp_348_fu_1168_p3;
wire   [0:0] tmp_347_fu_1160_p3;
wire   [0:0] xor_ln46_69_fu_1176_p2;
wire   [0:0] icmp_ln46_140_fu_1154_p2;
wire   [0:0] or_ln46_134_fu_1182_p2;
wire   [0:0] and_ln46_140_fu_1188_p2;
wire   [0:0] icmp_ln45_69_fu_1080_p2;
wire   [2:0] select_ln46_69_fu_1194_p3;
wire   [3:0] trunc_ln46_133_fu_1242_p1;
wire   [0:0] tmp_349_fu_1226_p3;
wire   [0:0] icmp_ln46_141_fu_1246_p2;
wire   [0:0] or_ln46_70_fu_1252_p2;
wire   [0:0] tmp_350_fu_1234_p3;
wire   [0:0] and_ln46_141_fu_1258_p2;
wire   [2:0] trunc_ln46_68_fu_1216_p4;
wire   [2:0] zext_ln46_70_fu_1264_p1;
wire   [7:0] tmp_351_fu_1274_p4;
wire   [2:0] add_ln46_70_fu_1268_p2;
wire   [0:0] tmp_353_fu_1298_p3;
wire   [0:0] tmp_352_fu_1290_p3;
wire   [0:0] xor_ln46_70_fu_1306_p2;
wire   [0:0] icmp_ln46_142_fu_1284_p2;
wire   [0:0] or_ln46_135_fu_1312_p2;
wire   [0:0] and_ln46_142_fu_1318_p2;
wire   [0:0] icmp_ln45_70_fu_1210_p2;
wire   [2:0] select_ln46_70_fu_1324_p3;
wire   [3:0] trunc_ln46_134_fu_1372_p1;
wire   [0:0] tmp_354_fu_1356_p3;
wire   [0:0] icmp_ln46_143_fu_1376_p2;
wire   [0:0] or_ln46_71_fu_1382_p2;
wire   [0:0] tmp_355_fu_1364_p3;
wire   [0:0] and_ln46_143_fu_1388_p2;
wire   [2:0] trunc_ln46_69_fu_1346_p4;
wire   [2:0] zext_ln46_71_fu_1394_p1;
wire   [7:0] tmp_356_fu_1404_p4;
wire   [2:0] add_ln46_71_fu_1398_p2;
wire   [0:0] tmp_358_fu_1428_p3;
wire   [0:0] tmp_357_fu_1420_p3;
wire   [0:0] xor_ln46_71_fu_1436_p2;
wire   [0:0] icmp_ln46_144_fu_1414_p2;
wire   [0:0] or_ln46_136_fu_1442_p2;
wire   [0:0] and_ln46_144_fu_1448_p2;
wire   [0:0] icmp_ln45_71_fu_1340_p2;
wire   [2:0] select_ln46_71_fu_1454_p3;
wire   [3:0] trunc_ln46_135_fu_1502_p1;
wire   [0:0] tmp_359_fu_1486_p3;
wire   [0:0] icmp_ln46_145_fu_1506_p2;
wire   [0:0] or_ln46_72_fu_1512_p2;
wire   [0:0] tmp_360_fu_1494_p3;
wire   [0:0] and_ln46_145_fu_1518_p2;
wire   [2:0] trunc_ln46_70_fu_1476_p4;
wire   [2:0] zext_ln46_72_fu_1524_p1;
wire   [7:0] tmp_361_fu_1534_p4;
wire   [2:0] add_ln46_72_fu_1528_p2;
wire   [0:0] tmp_363_fu_1558_p3;
wire   [0:0] tmp_362_fu_1550_p3;
wire   [0:0] xor_ln46_72_fu_1566_p2;
wire   [0:0] icmp_ln46_146_fu_1544_p2;
wire   [0:0] or_ln46_137_fu_1572_p2;
wire   [0:0] and_ln46_146_fu_1578_p2;
wire   [0:0] icmp_ln45_72_fu_1470_p2;
wire   [2:0] select_ln46_72_fu_1584_p3;
wire   [3:0] trunc_ln46_136_fu_1632_p1;
wire   [0:0] tmp_364_fu_1616_p3;
wire   [0:0] icmp_ln46_147_fu_1636_p2;
wire   [0:0] or_ln46_73_fu_1642_p2;
wire   [0:0] tmp_365_fu_1624_p3;
wire   [0:0] and_ln46_147_fu_1648_p2;
wire   [2:0] trunc_ln46_71_fu_1606_p4;
wire   [2:0] zext_ln46_73_fu_1654_p1;
wire   [7:0] tmp_366_fu_1664_p4;
wire   [2:0] add_ln46_73_fu_1658_p2;
wire   [0:0] tmp_368_fu_1688_p3;
wire   [0:0] tmp_367_fu_1680_p3;
wire   [0:0] xor_ln46_73_fu_1696_p2;
wire   [0:0] icmp_ln46_148_fu_1674_p2;
wire   [0:0] or_ln46_138_fu_1702_p2;
wire   [0:0] and_ln46_148_fu_1708_p2;
wire   [0:0] icmp_ln45_73_fu_1600_p2;
wire   [2:0] select_ln46_73_fu_1714_p3;
wire   [3:0] trunc_ln46_137_fu_1762_p1;
wire   [0:0] tmp_369_fu_1746_p3;
wire   [0:0] icmp_ln46_149_fu_1766_p2;
wire   [0:0] or_ln46_74_fu_1772_p2;
wire   [0:0] tmp_370_fu_1754_p3;
wire   [0:0] and_ln46_149_fu_1778_p2;
wire   [2:0] trunc_ln46_72_fu_1736_p4;
wire   [2:0] zext_ln46_74_fu_1784_p1;
wire   [7:0] tmp_371_fu_1794_p4;
wire   [2:0] add_ln46_74_fu_1788_p2;
wire   [0:0] tmp_373_fu_1818_p3;
wire   [0:0] tmp_372_fu_1810_p3;
wire   [0:0] xor_ln46_74_fu_1826_p2;
wire   [0:0] icmp_ln46_150_fu_1804_p2;
wire   [0:0] or_ln46_139_fu_1832_p2;
wire   [0:0] and_ln46_150_fu_1838_p2;
wire   [0:0] icmp_ln45_74_fu_1730_p2;
wire   [2:0] select_ln46_74_fu_1844_p3;
wire   [3:0] trunc_ln46_138_fu_1892_p1;
wire   [0:0] tmp_374_fu_1876_p3;
wire   [0:0] icmp_ln46_151_fu_1896_p2;
wire   [0:0] or_ln46_75_fu_1902_p2;
wire   [0:0] tmp_375_fu_1884_p3;
wire   [0:0] and_ln46_151_fu_1908_p2;
wire   [2:0] trunc_ln46_73_fu_1866_p4;
wire   [2:0] zext_ln46_75_fu_1914_p1;
wire   [7:0] tmp_376_fu_1924_p4;
wire   [2:0] add_ln46_75_fu_1918_p2;
wire   [0:0] tmp_378_fu_1948_p3;
wire   [0:0] tmp_377_fu_1940_p3;
wire   [0:0] xor_ln46_75_fu_1956_p2;
wire   [0:0] icmp_ln46_152_fu_1934_p2;
wire   [0:0] or_ln46_140_fu_1962_p2;
wire   [0:0] and_ln46_152_fu_1968_p2;
wire   [0:0] icmp_ln45_75_fu_1860_p2;
wire   [2:0] select_ln46_75_fu_1974_p3;
wire   [3:0] trunc_ln46_139_fu_2022_p1;
wire   [0:0] tmp_379_fu_2006_p3;
wire   [0:0] icmp_ln46_153_fu_2026_p2;
wire   [0:0] or_ln46_76_fu_2032_p2;
wire   [0:0] tmp_380_fu_2014_p3;
wire   [0:0] and_ln46_153_fu_2038_p2;
wire   [2:0] trunc_ln46_74_fu_1996_p4;
wire   [2:0] zext_ln46_76_fu_2044_p1;
wire   [7:0] tmp_381_fu_2054_p4;
wire   [2:0] add_ln46_76_fu_2048_p2;
wire   [0:0] tmp_383_fu_2078_p3;
wire   [0:0] tmp_382_fu_2070_p3;
wire   [0:0] xor_ln46_76_fu_2086_p2;
wire   [0:0] icmp_ln46_154_fu_2064_p2;
wire   [0:0] or_ln46_141_fu_2092_p2;
wire   [0:0] and_ln46_154_fu_2098_p2;
wire   [0:0] icmp_ln45_76_fu_1990_p2;
wire   [2:0] select_ln46_76_fu_2104_p3;
wire   [3:0] trunc_ln46_140_fu_2152_p1;
wire   [0:0] tmp_384_fu_2136_p3;
wire   [0:0] icmp_ln46_155_fu_2156_p2;
wire   [0:0] or_ln46_77_fu_2162_p2;
wire   [0:0] tmp_385_fu_2144_p3;
wire   [0:0] and_ln46_155_fu_2168_p2;
wire   [2:0] trunc_ln46_75_fu_2126_p4;
wire   [2:0] zext_ln46_77_fu_2174_p1;
wire   [7:0] tmp_386_fu_2184_p4;
wire   [2:0] add_ln46_77_fu_2178_p2;
wire   [0:0] tmp_388_fu_2208_p3;
wire   [0:0] tmp_387_fu_2200_p3;
wire   [0:0] xor_ln46_77_fu_2216_p2;
wire   [0:0] icmp_ln46_156_fu_2194_p2;
wire   [0:0] or_ln46_142_fu_2222_p2;
wire   [0:0] and_ln46_156_fu_2228_p2;
wire   [0:0] icmp_ln45_77_fu_2120_p2;
wire   [2:0] select_ln46_77_fu_2234_p3;
wire   [3:0] trunc_ln46_141_fu_2282_p1;
wire   [0:0] tmp_389_fu_2266_p3;
wire   [0:0] icmp_ln46_157_fu_2286_p2;
wire   [0:0] or_ln46_78_fu_2292_p2;
wire   [0:0] tmp_390_fu_2274_p3;
wire   [0:0] and_ln46_157_fu_2298_p2;
wire   [2:0] trunc_ln46_76_fu_2256_p4;
wire   [2:0] zext_ln46_78_fu_2304_p1;
wire   [7:0] tmp_391_fu_2314_p4;
wire   [2:0] add_ln46_78_fu_2308_p2;
wire   [0:0] tmp_393_fu_2338_p3;
wire   [0:0] tmp_392_fu_2330_p3;
wire   [0:0] xor_ln46_78_fu_2346_p2;
wire   [0:0] icmp_ln46_158_fu_2324_p2;
wire   [0:0] or_ln46_143_fu_2352_p2;
wire   [0:0] and_ln46_158_fu_2358_p2;
wire   [0:0] icmp_ln45_78_fu_2250_p2;
wire   [2:0] select_ln46_78_fu_2364_p3;
wire   [3:0] trunc_ln46_142_fu_2412_p1;
wire   [0:0] tmp_394_fu_2396_p3;
wire   [0:0] icmp_ln46_159_fu_2416_p2;
wire   [0:0] or_ln46_79_fu_2422_p2;
wire   [0:0] tmp_395_fu_2404_p3;
wire   [0:0] and_ln46_159_fu_2428_p2;
wire   [2:0] trunc_ln46_77_fu_2386_p4;
wire   [2:0] zext_ln46_79_fu_2434_p1;
wire   [7:0] tmp_396_fu_2444_p4;
wire   [2:0] add_ln46_79_fu_2438_p2;
wire   [0:0] tmp_398_fu_2468_p3;
wire   [0:0] tmp_397_fu_2460_p3;
wire   [0:0] xor_ln46_79_fu_2476_p2;
wire   [0:0] icmp_ln46_160_fu_2454_p2;
wire   [0:0] or_ln46_144_fu_2482_p2;
wire   [0:0] and_ln46_160_fu_2488_p2;
wire   [0:0] icmp_ln45_79_fu_2380_p2;
wire   [2:0] select_ln46_79_fu_2494_p3;
wire   [3:0] trunc_ln46_143_fu_2542_p1;
wire   [0:0] tmp_399_fu_2526_p3;
wire   [0:0] icmp_ln46_161_fu_2546_p2;
wire   [0:0] or_ln46_80_fu_2552_p2;
wire   [0:0] tmp_400_fu_2534_p3;
wire   [0:0] and_ln46_161_fu_2558_p2;
wire   [2:0] trunc_ln46_78_fu_2516_p4;
wire   [2:0] zext_ln46_80_fu_2564_p1;
wire   [7:0] tmp_401_fu_2574_p4;
wire   [2:0] add_ln46_80_fu_2568_p2;
wire   [0:0] tmp_403_fu_2598_p3;
wire   [0:0] tmp_402_fu_2590_p3;
wire   [0:0] xor_ln46_80_fu_2606_p2;
wire   [0:0] icmp_ln46_162_fu_2584_p2;
wire   [0:0] or_ln46_145_fu_2612_p2;
wire   [0:0] and_ln46_162_fu_2618_p2;
wire   [0:0] icmp_ln45_80_fu_2510_p2;
wire   [2:0] select_ln46_80_fu_2624_p3;
wire   [3:0] trunc_ln46_144_fu_2672_p1;
wire   [0:0] tmp_404_fu_2656_p3;
wire   [0:0] icmp_ln46_163_fu_2676_p2;
wire   [0:0] or_ln46_81_fu_2682_p2;
wire   [0:0] tmp_405_fu_2664_p3;
wire   [0:0] and_ln46_163_fu_2688_p2;
wire   [2:0] trunc_ln46_79_fu_2646_p4;
wire   [2:0] zext_ln46_81_fu_2694_p1;
wire   [7:0] tmp_406_fu_2704_p4;
wire   [2:0] add_ln46_81_fu_2698_p2;
wire   [0:0] tmp_408_fu_2728_p3;
wire   [0:0] tmp_407_fu_2720_p3;
wire   [0:0] xor_ln46_81_fu_2736_p2;
wire   [0:0] icmp_ln46_164_fu_2714_p2;
wire   [0:0] or_ln46_146_fu_2742_p2;
wire   [0:0] and_ln46_164_fu_2748_p2;
wire   [0:0] icmp_ln45_81_fu_2640_p2;
wire   [2:0] select_ln46_81_fu_2754_p3;
wire   [3:0] trunc_ln46_145_fu_2802_p1;
wire   [0:0] tmp_409_fu_2786_p3;
wire   [0:0] icmp_ln46_165_fu_2806_p2;
wire   [0:0] or_ln46_82_fu_2812_p2;
wire   [0:0] tmp_410_fu_2794_p3;
wire   [0:0] and_ln46_165_fu_2818_p2;
wire   [2:0] trunc_ln46_80_fu_2776_p4;
wire   [2:0] zext_ln46_82_fu_2824_p1;
wire   [7:0] tmp_411_fu_2834_p4;
wire   [2:0] add_ln46_82_fu_2828_p2;
wire   [0:0] tmp_413_fu_2858_p3;
wire   [0:0] tmp_412_fu_2850_p3;
wire   [0:0] xor_ln46_82_fu_2866_p2;
wire   [0:0] icmp_ln46_166_fu_2844_p2;
wire   [0:0] or_ln46_147_fu_2872_p2;
wire   [0:0] and_ln46_166_fu_2878_p2;
wire   [0:0] icmp_ln45_82_fu_2770_p2;
wire   [2:0] select_ln46_82_fu_2884_p3;
wire   [3:0] trunc_ln46_146_fu_2932_p1;
wire   [0:0] tmp_414_fu_2916_p3;
wire   [0:0] icmp_ln46_167_fu_2936_p2;
wire   [0:0] or_ln46_83_fu_2942_p2;
wire   [0:0] tmp_415_fu_2924_p3;
wire   [0:0] and_ln46_167_fu_2948_p2;
wire   [2:0] trunc_ln46_81_fu_2906_p4;
wire   [2:0] zext_ln46_83_fu_2954_p1;
wire   [7:0] tmp_416_fu_2964_p4;
wire   [2:0] add_ln46_83_fu_2958_p2;
wire   [0:0] tmp_418_fu_2988_p3;
wire   [0:0] tmp_417_fu_2980_p3;
wire   [0:0] xor_ln46_83_fu_2996_p2;
wire   [0:0] icmp_ln46_168_fu_2974_p2;
wire   [0:0] or_ln46_148_fu_3002_p2;
wire   [0:0] and_ln46_168_fu_3008_p2;
wire   [0:0] icmp_ln45_83_fu_2900_p2;
wire   [2:0] select_ln46_83_fu_3014_p3;
wire   [3:0] trunc_ln46_147_fu_3062_p1;
wire   [0:0] tmp_419_fu_3046_p3;
wire   [0:0] icmp_ln46_169_fu_3066_p2;
wire   [0:0] or_ln46_84_fu_3072_p2;
wire   [0:0] tmp_420_fu_3054_p3;
wire   [0:0] and_ln46_169_fu_3078_p2;
wire   [2:0] trunc_ln46_82_fu_3036_p4;
wire   [2:0] zext_ln46_84_fu_3084_p1;
wire   [7:0] tmp_421_fu_3094_p4;
wire   [2:0] add_ln46_84_fu_3088_p2;
wire   [0:0] tmp_423_fu_3118_p3;
wire   [0:0] tmp_422_fu_3110_p3;
wire   [0:0] xor_ln46_84_fu_3126_p2;
wire   [0:0] icmp_ln46_170_fu_3104_p2;
wire   [0:0] or_ln46_149_fu_3132_p2;
wire   [0:0] and_ln46_170_fu_3138_p2;
wire   [0:0] icmp_ln45_84_fu_3030_p2;
wire   [2:0] select_ln46_84_fu_3144_p3;
wire   [3:0] trunc_ln46_148_fu_3192_p1;
wire   [0:0] tmp_424_fu_3176_p3;
wire   [0:0] icmp_ln46_171_fu_3196_p2;
wire   [0:0] or_ln46_85_fu_3202_p2;
wire   [0:0] tmp_425_fu_3184_p3;
wire   [0:0] and_ln46_171_fu_3208_p2;
wire   [2:0] trunc_ln46_83_fu_3166_p4;
wire   [2:0] zext_ln46_85_fu_3214_p1;
wire   [7:0] tmp_426_fu_3224_p4;
wire   [2:0] add_ln46_85_fu_3218_p2;
wire   [0:0] tmp_428_fu_3248_p3;
wire   [0:0] tmp_427_fu_3240_p3;
wire   [0:0] xor_ln46_85_fu_3256_p2;
wire   [0:0] icmp_ln46_172_fu_3234_p2;
wire   [0:0] or_ln46_150_fu_3262_p2;
wire   [0:0] and_ln46_172_fu_3268_p2;
wire   [0:0] icmp_ln45_85_fu_3160_p2;
wire   [2:0] select_ln46_85_fu_3274_p3;
wire   [3:0] trunc_ln46_149_fu_3322_p1;
wire   [0:0] tmp_429_fu_3306_p3;
wire   [0:0] icmp_ln46_173_fu_3326_p2;
wire   [0:0] or_ln46_86_fu_3332_p2;
wire   [0:0] tmp_430_fu_3314_p3;
wire   [0:0] and_ln46_173_fu_3338_p2;
wire   [2:0] trunc_ln46_84_fu_3296_p4;
wire   [2:0] zext_ln46_86_fu_3344_p1;
wire   [7:0] tmp_431_fu_3354_p4;
wire   [2:0] add_ln46_86_fu_3348_p2;
wire   [0:0] tmp_433_fu_3378_p3;
wire   [0:0] tmp_432_fu_3370_p3;
wire   [0:0] xor_ln46_86_fu_3386_p2;
wire   [0:0] icmp_ln46_174_fu_3364_p2;
wire   [0:0] or_ln46_151_fu_3392_p2;
wire   [0:0] and_ln46_174_fu_3398_p2;
wire   [0:0] icmp_ln45_86_fu_3290_p2;
wire   [2:0] select_ln46_86_fu_3404_p3;
wire   [3:0] trunc_ln46_150_fu_3452_p1;
wire   [0:0] tmp_434_fu_3436_p3;
wire   [0:0] icmp_ln46_175_fu_3456_p2;
wire   [0:0] or_ln46_87_fu_3462_p2;
wire   [0:0] tmp_435_fu_3444_p3;
wire   [0:0] and_ln46_175_fu_3468_p2;
wire   [2:0] trunc_ln46_85_fu_3426_p4;
wire   [2:0] zext_ln46_87_fu_3474_p1;
wire   [7:0] tmp_436_fu_3484_p4;
wire   [2:0] add_ln46_87_fu_3478_p2;
wire   [0:0] tmp_438_fu_3508_p3;
wire   [0:0] tmp_437_fu_3500_p3;
wire   [0:0] xor_ln46_87_fu_3516_p2;
wire   [0:0] icmp_ln46_176_fu_3494_p2;
wire   [0:0] or_ln46_152_fu_3522_p2;
wire   [0:0] and_ln46_176_fu_3528_p2;
wire   [0:0] icmp_ln45_87_fu_3420_p2;
wire   [2:0] select_ln46_87_fu_3534_p3;
wire   [3:0] trunc_ln46_151_fu_3582_p1;
wire   [0:0] tmp_439_fu_3566_p3;
wire   [0:0] icmp_ln46_177_fu_3586_p2;
wire   [0:0] or_ln46_88_fu_3592_p2;
wire   [0:0] tmp_440_fu_3574_p3;
wire   [0:0] and_ln46_177_fu_3598_p2;
wire   [2:0] trunc_ln46_86_fu_3556_p4;
wire   [2:0] zext_ln46_88_fu_3604_p1;
wire   [7:0] tmp_441_fu_3614_p4;
wire   [2:0] add_ln46_88_fu_3608_p2;
wire   [0:0] tmp_443_fu_3638_p3;
wire   [0:0] tmp_442_fu_3630_p3;
wire   [0:0] xor_ln46_88_fu_3646_p2;
wire   [0:0] icmp_ln46_178_fu_3624_p2;
wire   [0:0] or_ln46_153_fu_3652_p2;
wire   [0:0] and_ln46_178_fu_3658_p2;
wire   [0:0] icmp_ln45_88_fu_3550_p2;
wire   [2:0] select_ln46_88_fu_3664_p3;
wire   [3:0] trunc_ln46_152_fu_3712_p1;
wire   [0:0] tmp_444_fu_3696_p3;
wire   [0:0] icmp_ln46_179_fu_3716_p2;
wire   [0:0] or_ln46_89_fu_3722_p2;
wire   [0:0] tmp_445_fu_3704_p3;
wire   [0:0] and_ln46_179_fu_3728_p2;
wire   [2:0] trunc_ln46_87_fu_3686_p4;
wire   [2:0] zext_ln46_89_fu_3734_p1;
wire   [7:0] tmp_446_fu_3744_p4;
wire   [2:0] add_ln46_89_fu_3738_p2;
wire   [0:0] tmp_448_fu_3768_p3;
wire   [0:0] tmp_447_fu_3760_p3;
wire   [0:0] xor_ln46_89_fu_3776_p2;
wire   [0:0] icmp_ln46_180_fu_3754_p2;
wire   [0:0] or_ln46_154_fu_3782_p2;
wire   [0:0] and_ln46_180_fu_3788_p2;
wire   [0:0] icmp_ln45_89_fu_3680_p2;
wire   [2:0] select_ln46_89_fu_3794_p3;
wire   [3:0] trunc_ln46_153_fu_3842_p1;
wire   [0:0] tmp_449_fu_3826_p3;
wire   [0:0] icmp_ln46_181_fu_3846_p2;
wire   [0:0] or_ln46_90_fu_3852_p2;
wire   [0:0] tmp_450_fu_3834_p3;
wire   [0:0] and_ln46_181_fu_3858_p2;
wire   [2:0] trunc_ln46_88_fu_3816_p4;
wire   [2:0] zext_ln46_90_fu_3864_p1;
wire   [7:0] tmp_451_fu_3874_p4;
wire   [2:0] add_ln46_90_fu_3868_p2;
wire   [0:0] tmp_453_fu_3898_p3;
wire   [0:0] tmp_452_fu_3890_p3;
wire   [0:0] xor_ln46_90_fu_3906_p2;
wire   [0:0] icmp_ln46_182_fu_3884_p2;
wire   [0:0] or_ln46_155_fu_3912_p2;
wire   [0:0] and_ln46_182_fu_3918_p2;
wire   [0:0] icmp_ln45_90_fu_3810_p2;
wire   [2:0] select_ln46_90_fu_3924_p3;
wire   [3:0] trunc_ln46_154_fu_3972_p1;
wire   [0:0] tmp_454_fu_3956_p3;
wire   [0:0] icmp_ln46_183_fu_3976_p2;
wire   [0:0] or_ln46_91_fu_3982_p2;
wire   [0:0] tmp_455_fu_3964_p3;
wire   [0:0] and_ln46_183_fu_3988_p2;
wire   [2:0] trunc_ln46_89_fu_3946_p4;
wire   [2:0] zext_ln46_91_fu_3994_p1;
wire   [7:0] tmp_456_fu_4004_p4;
wire   [2:0] add_ln46_91_fu_3998_p2;
wire   [0:0] tmp_458_fu_4028_p3;
wire   [0:0] tmp_457_fu_4020_p3;
wire   [0:0] xor_ln46_91_fu_4036_p2;
wire   [0:0] icmp_ln46_184_fu_4014_p2;
wire   [0:0] or_ln46_156_fu_4042_p2;
wire   [0:0] and_ln46_184_fu_4048_p2;
wire   [0:0] icmp_ln45_91_fu_3940_p2;
wire   [2:0] select_ln46_91_fu_4054_p3;
wire   [3:0] trunc_ln46_155_fu_4102_p1;
wire   [0:0] tmp_459_fu_4086_p3;
wire   [0:0] icmp_ln46_185_fu_4106_p2;
wire   [0:0] or_ln46_92_fu_4112_p2;
wire   [0:0] tmp_460_fu_4094_p3;
wire   [0:0] and_ln46_185_fu_4118_p2;
wire   [2:0] trunc_ln46_90_fu_4076_p4;
wire   [2:0] zext_ln46_92_fu_4124_p1;
wire   [7:0] tmp_461_fu_4134_p4;
wire   [2:0] add_ln46_92_fu_4128_p2;
wire   [0:0] tmp_463_fu_4158_p3;
wire   [0:0] tmp_462_fu_4150_p3;
wire   [0:0] xor_ln46_92_fu_4166_p2;
wire   [0:0] icmp_ln46_186_fu_4144_p2;
wire   [0:0] or_ln46_157_fu_4172_p2;
wire   [0:0] and_ln46_186_fu_4178_p2;
wire   [0:0] icmp_ln45_92_fu_4070_p2;
wire   [2:0] select_ln46_92_fu_4184_p3;
wire   [3:0] trunc_ln46_156_fu_4232_p1;
wire   [0:0] tmp_464_fu_4216_p3;
wire   [0:0] icmp_ln46_187_fu_4236_p2;
wire   [0:0] or_ln46_93_fu_4242_p2;
wire   [0:0] tmp_465_fu_4224_p3;
wire   [0:0] and_ln46_187_fu_4248_p2;
wire   [2:0] trunc_ln46_91_fu_4206_p4;
wire   [2:0] zext_ln46_93_fu_4254_p1;
wire   [7:0] tmp_466_fu_4264_p4;
wire   [2:0] add_ln46_93_fu_4258_p2;
wire   [0:0] tmp_468_fu_4288_p3;
wire   [0:0] tmp_467_fu_4280_p3;
wire   [0:0] xor_ln46_93_fu_4296_p2;
wire   [0:0] icmp_ln46_188_fu_4274_p2;
wire   [0:0] or_ln46_158_fu_4302_p2;
wire   [0:0] and_ln46_188_fu_4308_p2;
wire   [0:0] icmp_ln45_93_fu_4200_p2;
wire   [2:0] select_ln46_93_fu_4314_p3;
wire   [3:0] trunc_ln46_157_fu_4362_p1;
wire   [0:0] tmp_469_fu_4346_p3;
wire   [0:0] icmp_ln46_189_fu_4366_p2;
wire   [0:0] or_ln46_94_fu_4372_p2;
wire   [0:0] tmp_470_fu_4354_p3;
wire   [0:0] and_ln46_189_fu_4378_p2;
wire   [2:0] trunc_ln46_92_fu_4336_p4;
wire   [2:0] zext_ln46_94_fu_4384_p1;
wire   [7:0] tmp_471_fu_4394_p4;
wire   [2:0] add_ln46_94_fu_4388_p2;
wire   [0:0] tmp_473_fu_4418_p3;
wire   [0:0] tmp_472_fu_4410_p3;
wire   [0:0] xor_ln46_94_fu_4426_p2;
wire   [0:0] icmp_ln46_190_fu_4404_p2;
wire   [0:0] or_ln46_159_fu_4432_p2;
wire   [0:0] and_ln46_190_fu_4438_p2;
wire   [0:0] icmp_ln45_94_fu_4330_p2;
wire   [2:0] select_ln46_94_fu_4444_p3;
wire   [2:0] select_ln45_fu_422_p3;
wire   [2:0] select_ln45_64_fu_552_p3;
wire   [2:0] select_ln45_65_fu_682_p3;
wire   [2:0] select_ln45_66_fu_812_p3;
wire   [2:0] select_ln45_67_fu_942_p3;
wire   [2:0] select_ln45_68_fu_1072_p3;
wire   [2:0] select_ln45_69_fu_1202_p3;
wire   [2:0] select_ln45_70_fu_1332_p3;
wire   [2:0] select_ln45_71_fu_1462_p3;
wire   [2:0] select_ln45_72_fu_1592_p3;
wire   [2:0] select_ln45_73_fu_1722_p3;
wire   [2:0] select_ln45_74_fu_1852_p3;
wire   [2:0] select_ln45_75_fu_1982_p3;
wire   [2:0] select_ln45_76_fu_2112_p3;
wire   [2:0] select_ln45_77_fu_2242_p3;
wire   [2:0] select_ln45_78_fu_2372_p3;
wire   [2:0] select_ln45_79_fu_2502_p3;
wire   [2:0] select_ln45_80_fu_2632_p3;
wire   [2:0] select_ln45_81_fu_2762_p3;
wire   [2:0] select_ln45_82_fu_2892_p3;
wire   [2:0] select_ln45_83_fu_3022_p3;
wire   [2:0] select_ln45_84_fu_3152_p3;
wire   [2:0] select_ln45_85_fu_3282_p3;
wire   [2:0] select_ln45_86_fu_3412_p3;
wire   [2:0] select_ln45_87_fu_3542_p3;
wire   [2:0] select_ln45_88_fu_3672_p3;
wire   [2:0] select_ln45_89_fu_3802_p3;
wire   [2:0] select_ln45_90_fu_3932_p3;
wire   [2:0] select_ln45_91_fu_4062_p3;
wire   [2:0] select_ln45_92_fu_4192_p3;
wire   [2:0] select_ln45_93_fu_4322_p3;
wire   [2:0] select_ln45_94_fu_4452_p3;
wire    ap_ce_reg;

assign add_ln46_64_fu_488_p2 = (trunc_ln46_s_fu_436_p4 + zext_ln46_64_fu_484_p1);

assign add_ln46_65_fu_618_p2 = (trunc_ln46_63_fu_566_p4 + zext_ln46_65_fu_614_p1);

assign add_ln46_66_fu_748_p2 = (trunc_ln46_64_fu_696_p4 + zext_ln46_66_fu_744_p1);

assign add_ln46_67_fu_878_p2 = (trunc_ln46_65_fu_826_p4 + zext_ln46_67_fu_874_p1);

assign add_ln46_68_fu_1008_p2 = (trunc_ln46_66_fu_956_p4 + zext_ln46_68_fu_1004_p1);

assign add_ln46_69_fu_1138_p2 = (trunc_ln46_67_fu_1086_p4 + zext_ln46_69_fu_1134_p1);

assign add_ln46_70_fu_1268_p2 = (trunc_ln46_68_fu_1216_p4 + zext_ln46_70_fu_1264_p1);

assign add_ln46_71_fu_1398_p2 = (trunc_ln46_69_fu_1346_p4 + zext_ln46_71_fu_1394_p1);

assign add_ln46_72_fu_1528_p2 = (trunc_ln46_70_fu_1476_p4 + zext_ln46_72_fu_1524_p1);

assign add_ln46_73_fu_1658_p2 = (trunc_ln46_71_fu_1606_p4 + zext_ln46_73_fu_1654_p1);

assign add_ln46_74_fu_1788_p2 = (trunc_ln46_72_fu_1736_p4 + zext_ln46_74_fu_1784_p1);

assign add_ln46_75_fu_1918_p2 = (trunc_ln46_73_fu_1866_p4 + zext_ln46_75_fu_1914_p1);

assign add_ln46_76_fu_2048_p2 = (trunc_ln46_74_fu_1996_p4 + zext_ln46_76_fu_2044_p1);

assign add_ln46_77_fu_2178_p2 = (trunc_ln46_75_fu_2126_p4 + zext_ln46_77_fu_2174_p1);

assign add_ln46_78_fu_2308_p2 = (trunc_ln46_76_fu_2256_p4 + zext_ln46_78_fu_2304_p1);

assign add_ln46_79_fu_2438_p2 = (trunc_ln46_77_fu_2386_p4 + zext_ln46_79_fu_2434_p1);

assign add_ln46_80_fu_2568_p2 = (trunc_ln46_78_fu_2516_p4 + zext_ln46_80_fu_2564_p1);

assign add_ln46_81_fu_2698_p2 = (trunc_ln46_79_fu_2646_p4 + zext_ln46_81_fu_2694_p1);

assign add_ln46_82_fu_2828_p2 = (trunc_ln46_80_fu_2776_p4 + zext_ln46_82_fu_2824_p1);

assign add_ln46_83_fu_2958_p2 = (trunc_ln46_81_fu_2906_p4 + zext_ln46_83_fu_2954_p1);

assign add_ln46_84_fu_3088_p2 = (trunc_ln46_82_fu_3036_p4 + zext_ln46_84_fu_3084_p1);

assign add_ln46_85_fu_3218_p2 = (trunc_ln46_83_fu_3166_p4 + zext_ln46_85_fu_3214_p1);

assign add_ln46_86_fu_3348_p2 = (trunc_ln46_84_fu_3296_p4 + zext_ln46_86_fu_3344_p1);

assign add_ln46_87_fu_3478_p2 = (trunc_ln46_85_fu_3426_p4 + zext_ln46_87_fu_3474_p1);

assign add_ln46_88_fu_3608_p2 = (trunc_ln46_86_fu_3556_p4 + zext_ln46_88_fu_3604_p1);

assign add_ln46_89_fu_3738_p2 = (trunc_ln46_87_fu_3686_p4 + zext_ln46_89_fu_3734_p1);

assign add_ln46_90_fu_3868_p2 = (trunc_ln46_88_fu_3816_p4 + zext_ln46_90_fu_3864_p1);

assign add_ln46_91_fu_3998_p2 = (trunc_ln46_89_fu_3946_p4 + zext_ln46_91_fu_3994_p1);

assign add_ln46_92_fu_4128_p2 = (trunc_ln46_90_fu_4076_p4 + zext_ln46_92_fu_4124_p1);

assign add_ln46_93_fu_4258_p2 = (trunc_ln46_91_fu_4206_p4 + zext_ln46_93_fu_4254_p1);

assign add_ln46_94_fu_4388_p2 = (trunc_ln46_92_fu_4336_p4 + zext_ln46_94_fu_4384_p1);

assign add_ln46_fu_358_p2 = (trunc_ln2_fu_306_p4 + zext_ln46_fu_354_p1);

assign and_ln46_128_fu_408_p2 = (or_ln46_128_fu_402_p2 & icmp_ln46_128_fu_374_p2);

assign and_ln46_129_fu_478_p2 = (tmp_323_fu_454_p3 & or_ln46_64_fu_472_p2);

assign and_ln46_130_fu_538_p2 = (or_ln46_129_fu_532_p2 & icmp_ln46_130_fu_504_p2);

assign and_ln46_131_fu_608_p2 = (tmp_327_fu_584_p3 & or_ln46_65_fu_602_p2);

assign and_ln46_132_fu_668_p2 = (or_ln46_130_fu_662_p2 & icmp_ln46_132_fu_634_p2);

assign and_ln46_133_fu_738_p2 = (tmp_331_fu_714_p3 & or_ln46_66_fu_732_p2);

assign and_ln46_134_fu_798_p2 = (or_ln46_131_fu_792_p2 & icmp_ln46_134_fu_764_p2);

assign and_ln46_135_fu_868_p2 = (tmp_335_fu_844_p3 & or_ln46_67_fu_862_p2);

assign and_ln46_136_fu_928_p2 = (or_ln46_132_fu_922_p2 & icmp_ln46_136_fu_894_p2);

assign and_ln46_137_fu_998_p2 = (tmp_340_fu_974_p3 & or_ln46_68_fu_992_p2);

assign and_ln46_138_fu_1058_p2 = (or_ln46_133_fu_1052_p2 & icmp_ln46_138_fu_1024_p2);

assign and_ln46_139_fu_1128_p2 = (tmp_345_fu_1104_p3 & or_ln46_69_fu_1122_p2);

assign and_ln46_140_fu_1188_p2 = (or_ln46_134_fu_1182_p2 & icmp_ln46_140_fu_1154_p2);

assign and_ln46_141_fu_1258_p2 = (tmp_350_fu_1234_p3 & or_ln46_70_fu_1252_p2);

assign and_ln46_142_fu_1318_p2 = (or_ln46_135_fu_1312_p2 & icmp_ln46_142_fu_1284_p2);

assign and_ln46_143_fu_1388_p2 = (tmp_355_fu_1364_p3 & or_ln46_71_fu_1382_p2);

assign and_ln46_144_fu_1448_p2 = (or_ln46_136_fu_1442_p2 & icmp_ln46_144_fu_1414_p2);

assign and_ln46_145_fu_1518_p2 = (tmp_360_fu_1494_p3 & or_ln46_72_fu_1512_p2);

assign and_ln46_146_fu_1578_p2 = (or_ln46_137_fu_1572_p2 & icmp_ln46_146_fu_1544_p2);

assign and_ln46_147_fu_1648_p2 = (tmp_365_fu_1624_p3 & or_ln46_73_fu_1642_p2);

assign and_ln46_148_fu_1708_p2 = (or_ln46_138_fu_1702_p2 & icmp_ln46_148_fu_1674_p2);

assign and_ln46_149_fu_1778_p2 = (tmp_370_fu_1754_p3 & or_ln46_74_fu_1772_p2);

assign and_ln46_150_fu_1838_p2 = (or_ln46_139_fu_1832_p2 & icmp_ln46_150_fu_1804_p2);

assign and_ln46_151_fu_1908_p2 = (tmp_375_fu_1884_p3 & or_ln46_75_fu_1902_p2);

assign and_ln46_152_fu_1968_p2 = (or_ln46_140_fu_1962_p2 & icmp_ln46_152_fu_1934_p2);

assign and_ln46_153_fu_2038_p2 = (tmp_380_fu_2014_p3 & or_ln46_76_fu_2032_p2);

assign and_ln46_154_fu_2098_p2 = (or_ln46_141_fu_2092_p2 & icmp_ln46_154_fu_2064_p2);

assign and_ln46_155_fu_2168_p2 = (tmp_385_fu_2144_p3 & or_ln46_77_fu_2162_p2);

assign and_ln46_156_fu_2228_p2 = (or_ln46_142_fu_2222_p2 & icmp_ln46_156_fu_2194_p2);

assign and_ln46_157_fu_2298_p2 = (tmp_390_fu_2274_p3 & or_ln46_78_fu_2292_p2);

assign and_ln46_158_fu_2358_p2 = (or_ln46_143_fu_2352_p2 & icmp_ln46_158_fu_2324_p2);

assign and_ln46_159_fu_2428_p2 = (tmp_395_fu_2404_p3 & or_ln46_79_fu_2422_p2);

assign and_ln46_160_fu_2488_p2 = (or_ln46_144_fu_2482_p2 & icmp_ln46_160_fu_2454_p2);

assign and_ln46_161_fu_2558_p2 = (tmp_400_fu_2534_p3 & or_ln46_80_fu_2552_p2);

assign and_ln46_162_fu_2618_p2 = (or_ln46_145_fu_2612_p2 & icmp_ln46_162_fu_2584_p2);

assign and_ln46_163_fu_2688_p2 = (tmp_405_fu_2664_p3 & or_ln46_81_fu_2682_p2);

assign and_ln46_164_fu_2748_p2 = (or_ln46_146_fu_2742_p2 & icmp_ln46_164_fu_2714_p2);

assign and_ln46_165_fu_2818_p2 = (tmp_410_fu_2794_p3 & or_ln46_82_fu_2812_p2);

assign and_ln46_166_fu_2878_p2 = (or_ln46_147_fu_2872_p2 & icmp_ln46_166_fu_2844_p2);

assign and_ln46_167_fu_2948_p2 = (tmp_415_fu_2924_p3 & or_ln46_83_fu_2942_p2);

assign and_ln46_168_fu_3008_p2 = (or_ln46_148_fu_3002_p2 & icmp_ln46_168_fu_2974_p2);

assign and_ln46_169_fu_3078_p2 = (tmp_420_fu_3054_p3 & or_ln46_84_fu_3072_p2);

assign and_ln46_170_fu_3138_p2 = (or_ln46_149_fu_3132_p2 & icmp_ln46_170_fu_3104_p2);

assign and_ln46_171_fu_3208_p2 = (tmp_425_fu_3184_p3 & or_ln46_85_fu_3202_p2);

assign and_ln46_172_fu_3268_p2 = (or_ln46_150_fu_3262_p2 & icmp_ln46_172_fu_3234_p2);

assign and_ln46_173_fu_3338_p2 = (tmp_430_fu_3314_p3 & or_ln46_86_fu_3332_p2);

assign and_ln46_174_fu_3398_p2 = (or_ln46_151_fu_3392_p2 & icmp_ln46_174_fu_3364_p2);

assign and_ln46_175_fu_3468_p2 = (tmp_435_fu_3444_p3 & or_ln46_87_fu_3462_p2);

assign and_ln46_176_fu_3528_p2 = (or_ln46_152_fu_3522_p2 & icmp_ln46_176_fu_3494_p2);

assign and_ln46_177_fu_3598_p2 = (tmp_440_fu_3574_p3 & or_ln46_88_fu_3592_p2);

assign and_ln46_178_fu_3658_p2 = (or_ln46_153_fu_3652_p2 & icmp_ln46_178_fu_3624_p2);

assign and_ln46_179_fu_3728_p2 = (tmp_445_fu_3704_p3 & or_ln46_89_fu_3722_p2);

assign and_ln46_180_fu_3788_p2 = (or_ln46_154_fu_3782_p2 & icmp_ln46_180_fu_3754_p2);

assign and_ln46_181_fu_3858_p2 = (tmp_450_fu_3834_p3 & or_ln46_90_fu_3852_p2);

assign and_ln46_182_fu_3918_p2 = (or_ln46_155_fu_3912_p2 & icmp_ln46_182_fu_3884_p2);

assign and_ln46_183_fu_3988_p2 = (tmp_455_fu_3964_p3 & or_ln46_91_fu_3982_p2);

assign and_ln46_184_fu_4048_p2 = (or_ln46_156_fu_4042_p2 & icmp_ln46_184_fu_4014_p2);

assign and_ln46_185_fu_4118_p2 = (tmp_460_fu_4094_p3 & or_ln46_92_fu_4112_p2);

assign and_ln46_186_fu_4178_p2 = (or_ln46_157_fu_4172_p2 & icmp_ln46_186_fu_4144_p2);

assign and_ln46_187_fu_4248_p2 = (tmp_465_fu_4224_p3 & or_ln46_93_fu_4242_p2);

assign and_ln46_188_fu_4308_p2 = (or_ln46_158_fu_4302_p2 & icmp_ln46_188_fu_4274_p2);

assign and_ln46_189_fu_4378_p2 = (tmp_470_fu_4354_p3 & or_ln46_94_fu_4372_p2);

assign and_ln46_190_fu_4438_p2 = (or_ln46_159_fu_4432_p2 & icmp_ln46_190_fu_4404_p2);

assign and_ln46_fu_348_p2 = (tmp_319_fu_324_p3 & or_ln46_fu_342_p2);

assign ap_ready = 1'b1;

assign icmp_ln46_128_fu_374_p2 = ((tmp_34_fu_364_p4 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_129_fu_466_p2 = ((trunc_ln46_127_fu_462_p1 != 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_130_fu_504_p2 = ((tmp_s_fu_494_p4 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_131_fu_596_p2 = ((trunc_ln46_128_fu_592_p1 != 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_132_fu_634_p2 = ((tmp_317_fu_624_p4 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_133_fu_726_p2 = ((trunc_ln46_129_fu_722_p1 != 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_134_fu_764_p2 = ((tmp_318_fu_754_p4 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_135_fu_856_p2 = ((trunc_ln46_130_fu_852_p1 != 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_136_fu_894_p2 = ((tmp_336_fu_884_p4 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_137_fu_986_p2 = ((trunc_ln46_131_fu_982_p1 != 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_138_fu_1024_p2 = ((tmp_341_fu_1014_p4 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_139_fu_1116_p2 = ((trunc_ln46_132_fu_1112_p1 != 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_140_fu_1154_p2 = ((tmp_346_fu_1144_p4 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_141_fu_1246_p2 = ((trunc_ln46_133_fu_1242_p1 != 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_142_fu_1284_p2 = ((tmp_351_fu_1274_p4 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_143_fu_1376_p2 = ((trunc_ln46_134_fu_1372_p1 != 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_144_fu_1414_p2 = ((tmp_356_fu_1404_p4 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_145_fu_1506_p2 = ((trunc_ln46_135_fu_1502_p1 != 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_146_fu_1544_p2 = ((tmp_361_fu_1534_p4 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_147_fu_1636_p2 = ((trunc_ln46_136_fu_1632_p1 != 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_148_fu_1674_p2 = ((tmp_366_fu_1664_p4 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_149_fu_1766_p2 = ((trunc_ln46_137_fu_1762_p1 != 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_150_fu_1804_p2 = ((tmp_371_fu_1794_p4 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_151_fu_1896_p2 = ((trunc_ln46_138_fu_1892_p1 != 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_152_fu_1934_p2 = ((tmp_376_fu_1924_p4 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_153_fu_2026_p2 = ((trunc_ln46_139_fu_2022_p1 != 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_154_fu_2064_p2 = ((tmp_381_fu_2054_p4 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_155_fu_2156_p2 = ((trunc_ln46_140_fu_2152_p1 != 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_156_fu_2194_p2 = ((tmp_386_fu_2184_p4 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_157_fu_2286_p2 = ((trunc_ln46_141_fu_2282_p1 != 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_158_fu_2324_p2 = ((tmp_391_fu_2314_p4 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_159_fu_2416_p2 = ((trunc_ln46_142_fu_2412_p1 != 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_160_fu_2454_p2 = ((tmp_396_fu_2444_p4 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_161_fu_2546_p2 = ((trunc_ln46_143_fu_2542_p1 != 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_162_fu_2584_p2 = ((tmp_401_fu_2574_p4 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_163_fu_2676_p2 = ((trunc_ln46_144_fu_2672_p1 != 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_164_fu_2714_p2 = ((tmp_406_fu_2704_p4 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_165_fu_2806_p2 = ((trunc_ln46_145_fu_2802_p1 != 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_166_fu_2844_p2 = ((tmp_411_fu_2834_p4 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_167_fu_2936_p2 = ((trunc_ln46_146_fu_2932_p1 != 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_168_fu_2974_p2 = ((tmp_416_fu_2964_p4 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_169_fu_3066_p2 = ((trunc_ln46_147_fu_3062_p1 != 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_170_fu_3104_p2 = ((tmp_421_fu_3094_p4 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_171_fu_3196_p2 = ((trunc_ln46_148_fu_3192_p1 != 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_172_fu_3234_p2 = ((tmp_426_fu_3224_p4 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_173_fu_3326_p2 = ((trunc_ln46_149_fu_3322_p1 != 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_174_fu_3364_p2 = ((tmp_431_fu_3354_p4 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_175_fu_3456_p2 = ((trunc_ln46_150_fu_3452_p1 != 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_176_fu_3494_p2 = ((tmp_436_fu_3484_p4 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_177_fu_3586_p2 = ((trunc_ln46_151_fu_3582_p1 != 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_178_fu_3624_p2 = ((tmp_441_fu_3614_p4 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_179_fu_3716_p2 = ((trunc_ln46_152_fu_3712_p1 != 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_180_fu_3754_p2 = ((tmp_446_fu_3744_p4 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_181_fu_3846_p2 = ((trunc_ln46_153_fu_3842_p1 != 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_182_fu_3884_p2 = ((tmp_451_fu_3874_p4 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_183_fu_3976_p2 = ((trunc_ln46_154_fu_3972_p1 != 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_184_fu_4014_p2 = ((tmp_456_fu_4004_p4 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_185_fu_4106_p2 = ((trunc_ln46_155_fu_4102_p1 != 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_186_fu_4144_p2 = ((tmp_461_fu_4134_p4 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_187_fu_4236_p2 = ((trunc_ln46_156_fu_4232_p1 != 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_188_fu_4274_p2 = ((tmp_466_fu_4264_p4 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_189_fu_4366_p2 = ((trunc_ln46_157_fu_4362_p1 != 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_190_fu_4404_p2 = ((tmp_471_fu_4394_p4 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_fu_336_p2 = ((trunc_ln46_fu_332_p1 != 4'd0) ? 1'b1 : 1'b0);

assign or_ln46_128_fu_402_p2 = (xor_ln46_fu_396_p2 | tmp_320_fu_380_p3);

assign or_ln46_129_fu_532_p2 = (xor_ln46_64_fu_526_p2 | tmp_324_fu_510_p3);

assign or_ln46_130_fu_662_p2 = (xor_ln46_65_fu_656_p2 | tmp_328_fu_640_p3);

assign or_ln46_131_fu_792_p2 = (xor_ln46_66_fu_786_p2 | tmp_332_fu_770_p3);

assign or_ln46_132_fu_922_p2 = (xor_ln46_67_fu_916_p2 | tmp_337_fu_900_p3);

assign or_ln46_133_fu_1052_p2 = (xor_ln46_68_fu_1046_p2 | tmp_342_fu_1030_p3);

assign or_ln46_134_fu_1182_p2 = (xor_ln46_69_fu_1176_p2 | tmp_347_fu_1160_p3);

assign or_ln46_135_fu_1312_p2 = (xor_ln46_70_fu_1306_p2 | tmp_352_fu_1290_p3);

assign or_ln46_136_fu_1442_p2 = (xor_ln46_71_fu_1436_p2 | tmp_357_fu_1420_p3);

assign or_ln46_137_fu_1572_p2 = (xor_ln46_72_fu_1566_p2 | tmp_362_fu_1550_p3);

assign or_ln46_138_fu_1702_p2 = (xor_ln46_73_fu_1696_p2 | tmp_367_fu_1680_p3);

assign or_ln46_139_fu_1832_p2 = (xor_ln46_74_fu_1826_p2 | tmp_372_fu_1810_p3);

assign or_ln46_140_fu_1962_p2 = (xor_ln46_75_fu_1956_p2 | tmp_377_fu_1940_p3);

assign or_ln46_141_fu_2092_p2 = (xor_ln46_76_fu_2086_p2 | tmp_382_fu_2070_p3);

assign or_ln46_142_fu_2222_p2 = (xor_ln46_77_fu_2216_p2 | tmp_387_fu_2200_p3);

assign or_ln46_143_fu_2352_p2 = (xor_ln46_78_fu_2346_p2 | tmp_392_fu_2330_p3);

assign or_ln46_144_fu_2482_p2 = (xor_ln46_79_fu_2476_p2 | tmp_397_fu_2460_p3);

assign or_ln46_145_fu_2612_p2 = (xor_ln46_80_fu_2606_p2 | tmp_402_fu_2590_p3);

assign or_ln46_146_fu_2742_p2 = (xor_ln46_81_fu_2736_p2 | tmp_407_fu_2720_p3);

assign or_ln46_147_fu_2872_p2 = (xor_ln46_82_fu_2866_p2 | tmp_412_fu_2850_p3);

assign or_ln46_148_fu_3002_p2 = (xor_ln46_83_fu_2996_p2 | tmp_417_fu_2980_p3);

assign or_ln46_149_fu_3132_p2 = (xor_ln46_84_fu_3126_p2 | tmp_422_fu_3110_p3);

assign or_ln46_150_fu_3262_p2 = (xor_ln46_85_fu_3256_p2 | tmp_427_fu_3240_p3);

assign or_ln46_151_fu_3392_p2 = (xor_ln46_86_fu_3386_p2 | tmp_432_fu_3370_p3);

assign or_ln46_152_fu_3522_p2 = (xor_ln46_87_fu_3516_p2 | tmp_437_fu_3500_p3);

assign or_ln46_153_fu_3652_p2 = (xor_ln46_88_fu_3646_p2 | tmp_442_fu_3630_p3);

assign or_ln46_154_fu_3782_p2 = (xor_ln46_89_fu_3776_p2 | tmp_447_fu_3760_p3);

assign or_ln46_155_fu_3912_p2 = (xor_ln46_90_fu_3906_p2 | tmp_452_fu_3890_p3);

assign or_ln46_156_fu_4042_p2 = (xor_ln46_91_fu_4036_p2 | tmp_457_fu_4020_p3);

assign or_ln46_157_fu_4172_p2 = (xor_ln46_92_fu_4166_p2 | tmp_462_fu_4150_p3);

assign or_ln46_158_fu_4302_p2 = (xor_ln46_93_fu_4296_p2 | tmp_467_fu_4280_p3);

assign or_ln46_159_fu_4432_p2 = (xor_ln46_94_fu_4426_p2 | tmp_472_fu_4410_p3);

assign or_ln46_64_fu_472_p2 = (tmp_322_fu_446_p3 | icmp_ln46_129_fu_466_p2);

assign or_ln46_65_fu_602_p2 = (tmp_326_fu_576_p3 | icmp_ln46_131_fu_596_p2);

assign or_ln46_66_fu_732_p2 = (tmp_330_fu_706_p3 | icmp_ln46_133_fu_726_p2);

assign or_ln46_67_fu_862_p2 = (tmp_334_fu_836_p3 | icmp_ln46_135_fu_856_p2);

assign or_ln46_68_fu_992_p2 = (tmp_339_fu_966_p3 | icmp_ln46_137_fu_986_p2);

assign or_ln46_69_fu_1122_p2 = (tmp_344_fu_1096_p3 | icmp_ln46_139_fu_1116_p2);

assign or_ln46_70_fu_1252_p2 = (tmp_349_fu_1226_p3 | icmp_ln46_141_fu_1246_p2);

assign or_ln46_71_fu_1382_p2 = (tmp_354_fu_1356_p3 | icmp_ln46_143_fu_1376_p2);

assign or_ln46_72_fu_1512_p2 = (tmp_359_fu_1486_p3 | icmp_ln46_145_fu_1506_p2);

assign or_ln46_73_fu_1642_p2 = (tmp_364_fu_1616_p3 | icmp_ln46_147_fu_1636_p2);

assign or_ln46_74_fu_1772_p2 = (tmp_369_fu_1746_p3 | icmp_ln46_149_fu_1766_p2);

assign or_ln46_75_fu_1902_p2 = (tmp_374_fu_1876_p3 | icmp_ln46_151_fu_1896_p2);

assign or_ln46_76_fu_2032_p2 = (tmp_379_fu_2006_p3 | icmp_ln46_153_fu_2026_p2);

assign or_ln46_77_fu_2162_p2 = (tmp_384_fu_2136_p3 | icmp_ln46_155_fu_2156_p2);

assign or_ln46_78_fu_2292_p2 = (tmp_389_fu_2266_p3 | icmp_ln46_157_fu_2286_p2);

assign or_ln46_79_fu_2422_p2 = (tmp_394_fu_2396_p3 | icmp_ln46_159_fu_2416_p2);

assign or_ln46_80_fu_2552_p2 = (tmp_399_fu_2526_p3 | icmp_ln46_161_fu_2546_p2);

assign or_ln46_81_fu_2682_p2 = (tmp_404_fu_2656_p3 | icmp_ln46_163_fu_2676_p2);

assign or_ln46_82_fu_2812_p2 = (tmp_409_fu_2786_p3 | icmp_ln46_165_fu_2806_p2);

assign or_ln46_83_fu_2942_p2 = (tmp_414_fu_2916_p3 | icmp_ln46_167_fu_2936_p2);

assign or_ln46_84_fu_3072_p2 = (tmp_419_fu_3046_p3 | icmp_ln46_169_fu_3066_p2);

assign or_ln46_85_fu_3202_p2 = (tmp_424_fu_3176_p3 | icmp_ln46_171_fu_3196_p2);

assign or_ln46_86_fu_3332_p2 = (tmp_429_fu_3306_p3 | icmp_ln46_173_fu_3326_p2);

assign or_ln46_87_fu_3462_p2 = (tmp_434_fu_3436_p3 | icmp_ln46_175_fu_3456_p2);

assign or_ln46_88_fu_3592_p2 = (tmp_439_fu_3566_p3 | icmp_ln46_177_fu_3586_p2);

assign or_ln46_89_fu_3722_p2 = (tmp_444_fu_3696_p3 | icmp_ln46_179_fu_3716_p2);

assign or_ln46_90_fu_3852_p2 = (tmp_449_fu_3826_p3 | icmp_ln46_181_fu_3846_p2);

assign or_ln46_91_fu_3982_p2 = (tmp_454_fu_3956_p3 | icmp_ln46_183_fu_3976_p2);

assign or_ln46_92_fu_4112_p2 = (tmp_459_fu_4086_p3 | icmp_ln46_185_fu_4106_p2);

assign or_ln46_93_fu_4242_p2 = (tmp_464_fu_4216_p3 | icmp_ln46_187_fu_4236_p2);

assign or_ln46_94_fu_4372_p2 = (tmp_469_fu_4346_p3 | icmp_ln46_189_fu_4366_p2);

assign or_ln46_fu_342_p2 = (tmp_fu_316_p3 | icmp_ln46_fu_336_p2);

assign select_ln45_64_fu_552_p3 = ((icmp_ln45_64_fu_430_p2[0:0] == 1'b1) ? select_ln46_64_fu_544_p3 : 3'd0);

assign select_ln45_65_fu_682_p3 = ((icmp_ln45_65_fu_560_p2[0:0] == 1'b1) ? select_ln46_65_fu_674_p3 : 3'd0);

assign select_ln45_66_fu_812_p3 = ((icmp_ln45_66_fu_690_p2[0:0] == 1'b1) ? select_ln46_66_fu_804_p3 : 3'd0);

assign select_ln45_67_fu_942_p3 = ((icmp_ln45_67_fu_820_p2[0:0] == 1'b1) ? select_ln46_67_fu_934_p3 : 3'd0);

assign select_ln45_68_fu_1072_p3 = ((icmp_ln45_68_fu_950_p2[0:0] == 1'b1) ? select_ln46_68_fu_1064_p3 : 3'd0);

assign select_ln45_69_fu_1202_p3 = ((icmp_ln45_69_fu_1080_p2[0:0] == 1'b1) ? select_ln46_69_fu_1194_p3 : 3'd0);

assign select_ln45_70_fu_1332_p3 = ((icmp_ln45_70_fu_1210_p2[0:0] == 1'b1) ? select_ln46_70_fu_1324_p3 : 3'd0);

assign select_ln45_71_fu_1462_p3 = ((icmp_ln45_71_fu_1340_p2[0:0] == 1'b1) ? select_ln46_71_fu_1454_p3 : 3'd0);

assign select_ln45_72_fu_1592_p3 = ((icmp_ln45_72_fu_1470_p2[0:0] == 1'b1) ? select_ln46_72_fu_1584_p3 : 3'd0);

assign select_ln45_73_fu_1722_p3 = ((icmp_ln45_73_fu_1600_p2[0:0] == 1'b1) ? select_ln46_73_fu_1714_p3 : 3'd0);

assign select_ln45_74_fu_1852_p3 = ((icmp_ln45_74_fu_1730_p2[0:0] == 1'b1) ? select_ln46_74_fu_1844_p3 : 3'd0);

assign select_ln45_75_fu_1982_p3 = ((icmp_ln45_75_fu_1860_p2[0:0] == 1'b1) ? select_ln46_75_fu_1974_p3 : 3'd0);

assign select_ln45_76_fu_2112_p3 = ((icmp_ln45_76_fu_1990_p2[0:0] == 1'b1) ? select_ln46_76_fu_2104_p3 : 3'd0);

assign select_ln45_77_fu_2242_p3 = ((icmp_ln45_77_fu_2120_p2[0:0] == 1'b1) ? select_ln46_77_fu_2234_p3 : 3'd0);

assign select_ln45_78_fu_2372_p3 = ((icmp_ln45_78_fu_2250_p2[0:0] == 1'b1) ? select_ln46_78_fu_2364_p3 : 3'd0);

assign select_ln45_79_fu_2502_p3 = ((icmp_ln45_79_fu_2380_p2[0:0] == 1'b1) ? select_ln46_79_fu_2494_p3 : 3'd0);

assign select_ln45_80_fu_2632_p3 = ((icmp_ln45_80_fu_2510_p2[0:0] == 1'b1) ? select_ln46_80_fu_2624_p3 : 3'd0);

assign select_ln45_81_fu_2762_p3 = ((icmp_ln45_81_fu_2640_p2[0:0] == 1'b1) ? select_ln46_81_fu_2754_p3 : 3'd0);

assign select_ln45_82_fu_2892_p3 = ((icmp_ln45_82_fu_2770_p2[0:0] == 1'b1) ? select_ln46_82_fu_2884_p3 : 3'd0);

assign select_ln45_83_fu_3022_p3 = ((icmp_ln45_83_fu_2900_p2[0:0] == 1'b1) ? select_ln46_83_fu_3014_p3 : 3'd0);

assign select_ln45_84_fu_3152_p3 = ((icmp_ln45_84_fu_3030_p2[0:0] == 1'b1) ? select_ln46_84_fu_3144_p3 : 3'd0);

assign select_ln45_85_fu_3282_p3 = ((icmp_ln45_85_fu_3160_p2[0:0] == 1'b1) ? select_ln46_85_fu_3274_p3 : 3'd0);

assign select_ln45_86_fu_3412_p3 = ((icmp_ln45_86_fu_3290_p2[0:0] == 1'b1) ? select_ln46_86_fu_3404_p3 : 3'd0);

assign select_ln45_87_fu_3542_p3 = ((icmp_ln45_87_fu_3420_p2[0:0] == 1'b1) ? select_ln46_87_fu_3534_p3 : 3'd0);

assign select_ln45_88_fu_3672_p3 = ((icmp_ln45_88_fu_3550_p2[0:0] == 1'b1) ? select_ln46_88_fu_3664_p3 : 3'd0);

assign select_ln45_89_fu_3802_p3 = ((icmp_ln45_89_fu_3680_p2[0:0] == 1'b1) ? select_ln46_89_fu_3794_p3 : 3'd0);

assign select_ln45_90_fu_3932_p3 = ((icmp_ln45_90_fu_3810_p2[0:0] == 1'b1) ? select_ln46_90_fu_3924_p3 : 3'd0);

assign select_ln45_91_fu_4062_p3 = ((icmp_ln45_91_fu_3940_p2[0:0] == 1'b1) ? select_ln46_91_fu_4054_p3 : 3'd0);

assign select_ln45_92_fu_4192_p3 = ((icmp_ln45_92_fu_4070_p2[0:0] == 1'b1) ? select_ln46_92_fu_4184_p3 : 3'd0);

assign select_ln45_93_fu_4322_p3 = ((icmp_ln45_93_fu_4200_p2[0:0] == 1'b1) ? select_ln46_93_fu_4314_p3 : 3'd0);

assign select_ln45_94_fu_4452_p3 = ((icmp_ln45_94_fu_4330_p2[0:0] == 1'b1) ? select_ln46_94_fu_4444_p3 : 3'd0);

assign select_ln45_fu_422_p3 = ((icmp_ln45_fu_300_p2[0:0] == 1'b1) ? select_ln46_fu_414_p3 : 3'd0);

assign select_ln46_64_fu_544_p3 = ((and_ln46_130_fu_538_p2[0:0] == 1'b1) ? add_ln46_64_fu_488_p2 : 3'd7);

assign select_ln46_65_fu_674_p3 = ((and_ln46_132_fu_668_p2[0:0] == 1'b1) ? add_ln46_65_fu_618_p2 : 3'd7);

assign select_ln46_66_fu_804_p3 = ((and_ln46_134_fu_798_p2[0:0] == 1'b1) ? add_ln46_66_fu_748_p2 : 3'd7);

assign select_ln46_67_fu_934_p3 = ((and_ln46_136_fu_928_p2[0:0] == 1'b1) ? add_ln46_67_fu_878_p2 : 3'd7);

assign select_ln46_68_fu_1064_p3 = ((and_ln46_138_fu_1058_p2[0:0] == 1'b1) ? add_ln46_68_fu_1008_p2 : 3'd7);

assign select_ln46_69_fu_1194_p3 = ((and_ln46_140_fu_1188_p2[0:0] == 1'b1) ? add_ln46_69_fu_1138_p2 : 3'd7);

assign select_ln46_70_fu_1324_p3 = ((and_ln46_142_fu_1318_p2[0:0] == 1'b1) ? add_ln46_70_fu_1268_p2 : 3'd7);

assign select_ln46_71_fu_1454_p3 = ((and_ln46_144_fu_1448_p2[0:0] == 1'b1) ? add_ln46_71_fu_1398_p2 : 3'd7);

assign select_ln46_72_fu_1584_p3 = ((and_ln46_146_fu_1578_p2[0:0] == 1'b1) ? add_ln46_72_fu_1528_p2 : 3'd7);

assign select_ln46_73_fu_1714_p3 = ((and_ln46_148_fu_1708_p2[0:0] == 1'b1) ? add_ln46_73_fu_1658_p2 : 3'd7);

assign select_ln46_74_fu_1844_p3 = ((and_ln46_150_fu_1838_p2[0:0] == 1'b1) ? add_ln46_74_fu_1788_p2 : 3'd7);

assign select_ln46_75_fu_1974_p3 = ((and_ln46_152_fu_1968_p2[0:0] == 1'b1) ? add_ln46_75_fu_1918_p2 : 3'd7);

assign select_ln46_76_fu_2104_p3 = ((and_ln46_154_fu_2098_p2[0:0] == 1'b1) ? add_ln46_76_fu_2048_p2 : 3'd7);

assign select_ln46_77_fu_2234_p3 = ((and_ln46_156_fu_2228_p2[0:0] == 1'b1) ? add_ln46_77_fu_2178_p2 : 3'd7);

assign select_ln46_78_fu_2364_p3 = ((and_ln46_158_fu_2358_p2[0:0] == 1'b1) ? add_ln46_78_fu_2308_p2 : 3'd7);

assign select_ln46_79_fu_2494_p3 = ((and_ln46_160_fu_2488_p2[0:0] == 1'b1) ? add_ln46_79_fu_2438_p2 : 3'd7);

assign select_ln46_80_fu_2624_p3 = ((and_ln46_162_fu_2618_p2[0:0] == 1'b1) ? add_ln46_80_fu_2568_p2 : 3'd7);

assign select_ln46_81_fu_2754_p3 = ((and_ln46_164_fu_2748_p2[0:0] == 1'b1) ? add_ln46_81_fu_2698_p2 : 3'd7);

assign select_ln46_82_fu_2884_p3 = ((and_ln46_166_fu_2878_p2[0:0] == 1'b1) ? add_ln46_82_fu_2828_p2 : 3'd7);

assign select_ln46_83_fu_3014_p3 = ((and_ln46_168_fu_3008_p2[0:0] == 1'b1) ? add_ln46_83_fu_2958_p2 : 3'd7);

assign select_ln46_84_fu_3144_p3 = ((and_ln46_170_fu_3138_p2[0:0] == 1'b1) ? add_ln46_84_fu_3088_p2 : 3'd7);

assign select_ln46_85_fu_3274_p3 = ((and_ln46_172_fu_3268_p2[0:0] == 1'b1) ? add_ln46_85_fu_3218_p2 : 3'd7);

assign select_ln46_86_fu_3404_p3 = ((and_ln46_174_fu_3398_p2[0:0] == 1'b1) ? add_ln46_86_fu_3348_p2 : 3'd7);

assign select_ln46_87_fu_3534_p3 = ((and_ln46_176_fu_3528_p2[0:0] == 1'b1) ? add_ln46_87_fu_3478_p2 : 3'd7);

assign select_ln46_88_fu_3664_p3 = ((and_ln46_178_fu_3658_p2[0:0] == 1'b1) ? add_ln46_88_fu_3608_p2 : 3'd7);

assign select_ln46_89_fu_3794_p3 = ((and_ln46_180_fu_3788_p2[0:0] == 1'b1) ? add_ln46_89_fu_3738_p2 : 3'd7);

assign select_ln46_90_fu_3924_p3 = ((and_ln46_182_fu_3918_p2[0:0] == 1'b1) ? add_ln46_90_fu_3868_p2 : 3'd7);

assign select_ln46_91_fu_4054_p3 = ((and_ln46_184_fu_4048_p2[0:0] == 1'b1) ? add_ln46_91_fu_3998_p2 : 3'd7);

assign select_ln46_92_fu_4184_p3 = ((and_ln46_186_fu_4178_p2[0:0] == 1'b1) ? add_ln46_92_fu_4128_p2 : 3'd7);

assign select_ln46_93_fu_4314_p3 = ((and_ln46_188_fu_4308_p2[0:0] == 1'b1) ? add_ln46_93_fu_4258_p2 : 3'd7);

assign select_ln46_94_fu_4444_p3 = ((and_ln46_190_fu_4438_p2[0:0] == 1'b1) ? add_ln46_94_fu_4388_p2 : 3'd7);

assign select_ln46_fu_414_p3 = ((and_ln46_128_fu_408_p2[0:0] == 1'b1) ? add_ln46_fu_358_p2 : 3'd7);

assign tmp_317_fu_624_p4 = {{data_2_val[15:8]}};

assign tmp_318_fu_754_p4 = {{data_3_val[15:8]}};

assign tmp_319_fu_324_p3 = data_0_val[32'd4];

assign tmp_320_fu_380_p3 = add_ln46_fu_358_p2[32'd2];

assign tmp_321_fu_388_p3 = data_0_val[32'd7];

assign tmp_322_fu_446_p3 = data_1_val[32'd5];

assign tmp_323_fu_454_p3 = data_1_val[32'd4];

assign tmp_324_fu_510_p3 = add_ln46_64_fu_488_p2[32'd2];

assign tmp_325_fu_518_p3 = data_1_val[32'd7];

assign tmp_326_fu_576_p3 = data_2_val[32'd5];

assign tmp_327_fu_584_p3 = data_2_val[32'd4];

assign tmp_328_fu_640_p3 = add_ln46_65_fu_618_p2[32'd2];

assign tmp_329_fu_648_p3 = data_2_val[32'd7];

assign tmp_330_fu_706_p3 = data_3_val[32'd5];

assign tmp_331_fu_714_p3 = data_3_val[32'd4];

assign tmp_332_fu_770_p3 = add_ln46_66_fu_748_p2[32'd2];

assign tmp_333_fu_778_p3 = data_3_val[32'd7];

assign tmp_334_fu_836_p3 = data_4_val[32'd5];

assign tmp_335_fu_844_p3 = data_4_val[32'd4];

assign tmp_336_fu_884_p4 = {{data_4_val[15:8]}};

assign tmp_337_fu_900_p3 = add_ln46_67_fu_878_p2[32'd2];

assign tmp_338_fu_908_p3 = data_4_val[32'd7];

assign tmp_339_fu_966_p3 = data_5_val[32'd5];

assign tmp_340_fu_974_p3 = data_5_val[32'd4];

assign tmp_341_fu_1014_p4 = {{data_5_val[15:8]}};

assign tmp_342_fu_1030_p3 = add_ln46_68_fu_1008_p2[32'd2];

assign tmp_343_fu_1038_p3 = data_5_val[32'd7];

assign tmp_344_fu_1096_p3 = data_6_val[32'd5];

assign tmp_345_fu_1104_p3 = data_6_val[32'd4];

assign tmp_346_fu_1144_p4 = {{data_6_val[15:8]}};

assign tmp_347_fu_1160_p3 = add_ln46_69_fu_1138_p2[32'd2];

assign tmp_348_fu_1168_p3 = data_6_val[32'd7];

assign tmp_349_fu_1226_p3 = data_7_val[32'd5];

assign tmp_34_fu_364_p4 = {{data_0_val[15:8]}};

assign tmp_350_fu_1234_p3 = data_7_val[32'd4];

assign tmp_351_fu_1274_p4 = {{data_7_val[15:8]}};

assign tmp_352_fu_1290_p3 = add_ln46_70_fu_1268_p2[32'd2];

assign tmp_353_fu_1298_p3 = data_7_val[32'd7];

assign tmp_354_fu_1356_p3 = data_8_val[32'd5];

assign tmp_355_fu_1364_p3 = data_8_val[32'd4];

assign tmp_356_fu_1404_p4 = {{data_8_val[15:8]}};

assign tmp_357_fu_1420_p3 = add_ln46_71_fu_1398_p2[32'd2];

assign tmp_358_fu_1428_p3 = data_8_val[32'd7];

assign tmp_359_fu_1486_p3 = data_9_val[32'd5];

assign tmp_360_fu_1494_p3 = data_9_val[32'd4];

assign tmp_361_fu_1534_p4 = {{data_9_val[15:8]}};

assign tmp_362_fu_1550_p3 = add_ln46_72_fu_1528_p2[32'd2];

assign tmp_363_fu_1558_p3 = data_9_val[32'd7];

assign tmp_364_fu_1616_p3 = data_10_val[32'd5];

assign tmp_365_fu_1624_p3 = data_10_val[32'd4];

assign tmp_366_fu_1664_p4 = {{data_10_val[15:8]}};

assign tmp_367_fu_1680_p3 = add_ln46_73_fu_1658_p2[32'd2];

assign tmp_368_fu_1688_p3 = data_10_val[32'd7];

assign tmp_369_fu_1746_p3 = data_11_val[32'd5];

assign tmp_370_fu_1754_p3 = data_11_val[32'd4];

assign tmp_371_fu_1794_p4 = {{data_11_val[15:8]}};

assign tmp_372_fu_1810_p3 = add_ln46_74_fu_1788_p2[32'd2];

assign tmp_373_fu_1818_p3 = data_11_val[32'd7];

assign tmp_374_fu_1876_p3 = data_12_val[32'd5];

assign tmp_375_fu_1884_p3 = data_12_val[32'd4];

assign tmp_376_fu_1924_p4 = {{data_12_val[15:8]}};

assign tmp_377_fu_1940_p3 = add_ln46_75_fu_1918_p2[32'd2];

assign tmp_378_fu_1948_p3 = data_12_val[32'd7];

assign tmp_379_fu_2006_p3 = data_13_val[32'd5];

assign tmp_380_fu_2014_p3 = data_13_val[32'd4];

assign tmp_381_fu_2054_p4 = {{data_13_val[15:8]}};

assign tmp_382_fu_2070_p3 = add_ln46_76_fu_2048_p2[32'd2];

assign tmp_383_fu_2078_p3 = data_13_val[32'd7];

assign tmp_384_fu_2136_p3 = data_14_val[32'd5];

assign tmp_385_fu_2144_p3 = data_14_val[32'd4];

assign tmp_386_fu_2184_p4 = {{data_14_val[15:8]}};

assign tmp_387_fu_2200_p3 = add_ln46_77_fu_2178_p2[32'd2];

assign tmp_388_fu_2208_p3 = data_14_val[32'd7];

assign tmp_389_fu_2266_p3 = data_15_val[32'd5];

assign tmp_390_fu_2274_p3 = data_15_val[32'd4];

assign tmp_391_fu_2314_p4 = {{data_15_val[15:8]}};

assign tmp_392_fu_2330_p3 = add_ln46_78_fu_2308_p2[32'd2];

assign tmp_393_fu_2338_p3 = data_15_val[32'd7];

assign tmp_394_fu_2396_p3 = data_16_val[32'd5];

assign tmp_395_fu_2404_p3 = data_16_val[32'd4];

assign tmp_396_fu_2444_p4 = {{data_16_val[15:8]}};

assign tmp_397_fu_2460_p3 = add_ln46_79_fu_2438_p2[32'd2];

assign tmp_398_fu_2468_p3 = data_16_val[32'd7];

assign tmp_399_fu_2526_p3 = data_17_val[32'd5];

assign tmp_400_fu_2534_p3 = data_17_val[32'd4];

assign tmp_401_fu_2574_p4 = {{data_17_val[15:8]}};

assign tmp_402_fu_2590_p3 = add_ln46_80_fu_2568_p2[32'd2];

assign tmp_403_fu_2598_p3 = data_17_val[32'd7];

assign tmp_404_fu_2656_p3 = data_18_val[32'd5];

assign tmp_405_fu_2664_p3 = data_18_val[32'd4];

assign tmp_406_fu_2704_p4 = {{data_18_val[15:8]}};

assign tmp_407_fu_2720_p3 = add_ln46_81_fu_2698_p2[32'd2];

assign tmp_408_fu_2728_p3 = data_18_val[32'd7];

assign tmp_409_fu_2786_p3 = data_19_val[32'd5];

assign tmp_410_fu_2794_p3 = data_19_val[32'd4];

assign tmp_411_fu_2834_p4 = {{data_19_val[15:8]}};

assign tmp_412_fu_2850_p3 = add_ln46_82_fu_2828_p2[32'd2];

assign tmp_413_fu_2858_p3 = data_19_val[32'd7];

assign tmp_414_fu_2916_p3 = data_20_val[32'd5];

assign tmp_415_fu_2924_p3 = data_20_val[32'd4];

assign tmp_416_fu_2964_p4 = {{data_20_val[15:8]}};

assign tmp_417_fu_2980_p3 = add_ln46_83_fu_2958_p2[32'd2];

assign tmp_418_fu_2988_p3 = data_20_val[32'd7];

assign tmp_419_fu_3046_p3 = data_21_val[32'd5];

assign tmp_420_fu_3054_p3 = data_21_val[32'd4];

assign tmp_421_fu_3094_p4 = {{data_21_val[15:8]}};

assign tmp_422_fu_3110_p3 = add_ln46_84_fu_3088_p2[32'd2];

assign tmp_423_fu_3118_p3 = data_21_val[32'd7];

assign tmp_424_fu_3176_p3 = data_22_val[32'd5];

assign tmp_425_fu_3184_p3 = data_22_val[32'd4];

assign tmp_426_fu_3224_p4 = {{data_22_val[15:8]}};

assign tmp_427_fu_3240_p3 = add_ln46_85_fu_3218_p2[32'd2];

assign tmp_428_fu_3248_p3 = data_22_val[32'd7];

assign tmp_429_fu_3306_p3 = data_23_val[32'd5];

assign tmp_430_fu_3314_p3 = data_23_val[32'd4];

assign tmp_431_fu_3354_p4 = {{data_23_val[15:8]}};

assign tmp_432_fu_3370_p3 = add_ln46_86_fu_3348_p2[32'd2];

assign tmp_433_fu_3378_p3 = data_23_val[32'd7];

assign tmp_434_fu_3436_p3 = data_24_val[32'd5];

assign tmp_435_fu_3444_p3 = data_24_val[32'd4];

assign tmp_436_fu_3484_p4 = {{data_24_val[15:8]}};

assign tmp_437_fu_3500_p3 = add_ln46_87_fu_3478_p2[32'd2];

assign tmp_438_fu_3508_p3 = data_24_val[32'd7];

assign tmp_439_fu_3566_p3 = data_25_val[32'd5];

assign tmp_440_fu_3574_p3 = data_25_val[32'd4];

assign tmp_441_fu_3614_p4 = {{data_25_val[15:8]}};

assign tmp_442_fu_3630_p3 = add_ln46_88_fu_3608_p2[32'd2];

assign tmp_443_fu_3638_p3 = data_25_val[32'd7];

assign tmp_444_fu_3696_p3 = data_26_val[32'd5];

assign tmp_445_fu_3704_p3 = data_26_val[32'd4];

assign tmp_446_fu_3744_p4 = {{data_26_val[15:8]}};

assign tmp_447_fu_3760_p3 = add_ln46_89_fu_3738_p2[32'd2];

assign tmp_448_fu_3768_p3 = data_26_val[32'd7];

assign tmp_449_fu_3826_p3 = data_27_val[32'd5];

assign tmp_450_fu_3834_p3 = data_27_val[32'd4];

assign tmp_451_fu_3874_p4 = {{data_27_val[15:8]}};

assign tmp_452_fu_3890_p3 = add_ln46_90_fu_3868_p2[32'd2];

assign tmp_453_fu_3898_p3 = data_27_val[32'd7];

assign tmp_454_fu_3956_p3 = data_28_val[32'd5];

assign tmp_455_fu_3964_p3 = data_28_val[32'd4];

assign tmp_456_fu_4004_p4 = {{data_28_val[15:8]}};

assign tmp_457_fu_4020_p3 = add_ln46_91_fu_3998_p2[32'd2];

assign tmp_458_fu_4028_p3 = data_28_val[32'd7];

assign tmp_459_fu_4086_p3 = data_29_val[32'd5];

assign tmp_460_fu_4094_p3 = data_29_val[32'd4];

assign tmp_461_fu_4134_p4 = {{data_29_val[15:8]}};

assign tmp_462_fu_4150_p3 = add_ln46_92_fu_4128_p2[32'd2];

assign tmp_463_fu_4158_p3 = data_29_val[32'd7];

assign tmp_464_fu_4216_p3 = data_30_val[32'd5];

assign tmp_465_fu_4224_p3 = data_30_val[32'd4];

assign tmp_466_fu_4264_p4 = {{data_30_val[15:8]}};

assign tmp_467_fu_4280_p3 = add_ln46_93_fu_4258_p2[32'd2];

assign tmp_468_fu_4288_p3 = data_30_val[32'd7];

assign tmp_469_fu_4346_p3 = data_31_val[32'd5];

assign tmp_470_fu_4354_p3 = data_31_val[32'd4];

assign tmp_471_fu_4394_p4 = {{data_31_val[15:8]}};

assign tmp_472_fu_4410_p3 = add_ln46_94_fu_4388_p2[32'd2];

assign tmp_473_fu_4418_p3 = data_31_val[32'd7];

assign tmp_fu_316_p3 = data_0_val[32'd5];

assign tmp_s_fu_494_p4 = {{data_1_val[15:8]}};

assign trunc_ln2_fu_306_p4 = {{data_0_val[7:5]}};

assign trunc_ln46_127_fu_462_p1 = data_1_val[3:0];

assign trunc_ln46_128_fu_592_p1 = data_2_val[3:0];

assign trunc_ln46_129_fu_722_p1 = data_3_val[3:0];

assign trunc_ln46_130_fu_852_p1 = data_4_val[3:0];

assign trunc_ln46_131_fu_982_p1 = data_5_val[3:0];

assign trunc_ln46_132_fu_1112_p1 = data_6_val[3:0];

assign trunc_ln46_133_fu_1242_p1 = data_7_val[3:0];

assign trunc_ln46_134_fu_1372_p1 = data_8_val[3:0];

assign trunc_ln46_135_fu_1502_p1 = data_9_val[3:0];

assign trunc_ln46_136_fu_1632_p1 = data_10_val[3:0];

assign trunc_ln46_137_fu_1762_p1 = data_11_val[3:0];

assign trunc_ln46_138_fu_1892_p1 = data_12_val[3:0];

assign trunc_ln46_139_fu_2022_p1 = data_13_val[3:0];

assign trunc_ln46_140_fu_2152_p1 = data_14_val[3:0];

assign trunc_ln46_141_fu_2282_p1 = data_15_val[3:0];

assign trunc_ln46_142_fu_2412_p1 = data_16_val[3:0];

assign trunc_ln46_143_fu_2542_p1 = data_17_val[3:0];

assign trunc_ln46_144_fu_2672_p1 = data_18_val[3:0];

assign trunc_ln46_145_fu_2802_p1 = data_19_val[3:0];

assign trunc_ln46_146_fu_2932_p1 = data_20_val[3:0];

assign trunc_ln46_147_fu_3062_p1 = data_21_val[3:0];

assign trunc_ln46_148_fu_3192_p1 = data_22_val[3:0];

assign trunc_ln46_149_fu_3322_p1 = data_23_val[3:0];

assign trunc_ln46_150_fu_3452_p1 = data_24_val[3:0];

assign trunc_ln46_151_fu_3582_p1 = data_25_val[3:0];

assign trunc_ln46_152_fu_3712_p1 = data_26_val[3:0];

assign trunc_ln46_153_fu_3842_p1 = data_27_val[3:0];

assign trunc_ln46_154_fu_3972_p1 = data_28_val[3:0];

assign trunc_ln46_155_fu_4102_p1 = data_29_val[3:0];

assign trunc_ln46_156_fu_4232_p1 = data_30_val[3:0];

assign trunc_ln46_157_fu_4362_p1 = data_31_val[3:0];

assign trunc_ln46_63_fu_566_p4 = {{data_2_val[7:5]}};

assign trunc_ln46_64_fu_696_p4 = {{data_3_val[7:5]}};

assign trunc_ln46_65_fu_826_p4 = {{data_4_val[7:5]}};

assign trunc_ln46_66_fu_956_p4 = {{data_5_val[7:5]}};

assign trunc_ln46_67_fu_1086_p4 = {{data_6_val[7:5]}};

assign trunc_ln46_68_fu_1216_p4 = {{data_7_val[7:5]}};

assign trunc_ln46_69_fu_1346_p4 = {{data_8_val[7:5]}};

assign trunc_ln46_70_fu_1476_p4 = {{data_9_val[7:5]}};

assign trunc_ln46_71_fu_1606_p4 = {{data_10_val[7:5]}};

assign trunc_ln46_72_fu_1736_p4 = {{data_11_val[7:5]}};

assign trunc_ln46_73_fu_1866_p4 = {{data_12_val[7:5]}};

assign trunc_ln46_74_fu_1996_p4 = {{data_13_val[7:5]}};

assign trunc_ln46_75_fu_2126_p4 = {{data_14_val[7:5]}};

assign trunc_ln46_76_fu_2256_p4 = {{data_15_val[7:5]}};

assign trunc_ln46_77_fu_2386_p4 = {{data_16_val[7:5]}};

assign trunc_ln46_78_fu_2516_p4 = {{data_17_val[7:5]}};

assign trunc_ln46_79_fu_2646_p4 = {{data_18_val[7:5]}};

assign trunc_ln46_80_fu_2776_p4 = {{data_19_val[7:5]}};

assign trunc_ln46_81_fu_2906_p4 = {{data_20_val[7:5]}};

assign trunc_ln46_82_fu_3036_p4 = {{data_21_val[7:5]}};

assign trunc_ln46_83_fu_3166_p4 = {{data_22_val[7:5]}};

assign trunc_ln46_84_fu_3296_p4 = {{data_23_val[7:5]}};

assign trunc_ln46_85_fu_3426_p4 = {{data_24_val[7:5]}};

assign trunc_ln46_86_fu_3556_p4 = {{data_25_val[7:5]}};

assign trunc_ln46_87_fu_3686_p4 = {{data_26_val[7:5]}};

assign trunc_ln46_88_fu_3816_p4 = {{data_27_val[7:5]}};

assign trunc_ln46_89_fu_3946_p4 = {{data_28_val[7:5]}};

assign trunc_ln46_90_fu_4076_p4 = {{data_29_val[7:5]}};

assign trunc_ln46_91_fu_4206_p4 = {{data_30_val[7:5]}};

assign trunc_ln46_92_fu_4336_p4 = {{data_31_val[7:5]}};

assign trunc_ln46_fu_332_p1 = data_0_val[3:0];

assign trunc_ln46_s_fu_436_p4 = {{data_1_val[7:5]}};

assign xor_ln46_64_fu_526_p2 = (tmp_325_fu_518_p3 ^ 1'd1);

assign xor_ln46_65_fu_656_p2 = (tmp_329_fu_648_p3 ^ 1'd1);

assign xor_ln46_66_fu_786_p2 = (tmp_333_fu_778_p3 ^ 1'd1);

assign xor_ln46_67_fu_916_p2 = (tmp_338_fu_908_p3 ^ 1'd1);

assign xor_ln46_68_fu_1046_p2 = (tmp_343_fu_1038_p3 ^ 1'd1);

assign xor_ln46_69_fu_1176_p2 = (tmp_348_fu_1168_p3 ^ 1'd1);

assign xor_ln46_70_fu_1306_p2 = (tmp_353_fu_1298_p3 ^ 1'd1);

assign xor_ln46_71_fu_1436_p2 = (tmp_358_fu_1428_p3 ^ 1'd1);

assign xor_ln46_72_fu_1566_p2 = (tmp_363_fu_1558_p3 ^ 1'd1);

assign xor_ln46_73_fu_1696_p2 = (tmp_368_fu_1688_p3 ^ 1'd1);

assign xor_ln46_74_fu_1826_p2 = (tmp_373_fu_1818_p3 ^ 1'd1);

assign xor_ln46_75_fu_1956_p2 = (tmp_378_fu_1948_p3 ^ 1'd1);

assign xor_ln46_76_fu_2086_p2 = (tmp_383_fu_2078_p3 ^ 1'd1);

assign xor_ln46_77_fu_2216_p2 = (tmp_388_fu_2208_p3 ^ 1'd1);

assign xor_ln46_78_fu_2346_p2 = (tmp_393_fu_2338_p3 ^ 1'd1);

assign xor_ln46_79_fu_2476_p2 = (tmp_398_fu_2468_p3 ^ 1'd1);

assign xor_ln46_80_fu_2606_p2 = (tmp_403_fu_2598_p3 ^ 1'd1);

assign xor_ln46_81_fu_2736_p2 = (tmp_408_fu_2728_p3 ^ 1'd1);

assign xor_ln46_82_fu_2866_p2 = (tmp_413_fu_2858_p3 ^ 1'd1);

assign xor_ln46_83_fu_2996_p2 = (tmp_418_fu_2988_p3 ^ 1'd1);

assign xor_ln46_84_fu_3126_p2 = (tmp_423_fu_3118_p3 ^ 1'd1);

assign xor_ln46_85_fu_3256_p2 = (tmp_428_fu_3248_p3 ^ 1'd1);

assign xor_ln46_86_fu_3386_p2 = (tmp_433_fu_3378_p3 ^ 1'd1);

assign xor_ln46_87_fu_3516_p2 = (tmp_438_fu_3508_p3 ^ 1'd1);

assign xor_ln46_88_fu_3646_p2 = (tmp_443_fu_3638_p3 ^ 1'd1);

assign xor_ln46_89_fu_3776_p2 = (tmp_448_fu_3768_p3 ^ 1'd1);

assign xor_ln46_90_fu_3906_p2 = (tmp_453_fu_3898_p3 ^ 1'd1);

assign xor_ln46_91_fu_4036_p2 = (tmp_458_fu_4028_p3 ^ 1'd1);

assign xor_ln46_92_fu_4166_p2 = (tmp_463_fu_4158_p3 ^ 1'd1);

assign xor_ln46_93_fu_4296_p2 = (tmp_468_fu_4288_p3 ^ 1'd1);

assign xor_ln46_94_fu_4426_p2 = (tmp_473_fu_4418_p3 ^ 1'd1);

assign xor_ln46_fu_396_p2 = (tmp_321_fu_388_p3 ^ 1'd1);

assign zext_ln46_64_fu_484_p1 = and_ln46_129_fu_478_p2;

assign zext_ln46_65_fu_614_p1 = and_ln46_131_fu_608_p2;

assign zext_ln46_66_fu_744_p1 = and_ln46_133_fu_738_p2;

assign zext_ln46_67_fu_874_p1 = and_ln46_135_fu_868_p2;

assign zext_ln46_68_fu_1004_p1 = and_ln46_137_fu_998_p2;

assign zext_ln46_69_fu_1134_p1 = and_ln46_139_fu_1128_p2;

assign zext_ln46_70_fu_1264_p1 = and_ln46_141_fu_1258_p2;

assign zext_ln46_71_fu_1394_p1 = and_ln46_143_fu_1388_p2;

assign zext_ln46_72_fu_1524_p1 = and_ln46_145_fu_1518_p2;

assign zext_ln46_73_fu_1654_p1 = and_ln46_147_fu_1648_p2;

assign zext_ln46_74_fu_1784_p1 = and_ln46_149_fu_1778_p2;

assign zext_ln46_75_fu_1914_p1 = and_ln46_151_fu_1908_p2;

assign zext_ln46_76_fu_2044_p1 = and_ln46_153_fu_2038_p2;

assign zext_ln46_77_fu_2174_p1 = and_ln46_155_fu_2168_p2;

assign zext_ln46_78_fu_2304_p1 = and_ln46_157_fu_2298_p2;

assign zext_ln46_79_fu_2434_p1 = and_ln46_159_fu_2428_p2;

assign zext_ln46_80_fu_2564_p1 = and_ln46_161_fu_2558_p2;

assign zext_ln46_81_fu_2694_p1 = and_ln46_163_fu_2688_p2;

assign zext_ln46_82_fu_2824_p1 = and_ln46_165_fu_2818_p2;

assign zext_ln46_83_fu_2954_p1 = and_ln46_167_fu_2948_p2;

assign zext_ln46_84_fu_3084_p1 = and_ln46_169_fu_3078_p2;

assign zext_ln46_85_fu_3214_p1 = and_ln46_171_fu_3208_p2;

assign zext_ln46_86_fu_3344_p1 = and_ln46_173_fu_3338_p2;

assign zext_ln46_87_fu_3474_p1 = and_ln46_175_fu_3468_p2;

assign zext_ln46_88_fu_3604_p1 = and_ln46_177_fu_3598_p2;

assign zext_ln46_89_fu_3734_p1 = and_ln46_179_fu_3728_p2;

assign zext_ln46_90_fu_3864_p1 = and_ln46_181_fu_3858_p2;

assign zext_ln46_91_fu_3994_p1 = and_ln46_183_fu_3988_p2;

assign zext_ln46_92_fu_4124_p1 = and_ln46_185_fu_4118_p2;

assign zext_ln46_93_fu_4254_p1 = and_ln46_187_fu_4248_p2;

assign zext_ln46_94_fu_4384_p1 = and_ln46_189_fu_4378_p2;

assign zext_ln46_fu_354_p1 = and_ln46_fu_348_p2;

assign ap_return_0 = select_ln45_fu_422_p3;

assign ap_return_1 = select_ln45_64_fu_552_p3;

assign ap_return_10 = select_ln45_73_fu_1722_p3;

assign ap_return_11 = select_ln45_74_fu_1852_p3;

assign ap_return_12 = select_ln45_75_fu_1982_p3;

assign ap_return_13 = select_ln45_76_fu_2112_p3;

assign ap_return_14 = select_ln45_77_fu_2242_p3;

assign ap_return_15 = select_ln45_78_fu_2372_p3;

assign ap_return_16 = select_ln45_79_fu_2502_p3;

assign ap_return_17 = select_ln45_80_fu_2632_p3;

assign ap_return_18 = select_ln45_81_fu_2762_p3;

assign ap_return_19 = select_ln45_82_fu_2892_p3;

assign ap_return_2 = select_ln45_65_fu_682_p3;

assign ap_return_20 = select_ln45_83_fu_3022_p3;

assign ap_return_21 = select_ln45_84_fu_3152_p3;

assign ap_return_22 = select_ln45_85_fu_3282_p3;

assign ap_return_23 = select_ln45_86_fu_3412_p3;

assign ap_return_24 = select_ln45_87_fu_3542_p3;

assign ap_return_25 = select_ln45_88_fu_3672_p3;

assign ap_return_26 = select_ln45_89_fu_3802_p3;

assign ap_return_27 = select_ln45_90_fu_3932_p3;

assign ap_return_28 = select_ln45_91_fu_4062_p3;

assign ap_return_29 = select_ln45_92_fu_4192_p3;

assign ap_return_3 = select_ln45_66_fu_812_p3;

assign ap_return_30 = select_ln45_93_fu_4322_p3;

assign ap_return_31 = select_ln45_94_fu_4452_p3;

assign ap_return_4 = select_ln45_67_fu_942_p3;

assign ap_return_5 = select_ln45_68_fu_1072_p3;

assign ap_return_6 = select_ln45_69_fu_1202_p3;

assign ap_return_7 = select_ln45_70_fu_1332_p3;

assign ap_return_8 = select_ln45_71_fu_1462_p3;

assign ap_return_9 = select_ln45_72_fu_1592_p3;

assign icmp_ln45_64_fu_430_p2 = (($signed(data_1_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_65_fu_560_p2 = (($signed(data_2_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_66_fu_690_p2 = (($signed(data_3_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_67_fu_820_p2 = (($signed(data_4_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_68_fu_950_p2 = (($signed(data_5_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_69_fu_1080_p2 = (($signed(data_6_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_70_fu_1210_p2 = (($signed(data_7_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_71_fu_1340_p2 = (($signed(data_8_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_72_fu_1470_p2 = (($signed(data_9_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_73_fu_1600_p2 = (($signed(data_10_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_74_fu_1730_p2 = (($signed(data_11_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_75_fu_1860_p2 = (($signed(data_12_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_76_fu_1990_p2 = (($signed(data_13_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_77_fu_2120_p2 = (($signed(data_14_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_78_fu_2250_p2 = (($signed(data_15_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_79_fu_2380_p2 = (($signed(data_16_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_80_fu_2510_p2 = (($signed(data_17_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_81_fu_2640_p2 = (($signed(data_18_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_82_fu_2770_p2 = (($signed(data_19_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_83_fu_2900_p2 = (($signed(data_20_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_84_fu_3030_p2 = (($signed(data_21_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_85_fu_3160_p2 = (($signed(data_22_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_86_fu_3290_p2 = (($signed(data_23_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_87_fu_3420_p2 = (($signed(data_24_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_88_fu_3550_p2 = (($signed(data_25_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_89_fu_3680_p2 = (($signed(data_26_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_90_fu_3810_p2 = (($signed(data_27_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_91_fu_3940_p2 = (($signed(data_28_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_92_fu_4070_p2 = (($signed(data_29_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_93_fu_4200_p2 = (($signed(data_30_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_94_fu_4330_p2 = (($signed(data_31_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_fu_300_p2 = (($signed(data_0_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

endmodule //myproject_relu_ap_fixed_16_8_5_3_0_ap_ufixed_3_0_4_0_0_relu_config4_s
