// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_dense_latency_ap_ufixed_3_0_4_0_0_ap_fixed_16_8_5_3_0_config11_s (
        ap_clk,
        ap_rst,
        data_0_val,
        data_1_val,
        data_2_val,
        data_3_val,
        data_4_val,
        data_5_val,
        data_6_val,
        data_7_val,
        data_8_val,
        data_9_val,
        data_10_val,
        data_11_val,
        data_12_val,
        data_13_val,
        data_14_val,
        data_15_val,
        data_16_val,
        data_17_val,
        data_18_val,
        data_19_val,
        data_20_val,
        data_21_val,
        data_22_val,
        data_23_val,
        data_24_val,
        data_25_val,
        data_26_val,
        data_27_val,
        data_28_val,
        data_29_val,
        data_30_val,
        data_31_val,
        data_32_val,
        data_34_val,
        data_35_val,
        data_36_val,
        data_37_val,
        data_38_val,
        data_40_val,
        data_41_val,
        data_42_val,
        data_43_val,
        data_44_val,
        data_45_val,
        data_46_val,
        data_47_val,
        data_48_val,
        data_49_val,
        data_50_val,
        data_51_val,
        data_52_val,
        data_53_val,
        data_54_val,
        data_55_val,
        data_56_val,
        data_57_val,
        data_58_val,
        data_59_val,
        data_60_val,
        data_61_val,
        data_62_val,
        data_63_val,
        ap_return,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [2:0] data_0_val;
input  [2:0] data_1_val;
input  [2:0] data_2_val;
input  [2:0] data_3_val;
input  [2:0] data_4_val;
input  [2:0] data_5_val;
input  [2:0] data_6_val;
input  [2:0] data_7_val;
input  [2:0] data_8_val;
input  [2:0] data_9_val;
input  [2:0] data_10_val;
input  [2:0] data_11_val;
input  [2:0] data_12_val;
input  [2:0] data_13_val;
input  [2:0] data_14_val;
input  [2:0] data_15_val;
input  [2:0] data_16_val;
input  [2:0] data_17_val;
input  [2:0] data_18_val;
input  [2:0] data_19_val;
input  [2:0] data_20_val;
input  [2:0] data_21_val;
input  [2:0] data_22_val;
input  [2:0] data_23_val;
input  [2:0] data_24_val;
input  [2:0] data_25_val;
input  [2:0] data_26_val;
input  [2:0] data_27_val;
input  [2:0] data_28_val;
input  [2:0] data_29_val;
input  [2:0] data_30_val;
input  [2:0] data_31_val;
input  [2:0] data_32_val;
input  [2:0] data_34_val;
input  [2:0] data_35_val;
input  [2:0] data_36_val;
input  [2:0] data_37_val;
input  [2:0] data_38_val;
input  [2:0] data_40_val;
input  [2:0] data_41_val;
input  [2:0] data_42_val;
input  [2:0] data_43_val;
input  [2:0] data_44_val;
input  [2:0] data_45_val;
input  [2:0] data_46_val;
input  [2:0] data_47_val;
input  [2:0] data_48_val;
input  [2:0] data_49_val;
input  [2:0] data_50_val;
input  [2:0] data_51_val;
input  [2:0] data_52_val;
input  [2:0] data_53_val;
input  [2:0] data_54_val;
input  [2:0] data_55_val;
input  [2:0] data_56_val;
input  [2:0] data_57_val;
input  [2:0] data_58_val;
input  [2:0] data_59_val;
input  [2:0] data_60_val;
input  [2:0] data_61_val;
input  [2:0] data_62_val;
input  [2:0] data_63_val;
output  [15:0] ap_return;
input   ap_ce;

reg[15:0] ap_return;

reg   [6:0] trunc_ln42_32_reg_15311;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_11001;
reg   [6:0] trunc_ln42_33_reg_15316;
wire   [8:0] add_ln58_2420_fu_14767_p2;
reg   [8:0] add_ln58_2420_reg_15321;
wire   [10:0] add_ln58_2423_fu_14789_p2;
reg   [10:0] add_ln58_2423_reg_15326;
wire   [9:0] add_ln58_2427_fu_14815_p2;
reg   [9:0] add_ln58_2427_reg_15331;
wire   [9:0] add_ln58_2430_fu_14841_p2;
reg   [9:0] add_ln58_2430_reg_15336;
wire   [8:0] add_ln58_2433_fu_14847_p2;
reg   [8:0] add_ln58_2433_reg_15341;
wire   [14:0] add_ln58_2434_fu_14853_p2;
reg   [14:0] add_ln58_2434_reg_15346;
wire   [9:0] add_ln58_2438_fu_14879_p2;
reg   [9:0] add_ln58_2438_reg_15351;
wire   [8:0] add_ln58_2442_fu_14901_p2;
reg   [8:0] add_ln58_2442_reg_15356;
wire   [9:0] add_ln58_2445_fu_14927_p2;
reg   [9:0] add_ln58_2445_reg_15361;
wire   [9:0] add_ln58_2451_fu_14953_p2;
reg   [9:0] add_ln58_2451_reg_15366;
wire   [8:0] add_ln58_2454_fu_14979_p2;
reg   [8:0] add_ln58_2454_reg_15371;
wire   [9:0] add_ln58_2458_fu_15005_p2;
reg   [9:0] add_ln58_2458_reg_15376;
wire   [9:0] add_ln58_2461_fu_15027_p2;
reg   [9:0] add_ln58_2461_reg_15381;
wire   [6:0] add_ln58_2464_fu_15033_p2;
reg   [6:0] add_ln58_2464_reg_15386;
wire   [9:0] add_ln58_2469_fu_15055_p2;
reg   [9:0] add_ln58_2469_reg_15391;
wire   [14:0] add_ln58_2477_fu_15117_p2;
reg   [14:0] add_ln58_2477_reg_15396;
wire   [2:0] mul_ln42_10_fu_669_p0;
wire   [7:0] mul_ln42_10_fu_669_p1;
wire    ap_block_pp0_stage0;
wire   [2:0] mul_ln73_6_fu_670_p0;
wire  signed [8:0] mul_ln73_6_fu_670_p1;
wire   [2:0] mul_ln42_5_fu_671_p0;
wire   [8:0] mul_ln42_5_fu_671_p1;
wire   [2:0] mul_ln73_13_fu_673_p0;
wire  signed [7:0] mul_ln73_13_fu_673_p1;
wire   [2:0] mul_ln42_19_fu_674_p0;
wire   [7:0] mul_ln42_19_fu_674_p1;
wire   [2:0] mul_ln73_12_fu_675_p0;
wire  signed [5:0] mul_ln73_12_fu_675_p1;
wire   [2:0] mul_ln73_7_fu_676_p0;
wire  signed [5:0] mul_ln73_7_fu_676_p1;
wire   [2:0] mul_ln42_9_fu_678_p0;
wire   [7:0] mul_ln42_9_fu_678_p1;
wire   [2:0] mul_ln73_10_fu_679_p0;
wire  signed [6:0] mul_ln73_10_fu_679_p1;
wire   [2:0] mul_ln42_18_fu_680_p0;
wire   [7:0] mul_ln42_18_fu_680_p1;
wire   [2:0] mul_ln42_24_fu_681_p0;
wire   [6:0] mul_ln42_24_fu_681_p1;
wire   [2:0] mul_ln42_15_fu_682_p0;
wire   [7:0] mul_ln42_15_fu_682_p1;
wire   [2:0] mul_ln73_5_fu_683_p0;
wire  signed [6:0] mul_ln73_5_fu_683_p1;
wire   [2:0] mul_ln42_20_fu_684_p0;
wire   [8:0] mul_ln42_20_fu_684_p1;
wire   [2:0] mul_ln73_15_fu_685_p0;
wire  signed [7:0] mul_ln73_15_fu_685_p1;
wire   [2:0] mul_ln42_2_fu_686_p0;
wire   [8:0] mul_ln42_2_fu_686_p1;
wire   [2:0] mul_ln42_1_fu_687_p0;
wire   [6:0] mul_ln42_1_fu_687_p1;
wire   [2:0] mul_ln42_12_fu_689_p0;
wire   [6:0] mul_ln42_12_fu_689_p1;
wire   [2:0] mul_ln73_18_fu_692_p0;
wire  signed [8:0] mul_ln73_18_fu_692_p1;
wire   [2:0] mul_ln73_20_fu_693_p0;
wire  signed [6:0] mul_ln73_20_fu_693_p1;
wire   [2:0] mul_ln73_3_fu_694_p0;
wire  signed [5:0] mul_ln73_3_fu_694_p1;
wire   [2:0] mul_ln73_14_fu_697_p0;
wire  signed [7:0] mul_ln73_14_fu_697_p1;
wire   [2:0] mul_ln73_1_fu_699_p0;
wire  signed [8:0] mul_ln73_1_fu_699_p1;
wire   [2:0] mul_ln42_22_fu_701_p0;
wire   [6:0] mul_ln42_22_fu_701_p1;
wire   [2:0] mul_ln42_21_fu_702_p0;
wire   [7:0] mul_ln42_21_fu_702_p1;
wire   [2:0] mul_ln73_9_fu_704_p0;
wire  signed [6:0] mul_ln73_9_fu_704_p1;
wire   [2:0] mul_ln42_7_fu_705_p0;
wire   [7:0] mul_ln42_7_fu_705_p1;
wire   [2:0] mul_ln73_8_fu_706_p0;
wire  signed [7:0] mul_ln73_8_fu_706_p1;
wire   [2:0] mul_ln73_4_fu_707_p0;
wire  signed [7:0] mul_ln73_4_fu_707_p1;
wire   [2:0] mul_ln73_16_fu_708_p0;
wire  signed [5:0] mul_ln73_16_fu_708_p1;
wire   [2:0] mul_ln42_fu_709_p0;
wire   [6:0] mul_ln42_fu_709_p1;
wire   [2:0] mul_ln42_13_fu_712_p0;
wire   [7:0] mul_ln42_13_fu_712_p1;
wire   [2:0] mul_ln42_16_fu_713_p0;
wire   [7:0] mul_ln42_16_fu_713_p1;
wire   [2:0] mul_ln73_fu_714_p0;
wire  signed [9:0] mul_ln73_fu_714_p1;
wire   [2:0] mul_ln73_11_fu_715_p0;
wire  signed [6:0] mul_ln73_11_fu_715_p1;
wire   [2:0] mul_ln42_11_fu_716_p0;
wire   [8:0] mul_ln42_11_fu_716_p1;
wire   [2:0] mul_ln42_25_fu_718_p0;
wire   [7:0] mul_ln42_25_fu_718_p1;
wire   [2:0] mul_ln73_19_fu_719_p0;
wire  signed [7:0] mul_ln73_19_fu_719_p1;
wire   [2:0] mul_ln42_6_fu_721_p0;
wire   [7:0] mul_ln42_6_fu_721_p1;
wire   [2:0] mul_ln73_17_fu_722_p0;
wire  signed [6:0] mul_ln73_17_fu_722_p1;
wire   [2:0] mul_ln73_2_fu_723_p0;
wire  signed [7:0] mul_ln73_2_fu_723_p1;
wire   [2:0] mul_ln42_3_fu_724_p0;
wire   [6:0] mul_ln42_3_fu_724_p1;
wire   [2:0] mul_ln42_14_fu_725_p0;
wire   [8:0] mul_ln42_14_fu_725_p1;
wire   [2:0] mul_ln42_8_fu_727_p0;
wire   [7:0] mul_ln42_8_fu_727_p1;
wire   [2:0] mul_ln42_23_fu_728_p0;
wire   [7:0] mul_ln42_23_fu_728_p1;
wire   [2:0] mul_ln42_26_fu_729_p0;
wire   [6:0] mul_ln42_26_fu_729_p1;
wire   [2:0] mul_ln42_17_fu_730_p0;
wire   [8:0] mul_ln42_17_fu_730_p1;
wire   [2:0] mul_ln42_4_fu_731_p0;
wire   [8:0] mul_ln42_4_fu_731_p1;
wire   [4:0] tmp_fu_13361_p3;
wire   [5:0] zext_ln70_fu_13357_p1;
wire   [5:0] zext_ln73_11_fu_13369_p1;
wire   [5:0] sub_ln73_8_fu_13373_p2;
wire   [2:0] trunc_ln_fu_13379_p4;
wire   [8:0] shl_ln42_1_fu_13393_p3;
wire   [6:0] shl_ln42_2_fu_13405_p3;
wire   [9:0] zext_ln42_fu_13401_p1;
wire   [9:0] zext_ln42_1_fu_13413_p1;
wire   [9:0] add_ln42_fu_13417_p2;
wire   [8:0] mul_ln42_fu_709_p2;
wire   [5:0] trunc_ln42_2_fu_13438_p4;
wire   [8:0] mul_ln42_1_fu_687_p2;
wire   [5:0] trunc_ln42_3_fu_13457_p4;
wire   [10:0] mul_ln42_2_fu_686_p2;
wire   [12:0] mul_ln73_fu_714_p2;
wire   [9:0] trunc_ln42_4_fu_13491_p4;
wire   [11:0] mul_ln73_1_fu_699_p2;
wire   [8:0] trunc_ln42_5_fu_13510_p4;
wire   [8:0] mul_ln42_3_fu_724_p2;
wire   [5:0] trunc_ln42_6_fu_13529_p4;
wire   [10:0] mul_ln42_4_fu_731_p2;
wire   [10:0] mul_ln73_2_fu_723_p2;
wire   [7:0] trunc_ln42_7_fu_13563_p4;
wire   [8:0] mul_ln73_3_fu_694_p2;
wire   [5:0] trunc_ln42_8_fu_13582_p4;
wire   [10:0] mul_ln73_4_fu_707_p2;
wire   [7:0] trunc_ln42_9_fu_13601_p4;
wire   [7:0] shl_ln_fu_13615_p3;
wire   [8:0] zext_ln73_fu_13623_p1;
wire   [4:0] shl_ln73_1_fu_13633_p3;
wire   [8:0] sub_ln73_fu_13627_p2;
wire   [8:0] zext_ln73_1_fu_13641_p1;
wire   [8:0] sub_ln73_1_fu_13645_p2;
wire   [5:0] trunc_ln42_s_fu_13651_p4;
wire   [9:0] mul_ln73_5_fu_683_p2;
wire   [6:0] trunc_ln42_10_fu_13670_p4;
wire   [10:0] mul_ln42_5_fu_671_p2;
wire   [7:0] lshr_ln42_s_fu_13689_p4;
wire   [9:0] mul_ln42_6_fu_721_p2;
wire   [6:0] lshr_ln42_1_fu_13708_p4;
wire   [9:0] shl_ln73_2_fu_13722_p3;
wire   [7:0] shl_ln73_3_fu_13734_p3;
wire   [10:0] zext_ln73_3_fu_13742_p1;
wire   [10:0] zext_ln73_2_fu_13730_p1;
wire   [10:0] sub_ln73_2_fu_13746_p2;
wire   [7:0] trunc_ln42_11_fu_13752_p4;
wire   [11:0] mul_ln73_6_fu_670_p2;
wire   [8:0] trunc_ln42_12_fu_13771_p4;
wire   [9:0] shl_ln42_3_fu_13785_p3;
wire   [4:0] shl_ln42_4_fu_13797_p3;
wire   [10:0] zext_ln42_5_fu_13793_p1;
wire   [10:0] zext_ln42_6_fu_13805_p1;
wire   [10:0] sub_ln42_fu_13809_p2;
wire   [7:0] trunc_ln42_13_fu_13815_p4;
wire  signed [12:0] sext_ln70_10_fu_13825_p1;
wire   [8:0] mul_ln73_7_fu_676_p2;
wire   [5:0] trunc_ln42_14_fu_13838_p4;
wire   [9:0] mul_ln42_7_fu_705_p2;
wire   [6:0] lshr_ln42_2_fu_13857_p4;
wire   [10:0] mul_ln73_8_fu_706_p2;
wire   [7:0] trunc_ln42_15_fu_13876_p4;
wire   [9:0] mul_ln73_9_fu_704_p2;
wire   [6:0] trunc_ln42_16_fu_13895_p4;
wire   [9:0] mul_ln42_8_fu_727_p2;
wire   [6:0] lshr_ln42_3_fu_13914_p4;
wire   [6:0] shl_ln73_4_fu_13928_p3;
wire   [3:0] shl_ln73_5_fu_13940_p3;
wire   [7:0] zext_ln73_5_fu_13948_p1;
wire   [7:0] zext_ln73_4_fu_13936_p1;
wire   [7:0] sub_ln73_3_fu_13952_p2;
wire   [4:0] trunc_ln42_17_fu_13958_p4;
wire   [9:0] mul_ln73_10_fu_679_p2;
wire   [6:0] trunc_ln42_18_fu_13977_p4;
wire   [9:0] mul_ln42_9_fu_678_p2;
wire   [6:0] lshr_ln42_4_fu_13996_p4;
wire   [8:0] mul_ln42_10_fu_669_p2;
wire   [5:0] lshr_ln42_5_fu_14015_p4;
wire   [9:0] mul_ln73_11_fu_715_p2;
wire   [6:0] trunc_ln42_19_fu_14034_p4;
wire   [10:0] mul_ln42_11_fu_716_p2;
wire   [7:0] lshr_ln42_6_fu_14053_p4;
wire   [7:0] shl_ln73_6_fu_14067_p3;
wire   [8:0] zext_ln73_6_fu_14075_p1;
wire   [8:0] sub_ln73_4_fu_14079_p2;
wire   [5:0] trunc_ln42_20_fu_14085_p4;
wire   [8:0] mul_ln73_12_fu_675_p2;
wire   [5:0] trunc_ln42_21_fu_14104_p4;
wire   [10:0] mul_ln73_13_fu_673_p2;
wire   [7:0] trunc_ln42_22_fu_14123_p4;
wire   [8:0] mul_ln42_12_fu_689_p2;
wire   [5:0] lshr_ln42_7_fu_14142_p4;
wire   [9:0] shl_ln73_7_fu_14156_p3;
wire   [5:0] shl_ln73_8_fu_14168_p3;
wire   [10:0] zext_ln73_8_fu_14176_p1;
wire   [10:0] zext_ln73_7_fu_14164_p1;
wire   [10:0] sub_ln73_5_fu_14180_p2;
wire   [7:0] trunc_ln42_23_fu_14186_p4;
wire   [9:0] mul_ln42_13_fu_712_p2;
wire   [6:0] trunc_ln42_24_fu_14205_p4;
wire   [9:0] mul_ln42_14_fu_725_p2;
wire   [6:0] tmp_1_fu_14224_p4;
wire   [9:0] mul_ln42_15_fu_682_p2;
wire   [6:0] trunc_ln42_25_fu_14243_p4;
wire   [9:0] mul_ln42_16_fu_713_p2;
wire   [6:0] trunc_ln42_26_fu_14262_p4;
wire   [10:0] mul_ln42_17_fu_730_p2;
wire   [9:0] mul_ln42_18_fu_680_p2;
wire   [6:0] lshr_ln42_40_cast_fu_14296_p4;
wire   [10:0] mul_ln73_14_fu_697_p2;
wire   [7:0] trunc_ln42_28_fu_14315_p4;
wire   [9:0] mul_ln42_19_fu_674_p2;
wire   [6:0] lshr_ln42_8_fu_14334_p4;
wire   [10:0] mul_ln73_15_fu_685_p2;
wire   [7:0] trunc_ln42_29_fu_14353_p4;
wire   [10:0] mul_ln42_20_fu_684_p2;
wire   [7:0] lshr_ln42_9_fu_14380_p4;
wire   [3:0] shl_ln42_5_fu_14394_p3;
wire   [8:0] mul_ln73_16_fu_708_p2;
wire   [5:0] trunc_ln42_30_fu_14411_p4;
wire   [8:0] mul_ln42_21_fu_702_p2;
wire   [5:0] tmp_2_fu_14430_p4;
wire   [8:0] mul_ln42_22_fu_701_p2;
wire   [5:0] trunc_ln42_31_fu_14449_p4;
wire   [8:0] shl_ln42_6_fu_14463_p3;
wire   [5:0] shl_ln42_7_fu_14475_p3;
wire   [9:0] zext_ln42_17_fu_14471_p1;
wire   [9:0] zext_ln42_18_fu_14483_p1;
wire   [9:0] sub_ln42_1_fu_14487_p2;
wire   [9:0] mul_ln73_17_fu_722_p2;
wire   [9:0] mul_ln42_23_fu_728_p2;
wire   [6:0] lshr_ln42_10_fu_14523_p4;
wire   [11:0] mul_ln73_18_fu_692_p2;
wire   [8:0] trunc_ln42_34_fu_14542_p4;
wire   [10:0] mul_ln73_19_fu_719_p2;
wire   [7:0] trunc_ln42_35_fu_14561_p4;
wire   [7:0] shl_ln73_9_fu_14575_p3;
wire   [8:0] zext_ln73_9_fu_14583_p1;
wire   [3:0] shl_ln73_s_fu_14593_p3;
wire   [8:0] sub_ln73_6_fu_14587_p2;
wire   [8:0] zext_ln73_10_fu_14601_p1;
wire   [8:0] sub_ln73_7_fu_14605_p2;
wire   [5:0] trunc_ln42_36_fu_14611_p4;
wire   [8:0] mul_ln42_24_fu_681_p2;
wire   [5:0] trunc_ln42_37_fu_14630_p4;
wire   [4:0] shl_ln42_8_fu_14644_p3;
wire   [9:0] mul_ln42_25_fu_718_p2;
wire   [6:0] lshr_ln42_11_fu_14661_p4;
wire   [5:0] shl_ln42_9_fu_14679_p3;
wire   [6:0] zext_ln42_22_fu_14687_p1;
wire   [6:0] zext_ln70_44_fu_14675_p1;
wire   [6:0] sub_ln42_2_fu_14691_p2;
wire   [3:0] trunc_ln42_38_fu_14697_p4;
wire  signed [12:0] sext_ln42_1_fu_14707_p1;
wire   [8:0] mul_ln42_26_fu_729_p2;
wire   [5:0] lshr_ln42_12_fu_14720_p4;
wire   [9:0] mul_ln73_20_fu_693_p2;
wire   [6:0] trunc_ln42_39_fu_14739_p4;
wire   [3:0] shl_ln1_fu_14367_p3;
wire   [6:0] trunc_ln42_1_fu_13423_p4;
wire   [6:0] zext_ln42_2_fu_13448_p1;
wire   [6:0] add_ln58_fu_14757_p2;
wire   [8:0] zext_ln58_155_fu_14763_p1;
wire  signed [8:0] sext_ln70_fu_13389_p1;
wire   [7:0] zext_ln42_3_fu_13467_p1;
wire   [7:0] lshr_ln42_4_cast_fu_13476_p4;
wire   [7:0] add_ln58_2421_fu_14773_p2;
wire  signed [10:0] sext_ln70_1_fu_13501_p1;
wire  signed [10:0] sext_ln70_2_fu_13520_p1;
wire   [10:0] add_ln58_2422_fu_14783_p2;
wire   [10:0] zext_ln58_156_fu_14779_p1;
wire   [7:0] zext_ln42_4_fu_13539_p1;
wire   [7:0] lshr_ln42_8_cast_fu_13548_p4;
wire   [7:0] add_ln58_2425_fu_14795_p2;
wire  signed [8:0] sext_ln70_3_fu_13573_p1;
wire  signed [8:0] sext_ln70_4_fu_13592_p1;
wire   [8:0] add_ln58_2426_fu_14805_p2;
wire  signed [9:0] sext_ln58_2215_fu_14811_p1;
wire   [9:0] zext_ln58_157_fu_14801_p1;
wire  signed [8:0] sext_ln70_5_fu_13611_p1;
wire  signed [8:0] sext_ln70_6_fu_13661_p1;
wire   [8:0] add_ln58_2428_fu_14821_p2;
wire  signed [8:0] sext_ln70_7_fu_13680_p1;
wire   [8:0] zext_ln70_47_fu_13699_p1;
wire   [8:0] add_ln58_2429_fu_14831_p2;
wire  signed [9:0] sext_ln58_2218_fu_14837_p1;
wire  signed [9:0] sext_ln58_2217_fu_14827_p1;
wire   [8:0] zext_ln70_48_fu_13718_p1;
wire  signed [8:0] sext_ln70_8_fu_13762_p1;
wire  signed [14:0] sext_ln70_9_fu_13781_p1;
wire   [14:0] zext_ln70_49_fu_13829_p1;
wire  signed [7:0] sext_ln70_11_fu_13848_p1;
wire   [7:0] zext_ln70_50_fu_13867_p1;
wire   [7:0] add_ln58_2436_fu_14859_p2;
wire  signed [8:0] sext_ln70_12_fu_13886_p1;
wire  signed [8:0] sext_ln70_13_fu_13905_p1;
wire   [8:0] add_ln58_2437_fu_14869_p2;
wire  signed [9:0] sext_ln58_2224_fu_14875_p1;
wire  signed [9:0] sext_ln58_2223_fu_14865_p1;
wire   [7:0] zext_ln70_51_fu_13924_p1;
wire  signed [7:0] sext_ln70_14_fu_13968_p1;
wire   [7:0] add_ln58_2440_fu_14885_p2;
wire  signed [8:0] sext_ln70_15_fu_13987_p1;
wire   [8:0] zext_ln42_7_fu_14006_p1;
wire   [8:0] add_ln58_2441_fu_14895_p2;
wire  signed [8:0] sext_ln58_2226_fu_14891_p1;
wire   [7:0] zext_ln70_52_fu_14025_p1;
wire  signed [7:0] sext_ln70_16_fu_14044_p1;
wire   [7:0] add_ln58_2443_fu_14907_p2;
wire   [8:0] zext_ln70_53_fu_14063_p1;
wire  signed [8:0] sext_ln70_17_fu_14095_p1;
wire   [8:0] add_ln58_2444_fu_14917_p2;
wire  signed [9:0] sext_ln58_2229_fu_14923_p1;
wire  signed [9:0] sext_ln58_2228_fu_14913_p1;
wire  signed [8:0] sext_ln70_18_fu_14114_p1;
wire  signed [8:0] sext_ln70_19_fu_14133_p1;
wire   [8:0] add_ln58_2449_fu_14933_p2;
wire   [8:0] zext_ln70_54_fu_14152_p1;
wire  signed [8:0] sext_ln70_20_fu_14196_p1;
wire   [8:0] add_ln58_2450_fu_14943_p2;
wire  signed [9:0] sext_ln58_2234_fu_14949_p1;
wire  signed [9:0] sext_ln58_2233_fu_14939_p1;
wire   [7:0] zext_ln42_9_fu_14215_p1;
wire   [7:0] zext_ln42_11_fu_14234_p1;
wire   [7:0] add_ln58_2452_fu_14959_p2;
wire   [7:0] zext_ln42_12_fu_14253_p1;
wire   [7:0] zext_ln42_13_fu_14272_p1;
wire   [7:0] add_ln58_2453_fu_14969_p2;
wire   [8:0] zext_ln58_159_fu_14975_p1;
wire   [8:0] zext_ln58_158_fu_14965_p1;
wire   [7:0] trunc_ln42_27_fu_14281_p4;
wire   [7:0] lshr_ln42_40_cast_cast_fu_14306_p1;
wire   [7:0] add_ln58_2456_fu_14985_p2;
wire  signed [8:0] sext_ln70_21_fu_14325_p1;
wire   [8:0] zext_ln70_55_fu_14344_p1;
wire   [8:0] add_ln58_2457_fu_14995_p2;
wire  signed [9:0] sext_ln58_2237_fu_15001_p1;
wire   [9:0] zext_ln58_161_fu_14991_p1;
wire  signed [9:0] sext_ln70_22_fu_14363_p1;
wire   [9:0] zext_ln70_56_fu_14390_p1;
wire   [6:0] zext_ln70_57_fu_14402_p1;
wire  signed [6:0] sext_ln42_fu_14421_p1;
wire   [6:0] add_ln58_2460_fu_15017_p2;
wire  signed [9:0] sext_ln58_2239_fu_15023_p1;
wire   [9:0] add_ln58_2459_fu_15011_p2;
wire   [6:0] zext_ln42_15_fu_14440_p1;
wire   [6:0] zext_ln42_16_fu_14459_p1;
wire   [9:0] zext_ln70_59_fu_14533_p1;
wire  signed [9:0] sext_ln70_25_fu_14552_p1;
wire  signed [8:0] sext_ln70_26_fu_14571_p1;
wire  signed [8:0] sext_ln70_27_fu_14621_p1;
wire   [8:0] add_ln58_2468_fu_15045_p2;
wire  signed [9:0] sext_ln58_2243_fu_15051_p1;
wire   [9:0] add_ln58_2467_fu_15039_p2;
wire   [6:0] zext_ln42_19_fu_14640_p1;
wire   [6:0] zext_ln42_20_fu_14652_p1;
wire   [6:0] add_ln58_2471_fu_15061_p2;
wire   [13:0] zext_ln42_21_fu_14671_p1;
wire   [13:0] zext_ln42_23_fu_14711_p1;
wire   [13:0] add_ln58_2472_fu_15071_p2;
wire   [13:0] zext_ln58_163_fu_15067_p1;
wire   [13:0] add_ln58_2473_fu_15077_p2;
wire   [7:0] zext_ln70_60_fu_14730_p1;
wire  signed [7:0] sext_ln58_fu_14749_p1;
wire   [7:0] add_ln58_2474_fu_15087_p2;
wire   [9:0] zext_ln58_fu_14753_p1;
wire   [9:0] add_ln58_2475_fu_15097_p2;
wire  signed [10:0] sext_ln58_2247_fu_15103_p1;
wire  signed [10:0] sext_ln58_2246_fu_15093_p1;
wire   [10:0] add_ln58_2476_fu_15107_p2;
wire  signed [14:0] sext_ln58_2248_fu_15113_p1;
wire   [14:0] zext_ln58_164_fu_15083_p1;
wire  signed [12:0] sext_ln70_23_fu_15123_p1;
wire  signed [11:0] sext_ln58_2214_fu_15136_p1;
wire  signed [11:0] sext_ln58_2213_fu_15133_p1;
wire  signed [10:0] sext_ln58_2219_fu_15148_p1;
wire  signed [10:0] sext_ln58_2216_fu_15145_p1;
wire   [10:0] add_ln58_2431_fu_15151_p2;
wire  signed [11:0] sext_ln58_2220_fu_15157_p1;
wire   [11:0] add_ln58_2424_fu_15139_p2;
wire   [11:0] add_ln58_2432_fu_15161_p2;
wire  signed [14:0] sext_ln58_2222_fu_15171_p1;
wire  signed [14:0] sext_ln58_2225_fu_15179_p1;
wire   [14:0] add_ln58_2435_fu_15174_p2;
wire  signed [10:0] sext_ln58_2230_fu_15191_p1;
wire  signed [10:0] sext_ln58_2227_fu_15188_p1;
wire   [10:0] add_ln58_2446_fu_15194_p2;
wire  signed [14:0] sext_ln58_2231_fu_15200_p1;
wire   [14:0] add_ln58_2439_fu_15182_p2;
wire   [14:0] add_ln58_2447_fu_15204_p2;
wire  signed [14:0] sext_ln58_2221_fu_15167_p1;
wire   [14:0] add_ln58_2448_fu_15210_p2;
wire   [10:0] zext_ln58_160_fu_15223_p1;
wire  signed [10:0] sext_ln58_2235_fu_15220_p1;
wire   [10:0] add_ln58_2455_fu_15226_p2;
wire  signed [10:0] sext_ln58_2240_fu_15239_p1;
wire  signed [10:0] sext_ln58_2238_fu_15236_p1;
wire   [10:0] add_ln58_2462_fu_15242_p2;
wire  signed [11:0] sext_ln58_2241_fu_15248_p1;
wire  signed [11:0] sext_ln58_2236_fu_15232_p1;
wire   [11:0] add_ln58_2463_fu_15252_p2;
wire   [14:0] zext_ln70_58_fu_15126_p1;
wire  signed [14:0] sext_ln70_24_fu_15130_p1;
wire   [14:0] add_ln58_2465_fu_15265_p2;
wire   [14:0] zext_ln58_162_fu_15262_p1;
wire  signed [14:0] sext_ln58_2244_fu_15277_p1;
wire   [14:0] add_ln58_2466_fu_15271_p2;
wire   [14:0] add_ln58_2470_fu_15280_p2;
wire  signed [15:0] sext_ln58_2249_fu_15290_p1;
wire  signed [15:0] sext_ln58_2245_fu_15286_p1;
wire   [15:0] add_ln58_2478_fu_15293_p2;
wire  signed [15:0] sext_ln58_2242_fu_15258_p1;
wire   [15:0] add_ln58_2479_fu_15299_p2;
wire  signed [15:0] sext_ln58_2232_fu_15216_p1;
wire   [15:0] add_ln58_2480_fu_15305_p2;
reg    ap_ce_reg;
reg   [15:0] ap_return_int_reg;
wire   [8:0] mul_ln42_10_fu_669_p00;
wire   [10:0] mul_ln42_11_fu_716_p00;
wire   [8:0] mul_ln42_12_fu_689_p00;
wire   [9:0] mul_ln42_13_fu_712_p00;
wire   [9:0] mul_ln42_14_fu_725_p00;
wire   [9:0] mul_ln42_15_fu_682_p00;
wire   [9:0] mul_ln42_16_fu_713_p00;
wire   [10:0] mul_ln42_17_fu_730_p00;
wire   [9:0] mul_ln42_18_fu_680_p00;
wire   [9:0] mul_ln42_19_fu_674_p00;
wire   [8:0] mul_ln42_1_fu_687_p00;
wire   [10:0] mul_ln42_20_fu_684_p00;
wire   [8:0] mul_ln42_21_fu_702_p00;
wire   [8:0] mul_ln42_22_fu_701_p00;
wire   [9:0] mul_ln42_23_fu_728_p00;
wire   [8:0] mul_ln42_24_fu_681_p00;
wire   [9:0] mul_ln42_25_fu_718_p00;
wire   [8:0] mul_ln42_26_fu_729_p00;
wire   [10:0] mul_ln42_2_fu_686_p00;
wire   [8:0] mul_ln42_3_fu_724_p00;
wire   [10:0] mul_ln42_4_fu_731_p00;
wire   [10:0] mul_ln42_5_fu_671_p00;
wire   [9:0] mul_ln42_6_fu_721_p00;
wire   [9:0] mul_ln42_7_fu_705_p00;
wire   [9:0] mul_ln42_8_fu_727_p00;
wire   [9:0] mul_ln42_9_fu_678_p00;
wire   [8:0] mul_ln42_fu_709_p00;
wire   [9:0] mul_ln73_10_fu_679_p00;
wire   [9:0] mul_ln73_11_fu_715_p00;
wire   [8:0] mul_ln73_12_fu_675_p00;
wire   [10:0] mul_ln73_13_fu_673_p00;
wire   [10:0] mul_ln73_14_fu_697_p00;
wire   [10:0] mul_ln73_15_fu_685_p00;
wire   [8:0] mul_ln73_16_fu_708_p00;
wire   [9:0] mul_ln73_17_fu_722_p00;
wire   [11:0] mul_ln73_18_fu_692_p00;
wire   [10:0] mul_ln73_19_fu_719_p00;
wire   [11:0] mul_ln73_1_fu_699_p00;
wire   [9:0] mul_ln73_20_fu_693_p00;
wire   [10:0] mul_ln73_2_fu_723_p00;
wire   [8:0] mul_ln73_3_fu_694_p00;
wire   [10:0] mul_ln73_4_fu_707_p00;
wire   [9:0] mul_ln73_5_fu_683_p00;
wire   [11:0] mul_ln73_6_fu_670_p00;
wire   [8:0] mul_ln73_7_fu_676_p00;
wire   [10:0] mul_ln73_8_fu_706_p00;
wire   [9:0] mul_ln73_9_fu_704_p00;
wire   [12:0] mul_ln73_fu_714_p00;

myproject_mul_3ns_8ns_9_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 9 ))
mul_3ns_8ns_9_1_0_U414(
    .din0(mul_ln42_10_fu_669_p0),
    .din1(mul_ln42_10_fu_669_p1),
    .dout(mul_ln42_10_fu_669_p2)
);

myproject_mul_3ns_9s_12_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 12 ))
mul_3ns_9s_12_1_0_U415(
    .din0(mul_ln73_6_fu_670_p0),
    .din1(mul_ln73_6_fu_670_p1),
    .dout(mul_ln73_6_fu_670_p2)
);

myproject_mul_3ns_9ns_11_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 11 ))
mul_3ns_9ns_11_1_0_U416(
    .din0(mul_ln42_5_fu_671_p0),
    .din1(mul_ln42_5_fu_671_p1),
    .dout(mul_ln42_5_fu_671_p2)
);

myproject_mul_3ns_8s_11_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 11 ))
mul_3ns_8s_11_1_0_U417(
    .din0(mul_ln73_13_fu_673_p0),
    .din1(mul_ln73_13_fu_673_p1),
    .dout(mul_ln73_13_fu_673_p2)
);

myproject_mul_3ns_8ns_10_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 10 ))
mul_3ns_8ns_10_1_0_U418(
    .din0(mul_ln42_19_fu_674_p0),
    .din1(mul_ln42_19_fu_674_p1),
    .dout(mul_ln42_19_fu_674_p2)
);

myproject_mul_3ns_6s_9_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 9 ))
mul_3ns_6s_9_1_0_U419(
    .din0(mul_ln73_12_fu_675_p0),
    .din1(mul_ln73_12_fu_675_p1),
    .dout(mul_ln73_12_fu_675_p2)
);

myproject_mul_3ns_6s_9_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 9 ))
mul_3ns_6s_9_1_0_U420(
    .din0(mul_ln73_7_fu_676_p0),
    .din1(mul_ln73_7_fu_676_p1),
    .dout(mul_ln73_7_fu_676_p2)
);

myproject_mul_3ns_8ns_10_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 10 ))
mul_3ns_8ns_10_1_0_U421(
    .din0(mul_ln42_9_fu_678_p0),
    .din1(mul_ln42_9_fu_678_p1),
    .dout(mul_ln42_9_fu_678_p2)
);

myproject_mul_3ns_7s_10_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 10 ))
mul_3ns_7s_10_1_0_U422(
    .din0(mul_ln73_10_fu_679_p0),
    .din1(mul_ln73_10_fu_679_p1),
    .dout(mul_ln73_10_fu_679_p2)
);

myproject_mul_3ns_8ns_10_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 10 ))
mul_3ns_8ns_10_1_0_U423(
    .din0(mul_ln42_18_fu_680_p0),
    .din1(mul_ln42_18_fu_680_p1),
    .dout(mul_ln42_18_fu_680_p2)
);

myproject_mul_3ns_7ns_9_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 9 ))
mul_3ns_7ns_9_1_0_U424(
    .din0(mul_ln42_24_fu_681_p0),
    .din1(mul_ln42_24_fu_681_p1),
    .dout(mul_ln42_24_fu_681_p2)
);

myproject_mul_3ns_8ns_10_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 10 ))
mul_3ns_8ns_10_1_0_U425(
    .din0(mul_ln42_15_fu_682_p0),
    .din1(mul_ln42_15_fu_682_p1),
    .dout(mul_ln42_15_fu_682_p2)
);

myproject_mul_3ns_7s_10_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 10 ))
mul_3ns_7s_10_1_0_U426(
    .din0(mul_ln73_5_fu_683_p0),
    .din1(mul_ln73_5_fu_683_p1),
    .dout(mul_ln73_5_fu_683_p2)
);

myproject_mul_3ns_9ns_11_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 11 ))
mul_3ns_9ns_11_1_0_U427(
    .din0(mul_ln42_20_fu_684_p0),
    .din1(mul_ln42_20_fu_684_p1),
    .dout(mul_ln42_20_fu_684_p2)
);

myproject_mul_3ns_8s_11_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 11 ))
mul_3ns_8s_11_1_0_U428(
    .din0(mul_ln73_15_fu_685_p0),
    .din1(mul_ln73_15_fu_685_p1),
    .dout(mul_ln73_15_fu_685_p2)
);

myproject_mul_3ns_9ns_11_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 11 ))
mul_3ns_9ns_11_1_0_U429(
    .din0(mul_ln42_2_fu_686_p0),
    .din1(mul_ln42_2_fu_686_p1),
    .dout(mul_ln42_2_fu_686_p2)
);

myproject_mul_3ns_7ns_9_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 9 ))
mul_3ns_7ns_9_1_0_U430(
    .din0(mul_ln42_1_fu_687_p0),
    .din1(mul_ln42_1_fu_687_p1),
    .dout(mul_ln42_1_fu_687_p2)
);

myproject_mul_3ns_7ns_9_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 9 ))
mul_3ns_7ns_9_1_0_U431(
    .din0(mul_ln42_12_fu_689_p0),
    .din1(mul_ln42_12_fu_689_p1),
    .dout(mul_ln42_12_fu_689_p2)
);

myproject_mul_3ns_9s_12_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 12 ))
mul_3ns_9s_12_1_0_U432(
    .din0(mul_ln73_18_fu_692_p0),
    .din1(mul_ln73_18_fu_692_p1),
    .dout(mul_ln73_18_fu_692_p2)
);

myproject_mul_3ns_7s_10_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 10 ))
mul_3ns_7s_10_1_0_U433(
    .din0(mul_ln73_20_fu_693_p0),
    .din1(mul_ln73_20_fu_693_p1),
    .dout(mul_ln73_20_fu_693_p2)
);

myproject_mul_3ns_6s_9_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 9 ))
mul_3ns_6s_9_1_0_U434(
    .din0(mul_ln73_3_fu_694_p0),
    .din1(mul_ln73_3_fu_694_p1),
    .dout(mul_ln73_3_fu_694_p2)
);

myproject_mul_3ns_8s_11_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 11 ))
mul_3ns_8s_11_1_0_U435(
    .din0(mul_ln73_14_fu_697_p0),
    .din1(mul_ln73_14_fu_697_p1),
    .dout(mul_ln73_14_fu_697_p2)
);

myproject_mul_3ns_9s_12_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 12 ))
mul_3ns_9s_12_1_0_U436(
    .din0(mul_ln73_1_fu_699_p0),
    .din1(mul_ln73_1_fu_699_p1),
    .dout(mul_ln73_1_fu_699_p2)
);

myproject_mul_3ns_7ns_9_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 9 ))
mul_3ns_7ns_9_1_0_U437(
    .din0(mul_ln42_22_fu_701_p0),
    .din1(mul_ln42_22_fu_701_p1),
    .dout(mul_ln42_22_fu_701_p2)
);

myproject_mul_3ns_8ns_9_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 9 ))
mul_3ns_8ns_9_1_0_U438(
    .din0(mul_ln42_21_fu_702_p0),
    .din1(mul_ln42_21_fu_702_p1),
    .dout(mul_ln42_21_fu_702_p2)
);

myproject_mul_3ns_7s_10_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 10 ))
mul_3ns_7s_10_1_0_U439(
    .din0(mul_ln73_9_fu_704_p0),
    .din1(mul_ln73_9_fu_704_p1),
    .dout(mul_ln73_9_fu_704_p2)
);

myproject_mul_3ns_8ns_10_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 10 ))
mul_3ns_8ns_10_1_0_U440(
    .din0(mul_ln42_7_fu_705_p0),
    .din1(mul_ln42_7_fu_705_p1),
    .dout(mul_ln42_7_fu_705_p2)
);

myproject_mul_3ns_8s_11_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 11 ))
mul_3ns_8s_11_1_0_U441(
    .din0(mul_ln73_8_fu_706_p0),
    .din1(mul_ln73_8_fu_706_p1),
    .dout(mul_ln73_8_fu_706_p2)
);

myproject_mul_3ns_8s_11_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 11 ))
mul_3ns_8s_11_1_0_U442(
    .din0(mul_ln73_4_fu_707_p0),
    .din1(mul_ln73_4_fu_707_p1),
    .dout(mul_ln73_4_fu_707_p2)
);

myproject_mul_3ns_6s_9_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 9 ))
mul_3ns_6s_9_1_0_U443(
    .din0(mul_ln73_16_fu_708_p0),
    .din1(mul_ln73_16_fu_708_p1),
    .dout(mul_ln73_16_fu_708_p2)
);

myproject_mul_3ns_7ns_9_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 9 ))
mul_3ns_7ns_9_1_0_U444(
    .din0(mul_ln42_fu_709_p0),
    .din1(mul_ln42_fu_709_p1),
    .dout(mul_ln42_fu_709_p2)
);

myproject_mul_3ns_8ns_10_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 10 ))
mul_3ns_8ns_10_1_0_U445(
    .din0(mul_ln42_13_fu_712_p0),
    .din1(mul_ln42_13_fu_712_p1),
    .dout(mul_ln42_13_fu_712_p2)
);

myproject_mul_3ns_8ns_10_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 10 ))
mul_3ns_8ns_10_1_0_U446(
    .din0(mul_ln42_16_fu_713_p0),
    .din1(mul_ln42_16_fu_713_p1),
    .dout(mul_ln42_16_fu_713_p2)
);

myproject_mul_3ns_10s_13_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 13 ))
mul_3ns_10s_13_1_0_U447(
    .din0(mul_ln73_fu_714_p0),
    .din1(mul_ln73_fu_714_p1),
    .dout(mul_ln73_fu_714_p2)
);

myproject_mul_3ns_7s_10_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 10 ))
mul_3ns_7s_10_1_0_U448(
    .din0(mul_ln73_11_fu_715_p0),
    .din1(mul_ln73_11_fu_715_p1),
    .dout(mul_ln73_11_fu_715_p2)
);

myproject_mul_3ns_9ns_11_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 11 ))
mul_3ns_9ns_11_1_0_U449(
    .din0(mul_ln42_11_fu_716_p0),
    .din1(mul_ln42_11_fu_716_p1),
    .dout(mul_ln42_11_fu_716_p2)
);

myproject_mul_3ns_8ns_10_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 10 ))
mul_3ns_8ns_10_1_0_U450(
    .din0(mul_ln42_25_fu_718_p0),
    .din1(mul_ln42_25_fu_718_p1),
    .dout(mul_ln42_25_fu_718_p2)
);

myproject_mul_3ns_8s_11_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 11 ))
mul_3ns_8s_11_1_0_U451(
    .din0(mul_ln73_19_fu_719_p0),
    .din1(mul_ln73_19_fu_719_p1),
    .dout(mul_ln73_19_fu_719_p2)
);

myproject_mul_3ns_8ns_10_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 10 ))
mul_3ns_8ns_10_1_0_U452(
    .din0(mul_ln42_6_fu_721_p0),
    .din1(mul_ln42_6_fu_721_p1),
    .dout(mul_ln42_6_fu_721_p2)
);

myproject_mul_3ns_7s_10_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 10 ))
mul_3ns_7s_10_1_0_U453(
    .din0(mul_ln73_17_fu_722_p0),
    .din1(mul_ln73_17_fu_722_p1),
    .dout(mul_ln73_17_fu_722_p2)
);

myproject_mul_3ns_8s_11_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 11 ))
mul_3ns_8s_11_1_0_U454(
    .din0(mul_ln73_2_fu_723_p0),
    .din1(mul_ln73_2_fu_723_p1),
    .dout(mul_ln73_2_fu_723_p2)
);

myproject_mul_3ns_7ns_9_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 9 ))
mul_3ns_7ns_9_1_0_U455(
    .din0(mul_ln42_3_fu_724_p0),
    .din1(mul_ln42_3_fu_724_p1),
    .dout(mul_ln42_3_fu_724_p2)
);

myproject_mul_3ns_9ns_10_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 10 ))
mul_3ns_9ns_10_1_0_U456(
    .din0(mul_ln42_14_fu_725_p0),
    .din1(mul_ln42_14_fu_725_p1),
    .dout(mul_ln42_14_fu_725_p2)
);

myproject_mul_3ns_8ns_10_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 10 ))
mul_3ns_8ns_10_1_0_U457(
    .din0(mul_ln42_8_fu_727_p0),
    .din1(mul_ln42_8_fu_727_p1),
    .dout(mul_ln42_8_fu_727_p2)
);

myproject_mul_3ns_8ns_10_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 10 ))
mul_3ns_8ns_10_1_0_U458(
    .din0(mul_ln42_23_fu_728_p0),
    .din1(mul_ln42_23_fu_728_p1),
    .dout(mul_ln42_23_fu_728_p2)
);

myproject_mul_3ns_7ns_9_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 9 ))
mul_3ns_7ns_9_1_0_U459(
    .din0(mul_ln42_26_fu_729_p0),
    .din1(mul_ln42_26_fu_729_p1),
    .dout(mul_ln42_26_fu_729_p2)
);

myproject_mul_3ns_9ns_11_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 11 ))
mul_3ns_9ns_11_1_0_U460(
    .din0(mul_ln42_17_fu_730_p0),
    .din1(mul_ln42_17_fu_730_p1),
    .dout(mul_ln42_17_fu_730_p2)
);

myproject_mul_3ns_9ns_11_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 11 ))
mul_3ns_9ns_11_1_0_U461(
    .din0(mul_ln42_4_fu_731_p0),
    .din1(mul_ln42_4_fu_731_p1),
    .dout(mul_ln42_4_fu_731_p2)
);

always @ (posedge ap_clk) begin
    ap_ce_reg <= ap_ce;
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == 1'b1))) begin
        add_ln58_2420_reg_15321 <= add_ln58_2420_fu_14767_p2;
        add_ln58_2423_reg_15326 <= add_ln58_2423_fu_14789_p2;
        add_ln58_2427_reg_15331 <= add_ln58_2427_fu_14815_p2;
        add_ln58_2430_reg_15336 <= add_ln58_2430_fu_14841_p2;
        add_ln58_2433_reg_15341 <= add_ln58_2433_fu_14847_p2;
        add_ln58_2434_reg_15346 <= add_ln58_2434_fu_14853_p2;
        add_ln58_2438_reg_15351 <= add_ln58_2438_fu_14879_p2;
        add_ln58_2442_reg_15356 <= add_ln58_2442_fu_14901_p2;
        add_ln58_2445_reg_15361 <= add_ln58_2445_fu_14927_p2;
        add_ln58_2451_reg_15366 <= add_ln58_2451_fu_14953_p2;
        add_ln58_2454_reg_15371 <= add_ln58_2454_fu_14979_p2;
        add_ln58_2458_reg_15376 <= add_ln58_2458_fu_15005_p2;
        add_ln58_2461_reg_15381 <= add_ln58_2461_fu_15027_p2;
        add_ln58_2464_reg_15386 <= add_ln58_2464_fu_15033_p2;
        add_ln58_2469_reg_15391 <= add_ln58_2469_fu_15055_p2;
        add_ln58_2477_reg_15396 <= add_ln58_2477_fu_15117_p2;
        trunc_ln42_32_reg_15311 <= {{sub_ln42_1_fu_14487_p2[9:3]}};
        trunc_ln42_33_reg_15316 <= {{mul_ln73_17_fu_722_p2[9:3]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce_reg)) begin
        ap_return_int_reg <= add_ln58_2480_fu_15305_p2;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return = ap_return_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return = add_ln58_2480_fu_15305_p2;
    end else begin
        ap_return = 'bx;
    end
end

assign add_ln42_fu_13417_p2 = (zext_ln42_fu_13401_p1 + zext_ln42_1_fu_13413_p1);

assign add_ln58_2420_fu_14767_p2 = ($signed(zext_ln58_155_fu_14763_p1) + $signed(sext_ln70_fu_13389_p1));

assign add_ln58_2421_fu_14773_p2 = (zext_ln42_3_fu_13467_p1 + lshr_ln42_4_cast_fu_13476_p4);

assign add_ln58_2422_fu_14783_p2 = ($signed(sext_ln70_1_fu_13501_p1) + $signed(sext_ln70_2_fu_13520_p1));

assign add_ln58_2423_fu_14789_p2 = (add_ln58_2422_fu_14783_p2 + zext_ln58_156_fu_14779_p1);

assign add_ln58_2424_fu_15139_p2 = ($signed(sext_ln58_2214_fu_15136_p1) + $signed(sext_ln58_2213_fu_15133_p1));

assign add_ln58_2425_fu_14795_p2 = (zext_ln42_4_fu_13539_p1 + lshr_ln42_8_cast_fu_13548_p4);

assign add_ln58_2426_fu_14805_p2 = ($signed(sext_ln70_3_fu_13573_p1) + $signed(sext_ln70_4_fu_13592_p1));

assign add_ln58_2427_fu_14815_p2 = ($signed(sext_ln58_2215_fu_14811_p1) + $signed(zext_ln58_157_fu_14801_p1));

assign add_ln58_2428_fu_14821_p2 = ($signed(sext_ln70_5_fu_13611_p1) + $signed(sext_ln70_6_fu_13661_p1));

assign add_ln58_2429_fu_14831_p2 = ($signed(sext_ln70_7_fu_13680_p1) + $signed(zext_ln70_47_fu_13699_p1));

assign add_ln58_2430_fu_14841_p2 = ($signed(sext_ln58_2218_fu_14837_p1) + $signed(sext_ln58_2217_fu_14827_p1));

assign add_ln58_2431_fu_15151_p2 = ($signed(sext_ln58_2219_fu_15148_p1) + $signed(sext_ln58_2216_fu_15145_p1));

assign add_ln58_2432_fu_15161_p2 = ($signed(sext_ln58_2220_fu_15157_p1) + $signed(add_ln58_2424_fu_15139_p2));

assign add_ln58_2433_fu_14847_p2 = ($signed(zext_ln70_48_fu_13718_p1) + $signed(sext_ln70_8_fu_13762_p1));

assign add_ln58_2434_fu_14853_p2 = ($signed(sext_ln70_9_fu_13781_p1) + $signed(zext_ln70_49_fu_13829_p1));

assign add_ln58_2435_fu_15174_p2 = ($signed(add_ln58_2434_reg_15346) + $signed(sext_ln58_2222_fu_15171_p1));

assign add_ln58_2436_fu_14859_p2 = ($signed(sext_ln70_11_fu_13848_p1) + $signed(zext_ln70_50_fu_13867_p1));

assign add_ln58_2437_fu_14869_p2 = ($signed(sext_ln70_12_fu_13886_p1) + $signed(sext_ln70_13_fu_13905_p1));

assign add_ln58_2438_fu_14879_p2 = ($signed(sext_ln58_2224_fu_14875_p1) + $signed(sext_ln58_2223_fu_14865_p1));

assign add_ln58_2439_fu_15182_p2 = ($signed(sext_ln58_2225_fu_15179_p1) + $signed(add_ln58_2435_fu_15174_p2));

assign add_ln58_2440_fu_14885_p2 = ($signed(zext_ln70_51_fu_13924_p1) + $signed(sext_ln70_14_fu_13968_p1));

assign add_ln58_2441_fu_14895_p2 = ($signed(sext_ln70_15_fu_13987_p1) + $signed(zext_ln42_7_fu_14006_p1));

assign add_ln58_2442_fu_14901_p2 = ($signed(add_ln58_2441_fu_14895_p2) + $signed(sext_ln58_2226_fu_14891_p1));

assign add_ln58_2443_fu_14907_p2 = ($signed(zext_ln70_52_fu_14025_p1) + $signed(sext_ln70_16_fu_14044_p1));

assign add_ln58_2444_fu_14917_p2 = ($signed(zext_ln70_53_fu_14063_p1) + $signed(sext_ln70_17_fu_14095_p1));

assign add_ln58_2445_fu_14927_p2 = ($signed(sext_ln58_2229_fu_14923_p1) + $signed(sext_ln58_2228_fu_14913_p1));

assign add_ln58_2446_fu_15194_p2 = ($signed(sext_ln58_2230_fu_15191_p1) + $signed(sext_ln58_2227_fu_15188_p1));

assign add_ln58_2447_fu_15204_p2 = ($signed(sext_ln58_2231_fu_15200_p1) + $signed(add_ln58_2439_fu_15182_p2));

assign add_ln58_2448_fu_15210_p2 = ($signed(add_ln58_2447_fu_15204_p2) + $signed(sext_ln58_2221_fu_15167_p1));

assign add_ln58_2449_fu_14933_p2 = ($signed(sext_ln70_18_fu_14114_p1) + $signed(sext_ln70_19_fu_14133_p1));

assign add_ln58_2450_fu_14943_p2 = ($signed(zext_ln70_54_fu_14152_p1) + $signed(sext_ln70_20_fu_14196_p1));

assign add_ln58_2451_fu_14953_p2 = ($signed(sext_ln58_2234_fu_14949_p1) + $signed(sext_ln58_2233_fu_14939_p1));

assign add_ln58_2452_fu_14959_p2 = (zext_ln42_9_fu_14215_p1 + zext_ln42_11_fu_14234_p1);

assign add_ln58_2453_fu_14969_p2 = (zext_ln42_12_fu_14253_p1 + zext_ln42_13_fu_14272_p1);

assign add_ln58_2454_fu_14979_p2 = (zext_ln58_159_fu_14975_p1 + zext_ln58_158_fu_14965_p1);

assign add_ln58_2455_fu_15226_p2 = ($signed(zext_ln58_160_fu_15223_p1) + $signed(sext_ln58_2235_fu_15220_p1));

assign add_ln58_2456_fu_14985_p2 = (trunc_ln42_27_fu_14281_p4 + lshr_ln42_40_cast_cast_fu_14306_p1);

assign add_ln58_2457_fu_14995_p2 = ($signed(sext_ln70_21_fu_14325_p1) + $signed(zext_ln70_55_fu_14344_p1));

assign add_ln58_2458_fu_15005_p2 = ($signed(sext_ln58_2237_fu_15001_p1) + $signed(zext_ln58_161_fu_14991_p1));

assign add_ln58_2459_fu_15011_p2 = ($signed(sext_ln70_22_fu_14363_p1) + $signed(zext_ln70_56_fu_14390_p1));

assign add_ln58_2460_fu_15017_p2 = ($signed(zext_ln70_57_fu_14402_p1) + $signed(sext_ln42_fu_14421_p1));

assign add_ln58_2461_fu_15027_p2 = ($signed(sext_ln58_2239_fu_15023_p1) + $signed(add_ln58_2459_fu_15011_p2));

assign add_ln58_2462_fu_15242_p2 = ($signed(sext_ln58_2240_fu_15239_p1) + $signed(sext_ln58_2238_fu_15236_p1));

assign add_ln58_2463_fu_15252_p2 = ($signed(sext_ln58_2241_fu_15248_p1) + $signed(sext_ln58_2236_fu_15232_p1));

assign add_ln58_2464_fu_15033_p2 = (zext_ln42_15_fu_14440_p1 + zext_ln42_16_fu_14459_p1);

assign add_ln58_2465_fu_15265_p2 = ($signed(zext_ln70_58_fu_15126_p1) + $signed(sext_ln70_24_fu_15130_p1));

assign add_ln58_2466_fu_15271_p2 = (add_ln58_2465_fu_15265_p2 + zext_ln58_162_fu_15262_p1);

assign add_ln58_2467_fu_15039_p2 = ($signed(zext_ln70_59_fu_14533_p1) + $signed(sext_ln70_25_fu_14552_p1));

assign add_ln58_2468_fu_15045_p2 = ($signed(sext_ln70_26_fu_14571_p1) + $signed(sext_ln70_27_fu_14621_p1));

assign add_ln58_2469_fu_15055_p2 = ($signed(sext_ln58_2243_fu_15051_p1) + $signed(add_ln58_2467_fu_15039_p2));

assign add_ln58_2470_fu_15280_p2 = ($signed(sext_ln58_2244_fu_15277_p1) + $signed(add_ln58_2466_fu_15271_p2));

assign add_ln58_2471_fu_15061_p2 = (zext_ln42_19_fu_14640_p1 + zext_ln42_20_fu_14652_p1);

assign add_ln58_2472_fu_15071_p2 = (zext_ln42_21_fu_14671_p1 + zext_ln42_23_fu_14711_p1);

assign add_ln58_2473_fu_15077_p2 = (add_ln58_2472_fu_15071_p2 + zext_ln58_163_fu_15067_p1);

assign add_ln58_2474_fu_15087_p2 = ($signed(zext_ln70_60_fu_14730_p1) + $signed(sext_ln58_fu_14749_p1));

assign add_ln58_2475_fu_15097_p2 = ($signed(zext_ln58_fu_14753_p1) + $signed(10'd526));

assign add_ln58_2476_fu_15107_p2 = ($signed(sext_ln58_2247_fu_15103_p1) + $signed(sext_ln58_2246_fu_15093_p1));

assign add_ln58_2477_fu_15117_p2 = ($signed(sext_ln58_2248_fu_15113_p1) + $signed(zext_ln58_164_fu_15083_p1));

assign add_ln58_2478_fu_15293_p2 = ($signed(sext_ln58_2249_fu_15290_p1) + $signed(sext_ln58_2245_fu_15286_p1));

assign add_ln58_2479_fu_15299_p2 = ($signed(add_ln58_2478_fu_15293_p2) + $signed(sext_ln58_2242_fu_15258_p1));

assign add_ln58_2480_fu_15305_p2 = ($signed(add_ln58_2479_fu_15299_p2) + $signed(sext_ln58_2232_fu_15216_p1));

assign add_ln58_fu_14757_p2 = (trunc_ln42_1_fu_13423_p4 + zext_ln42_2_fu_13448_p1);

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign lshr_ln42_10_fu_14523_p4 = {{mul_ln42_23_fu_728_p2[9:3]}};

assign lshr_ln42_11_fu_14661_p4 = {{mul_ln42_25_fu_718_p2[9:3]}};

assign lshr_ln42_12_fu_14720_p4 = {{mul_ln42_26_fu_729_p2[8:3]}};

assign lshr_ln42_1_fu_13708_p4 = {{mul_ln42_6_fu_721_p2[9:3]}};

assign lshr_ln42_2_fu_13857_p4 = {{mul_ln42_7_fu_705_p2[9:3]}};

assign lshr_ln42_3_fu_13914_p4 = {{mul_ln42_8_fu_727_p2[9:3]}};

assign lshr_ln42_40_cast_cast_fu_14306_p1 = lshr_ln42_40_cast_fu_14296_p4;

assign lshr_ln42_40_cast_fu_14296_p4 = {{mul_ln42_18_fu_680_p2[9:3]}};

assign lshr_ln42_4_cast_fu_13476_p4 = {{mul_ln42_2_fu_686_p2[10:3]}};

assign lshr_ln42_4_fu_13996_p4 = {{mul_ln42_9_fu_678_p2[9:3]}};

assign lshr_ln42_5_fu_14015_p4 = {{mul_ln42_10_fu_669_p2[8:3]}};

assign lshr_ln42_6_fu_14053_p4 = {{mul_ln42_11_fu_716_p2[10:3]}};

assign lshr_ln42_7_fu_14142_p4 = {{mul_ln42_12_fu_689_p2[8:3]}};

assign lshr_ln42_8_cast_fu_13548_p4 = {{mul_ln42_4_fu_731_p2[10:3]}};

assign lshr_ln42_8_fu_14334_p4 = {{mul_ln42_19_fu_674_p2[9:3]}};

assign lshr_ln42_9_fu_14380_p4 = {{mul_ln42_20_fu_684_p2[10:3]}};

assign lshr_ln42_s_fu_13689_p4 = {{mul_ln42_5_fu_671_p2[10:3]}};

assign mul_ln42_10_fu_669_p0 = mul_ln42_10_fu_669_p00;

assign mul_ln42_10_fu_669_p00 = data_27_val;

assign mul_ln42_10_fu_669_p1 = 9'd73;

assign mul_ln42_11_fu_716_p0 = mul_ln42_11_fu_716_p00;

assign mul_ln42_11_fu_716_p00 = data_29_val;

assign mul_ln42_11_fu_716_p1 = 11'd176;

assign mul_ln42_12_fu_689_p0 = mul_ln42_12_fu_689_p00;

assign mul_ln42_12_fu_689_p00 = data_34_val;

assign mul_ln42_12_fu_689_p1 = 9'd50;

assign mul_ln42_13_fu_712_p0 = mul_ln42_13_fu_712_p00;

assign mul_ln42_13_fu_712_p00 = data_36_val;

assign mul_ln42_13_fu_712_p1 = 10'd94;

assign mul_ln42_14_fu_725_p0 = mul_ln42_14_fu_725_p00;

assign mul_ln42_14_fu_725_p00 = data_37_val;

assign mul_ln42_14_fu_725_p1 = 10'd135;

assign mul_ln42_15_fu_682_p0 = mul_ln42_15_fu_682_p00;

assign mul_ln42_15_fu_682_p00 = data_38_val;

assign mul_ln42_15_fu_682_p1 = 10'd104;

assign mul_ln42_16_fu_713_p0 = mul_ln42_16_fu_713_p00;

assign mul_ln42_16_fu_713_p00 = data_40_val;

assign mul_ln42_16_fu_713_p1 = 10'd106;

assign mul_ln42_17_fu_730_p0 = mul_ln42_17_fu_730_p00;

assign mul_ln42_17_fu_730_p00 = data_41_val;

assign mul_ln42_17_fu_730_p1 = 11'd173;

assign mul_ln42_18_fu_680_p0 = mul_ln42_18_fu_680_p00;

assign mul_ln42_18_fu_680_p00 = data_42_val;

assign mul_ln42_18_fu_680_p1 = 10'd107;

assign mul_ln42_19_fu_674_p0 = mul_ln42_19_fu_674_p00;

assign mul_ln42_19_fu_674_p00 = data_44_val;

assign mul_ln42_19_fu_674_p1 = 10'd113;

assign mul_ln42_1_fu_687_p0 = mul_ln42_1_fu_687_p00;

assign mul_ln42_1_fu_687_p00 = data_3_val;

assign mul_ln42_1_fu_687_p1 = 9'd45;

assign mul_ln42_20_fu_684_p0 = mul_ln42_20_fu_684_p00;

assign mul_ln42_20_fu_684_p00 = data_47_val;

assign mul_ln42_20_fu_684_p1 = 11'd190;

assign mul_ln42_21_fu_702_p0 = mul_ln42_21_fu_702_p00;

assign mul_ln42_21_fu_702_p00 = data_50_val;

assign mul_ln42_21_fu_702_p1 = 9'd69;

assign mul_ln42_22_fu_701_p0 = mul_ln42_22_fu_701_p00;

assign mul_ln42_22_fu_701_p00 = data_51_val;

assign mul_ln42_22_fu_701_p1 = 9'd37;

assign mul_ln42_23_fu_728_p0 = mul_ln42_23_fu_728_p00;

assign mul_ln42_23_fu_728_p00 = data_54_val;

assign mul_ln42_23_fu_728_p1 = 10'd100;

assign mul_ln42_24_fu_681_p0 = mul_ln42_24_fu_681_p00;

assign mul_ln42_24_fu_681_p00 = data_58_val;

assign mul_ln42_24_fu_681_p1 = 9'd55;

assign mul_ln42_25_fu_718_p0 = mul_ln42_25_fu_718_p00;

assign mul_ln42_25_fu_718_p00 = data_60_val;

assign mul_ln42_25_fu_718_p1 = 10'd123;

assign mul_ln42_26_fu_729_p0 = mul_ln42_26_fu_729_p00;

assign mul_ln42_26_fu_729_p00 = data_62_val;

assign mul_ln42_26_fu_729_p1 = 9'd54;

assign mul_ln42_2_fu_686_p0 = mul_ln42_2_fu_686_p00;

assign mul_ln42_2_fu_686_p00 = data_4_val;

assign mul_ln42_2_fu_686_p1 = 11'd187;

assign mul_ln42_3_fu_724_p0 = mul_ln42_3_fu_724_p00;

assign mul_ln42_3_fu_724_p00 = data_7_val;

assign mul_ln42_3_fu_724_p1 = 9'd43;

assign mul_ln42_4_fu_731_p0 = mul_ln42_4_fu_731_p00;

assign mul_ln42_4_fu_731_p00 = data_8_val;

assign mul_ln42_4_fu_731_p1 = 11'd149;

assign mul_ln42_5_fu_671_p0 = mul_ln42_5_fu_671_p00;

assign mul_ln42_5_fu_671_p00 = data_14_val;

assign mul_ln42_5_fu_671_p1 = 11'd173;

assign mul_ln42_6_fu_721_p0 = mul_ln42_6_fu_721_p00;

assign mul_ln42_6_fu_721_p00 = data_15_val;

assign mul_ln42_6_fu_721_p1 = 10'd88;

assign mul_ln42_7_fu_705_p0 = mul_ln42_7_fu_705_p00;

assign mul_ln42_7_fu_705_p00 = data_20_val;

assign mul_ln42_7_fu_705_p1 = 10'd110;

assign mul_ln42_8_fu_727_p0 = mul_ln42_8_fu_727_p00;

assign mul_ln42_8_fu_727_p00 = data_23_val;

assign mul_ln42_8_fu_727_p1 = 10'd100;

assign mul_ln42_9_fu_678_p0 = mul_ln42_9_fu_678_p00;

assign mul_ln42_9_fu_678_p00 = data_26_val;

assign mul_ln42_9_fu_678_p1 = 10'd101;

assign mul_ln42_fu_709_p0 = mul_ln42_fu_709_p00;

assign mul_ln42_fu_709_p00 = data_2_val;

assign mul_ln42_fu_709_p1 = 9'd57;

assign mul_ln73_10_fu_679_p0 = mul_ln73_10_fu_679_p00;

assign mul_ln73_10_fu_679_p00 = data_25_val;

assign mul_ln73_10_fu_679_p1 = 10'd983;

assign mul_ln73_11_fu_715_p0 = mul_ln73_11_fu_715_p00;

assign mul_ln73_11_fu_715_p00 = data_28_val;

assign mul_ln73_11_fu_715_p1 = 10'd987;

assign mul_ln73_12_fu_675_p0 = mul_ln73_12_fu_675_p00;

assign mul_ln73_12_fu_675_p00 = data_31_val;

assign mul_ln73_12_fu_675_p1 = 9'd493;

assign mul_ln73_13_fu_673_p0 = mul_ln73_13_fu_673_p00;

assign mul_ln73_13_fu_673_p00 = data_32_val;

assign mul_ln73_13_fu_673_p1 = 11'd1978;

assign mul_ln73_14_fu_697_p0 = mul_ln73_14_fu_697_p00;

assign mul_ln73_14_fu_697_p00 = data_43_val;

assign mul_ln73_14_fu_697_p1 = 11'd1946;

assign mul_ln73_15_fu_685_p0 = mul_ln73_15_fu_685_p00;

assign mul_ln73_15_fu_685_p00 = data_45_val;

assign mul_ln73_15_fu_685_p1 = 11'd1935;

assign mul_ln73_16_fu_708_p0 = mul_ln73_16_fu_708_p00;

assign mul_ln73_16_fu_708_p00 = data_49_val;

assign mul_ln73_16_fu_708_p1 = 9'd491;

assign mul_ln73_17_fu_722_p0 = mul_ln73_17_fu_722_p00;

assign mul_ln73_17_fu_722_p00 = data_53_val;

assign mul_ln73_17_fu_722_p1 = 10'd970;

assign mul_ln73_18_fu_692_p0 = mul_ln73_18_fu_692_p00;

assign mul_ln73_18_fu_692_p00 = data_55_val;

assign mul_ln73_18_fu_692_p1 = 12'd3920;

assign mul_ln73_19_fu_719_p0 = mul_ln73_19_fu_719_p00;

assign mul_ln73_19_fu_719_p00 = data_56_val;

assign mul_ln73_19_fu_719_p1 = 11'd1967;

assign mul_ln73_1_fu_699_p0 = mul_ln73_1_fu_699_p00;

assign mul_ln73_1_fu_699_p00 = data_6_val;

assign mul_ln73_1_fu_699_p1 = 12'd3928;

assign mul_ln73_20_fu_693_p0 = mul_ln73_20_fu_693_p00;

assign mul_ln73_20_fu_693_p00 = data_63_val;

assign mul_ln73_20_fu_693_p1 = 10'd969;

assign mul_ln73_2_fu_723_p0 = mul_ln73_2_fu_723_p00;

assign mul_ln73_2_fu_723_p00 = data_9_val;

assign mul_ln73_2_fu_723_p1 = 11'd1944;

assign mul_ln73_3_fu_694_p0 = mul_ln73_3_fu_694_p00;

assign mul_ln73_3_fu_694_p00 = data_10_val;

assign mul_ln73_3_fu_694_p1 = 9'd493;

assign mul_ln73_4_fu_707_p0 = mul_ln73_4_fu_707_p00;

assign mul_ln73_4_fu_707_p00 = data_11_val;

assign mul_ln73_4_fu_707_p1 = 11'd1962;

assign mul_ln73_5_fu_683_p0 = mul_ln73_5_fu_683_p00;

assign mul_ln73_5_fu_683_p00 = data_13_val;

assign mul_ln73_5_fu_683_p1 = 10'd982;

assign mul_ln73_6_fu_670_p0 = mul_ln73_6_fu_670_p00;

assign mul_ln73_6_fu_670_p00 = data_17_val;

assign mul_ln73_6_fu_670_p1 = 12'd3950;

assign mul_ln73_7_fu_676_p0 = mul_ln73_7_fu_676_p00;

assign mul_ln73_7_fu_676_p00 = data_19_val;

assign mul_ln73_7_fu_676_p1 = 9'd483;

assign mul_ln73_8_fu_706_p0 = mul_ln73_8_fu_706_p00;

assign mul_ln73_8_fu_706_p00 = data_21_val;

assign mul_ln73_8_fu_706_p1 = 11'd1975;

assign mul_ln73_9_fu_704_p0 = mul_ln73_9_fu_704_p00;

assign mul_ln73_9_fu_704_p00 = data_22_val;

assign mul_ln73_9_fu_704_p1 = 10'd977;

assign mul_ln73_fu_714_p0 = mul_ln73_fu_714_p00;

assign mul_ln73_fu_714_p00 = data_5_val;

assign mul_ln73_fu_714_p1 = 13'd7815;

assign sext_ln42_1_fu_14707_p1 = $signed(trunc_ln42_38_fu_14697_p4);

assign sext_ln42_fu_14421_p1 = $signed(trunc_ln42_30_fu_14411_p4);

assign sext_ln58_2213_fu_15133_p1 = $signed(add_ln58_2420_reg_15321);

assign sext_ln58_2214_fu_15136_p1 = $signed(add_ln58_2423_reg_15326);

assign sext_ln58_2215_fu_14811_p1 = $signed(add_ln58_2426_fu_14805_p2);

assign sext_ln58_2216_fu_15145_p1 = $signed(add_ln58_2427_reg_15331);

assign sext_ln58_2217_fu_14827_p1 = $signed(add_ln58_2428_fu_14821_p2);

assign sext_ln58_2218_fu_14837_p1 = $signed(add_ln58_2429_fu_14831_p2);

assign sext_ln58_2219_fu_15148_p1 = $signed(add_ln58_2430_reg_15336);

assign sext_ln58_2220_fu_15157_p1 = $signed(add_ln58_2431_fu_15151_p2);

assign sext_ln58_2221_fu_15167_p1 = $signed(add_ln58_2432_fu_15161_p2);

assign sext_ln58_2222_fu_15171_p1 = $signed(add_ln58_2433_reg_15341);

assign sext_ln58_2223_fu_14865_p1 = $signed(add_ln58_2436_fu_14859_p2);

assign sext_ln58_2224_fu_14875_p1 = $signed(add_ln58_2437_fu_14869_p2);

assign sext_ln58_2225_fu_15179_p1 = $signed(add_ln58_2438_reg_15351);

assign sext_ln58_2226_fu_14891_p1 = $signed(add_ln58_2440_fu_14885_p2);

assign sext_ln58_2227_fu_15188_p1 = $signed(add_ln58_2442_reg_15356);

assign sext_ln58_2228_fu_14913_p1 = $signed(add_ln58_2443_fu_14907_p2);

assign sext_ln58_2229_fu_14923_p1 = $signed(add_ln58_2444_fu_14917_p2);

assign sext_ln58_2230_fu_15191_p1 = $signed(add_ln58_2445_reg_15361);

assign sext_ln58_2231_fu_15200_p1 = $signed(add_ln58_2446_fu_15194_p2);

assign sext_ln58_2232_fu_15216_p1 = $signed(add_ln58_2448_fu_15210_p2);

assign sext_ln58_2233_fu_14939_p1 = $signed(add_ln58_2449_fu_14933_p2);

assign sext_ln58_2234_fu_14949_p1 = $signed(add_ln58_2450_fu_14943_p2);

assign sext_ln58_2235_fu_15220_p1 = $signed(add_ln58_2451_reg_15366);

assign sext_ln58_2236_fu_15232_p1 = $signed(add_ln58_2455_fu_15226_p2);

assign sext_ln58_2237_fu_15001_p1 = $signed(add_ln58_2457_fu_14995_p2);

assign sext_ln58_2238_fu_15236_p1 = $signed(add_ln58_2458_reg_15376);

assign sext_ln58_2239_fu_15023_p1 = $signed(add_ln58_2460_fu_15017_p2);

assign sext_ln58_2240_fu_15239_p1 = $signed(add_ln58_2461_reg_15381);

assign sext_ln58_2241_fu_15248_p1 = $signed(add_ln58_2462_fu_15242_p2);

assign sext_ln58_2242_fu_15258_p1 = $signed(add_ln58_2463_fu_15252_p2);

assign sext_ln58_2243_fu_15051_p1 = $signed(add_ln58_2468_fu_15045_p2);

assign sext_ln58_2244_fu_15277_p1 = $signed(add_ln58_2469_reg_15391);

assign sext_ln58_2245_fu_15286_p1 = $signed(add_ln58_2470_fu_15280_p2);

assign sext_ln58_2246_fu_15093_p1 = $signed(add_ln58_2474_fu_15087_p2);

assign sext_ln58_2247_fu_15103_p1 = $signed(add_ln58_2475_fu_15097_p2);

assign sext_ln58_2248_fu_15113_p1 = $signed(add_ln58_2476_fu_15107_p2);

assign sext_ln58_2249_fu_15290_p1 = $signed(add_ln58_2477_reg_15396);

assign sext_ln58_fu_14749_p1 = $signed(trunc_ln42_39_fu_14739_p4);

assign sext_ln70_10_fu_13825_p1 = $signed(trunc_ln42_13_fu_13815_p4);

assign sext_ln70_11_fu_13848_p1 = $signed(trunc_ln42_14_fu_13838_p4);

assign sext_ln70_12_fu_13886_p1 = $signed(trunc_ln42_15_fu_13876_p4);

assign sext_ln70_13_fu_13905_p1 = $signed(trunc_ln42_16_fu_13895_p4);

assign sext_ln70_14_fu_13968_p1 = $signed(trunc_ln42_17_fu_13958_p4);

assign sext_ln70_15_fu_13987_p1 = $signed(trunc_ln42_18_fu_13977_p4);

assign sext_ln70_16_fu_14044_p1 = $signed(trunc_ln42_19_fu_14034_p4);

assign sext_ln70_17_fu_14095_p1 = $signed(trunc_ln42_20_fu_14085_p4);

assign sext_ln70_18_fu_14114_p1 = $signed(trunc_ln42_21_fu_14104_p4);

assign sext_ln70_19_fu_14133_p1 = $signed(trunc_ln42_22_fu_14123_p4);

assign sext_ln70_1_fu_13501_p1 = $signed(trunc_ln42_4_fu_13491_p4);

assign sext_ln70_20_fu_14196_p1 = $signed(trunc_ln42_23_fu_14186_p4);

assign sext_ln70_21_fu_14325_p1 = $signed(trunc_ln42_28_fu_14315_p4);

assign sext_ln70_22_fu_14363_p1 = $signed(trunc_ln42_29_fu_14353_p4);

assign sext_ln70_23_fu_15123_p1 = $signed(trunc_ln42_32_reg_15311);

assign sext_ln70_24_fu_15130_p1 = $signed(trunc_ln42_33_reg_15316);

assign sext_ln70_25_fu_14552_p1 = $signed(trunc_ln42_34_fu_14542_p4);

assign sext_ln70_26_fu_14571_p1 = $signed(trunc_ln42_35_fu_14561_p4);

assign sext_ln70_27_fu_14621_p1 = $signed(trunc_ln42_36_fu_14611_p4);

assign sext_ln70_2_fu_13520_p1 = $signed(trunc_ln42_5_fu_13510_p4);

assign sext_ln70_3_fu_13573_p1 = $signed(trunc_ln42_7_fu_13563_p4);

assign sext_ln70_4_fu_13592_p1 = $signed(trunc_ln42_8_fu_13582_p4);

assign sext_ln70_5_fu_13611_p1 = $signed(trunc_ln42_9_fu_13601_p4);

assign sext_ln70_6_fu_13661_p1 = $signed(trunc_ln42_s_fu_13651_p4);

assign sext_ln70_7_fu_13680_p1 = $signed(trunc_ln42_10_fu_13670_p4);

assign sext_ln70_8_fu_13762_p1 = $signed(trunc_ln42_11_fu_13752_p4);

assign sext_ln70_9_fu_13781_p1 = $signed(trunc_ln42_12_fu_13771_p4);

assign sext_ln70_fu_13389_p1 = $signed(trunc_ln_fu_13379_p4);

assign shl_ln1_fu_14367_p3 = {{data_46_val}, {1'd0}};

assign shl_ln42_1_fu_13393_p3 = {{data_1_val}, {6'd0}};

assign shl_ln42_2_fu_13405_p3 = {{data_1_val}, {4'd0}};

assign shl_ln42_3_fu_13785_p3 = {{data_18_val}, {7'd0}};

assign shl_ln42_4_fu_13797_p3 = {{data_18_val}, {2'd0}};

assign shl_ln42_5_fu_14394_p3 = {{data_48_val}, {1'd0}};

assign shl_ln42_6_fu_14463_p3 = {{data_52_val}, {6'd0}};

assign shl_ln42_7_fu_14475_p3 = {{data_52_val}, {3'd0}};

assign shl_ln42_8_fu_14644_p3 = {{data_59_val}, {2'd0}};

assign shl_ln42_9_fu_14679_p3 = {{data_61_val}, {3'd0}};

assign shl_ln73_1_fu_13633_p3 = {{data_12_val}, {2'd0}};

assign shl_ln73_2_fu_13722_p3 = {{data_16_val}, {7'd0}};

assign shl_ln73_3_fu_13734_p3 = {{data_16_val}, {5'd0}};

assign shl_ln73_4_fu_13928_p3 = {{data_24_val}, {4'd0}};

assign shl_ln73_5_fu_13940_p3 = {{data_24_val}, {1'd0}};

assign shl_ln73_6_fu_14067_p3 = {{data_30_val}, {5'd0}};

assign shl_ln73_7_fu_14156_p3 = {{data_35_val}, {7'd0}};

assign shl_ln73_8_fu_14168_p3 = {{data_35_val}, {3'd0}};

assign shl_ln73_9_fu_14575_p3 = {{data_57_val}, {5'd0}};

assign shl_ln73_s_fu_14593_p3 = {{data_57_val}, {1'd0}};

assign shl_ln_fu_13615_p3 = {{data_12_val}, {5'd0}};

assign sub_ln42_1_fu_14487_p2 = (zext_ln42_17_fu_14471_p1 - zext_ln42_18_fu_14483_p1);

assign sub_ln42_2_fu_14691_p2 = (zext_ln42_22_fu_14687_p1 - zext_ln70_44_fu_14675_p1);

assign sub_ln42_fu_13809_p2 = (zext_ln42_5_fu_13793_p1 - zext_ln42_6_fu_13805_p1);

assign sub_ln73_1_fu_13645_p2 = (sub_ln73_fu_13627_p2 - zext_ln73_1_fu_13641_p1);

assign sub_ln73_2_fu_13746_p2 = (zext_ln73_3_fu_13742_p1 - zext_ln73_2_fu_13730_p1);

assign sub_ln73_3_fu_13952_p2 = (zext_ln73_5_fu_13948_p1 - zext_ln73_4_fu_13936_p1);

assign sub_ln73_4_fu_14079_p2 = (9'd0 - zext_ln73_6_fu_14075_p1);

assign sub_ln73_5_fu_14180_p2 = (zext_ln73_8_fu_14176_p1 - zext_ln73_7_fu_14164_p1);

assign sub_ln73_6_fu_14587_p2 = (9'd0 - zext_ln73_9_fu_14583_p1);

assign sub_ln73_7_fu_14605_p2 = (sub_ln73_6_fu_14587_p2 - zext_ln73_10_fu_14601_p1);

assign sub_ln73_8_fu_13373_p2 = (zext_ln70_fu_13357_p1 - zext_ln73_11_fu_13369_p1);

assign sub_ln73_fu_13627_p2 = (9'd0 - zext_ln73_fu_13623_p1);

assign tmp_1_fu_14224_p4 = {{mul_ln42_14_fu_725_p2[9:3]}};

assign tmp_2_fu_14430_p4 = {{mul_ln42_21_fu_702_p2[8:3]}};

assign tmp_fu_13361_p3 = {{data_0_val}, {2'd0}};

assign trunc_ln42_10_fu_13670_p4 = {{mul_ln73_5_fu_683_p2[9:3]}};

assign trunc_ln42_11_fu_13752_p4 = {{sub_ln73_2_fu_13746_p2[10:3]}};

assign trunc_ln42_12_fu_13771_p4 = {{mul_ln73_6_fu_670_p2[11:3]}};

assign trunc_ln42_13_fu_13815_p4 = {{sub_ln42_fu_13809_p2[10:3]}};

assign trunc_ln42_14_fu_13838_p4 = {{mul_ln73_7_fu_676_p2[8:3]}};

assign trunc_ln42_15_fu_13876_p4 = {{mul_ln73_8_fu_706_p2[10:3]}};

assign trunc_ln42_16_fu_13895_p4 = {{mul_ln73_9_fu_704_p2[9:3]}};

assign trunc_ln42_17_fu_13958_p4 = {{sub_ln73_3_fu_13952_p2[7:3]}};

assign trunc_ln42_18_fu_13977_p4 = {{mul_ln73_10_fu_679_p2[9:3]}};

assign trunc_ln42_19_fu_14034_p4 = {{mul_ln73_11_fu_715_p2[9:3]}};

assign trunc_ln42_1_fu_13423_p4 = {{add_ln42_fu_13417_p2[9:3]}};

assign trunc_ln42_20_fu_14085_p4 = {{sub_ln73_4_fu_14079_p2[8:3]}};

assign trunc_ln42_21_fu_14104_p4 = {{mul_ln73_12_fu_675_p2[8:3]}};

assign trunc_ln42_22_fu_14123_p4 = {{mul_ln73_13_fu_673_p2[10:3]}};

assign trunc_ln42_23_fu_14186_p4 = {{sub_ln73_5_fu_14180_p2[10:3]}};

assign trunc_ln42_24_fu_14205_p4 = {{mul_ln42_13_fu_712_p2[9:3]}};

assign trunc_ln42_25_fu_14243_p4 = {{mul_ln42_15_fu_682_p2[9:3]}};

assign trunc_ln42_26_fu_14262_p4 = {{mul_ln42_16_fu_713_p2[9:3]}};

assign trunc_ln42_27_fu_14281_p4 = {{mul_ln42_17_fu_730_p2[10:3]}};

assign trunc_ln42_28_fu_14315_p4 = {{mul_ln73_14_fu_697_p2[10:3]}};

assign trunc_ln42_29_fu_14353_p4 = {{mul_ln73_15_fu_685_p2[10:3]}};

assign trunc_ln42_2_fu_13438_p4 = {{mul_ln42_fu_709_p2[8:3]}};

assign trunc_ln42_30_fu_14411_p4 = {{mul_ln73_16_fu_708_p2[8:3]}};

assign trunc_ln42_31_fu_14449_p4 = {{mul_ln42_22_fu_701_p2[8:3]}};

assign trunc_ln42_34_fu_14542_p4 = {{mul_ln73_18_fu_692_p2[11:3]}};

assign trunc_ln42_35_fu_14561_p4 = {{mul_ln73_19_fu_719_p2[10:3]}};

assign trunc_ln42_36_fu_14611_p4 = {{sub_ln73_7_fu_14605_p2[8:3]}};

assign trunc_ln42_37_fu_14630_p4 = {{mul_ln42_24_fu_681_p2[8:3]}};

assign trunc_ln42_38_fu_14697_p4 = {{sub_ln42_2_fu_14691_p2[6:3]}};

assign trunc_ln42_39_fu_14739_p4 = {{mul_ln73_20_fu_693_p2[9:3]}};

assign trunc_ln42_3_fu_13457_p4 = {{mul_ln42_1_fu_687_p2[8:3]}};

assign trunc_ln42_4_fu_13491_p4 = {{mul_ln73_fu_714_p2[12:3]}};

assign trunc_ln42_5_fu_13510_p4 = {{mul_ln73_1_fu_699_p2[11:3]}};

assign trunc_ln42_6_fu_13529_p4 = {{mul_ln42_3_fu_724_p2[8:3]}};

assign trunc_ln42_7_fu_13563_p4 = {{mul_ln73_2_fu_723_p2[10:3]}};

assign trunc_ln42_8_fu_13582_p4 = {{mul_ln73_3_fu_694_p2[8:3]}};

assign trunc_ln42_9_fu_13601_p4 = {{mul_ln73_4_fu_707_p2[10:3]}};

assign trunc_ln42_s_fu_13651_p4 = {{sub_ln73_1_fu_13645_p2[8:3]}};

assign trunc_ln_fu_13379_p4 = {{sub_ln73_8_fu_13373_p2[5:3]}};

assign zext_ln42_11_fu_14234_p1 = tmp_1_fu_14224_p4;

assign zext_ln42_12_fu_14253_p1 = trunc_ln42_25_fu_14243_p4;

assign zext_ln42_13_fu_14272_p1 = trunc_ln42_26_fu_14262_p4;

assign zext_ln42_15_fu_14440_p1 = tmp_2_fu_14430_p4;

assign zext_ln42_16_fu_14459_p1 = trunc_ln42_31_fu_14449_p4;

assign zext_ln42_17_fu_14471_p1 = shl_ln42_6_fu_14463_p3;

assign zext_ln42_18_fu_14483_p1 = shl_ln42_7_fu_14475_p3;

assign zext_ln42_19_fu_14640_p1 = trunc_ln42_37_fu_14630_p4;

assign zext_ln42_1_fu_13413_p1 = shl_ln42_2_fu_13405_p3;

assign zext_ln42_20_fu_14652_p1 = shl_ln42_8_fu_14644_p3;

assign zext_ln42_21_fu_14671_p1 = lshr_ln42_11_fu_14661_p4;

assign zext_ln42_22_fu_14687_p1 = shl_ln42_9_fu_14679_p3;

assign zext_ln42_23_fu_14711_p1 = $unsigned(sext_ln42_1_fu_14707_p1);

assign zext_ln42_2_fu_13448_p1 = trunc_ln42_2_fu_13438_p4;

assign zext_ln42_3_fu_13467_p1 = trunc_ln42_3_fu_13457_p4;

assign zext_ln42_4_fu_13539_p1 = trunc_ln42_6_fu_13529_p4;

assign zext_ln42_5_fu_13793_p1 = shl_ln42_3_fu_13785_p3;

assign zext_ln42_6_fu_13805_p1 = shl_ln42_4_fu_13797_p3;

assign zext_ln42_7_fu_14006_p1 = lshr_ln42_4_fu_13996_p4;

assign zext_ln42_9_fu_14215_p1 = trunc_ln42_24_fu_14205_p4;

assign zext_ln42_fu_13401_p1 = shl_ln42_1_fu_13393_p3;

assign zext_ln58_155_fu_14763_p1 = add_ln58_fu_14757_p2;

assign zext_ln58_156_fu_14779_p1 = add_ln58_2421_fu_14773_p2;

assign zext_ln58_157_fu_14801_p1 = add_ln58_2425_fu_14795_p2;

assign zext_ln58_158_fu_14965_p1 = add_ln58_2452_fu_14959_p2;

assign zext_ln58_159_fu_14975_p1 = add_ln58_2453_fu_14969_p2;

assign zext_ln58_160_fu_15223_p1 = add_ln58_2454_reg_15371;

assign zext_ln58_161_fu_14991_p1 = add_ln58_2456_fu_14985_p2;

assign zext_ln58_162_fu_15262_p1 = add_ln58_2464_reg_15386;

assign zext_ln58_163_fu_15067_p1 = add_ln58_2471_fu_15061_p2;

assign zext_ln58_164_fu_15083_p1 = add_ln58_2473_fu_15077_p2;

assign zext_ln58_fu_14753_p1 = shl_ln1_fu_14367_p3;

assign zext_ln70_44_fu_14675_p1 = data_61_val;

assign zext_ln70_47_fu_13699_p1 = lshr_ln42_s_fu_13689_p4;

assign zext_ln70_48_fu_13718_p1 = lshr_ln42_1_fu_13708_p4;

assign zext_ln70_49_fu_13829_p1 = $unsigned(sext_ln70_10_fu_13825_p1);

assign zext_ln70_50_fu_13867_p1 = lshr_ln42_2_fu_13857_p4;

assign zext_ln70_51_fu_13924_p1 = lshr_ln42_3_fu_13914_p4;

assign zext_ln70_52_fu_14025_p1 = lshr_ln42_5_fu_14015_p4;

assign zext_ln70_53_fu_14063_p1 = lshr_ln42_6_fu_14053_p4;

assign zext_ln70_54_fu_14152_p1 = lshr_ln42_7_fu_14142_p4;

assign zext_ln70_55_fu_14344_p1 = lshr_ln42_8_fu_14334_p4;

assign zext_ln70_56_fu_14390_p1 = lshr_ln42_9_fu_14380_p4;

assign zext_ln70_57_fu_14402_p1 = shl_ln42_5_fu_14394_p3;

assign zext_ln70_58_fu_15126_p1 = $unsigned(sext_ln70_23_fu_15123_p1);

assign zext_ln70_59_fu_14533_p1 = lshr_ln42_10_fu_14523_p4;

assign zext_ln70_60_fu_14730_p1 = lshr_ln42_12_fu_14720_p4;

assign zext_ln70_fu_13357_p1 = data_0_val;

assign zext_ln73_10_fu_14601_p1 = shl_ln73_s_fu_14593_p3;

assign zext_ln73_11_fu_13369_p1 = tmp_fu_13361_p3;

assign zext_ln73_1_fu_13641_p1 = shl_ln73_1_fu_13633_p3;

assign zext_ln73_2_fu_13730_p1 = shl_ln73_2_fu_13722_p3;

assign zext_ln73_3_fu_13742_p1 = shl_ln73_3_fu_13734_p3;

assign zext_ln73_4_fu_13936_p1 = shl_ln73_4_fu_13928_p3;

assign zext_ln73_5_fu_13948_p1 = shl_ln73_5_fu_13940_p3;

assign zext_ln73_6_fu_14075_p1 = shl_ln73_6_fu_14067_p3;

assign zext_ln73_7_fu_14164_p1 = shl_ln73_7_fu_14156_p3;

assign zext_ln73_8_fu_14176_p1 = shl_ln73_8_fu_14168_p3;

assign zext_ln73_9_fu_14583_p1 = shl_ln73_9_fu_14575_p3;

assign zext_ln73_fu_13623_p1 = shl_ln_fu_13615_p3;

endmodule //myproject_dense_latency_ap_ufixed_3_0_4_0_0_ap_fixed_16_8_5_3_0_config11_s
