// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_normalize_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_config13_s (
        ap_ready,
        data_0_val,
        data_1_val,
        data_2_val,
        data_3_val,
        data_4_val,
        data_5_val,
        data_6_val,
        data_7_val,
        data_8_val,
        data_9_val,
        data_10_val,
        data_11_val,
        data_12_val,
        data_13_val,
        data_14_val,
        data_15_val,
        data_16_val,
        data_17_val,
        data_18_val,
        data_19_val,
        data_20_val,
        data_21_val,
        data_22_val,
        data_23_val,
        data_24_val,
        data_25_val,
        data_26_val,
        data_27_val,
        data_28_val,
        data_29_val,
        data_30_val,
        data_31_val,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9,
        ap_return_10,
        ap_return_11,
        ap_return_12,
        ap_return_13,
        ap_return_14,
        ap_return_15,
        ap_return_16,
        ap_return_17,
        ap_return_18,
        ap_return_19,
        ap_return_20,
        ap_return_21,
        ap_return_22,
        ap_return_23,
        ap_return_24,
        ap_return_25,
        ap_return_26,
        ap_return_27,
        ap_return_28,
        ap_return_29,
        ap_return_30,
        ap_return_31
);


output   ap_ready;
input  [15:0] data_0_val;
input  [15:0] data_1_val;
input  [15:0] data_2_val;
input  [15:0] data_3_val;
input  [15:0] data_4_val;
input  [15:0] data_5_val;
input  [15:0] data_6_val;
input  [15:0] data_7_val;
input  [15:0] data_8_val;
input  [15:0] data_9_val;
input  [15:0] data_10_val;
input  [15:0] data_11_val;
input  [15:0] data_12_val;
input  [15:0] data_13_val;
input  [15:0] data_14_val;
input  [15:0] data_15_val;
input  [15:0] data_16_val;
input  [15:0] data_17_val;
input  [15:0] data_18_val;
input  [15:0] data_19_val;
input  [15:0] data_20_val;
input  [15:0] data_21_val;
input  [15:0] data_22_val;
input  [15:0] data_23_val;
input  [15:0] data_24_val;
input  [15:0] data_25_val;
input  [15:0] data_26_val;
input  [15:0] data_27_val;
input  [15:0] data_28_val;
input  [15:0] data_29_val;
input  [15:0] data_30_val;
input  [15:0] data_31_val;
output  [15:0] ap_return_0;
output  [15:0] ap_return_1;
output  [15:0] ap_return_2;
output  [15:0] ap_return_3;
output  [15:0] ap_return_4;
output  [15:0] ap_return_5;
output  [15:0] ap_return_6;
output  [15:0] ap_return_7;
output  [15:0] ap_return_8;
output  [15:0] ap_return_9;
output  [15:0] ap_return_10;
output  [15:0] ap_return_11;
output  [15:0] ap_return_12;
output  [15:0] ap_return_13;
output  [15:0] ap_return_14;
output  [15:0] ap_return_15;
output  [15:0] ap_return_16;
output  [15:0] ap_return_17;
output  [15:0] ap_return_18;
output  [15:0] ap_return_19;
output  [15:0] ap_return_20;
output  [15:0] ap_return_21;
output  [15:0] ap_return_22;
output  [15:0] ap_return_23;
output  [15:0] ap_return_24;
output  [15:0] ap_return_25;
output  [15:0] ap_return_26;
output  [15:0] ap_return_27;
output  [15:0] ap_return_28;
output  [15:0] ap_return_29;
output  [15:0] ap_return_30;
output  [15:0] ap_return_31;

wire   [14:0] trunc_ln_fu_286_p4;
wire   [14:0] trunc_ln54_s_fu_300_p4;
wire   [14:0] trunc_ln54_116_fu_314_p4;
wire   [12:0] trunc_ln54_117_fu_328_p4;
wire   [14:0] trunc_ln54_118_fu_342_p4;
wire   [14:0] trunc_ln54_119_fu_356_p4;
wire   [14:0] trunc_ln54_120_fu_370_p4;
wire   [14:0] trunc_ln54_121_fu_384_p4;
wire   [14:0] trunc_ln54_122_fu_398_p4;
wire   [14:0] trunc_ln54_123_fu_412_p4;
wire   [14:0] trunc_ln54_124_fu_426_p4;
wire   [14:0] trunc_ln54_125_fu_440_p4;
wire   [14:0] trunc_ln54_126_fu_454_p4;
wire   [14:0] trunc_ln54_127_fu_468_p4;
wire   [14:0] trunc_ln54_128_fu_482_p4;
wire   [14:0] trunc_ln54_129_fu_496_p4;
wire   [14:0] trunc_ln54_130_fu_510_p4;
wire   [14:0] trunc_ln54_131_fu_524_p4;
wire   [14:0] trunc_ln54_132_fu_538_p4;
wire   [12:0] trunc_ln54_133_fu_552_p4;
wire   [14:0] trunc_ln54_134_fu_566_p4;
wire   [14:0] trunc_ln54_135_fu_580_p4;
wire   [14:0] trunc_ln54_136_fu_594_p4;
wire   [13:0] trunc_ln54_137_fu_608_p4;
wire   [13:0] trunc_ln54_138_fu_622_p4;
wire   [14:0] trunc_ln54_139_fu_636_p4;
wire   [14:0] trunc_ln54_140_fu_650_p4;
wire  signed [15:0] sext_ln54_fu_296_p1;
wire  signed [15:0] sext_ln54_118_fu_310_p1;
wire  signed [15:0] sext_ln54_119_fu_324_p1;
wire  signed [15:0] sext_ln54_120_fu_338_p1;
wire  signed [15:0] sext_ln54_121_fu_352_p1;
wire  signed [15:0] sext_ln54_122_fu_366_p1;
wire  signed [15:0] sext_ln54_123_fu_380_p1;
wire  signed [15:0] sext_ln54_124_fu_394_p1;
wire  signed [15:0] sext_ln54_125_fu_408_p1;
wire  signed [15:0] sext_ln54_126_fu_422_p1;
wire  signed [15:0] sext_ln54_127_fu_436_p1;
wire  signed [15:0] sext_ln54_128_fu_450_p1;
wire  signed [15:0] sext_ln54_129_fu_464_p1;
wire  signed [15:0] sext_ln54_130_fu_478_p1;
wire  signed [15:0] sext_ln54_131_fu_492_p1;
wire  signed [15:0] sext_ln54_132_fu_506_p1;
wire  signed [15:0] sext_ln54_133_fu_520_p1;
wire  signed [15:0] sext_ln54_134_fu_534_p1;
wire  signed [15:0] sext_ln54_135_fu_548_p1;
wire  signed [15:0] sext_ln54_136_fu_562_p1;
wire  signed [15:0] sext_ln54_137_fu_576_p1;
wire  signed [15:0] sext_ln54_138_fu_590_p1;
wire  signed [15:0] sext_ln54_139_fu_604_p1;
wire  signed [15:0] sext_ln54_140_fu_618_p1;
wire  signed [15:0] sext_ln54_141_fu_632_p1;
wire  signed [15:0] sext_ln54_142_fu_646_p1;
wire  signed [15:0] sext_ln54_143_fu_660_p1;

assign ap_ready = 1'b1;

assign sext_ln54_118_fu_310_p1 = $signed(trunc_ln54_s_fu_300_p4);

assign sext_ln54_119_fu_324_p1 = $signed(trunc_ln54_116_fu_314_p4);

assign sext_ln54_120_fu_338_p1 = $signed(trunc_ln54_117_fu_328_p4);

assign sext_ln54_121_fu_352_p1 = $signed(trunc_ln54_118_fu_342_p4);

assign sext_ln54_122_fu_366_p1 = $signed(trunc_ln54_119_fu_356_p4);

assign sext_ln54_123_fu_380_p1 = $signed(trunc_ln54_120_fu_370_p4);

assign sext_ln54_124_fu_394_p1 = $signed(trunc_ln54_121_fu_384_p4);

assign sext_ln54_125_fu_408_p1 = $signed(trunc_ln54_122_fu_398_p4);

assign sext_ln54_126_fu_422_p1 = $signed(trunc_ln54_123_fu_412_p4);

assign sext_ln54_127_fu_436_p1 = $signed(trunc_ln54_124_fu_426_p4);

assign sext_ln54_128_fu_450_p1 = $signed(trunc_ln54_125_fu_440_p4);

assign sext_ln54_129_fu_464_p1 = $signed(trunc_ln54_126_fu_454_p4);

assign sext_ln54_130_fu_478_p1 = $signed(trunc_ln54_127_fu_468_p4);

assign sext_ln54_131_fu_492_p1 = $signed(trunc_ln54_128_fu_482_p4);

assign sext_ln54_132_fu_506_p1 = $signed(trunc_ln54_129_fu_496_p4);

assign sext_ln54_133_fu_520_p1 = $signed(trunc_ln54_130_fu_510_p4);

assign sext_ln54_134_fu_534_p1 = $signed(trunc_ln54_131_fu_524_p4);

assign sext_ln54_135_fu_548_p1 = $signed(trunc_ln54_132_fu_538_p4);

assign sext_ln54_136_fu_562_p1 = $signed(trunc_ln54_133_fu_552_p4);

assign sext_ln54_137_fu_576_p1 = $signed(trunc_ln54_134_fu_566_p4);

assign sext_ln54_138_fu_590_p1 = $signed(trunc_ln54_135_fu_580_p4);

assign sext_ln54_139_fu_604_p1 = $signed(trunc_ln54_136_fu_594_p4);

assign sext_ln54_140_fu_618_p1 = $signed(trunc_ln54_137_fu_608_p4);

assign sext_ln54_141_fu_632_p1 = $signed(trunc_ln54_138_fu_622_p4);

assign sext_ln54_142_fu_646_p1 = $signed(trunc_ln54_139_fu_636_p4);

assign sext_ln54_143_fu_660_p1 = $signed(trunc_ln54_140_fu_650_p4);

assign sext_ln54_fu_296_p1 = $signed(trunc_ln_fu_286_p4);

assign trunc_ln54_116_fu_314_p4 = {{data_2_val[15:1]}};

assign trunc_ln54_117_fu_328_p4 = {{data_3_val[15:3]}};

assign trunc_ln54_118_fu_342_p4 = {{data_4_val[15:1]}};

assign trunc_ln54_119_fu_356_p4 = {{data_5_val[15:1]}};

assign trunc_ln54_120_fu_370_p4 = {{data_6_val[15:1]}};

assign trunc_ln54_121_fu_384_p4 = {{data_7_val[15:1]}};

assign trunc_ln54_122_fu_398_p4 = {{data_10_val[15:1]}};

assign trunc_ln54_123_fu_412_p4 = {{data_11_val[15:1]}};

assign trunc_ln54_124_fu_426_p4 = {{data_12_val[15:1]}};

assign trunc_ln54_125_fu_440_p4 = {{data_13_val[15:1]}};

assign trunc_ln54_126_fu_454_p4 = {{data_14_val[15:1]}};

assign trunc_ln54_127_fu_468_p4 = {{data_15_val[15:1]}};

assign trunc_ln54_128_fu_482_p4 = {{data_16_val[15:1]}};

assign trunc_ln54_129_fu_496_p4 = {{data_17_val[15:1]}};

assign trunc_ln54_130_fu_510_p4 = {{data_18_val[15:1]}};

assign trunc_ln54_131_fu_524_p4 = {{data_21_val[15:1]}};

assign trunc_ln54_132_fu_538_p4 = {{data_22_val[15:1]}};

assign trunc_ln54_133_fu_552_p4 = {{data_23_val[15:3]}};

assign trunc_ln54_134_fu_566_p4 = {{data_24_val[15:1]}};

assign trunc_ln54_135_fu_580_p4 = {{data_25_val[15:1]}};

assign trunc_ln54_136_fu_594_p4 = {{data_26_val[15:1]}};

assign trunc_ln54_137_fu_608_p4 = {{data_27_val[15:2]}};

assign trunc_ln54_138_fu_622_p4 = {{data_28_val[15:2]}};

assign trunc_ln54_139_fu_636_p4 = {{data_29_val[15:1]}};

assign trunc_ln54_140_fu_650_p4 = {{data_30_val[15:1]}};

assign trunc_ln54_s_fu_300_p4 = {{data_1_val[15:1]}};

assign trunc_ln_fu_286_p4 = {{data_0_val[15:1]}};

assign ap_return_0 = sext_ln54_fu_296_p1;

assign ap_return_1 = sext_ln54_118_fu_310_p1;

assign ap_return_10 = sext_ln54_125_fu_408_p1;

assign ap_return_11 = sext_ln54_126_fu_422_p1;

assign ap_return_12 = sext_ln54_127_fu_436_p1;

assign ap_return_13 = sext_ln54_128_fu_450_p1;

assign ap_return_14 = sext_ln54_129_fu_464_p1;

assign ap_return_15 = sext_ln54_130_fu_478_p1;

assign ap_return_16 = sext_ln54_131_fu_492_p1;

assign ap_return_17 = sext_ln54_132_fu_506_p1;

assign ap_return_18 = sext_ln54_133_fu_520_p1;

assign ap_return_19 = data_19_val;

assign ap_return_2 = sext_ln54_119_fu_324_p1;

assign ap_return_20 = data_20_val;

assign ap_return_21 = sext_ln54_134_fu_534_p1;

assign ap_return_22 = sext_ln54_135_fu_548_p1;

assign ap_return_23 = sext_ln54_136_fu_562_p1;

assign ap_return_24 = sext_ln54_137_fu_576_p1;

assign ap_return_25 = sext_ln54_138_fu_590_p1;

assign ap_return_26 = sext_ln54_139_fu_604_p1;

assign ap_return_27 = sext_ln54_140_fu_618_p1;

assign ap_return_28 = sext_ln54_141_fu_632_p1;

assign ap_return_29 = sext_ln54_142_fu_646_p1;

assign ap_return_3 = sext_ln54_120_fu_338_p1;

assign ap_return_30 = sext_ln54_143_fu_660_p1;

assign ap_return_31 = data_31_val;

assign ap_return_4 = sext_ln54_121_fu_352_p1;

assign ap_return_5 = sext_ln54_122_fu_366_p1;

assign ap_return_6 = sext_ln54_123_fu_380_p1;

assign ap_return_7 = sext_ln54_124_fu_394_p1;

assign ap_return_8 = data_8_val;

assign ap_return_9 = data_9_val;

endmodule //myproject_normalize_ap_fixed_16_8_5_3_0_ap_fixed_16_8_5_3_0_config13_s
