# DDR clocks

####
### DDR4 c1
####

set_property -dict {PACKAGE_PIN AN13 IOSTANDARD POD12_DCI} [get_ports {c1_ddr4_dq[24]}]
set_property -dict {PACKAGE_PIN AM13 IOSTANDARD POD12_DCI} [get_ports {c1_ddr4_dq[26]}]
set_property -dict {PACKAGE_PIN AT13 IOSTANDARD DIFF_POD12_DCI} [get_ports {c1_ddr4_dqs_c[6]}]
set_property -dict {PACKAGE_PIN AT14 IOSTANDARD DIFF_POD12_DCI} [get_ports {c1_ddr4_dqs_t[6]}]
set_property -dict {PACKAGE_PIN AR13 IOSTANDARD POD12_DCI} [get_ports {c1_ddr4_dq[25]}]
set_property -dict {PACKAGE_PIN AP13 IOSTANDARD POD12_DCI} [get_ports {c1_ddr4_dq[27]}]
set_property -dict {PACKAGE_PIN AM14 IOSTANDARD POD12_DCI} [get_ports {c1_ddr4_dq[28]}]
set_property -dict {PACKAGE_PIN AL14 IOSTANDARD POD12_DCI} [get_ports {c1_ddr4_dq[30]}]
set_property -dict {PACKAGE_PIN AT15 IOSTANDARD POD12_DCI} [get_ports {c1_ddr4_dq[31]}]
set_property -dict {PACKAGE_PIN AR15 IOSTANDARD POD12_DCI} [get_ports {c1_ddr4_dq[29]}]
set_property -dict {PACKAGE_PIN AP14 IOSTANDARD DIFF_POD12_DCI} [get_ports {c1_ddr4_dqs_c[7]}]
set_property -dict {PACKAGE_PIN AN14 IOSTANDARD DIFF_POD12_DCI} [get_ports {c1_ddr4_dqs_t[7]}]
set_property -dict {PACKAGE_PIN AV13 IOSTANDARD POD12_DCI} [get_ports {c1_ddr4_dq[9]}]
set_property -dict {PACKAGE_PIN AU13 IOSTANDARD POD12_DCI} [get_ports {c1_ddr4_dq[8]}]
set_property -dict {PACKAGE_PIN AY15 IOSTANDARD DIFF_POD12_DCI} [get_ports {c1_ddr4_dqs_c[2]}]
set_property -dict {PACKAGE_PIN AW15 IOSTANDARD DIFF_POD12_DCI} [get_ports {c1_ddr4_dqs_t[2]}]
set_property -dict {PACKAGE_PIN AW13 IOSTANDARD POD12_DCI} [get_ports {c1_ddr4_dq[10]}]
set_property -dict {PACKAGE_PIN AW14 IOSTANDARD POD12_DCI} [get_ports {c1_ddr4_dq[11]}]
set_property -dict {PACKAGE_PIN AV14 IOSTANDARD POD12_DCI} [get_ports {c1_ddr4_dq[14]}]
set_property -dict {PACKAGE_PIN AU14 IOSTANDARD POD12_DCI} [get_ports {c1_ddr4_dq[12]}]
set_property -dict {PACKAGE_PIN BA11 IOSTANDARD POD12_DCI} [get_ports {c1_ddr4_dq[15]}]
set_property -dict {PACKAGE_PIN AY11 IOSTANDARD POD12_DCI} [get_ports {c1_ddr4_dq[13]}]
set_property -dict {PACKAGE_PIN AY12 IOSTANDARD DIFF_POD12_DCI} [get_ports {c1_ddr4_dqs_c[3]}]
set_property -dict {PACKAGE_PIN AY13 IOSTANDARD DIFF_POD12_DCI} [get_ports {c1_ddr4_dqs_t[3]}]
set_property -dict {PACKAGE_PIN BA13 IOSTANDARD POD12_DCI} [get_ports {c1_ddr4_dq[18]}]
set_property -dict {PACKAGE_PIN BA14 IOSTANDARD POD12_DCI} [get_ports {c1_ddr4_dq[19]}]
set_property -dict {PACKAGE_PIN BB10 IOSTANDARD DIFF_POD12_DCI} [get_ports {c1_ddr4_dqs_c[4]}]
set_property -dict {PACKAGE_PIN BB11 IOSTANDARD DIFF_POD12_DCI} [get_ports {c1_ddr4_dqs_t[4]}]
set_property -dict {PACKAGE_PIN BB12 IOSTANDARD POD12_DCI} [get_ports {c1_ddr4_dq[17]}]
set_property -dict {PACKAGE_PIN BA12 IOSTANDARD POD12_DCI} [get_ports {c1_ddr4_dq[16]}]
set_property -dict {PACKAGE_PIN BA7 IOSTANDARD POD12_DCI} [get_ports {c1_ddr4_dq[22]}]
set_property -dict {PACKAGE_PIN BA8 IOSTANDARD POD12_DCI} [get_ports {c1_ddr4_dq[23]}]
set_property -dict {PACKAGE_PIN BC9 IOSTANDARD POD12_DCI} [get_ports {c1_ddr4_dq[20]}]
set_property -dict {PACKAGE_PIN BB9 IOSTANDARD POD12_DCI} [get_ports {c1_ddr4_dq[21]}]
set_property -dict {PACKAGE_PIN BA9 IOSTANDARD DIFF_POD12_DCI} [get_ports {c1_ddr4_dqs_c[5]}]
set_property -dict {PACKAGE_PIN BA10 IOSTANDARD DIFF_POD12_DCI} [get_ports {c1_ddr4_dqs_t[5]}]
set_property -dict {PACKAGE_PIN BD7 IOSTANDARD POD12_DCI} [get_ports {c1_ddr4_dq[1]}]
set_property -dict {PACKAGE_PIN BC7 IOSTANDARD POD12_DCI} [get_ports {c1_ddr4_dq[2]}]
set_property -dict {PACKAGE_PIN BF9 IOSTANDARD DIFF_POD12_DCI} [get_ports {c1_ddr4_dqs_c[0]}]
set_property -dict {PACKAGE_PIN BF10 IOSTANDARD DIFF_POD12_DCI} [get_ports {c1_ddr4_dqs_t[0]}]
set_property -dict {PACKAGE_PIN BD8 IOSTANDARD POD12_DCI} [get_ports {c1_ddr4_dq[3]}]
set_property -dict {PACKAGE_PIN BD9 IOSTANDARD POD12_DCI} [get_ports {c1_ddr4_dq[0]}]
set_property -dict {PACKAGE_PIN BF7 IOSTANDARD POD12_DCI} [get_ports {c1_ddr4_dq[7]}]
set_property -dict {PACKAGE_PIN BE7 IOSTANDARD POD12_DCI} [get_ports {c1_ddr4_dq[6]}]
set_property -dict {PACKAGE_PIN BE10 IOSTANDARD POD12_DCI} [get_ports {c1_ddr4_dq[5]}]
set_property -dict {PACKAGE_PIN BD10 IOSTANDARD POD12_DCI} [get_ports {c1_ddr4_dq[4]}]
set_property -dict {PACKAGE_PIN BF8 IOSTANDARD DIFF_POD12_DCI} [get_ports {c1_ddr4_dqs_c[1]}]
set_property -dict {PACKAGE_PIN BE8 IOSTANDARD DIFF_POD12_DCI} [get_ports {c1_ddr4_dqs_t[1]}]
set_property -dict {PACKAGE_PIN AM15 IOSTANDARD POD12_DCI} [get_ports {c1_ddr4_dq[56]}]
set_property -dict {PACKAGE_PIN AL15 IOSTANDARD POD12_DCI} [get_ports {c1_ddr4_dq[57]}]
set_property -dict {PACKAGE_PIN AR16 IOSTANDARD DIFF_POD12_DCI} [get_ports {c1_ddr4_dqs_c[14]}]
set_property -dict {PACKAGE_PIN AP16 IOSTANDARD DIFF_POD12_DCI} [get_ports {c1_ddr4_dqs_t[14]}]
#set_property -dict {PACKAGE_PIN AN18 IOSTANDARD LVCMOS12       } [get_ports c1_ddr4_event_n  ]; # Bank 66 VCCO - VCC1V2 Net "DDR4_C1_EVENT_B"  - IO_T3U_N12_66
set_property -dict {PACKAGE_PIN AN16 IOSTANDARD POD12_DCI} [get_ports {c1_ddr4_dq[59]}]
set_property -dict {PACKAGE_PIN AN17 IOSTANDARD POD12_DCI} [get_ports {c1_ddr4_dq[58]}]
set_property -dict {PACKAGE_PIN AL16 IOSTANDARD POD12_DCI} [get_ports {c1_ddr4_dq[63]}]
set_property -dict {PACKAGE_PIN AL17 IOSTANDARD POD12_DCI} [get_ports {c1_ddr4_dq[62]}]
set_property -dict {PACKAGE_PIN AR18 IOSTANDARD POD12_DCI} [get_ports {c1_ddr4_dq[60]}]
set_property -dict {PACKAGE_PIN AP18 IOSTANDARD POD12_DCI} [get_ports {c1_ddr4_dq[61]}]
set_property -dict {PACKAGE_PIN AM16 IOSTANDARD DIFF_POD12_DCI} [get_ports {c1_ddr4_dqs_c[15]}]
set_property -dict {PACKAGE_PIN AM17 IOSTANDARD DIFF_POD12_DCI} [get_ports {c1_ddr4_dqs_t[15]}]
set_property -dict {PACKAGE_PIN AU16 IOSTANDARD POD12_DCI} [get_ports {c1_ddr4_dq[50]}]
set_property -dict {PACKAGE_PIN AU17 IOSTANDARD POD12_DCI} [get_ports {c1_ddr4_dq[51]}]
set_property -dict {PACKAGE_PIN AW18 IOSTANDARD DIFF_POD12_DCI} [get_ports {c1_ddr4_dqs_c[12]}]
set_property -dict {PACKAGE_PIN AV18 IOSTANDARD DIFF_POD12_DCI} [get_ports {c1_ddr4_dqs_t[12]}]
set_property -dict {PACKAGE_PIN AR17 IOSTANDARD LVCMOS12} [get_ports c1_ddr4_reset_n]
set_property -dict {PACKAGE_PIN AV16 IOSTANDARD POD12_DCI} [get_ports {c1_ddr4_dq[48]}]
set_property -dict {PACKAGE_PIN AV17 IOSTANDARD POD12_DCI} [get_ports {c1_ddr4_dq[49]}]
set_property -dict {PACKAGE_PIN AT17 IOSTANDARD POD12_DCI} [get_ports {c1_ddr4_dq[55]}]
set_property -dict {PACKAGE_PIN AT18 IOSTANDARD POD12_DCI} [get_ports {c1_ddr4_dq[54]}]
set_property -dict {PACKAGE_PIN BB16 IOSTANDARD POD12_DCI} [get_ports {c1_ddr4_dq[53]}]
set_property -dict {PACKAGE_PIN BB17 IOSTANDARD POD12_DCI} [get_ports {c1_ddr4_dq[52]}]
set_property -dict {PACKAGE_PIN AY16 IOSTANDARD DIFF_POD12_DCI} [get_ports {c1_ddr4_dqs_c[13]}]
set_property -dict {PACKAGE_PIN AW16 IOSTANDARD DIFF_POD12_DCI} [get_ports {c1_ddr4_dqs_t[13]}]
set_property -dict {PACKAGE_PIN AY17 IOSTANDARD POD12_DCI} [get_ports {c1_ddr4_dq[40]}]
set_property -dict {PACKAGE_PIN AY18 IOSTANDARD POD12_DCI} [get_ports {c1_ddr4_dq[42]}]
set_property -dict {PACKAGE_PIN BC12 IOSTANDARD DIFF_POD12_DCI} [get_ports {c1_ddr4_dqs_c[10]}]
set_property -dict {PACKAGE_PIN BC13 IOSTANDARD DIFF_POD12_DCI} [get_ports {c1_ddr4_dqs_t[10]}]
set_property -dict {PACKAGE_PIN BA17 IOSTANDARD POD12_DCI} [get_ports {c1_ddr4_dq[41]}]
set_property -dict {PACKAGE_PIN BA18 IOSTANDARD POD12_DCI} [get_ports {c1_ddr4_dq[43]}]
set_property -dict {PACKAGE_PIN BB15 IOSTANDARD POD12_DCI} [get_ports {c1_ddr4_dq[45]}]
set_property -dict {PACKAGE_PIN BA15 IOSTANDARD POD12_DCI} [get_ports {c1_ddr4_dq[44]}]
set_property -dict {PACKAGE_PIN BD11 IOSTANDARD POD12_DCI} [get_ports {c1_ddr4_dq[47]}]
set_property -dict {PACKAGE_PIN BC11 IOSTANDARD POD12_DCI} [get_ports {c1_ddr4_dq[46]}]
set_property -dict {PACKAGE_PIN BC14 IOSTANDARD DIFF_POD12_DCI} [get_ports {c1_ddr4_dqs_c[11]}]
set_property -dict {PACKAGE_PIN BB14 IOSTANDARD DIFF_POD12_DCI} [get_ports {c1_ddr4_dqs_t[11]}]
set_property -dict {PACKAGE_PIN BD13 IOSTANDARD POD12_DCI} [get_ports {c1_ddr4_dq[35]}]
set_property -dict {PACKAGE_PIN BD14 IOSTANDARD POD12_DCI} [get_ports {c1_ddr4_dq[33]}]
set_property -dict {PACKAGE_PIN BE11 IOSTANDARD DIFF_POD12_DCI} [get_ports {c1_ddr4_dqs_c[8]}]
set_property -dict {PACKAGE_PIN BE12 IOSTANDARD DIFF_POD12_DCI} [get_ports {c1_ddr4_dqs_t[8]}]
set_property -dict {PACKAGE_PIN BF12 IOSTANDARD POD12_DCI} [get_ports {c1_ddr4_dq[34]}]
set_property -dict {PACKAGE_PIN BE13 IOSTANDARD POD12_DCI} [get_ports {c1_ddr4_dq[32]}]
set_property -dict {PACKAGE_PIN BD15 IOSTANDARD POD12_DCI} [get_ports {c1_ddr4_dq[36]}]
set_property -dict {PACKAGE_PIN BD16 IOSTANDARD POD12_DCI} [get_ports {c1_ddr4_dq[37]}]
set_property -dict {PACKAGE_PIN BF13 IOSTANDARD POD12_DCI} [get_ports {c1_ddr4_dq[39]}]
set_property -dict {PACKAGE_PIN BF14 IOSTANDARD POD12_DCI} [get_ports {c1_ddr4_dq[38]}]
set_property -dict {PACKAGE_PIN BF15 IOSTANDARD DIFF_POD12_DCI} [get_ports {c1_ddr4_dqs_c[9]}]
set_property -dict {PACKAGE_PIN BE15 IOSTANDARD DIFF_POD12_DCI} [get_ports {c1_ddr4_dqs_t[9]}]
set_property -dict {PACKAGE_PIN AM25 IOSTANDARD SSTL12_DCI} [get_ports {c1_ddr4_adr[15]}]
set_property -dict {PACKAGE_PIN AL25 IOSTANDARD SSTL12_DCI} [get_ports {c1_ddr4_adr[14]}]
set_property -dict {PACKAGE_PIN AP26 IOSTANDARD SSTL12_DCI} [get_ports {c1_ddr4_ba[1]}]
set_property -dict {PACKAGE_PIN AN26 IOSTANDARD SSTL12_DCI} [get_ports {c1_ddr4_adr[3]}]
set_property -dict {PACKAGE_PIN AM26 IOSTANDARD SSTL12_DCI} [get_ports {c1_ddr4_adr[10]}]
#set_property -dict {PACKAGE_PIN AP24 IOSTANDARD SSTL12_DCI     } [get_ports c1_ddr4_odt[1]   ]; # Bank 65 VCCO - VCC1V2 Net "DDR4_C1_ODT1"     - IO_L21N_T3L_N5_AD8N_D07_65
#set_property -dict {PACKAGE_PIN AP23 IOSTANDARD SSTL12_DCI     } [get_ports c1_ddr4_cs_n[3]  ]; # Bank 65 VCCO - VCC1V2 Net "DDR4_C1_CS_B3"    - IO_L21P_T3L_N4_AD8P_D06_65
#set_property -dict {PACKAGE_PIN AM24 IOSTANDARD SSTL12_DCI     } [get_ports c1_ddr4_adr[17]  ]; # Bank 65 VCCO - VCC1V2 Net "DDR4_C1_ADR17"    - IO_L20N_T3L_N3_AD1N_D09_65
set_property -dict {PACKAGE_PIN AL24 IOSTANDARD SSTL12_DCI} [get_ports {c1_ddr4_adr[13]}]
set_property -dict {PACKAGE_PIN AN24 IOSTANDARD SSTL12_DCI} [get_ports {c1_ddr4_adr[0]}]
set_property -dict {PACKAGE_PIN AN23 IOSTANDARD SSTL12_DCI} [get_ports {c1_ddr4_adr[16]}]
#set_property -dict {PACKAGE_PIN AV26 IOSTANDARD DIFF_SSTL12_DCI} [get_ports c1_ddr4_ck_c[1]  ]; # Bank 65 VCCO - VCC1V2 Net "DDR4_C1_CK_C1"    - IO_L17N_T2U_N9_AD10N_D15_65
#set_property -dict {PACKAGE_PIN AU26 IOSTANDARD DIFF_SSTL12_DCI} [get_ports c1_ddr4_ck_t[1]  ]; # Bank 65 VCCO - VCC1V2 Net "DDR4_C1_CK_T1"    - IO_L17P_T2U_N8_AD10P_D14_65
set_property -dict {PACKAGE_PIN AT23 IOSTANDARD SSTL12_DCI} [get_ports c1_ddr4_par]
#set_property -dict {PACKAGE_PIN AR23 IOSTANDARD SSTL12_DCI     } [get_ports c1_ddr4_cs_n[2]  ]; # Bank 65 VCCO - VCC1V2 Net "DDR4_C1_CS_B2"    - IO_L16P_T2U_N6_QBC_AD3P_A00_D16_65
#set_property -dict {PACKAGE_PIN AP25 IOSTANDARD SSTL12_DCI     } [get_ports c1_ddr4_cs_n[1]  ]; # Bank 65 VCCO - VCC1V2 Net "DDR4_C1_CS_B1"    - IO_T2U_N12_CSI_ADV_B_65
set_property -dict {PACKAGE_PIN AU24 IOSTANDARD SSTL12_DCI} [get_ports {c1_ddr4_ba[0]}]
set_property -dict {PACKAGE_PIN AT24 IOSTANDARD SSTL12_DCI} [get_ports {c1_ddr4_adr[1]}]
set_property -dict {PACKAGE_PIN AU25 IOSTANDARD DIFF_SSTL12_DCI} [get_ports {c1_ddr4_ck_c[0]}]
set_property -dict {PACKAGE_PIN AT25 IOSTANDARD DIFF_SSTL12_DCI} [get_ports {c1_ddr4_ck_t[0]}]
set_property -dict {PACKAGE_PIN AV24 IOSTANDARD SSTL12_DCI} [get_ports {c1_ddr4_adr[6]}]
set_property -dict {PACKAGE_PIN AV23 IOSTANDARD SSTL12_DCI} [get_ports {c1_ddr4_cs_n[0]}]
set_property -dict {PACKAGE_PIN AW26 IOSTANDARD SSTL12_DCI} [get_ports {c1_ddr4_bg[1]}]
set_property -dict {PACKAGE_PIN AW25 IOSTANDARD SSTL12_DCI} [get_ports c1_ddr4_act_n]
set_property -dict {PACKAGE_PIN AY25 IOSTANDARD SSTL12_DCI} [get_ports {c1_ddr4_adr[8]}]
set_property -dict {PACKAGE_PIN AY23 IOSTANDARD SSTL12_DCI} [get_ports {c1_ddr4_adr[5]}]
set_property -dict {PACKAGE_PIN AY22 IOSTANDARD SSTL12_DCI} [get_ports {c1_ddr4_adr[4]}]
set_property -dict {PACKAGE_PIN BA25 IOSTANDARD SSTL12_DCI} [get_ports {c1_ddr4_adr[11]}]
set_property -dict {PACKAGE_PIN AW24 IOSTANDARD SSTL12_DCI} [get_ports {c1_ddr4_adr[2]}]
set_property -dict {PACKAGE_PIN AW23 IOSTANDARD SSTL12_DCI} [get_ports {c1_ddr4_odt[0]}]
set_property -dict {PACKAGE_PIN BB25 IOSTANDARD SSTL12_DCI} [get_ports {c1_ddr4_cke[0]}]
#set_property -dict {PACKAGE_PIN BB24 IOSTANDARD SSTL12_DCI     } [get_ports c1_ddr4_cke[1]   ]; # Bank 65 VCCO - VCC1V2 Net "DDR4_C1_CKE1"     - IO_L9P_T1L_N4_AD12P_A14_D30_65
set_property -dict {PACKAGE_PIN BA23 IOSTANDARD SSTL12_DCI} [get_ports {c1_ddr4_adr[9]}]
set_property -dict {PACKAGE_PIN BA22 IOSTANDARD SSTL12_DCI} [get_ports {c1_ddr4_adr[7]}]
set_property -dict {PACKAGE_PIN BC22 IOSTANDARD SSTL12_DCI} [get_ports {c1_ddr4_bg[0]}]
set_property -dict {PACKAGE_PIN BB22 IOSTANDARD SSTL12_DCI} [get_ports {c1_ddr4_adr[12]}]
set_property -dict {PACKAGE_PIN BF25 IOSTANDARD POD12_DCI} [get_ports {c1_ddr4_dq[64]}]
set_property -dict {PACKAGE_PIN BF24 IOSTANDARD POD12_DCI} [get_ports {c1_ddr4_dq[65]}]
set_property -dict {PACKAGE_PIN BD24 IOSTANDARD DIFF_POD12_DCI} [get_ports {c1_ddr4_dqs_c[16]}]
set_property -dict {PACKAGE_PIN BC24 IOSTANDARD DIFF_POD12_DCI} [get_ports {c1_ddr4_dqs_t[16]}]
set_property -dict {PACKAGE_PIN BE25 IOSTANDARD POD12_DCI} [get_ports {c1_ddr4_dq[67]}]
set_property -dict {PACKAGE_PIN BD25 IOSTANDARD POD12_DCI} [get_ports {c1_ddr4_dq[66]}]
set_property -dict {PACKAGE_PIN BF23 IOSTANDARD POD12_DCI} [get_ports {c1_ddr4_dq[70]}]
set_property -dict {PACKAGE_PIN BE23 IOSTANDARD POD12_DCI} [get_ports {c1_ddr4_dq[71]}]
set_property -dict {PACKAGE_PIN BD23 IOSTANDARD POD12_DCI} [get_ports {c1_ddr4_dq[68]}]
set_property -dict {PACKAGE_PIN BC23 IOSTANDARD POD12_DCI} [get_ports {c1_ddr4_dq[69]}]
set_property -dict {PACKAGE_PIN BF22 IOSTANDARD DIFF_POD12_DCI} [get_ports {c1_ddr4_dqs_c[17]}]
set_property -dict {PACKAGE_PIN BE22 IOSTANDARD DIFF_POD12_DCI} [get_ports {c1_ddr4_dqs_t[17]}]

set_property PACKAGE_PIN AW20 [get_ports c1_sys_clk_p]
set_property PACKAGE_PIN AW19 [get_ports c1_sys_clk_n]

set_property IOSTANDARD LVDS [get_ports c1_sys_clk_n]
set_property IOSTANDARD LVDS [get_ports c1_sys_clk_p]

####################################################################################
# Constraints from file : 'u250_net_0.xdc'
####################################################################################

