name: Build RDMA 

on: 
  pull_request: 
    branches: 
    - master

defaults: 
  run: 
    shell: bash -ileo pipefail {0}

jobs: 
  build_rdma_perf:
    environment: fpga-synth
    runs-on: [self-hosted, linux, x64]

    steps: 
    - uses: actions/checkout@v3
      with: 
        submodules: recursive

    - name: Compile hardware for rdma_perf example 
      run: |
        mkdir examples_hw/build_rdma_perf && cd examples_hw/build_rdma_perf
        cmake ../ -DFDEV_NAME=u55c -DEXAMPLE=rdma_perf -DEN_XTERM=0
        make project && make bitgen 

    - name: Compile software for RDMA-server
      run: | 
        mkdir examples_sw/build_rdma_server && cd examples_sw/build_rdma_server
        cmake ../ -DEXAMPLE=rdma_server
        make 
    
    - name: Compile software for RDMA-client
      run: |
        mkdir examples_sw/build_rdma_client && cd examples_sw/build_rdma_client 
        cmake ../ -DEXAMPLE=rdma_client
        make

    - name: Artifact upload 
      uses: actions/upload-artifact@v3
      with: 
        name: bitstream-rdma-perf
        path: examples_hw/build_rdma_perf/bitstreams
        retention-days: 3